In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import numpy as np
import datetime as dt
import math as math
pd.set_option("display.max_columns", None)
from pandas.tseries.offsets import MonthEnd

### Identifiers: Prowess Company Code x NSE Symbol [Done later]

In [2]:
compCodeNse = pd.read_excel("Prowess Code_NSE Symbol.xlsx")
compCodeNse

                               Company Name  Prowess company code NSE symbol
0          'K' Steamship Agencies Pvt. Ltd.                     3        NaN
1      'X'Clusive Business Centre Pvt. Ltd.                307865        NaN
2                 1 To 1 Help.Net Pvt. Ltd.                591675        NaN
3              10C India Internet Pvt. Ltd.                556976        NaN
4           10I Commerce Services Pvt. Ltd.                560502        NaN
...                                     ...                   ...        ...
55307                    Zylog Systems Ltd.                275793      ZYLOG
55308       Zyma Laboratories Ltd. [Merged]                275794        NaN
55309      Zyphar'S Pharmaceutics Pvt. Ltd.                565342        NaN
55310                   Zytel Agencies Ltd.                275795        NaN
55311      Zyxel Technology India Pvt. Ltd.                432445        NaN

[55312 rows x 3 columns]

### READING ALL DATA FILES

#### 8 Ownership Data

In [3]:
own1 = pd.read_excel("Prowess IQ - Ownership Data.xlsx", sheet_name = 0, header = [0,1])
own2 = pd.read_excel("Prowess IQ - Ownership Data.xlsx", sheet_name = 1, header = [0,1])

In [4]:
own11 = own1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
own12 = own11.unstack().unstack(level = 1).reset_index()
own13 = own12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
own13["AsOnDate"] = pd.to_datetime(own13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

own21 = own2.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
own22 = own21.unstack().unstack(level = 1).reset_index()
own23 = own22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
own23["AsOnDate"] = pd.to_datetime(own23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [5]:
own = pd.concat([own13, own23], axis = 0).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop= True).drop_duplicates()
own

,AsOnDate,Company Name,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,2005-03-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005-06-30,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005-09-30,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005-12-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-03-31,20 Microns Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
297487,2023-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297488,2023-06-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297489,2023-09-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297490,2023-12-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297491,2024-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 1 Financial Data

In [6]:
fin1 = pd.read_excel("Prowess IQ - Financial Data.xlsx", sheet_name = 0, header = [0,1])

fin2 = pd.read_excel("Prowess IQ - Financial Data.xlsx", sheet_name = 1, header = [0,1])

In [7]:
# fin1 = fin_identifiers.drop(fin_identifiers.columns[[1,3,4,5,6,7,8,9,10,11,12,13]], axis = 1)

In [8]:
fin11 = fin1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
fin12 = fin11.unstack().unstack(level = 1).reset_index()
fin13 = fin12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
fin13["AsOnDate"] = pd.to_datetime(fin13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

fin21 = fin2.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
fin22 = fin21.unstack().unstack(level = 1).reset_index()
fin23 = fin22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
fin23["AsOnDate"] = pd.to_datetime(fin23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [9]:
fin = pd.concat([fin13, fin23], axis = 0).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop= True).drop_duplicates()
fin

,AsOnDate,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of fixed assets,Cash flow due to purchase of fixed assets,Net cash inflow or (outflow) from investing activities,Research & development expenses,Inter-corporate loans (Old Sch. VI)
0,2005-03-31,20 Microns Ltd.,578.3,-63.2,70.0,-8.78,698.5,66.3,2.3,2.08,NaN,NaN,389.1,70.6,NaN,NaN,NaN,NaN,NaN,68.2,-29.3,0.3,29.3,-38.6,NaN,NaN
1,2006-03-31,20 Microns Ltd.,720.8,18.0,83.1,2.58,742.9,80.0,9.4,1.98,NaN,NaN,399.6,57.7,NaN,NaN,NaN,NaN,0.9,53.8,-22.4,0.4,22.4,-20.8,1.9,NaN
2,2007-03-31,20 Microns Ltd.,933.6,35.7,125.2,4.51,845.1,121.5,45.1,1.78,NaN,NaN,423.6,70.6,NaN,NaN,NaN,NaN,2.5,61.9,-44.9,0.9,44.9,-44.2,6.3,NaN
3,2008-03-31,20 Microns Ltd.,1147.9,45.9,164.9,4.11,978.4,152.9,64.4,1.64,NaN,NaN,466.0,98.2,NaN,NaN,NaN,NaN,12.1,69.0,-48.2,2.8,48.2,-44.2,5.5,NaN
4,2009-03-31,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,-94.1,4.2,94.1,-89.9,3.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80089,2020-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80090,2021-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80091,2022-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80092,2023-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80093,2024-03-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 4 BVPS

In [10]:
bvps1 = pd.read_excel("Prowess IQ - BVPS.xlsx", sheet_name = 0, header = [0,1])
bvps2 = pd.read_excel("Prowess IQ - BVPS.xlsx", sheet_name = 1, header = [0,1])

In [11]:
bvps11 = bvps1.set_index([("Unnamed: 0_level_0","Company Name")])
bvps12 = bvps11.unstack().unstack(level = 1).reset_index()
bvps13 = bvps12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
bvps13["AsOnDate"] = pd.to_datetime(bvps13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
bvps14 = bvps13.merge(compCodeNse, on = ["Company Name"], how = "left")

bvps21 = bvps2.set_index([("Unnamed: 0_level_0","Company Name")])
bvps22 = bvps21.unstack().unstack(level = 1).reset_index()
bvps23 = bvps22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
bvps23["AsOnDate"] = pd.to_datetime(bvps23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
bvps24 = bvps23.merge(compCodeNse, on = ["Company Name"], how = "left")

In [12]:
bvps = pd.concat([bvps14, bvps24], axis = 0).sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
bvps = bvps[ bvps.columns[[1,0,2]]].dropna(subset = ["BV per Share "]).reset_index(drop = True).rename({"BV per Share ":"BVPS"}, axis = 1).drop_duplicates()
bvps

                    Company Name   AsOnDate   BVPS
0                20 Microns Ltd. 2009-03-31  25.19
1                20 Microns Ltd. 2010-03-31  29.03
2                20 Microns Ltd. 2011-03-31  31.12
3                20 Microns Ltd. 2012-03-31  36.38
4                20 Microns Ltd. 2013-03-31  20.92
...                          ...        ...    ...
54469    Shree Karni Fabcom Ltd. 2024-03-31   0.00
54470  Pratham Epc Projects Ltd. 2024-03-31   0.00
54471     Signoria Creation Ltd. 2024-03-31  32.18
54472      Enfuse Solutions Ltd. 2024-03-31  35.07
54473  Enser Communications Ltd. 2024-03-31  26.59

[51977 rows x 3 columns]

#### 2 Deferred Tax Liability

In [13]:
defTaxLia1 = pd.read_excel("Prowess IQ - Deferred Tax Liability.xlsx", sheet_name = 0, header = [0,1])

In [14]:
defTaxLia11 = defTaxLia1.set_index([("Unnamed: 0_level_0","Company Name")])
defTaxLia12 = defTaxLia11.unstack().unstack(level = 1).reset_index()
defTaxLia13 = defTaxLia12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
defTaxLia13["AsOnDate"] = pd.to_datetime(defTaxLia13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
defTaxLia14 = defTaxLia13.merge(compCodeNse, on = ["Company Name"], how = "left")

In [15]:
defTaxLia = defTaxLia14.sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop([ "NSE symbol"], axis =1)
defTaxLia = defTaxLia[ defTaxLia.columns[[1,0,2]]].dropna(subset = ["Deferred tax liability"]).reset_index( drop = True).drop_duplicates()
defTaxLia

                             Company Name   AsOnDate  Deferred tax liability
0        'K' Steamship Agencies Pvt. Ltd. 2011-03-31                     7.3
1        'K' Steamship Agencies Pvt. Ltd. 2012-03-31                     9.6
2        'K' Steamship Agencies Pvt. Ltd. 2013-03-31                     0.6
3        'K' Steamship Agencies Pvt. Ltd. 2014-03-31                     0.4
4        'K' Steamship Agencies Pvt. Ltd. 2015-03-31                     0.3
...                                   ...        ...                     ...
204869      Economist Communications Ltd. 2023-03-31                     0.4
204870                P V R Pictures Ltd. 2023-03-31                    35.8
204871  Pankaj Piyush Trade & Invst. Ltd. 2023-03-31                     0.2
204872   R D C Concrete (India) Pvt. Ltd. 2023-03-31                     1.7
204873                S M C Comtrade Ltd. 2023-03-31                     1.3

[204874 rows x 3 columns]

#### 3 Net Deferred Tax Liabilties

In [16]:
netDefTaxLia1 = pd.read_excel("Prowess IQ - Net Deferred Tax Liability.xlsx", sheet_name = 0, header = [0,1])

In [17]:
netDefTaxLia11 = netDefTaxLia1.set_index([("Unnamed: 0_level_0","Company Name")])
netDefTaxLia12 = netDefTaxLia11.unstack().unstack(level = 1).reset_index()
netDefTaxLia13 = netDefTaxLia12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
netDefTaxLia13["AsOnDate"] = pd.to_datetime(netDefTaxLia13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
netDefTaxLia14 = netDefTaxLia13.merge(compCodeNse, on = ["Company Name"], how = "left")

In [18]:
netDefTaxLia = netDefTaxLia14.sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
netDefTaxLia = netDefTaxLia[ netDefTaxLia.columns[[1,0,2]]].dropna(subset = ["Net deferred tax liabilities"]).reset_index( drop = True).drop_duplicates()
netDefTaxLia

,Company Name,AsOnDate,Net deferred tax liabilities
0,'K' Steamship Agencies Pvt. Ltd.,2011-03-31,6.1
1,'K' Steamship Agencies Pvt. Ltd.,2012-03-31,8.1
2,'K' Steamship Agencies Pvt. Ltd.,2013-03-31,-0.4
3,'K' Steamship Agencies Pvt. Ltd.,2014-03-31,-0.8
4,'K' Steamship Agencies Pvt. Ltd.,2015-03-31,-3.3
...,...,...,...
314437,Paras Healthcare Pvt. Ltd.,2023-03-31,-36.3
314438,R D C Concrete (India) Pvt. Ltd.,2023-03-31,-209.7
314439,S M C Comtrade Ltd.,2023-03-31,-6.1
314440,Shyama Infosys Ltd.,2023-03-31,-0.5
314441,T S R Darashaw Ltd.,2023-03-31,-3.5

#### 5 Shares Outstanding

In [19]:
sharesOut1 = pd.read_excel("Prowess IQ - Shares Outstanding.xlsx", sheet_name = 0, header = [0,1])
sharesOut2 = pd.read_excel("Prowess IQ - Shares Outstanding.xlsx", sheet_name = 1, header = [0,1])

In [20]:
sharesOut11 = sharesOut1.set_index([("Unnamed: 0_level_0","Company Name")])
sharesOut12 = sharesOut11.unstack().unstack(level = 1).reset_index()
sharesOut13 = sharesOut12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
sharesOut13["AsOnDate"] = pd.to_datetime(sharesOut13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
sharesOut14 = sharesOut13.merge(compCodeNse, on = ["Company Name"], how = "left")

sharesOut21 = sharesOut2.set_index([("Unnamed: 0_level_0","Company Name")])
sharesOut22 = sharesOut21.unstack().unstack(level = 1).reset_index()
sharesOut23 = sharesOut22.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
sharesOut23["AsOnDate"] = pd.to_datetime(sharesOut23["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)
sharesOut24 = sharesOut23.merge(compCodeNse, on = ["Company Name"], how = "left")

In [21]:
sharesOut = pd.concat([sharesOut14, sharesOut24], axis = 0).sort_values(by = ["Prowess company code", "AsOnDate"]).reset_index(drop= True).drop(["NSE symbol"], axis =1)
sharesOut = sharesOut[ sharesOut.columns[[1,0,2]]].dropna(subset = ["Shares Outstanding "]).reset_index( drop = True).rename({"Shares Oustanding ":"Shares Oustanding"}, axis = 1).drop_duplicates()
sharesOut

                    Company Name   AsOnDate  Shares Outstanding
0                20 Microns Ltd. 2009-03-31           14205248.0
1                20 Microns Ltd. 2010-03-31           14331028.0
2                20 Microns Ltd. 2011-03-31           14331028.0
3                20 Microns Ltd. 2012-03-31           14331028.0
4                20 Microns Ltd. 2013-03-31           31662056.0
...                          ...        ...                  ...
54469    Shree Karni Fabcom Ltd. 2024-03-31            7072000.0
54470  Pratham Epc Projects Ltd. 2024-03-31           17760000.0
54471     Signoria Creation Ltd. 2024-03-31            4758000.0
54472      Enfuse Solutions Ltd. 2024-03-31            8847600.0
54473  Enser Communications Ltd. 2024-03-31            8716059.0

[51977 rows x 3 columns]

#### 6 Market Data

In [22]:
market1 = pd.read_excel("Prowess IQ - Market Data.xlsx", sheet_name = 0, header = [0,1])

In [23]:
market11 = market1.drop([("Unnamed: 1_level_0","NSE symbol")], axis = 1).set_index([("Unnamed: 0_level_0","Company Name")])
market12 = market11.unstack().unstack(level = 1).reset_index()
market13 = market12.rename({"level_0":"AsOnDate", ("Unnamed: 0_level_0","Company Name"):"Company Name"}, axis = 1).sort_values(by = ["Company Name", "AsOnDate"]).reset_index(drop = True)
market13["AsOnDate"] = pd.to_datetime(market13["AsOnDate"], format = "%b %Y" ) + MonthEnd(0)

In [24]:
market = market13.sort_values(by = ["Company Name", "AsOnDate"]).dropna(subset = ["Market Capitalisation", "Total Returns", "P/B ", "Market Capitalisation / Enterprise Value"], how = "all").reset_index(drop= True).drop_duplicates()
market

,AsOnDate,Company Name,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value
0,2008-12-31,20 Microns Ltd.,220.98,2.62,0.42,0.33
1,2009-03-31,20 Microns Ltd.,214.50,0.67,0.60,0.28
2,2009-06-30,20 Microns Ltd.,328.85,-1.49,0.84,0.38
3,2009-09-30,20 Microns Ltd.,599.75,-1.99,1.47,0.52
4,2009-12-31,20 Microns Ltd.,659.94,-1.07,1.57,0.55
...,...,...,...,...,...,...
199881,2023-03-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199882,2023-06-30,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199883,2023-09-30,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199884,2023-12-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00
199885,2024-03-31,Zylog Systems Ltd.,20.65,-12.50,NaN,0.00

#### 7 Entity ID and stuff

In [25]:
# iden = fin_identifiers[fin_identifiers.columns[[0,1,2,3,4,5,6,7,8,9,10,11,12,13]]].droplevel( 0, axis =1)

In [26]:
# iden

In [27]:
iden = pd.read_excel("Prowess IQ - Indicators.xlsx")

In [28]:
iden

,Company Name,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address
0,'K' Steamship Agencies Pvt. Ltd.,3,Private Ltd.,10203010000,1971.0,Diversified,1.100000e+14,Diversified,34.0,20102000000,Private (Indian),Between 1951 and 1971,NaN,NaN
1,'X'Clusive Business Centre Pvt. Ltd.,307865,Private Ltd.,10203010000,1996.0,Diversified financial services,1.022000e+14,"Other financial service activities, except ins...",649.0,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
2,1 To 1 Help.Net Pvt. Ltd.,591675,Private Ltd.,10203010000,2001.0,Business services & consultancy,1.010415e+14,Management consultancy activities,70200.0,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
3,10C India Internet Pvt. Ltd.,556976,Private Ltd.,10203010000,2012.0,Telecommunication services,1.010406e+14,Other telecommunications activities,61900.0,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
4,10I Commerce Services Pvt. Ltd.,560502,Private Ltd.,10203010000,2015.0,Wholesale trading,1.010404e+14,"Wholesale of radio, television and other consu...",46522.0,20102000000,Private (Indian),After 2014,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55316,Zylog Systems Ltd.,275793,Public Ltd.,10203020000,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,20102000000,Private (Indian),Between 1991 and 2013,ZYLOG,NaN
55317,Zyma Laboratories Ltd. [Merged],275794,Public Ltd.,10203020000,1970.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,20102000000,Private (Indian),Between 1951 and 1971,NaN,NaN
55318,Zyphar'S Pharmaceutics Pvt. Ltd.,565342,Private Ltd.,10203010000,2006.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497.0,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN
55319,Zytel Agencies Ltd.,275795,Public Ltd.,10203020000,1984.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,20102000000,Private (Indian),Between 1972 and 1985,NaN,NaN
55320,Zyxel Technology India Pvt. Ltd.,432445,Private Ltd.,10203010000,2006.0,Retail trading,1.010404e+14,Retail sale of computers and computer peripherals,47411.0,20102000000,Private (Indian),Between 1991 and 2013,NaN,NaN

### Merging all the raw Data together before merging with main

In [29]:
# 1 fin
# 2 defTaxLia
# 3 netDefTaxLia

# 4 bvps
# 5 sharesOut

# 6 market

# 7 iden
# 8 own

In [30]:
# raw1 = compCodeNse.merge(fin, on = ["Company Name"], how = "outer")
raw2 = fin.merge(defTaxLia, on = ["Company Name", "AsOnDate"], how = "outer")
raw3 = raw2.merge(netDefTaxLia, on = ["Company Name", "AsOnDate"], how = "outer")

In [31]:
raw4 = raw3.merge(bvps, on = ["Company Name", "AsOnDate"], how = "outer")
raw5 = raw4.merge(sharesOut, on = ["Company Name", "AsOnDate"], how = "outer")

raw6 = raw5.merge(market, on = ["Company Name", "AsOnDate"], how = "outer")

raw7 = raw6.merge(iden, on = ["Company Name"], how = "outer")
raw8 = raw7.merge(own, on = ["Company Name", "AsOnDate"], how = "outer")

In [32]:
raw8

,AsOnDate,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of fixed assets,Cash flow due to purchase of fixed assets,Net cash inflow or (outflow) from investing activities,Research & development expenses,Inter-corporate loans (Old Sch. VI),Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,2005-03-31,20 Microns Ltd.,578.3,-63.2,70.0,-8.78,698.5,66.3,2.3,2.08,NaN,NaN,389.1,70.6,NaN,NaN,NaN,NaN,NaN,68.2,-29.3,0.3,29.3,-38.6,NaN,NaN,49.1,49.1,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-03-31,20 Microns Ltd.,720.8,18.0,83.1,2.58,742.9,80.0,9.4,1.98,NaN,NaN,399.6,57.7,NaN,NaN,NaN,NaN,0.9,53.8,-22.4,0.4,22.4,-20.8,1.9,NaN,66.6,38.4,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-03-31,20 Microns Ltd.,933.6,35.7,125.2,4.51,845.1,121.5,45.1,1.78,NaN,NaN,423.6,70.6,NaN,NaN,NaN,NaN,2.5,61.9,-44.9,0.9,44.9,-44.2,6.3,NaN,90.0,42.6,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008-03-31,20 Microns Ltd.,1147.9,45.9,164.9,4.11,978.4,152.9,64.4,1.64,NaN,NaN,466.0,98.2,NaN,NaN,NaN,NaN,12.1,69.0,-48.2,2.8,48.2,-44.2,5.5,NaN,90.2,61.7,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009-03-31,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,-94.1,4.2,94.1,-89.9,3.1,NaN,92.4,70.1,25.19,14205248.0,214.5,0.67,0.6,0.28,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585676,2005-12-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585677,2006-06-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585678,2006-09-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585679,2006-12-31,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585680,2007-06-30,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
main = pd.read_csv("Main_Firm_No Loc_No Fin v140924.csv")
main["AsOnDate"] = pd.to_datetime(main["AsOnDate"], format = "%Y-%m-%d")
main

,Symbol,Unnamed: 1,Symbol.1,AsOnDate,level_2,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted
0,20MICRONS,0,20MICRONS,2009-03-31,0,12,2.484907,0,0.000000,0,69.166667,4,0,8,0,0.000000,12,0,4,0,8,0,1,1,2009,0,0,0,0,0,0,0,6,0,0,6.419178,0.000000,0.000000,0.000000,0.333333,0.666667,0.333333,0.666667,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00032270'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,1,20MICRONS,2010-03-31,0,13,2.564949,0,0.000000,0,69.461538,4,0,9,0,0.000000,13,0,4,0,9,0,1,1,2010,0,0,0,0,0,0,0,7,0,0,6.893994,0.000000,0.000000,0.000000,0.307692,0.692308,0.307692,0.692308,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00031581'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20MICRONS,2,20MICRONS,2011-03-31,0,13,2.564949,0,0.000000,0,69.461538,2,0,11,0,0.000000,13,0,2,0,11,0,1,1,2011,0,0,0,0,0,0,0,6,0,0,7.893994,0.000000,0.000000,0.000000,0.153846,0.846154,0.153846,0.846154,0,0,0,0.000000,[],0.000000,0.000000,[],[],[],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20MICRONS,3,20MICRONS,2012-03-31,0,14,2.639057,0,0.000000,0,69.461538,2,0,12,0,0.000000,14,0,2,0,12,0,1,1,2012,0,0,0,0,0,0,0,6,0,0,8.324658,0.000000,0.000000,0.000000,0.142857,0.857143,0.142857,0.857143,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00042601'],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20MICRONS,4,20MICRONS,2013-03-31,0,14,2.639057,0,0.000000,0,69.461538,1,0,13,5,0.357143,9,0,1,5,8,4,1,1,2013,1,1,1,1,1,1,1,3,0,0,9.324658,0.000000,0.000000,0.357143,0.071429,0.571429,0.071429,0.928571,0,0,0,0.000000,[],0.200000,0.200000,[],"['P00027633', 'P00031581', 'P00027665', 'P0002...",[],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28894,ZYLOG,28894,ZYLOG,2014-03-31,0,13,2.564949,0,0.000000,0,67.166667,2,0,11,7,0.538462,6,1,1,6,5,1,3,1,2014,1,1,1,1,1,0,0,5,0,0,7.496944,0.538462,0.142857,0.461538,0.076923,0.384615,0.153846,0.846154,0,1,0,0.000000,[],0.428571,0.428571,['P00062851'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00048642', 'P00062851']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,3.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28895,ZYLOG,28895,ZYLOG,2015-03-31,0,15,2.708050,0,0.000000,0,67.166667,4,1,11,8,0.533333,7,2,2,6,5,1,3,1,2015,1,1,1,0,1,0,0,6,0,0,7.412237,0.933333,0.250000,0.400000,0.133333,0.333333,0.266667,0.733333,0,0,1,0.000000,[],0.375000,0.500000,['P00067111'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00067112', 'P00067111']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,4.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28896,ZYLOG,28896,ZYLOG,2016-03-31,0,20,2.995732,0,0.000000,0,65.125000,8,1,12,13,0.650000,7,5,3,8,4,1,3,1,2016,1,1,1,0,1,0,0,10,0,0,6.410274,1.100000,0.384615,0.400000,0.150000,0.200000,0.400000,0.600000,0,0,1,0.000000,[],0.230769,0.538462,"['P00036956', 'P00075400', 'P00075399', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00036956', 'P00073179', 'P00075400', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,7.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28897,ZYLOG,28897,ZYLOG,2017-03-31,0,22,3.091042,1,0.045455,1,65.125000,8,1,14,15,0.681818,7,6,2,9,5,1,3,1,2017,1,1,1,0,1,0,0,12,0,0,6.758655,1.590909,0.400000,0.409091,0.090909,0.227273,0.363636,0.636364,0,0,1,0.000000,[],0.200000,0.600000,"['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,9.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28898,ZYLOG,28898,ZYLOG,2018-03-31,0,22,3.091042,1,0.045455,1,65.125000,6,1,16,15,0.681818,7,5,1,10,6,1,3,1,2018,1,1,1,0,1,0,0,11,22,1,7.758655,2.272727,0.333333,0.454545,0.045455,0.272727,0.272727,0.727273,0,0,1,0.066667,['P00062851'],0.200000,0.533333,[],"['P00007571', 'P00013013', 'P00001781', 'P0003...",[],"['P00007571', 'P00013013', 'P00001781', 'P0000...",1.0,8.0,22.0,1.0,20.0,0.909091,15.0,1.0,14.0,0.933333,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
merged = main.merge(raw8, left_on = ["Symbol", "AsOnDate"], right_on = ["NSE symbol", "AsOnDate"], how = "left").drop_duplicates().drop(["Unnamed: 1", "Symbol.1", "level_2"], axis = 1)

In [35]:
FirmID = merged.Symbol.drop_duplicates().reset_index(drop = True).reset_index().rename({"index":"FirmID"}, axis = 1)
FirmID

      FirmID      Symbol
0          0   20MICRONS
1          1  21STCENMGM
2          2      360ONE
3          3   3IINFOLTD
4          4     3MINDIA
...      ...         ...
2772    2772       ZUARI
2773    2773    ZUARIIND
2774    2774   ZYDUSLIFE
2775    2775   ZYDUSWELL
2776    2776       ZYLOG

[2777 rows x 2 columns]

In [36]:
merged2 = FirmID.merge(merged, on = "Symbol", how = "inner")
merged2

,FirmID,Symbol,AsOnDate,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of fixed assets,Cash flow due to purchase of fixed assets,Net cash inflow or (outflow) from investing activities,Research & development expenses,Inter-corporate loans (Old Sch. VI),Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held
0,0,20MICRONS,2009-03-31,12,2.484907,0,0.000000,0,69.166667,4,0,8,0,0.000000,12,0,4,0,8,0,1,1,2009,0,0,0,0,0,0,0,6,0,0,6.419178,0.000000,0.000000,0.000000,0.333333,0.666667,0.333333,0.666667,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00032270'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,-94.1,4.2,94.1,-89.9,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90
1,0,20MICRONS,2010-03-31,13,2.564949,0,0.000000,0,69.461538,4,0,9,0,0.000000,13,0,4,0,9,0,1,1,2010,0,0,0,0,0,0,0,7,0,0,6.893994,0.000000,0.000000,0.000000,0.307692,0.692308,0.307692,0.692308,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00031581'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,-164.5,28.1,164.5,-196.5,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30
2,0,20MICRONS,2011-03-31,13,2.564949,0,0.000000,0,69.461538,2,0,11,0,0.000000,13,0,2,0,11,0,1,1,2011,0,0,0,0,0,0,0,6,0,0,7.893994,0.000000,0.000000,0.000000,0.153846,0.846154,0.153846,0.846154,0,0,0,0.000000,[],0.000000,0.000000,[],[],[],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,-154.0,8.3,154.0,-147.9,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46
3,0,20MICRONS,2012-03-31,14,2.639057,0,0.000000,0,69.461538,2,0,12,0,0.000000,14,0,2,0,12,0,1,1,2012,0,0,0,0,0,0,0,6,0,0,8.324658,0.000000,0.000000,0.000000,0.142857,0.857143,0.142857,0.857143,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00042601'],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,-414.7,15.6,414.7,-397.2,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35
4,0,20MICRONS,2013-03-31,14,2.639057,0,0.000000,0,69.461538,1,0,13,5,0.357143,9,0,1,5,8,4,1,1,2013,1,1,1,1,1,1,1,3,0,0,9.324658,0.000000,0.000000,0.357143,0.071429,0.571429,0.071429,0.928571,0,0,0,0.000000,[],0.200000,0.200000,[],"['P00027633', 'P00031581', 'P00027665', 'P0002...",[],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,-409.5,1.9,409.5,-361.2,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28894,2776,ZYLOG,2014-03-31,13,2.564949,0,0.000000,0,67.166667,2,0,11,7,0.538462,6,1,1,6,5,1,3,1,2014,1,1,1,1,1,0,0,5,0,0,7.496944,0.538462,0.142857,0.461538,0.076923,0.384615,0.153846,0.846154,0,1,0,0.000000,[],0.428571,0.428571,['P00062851'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00048642', 'P00062851']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,3.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,-2012.5,0.2,2012.5,-1354.6,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70
28895,2776,ZYLOG,2015-03-31,15,2.708050,0,0.000000,0,67.166667,4,1,11,8,0.533333,7,2,2,6,5,1,3,1,2015,1,1,1,0,1,0,0,6,0,0,7.412237,0.933333,0.250000,0.400000,0.133333,0.333333,0.266667,0.733333,0,0,1,0.000000,[],0.375000,0.500000,['P00067111'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00067112', 'P00067111']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,4.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,3131.3,-6284.1,-4542.8,-10.22,14773.4,-47.8,-1501.6,NaN,1726.5,833.9,9873.9,143.0,NaN,NaN,NaN,NaN,735.8,-78.6,-0.1,0.0,0.1,-23.5,NaN,985.1,171.5,171.5,-19.57,58992840.0,250.72,-4.49,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,83.84,12.26,71.58
28896,2776,ZYLOG,2016-03-31,20,2.995732,0,0.000000,0,65.125000,8,1,12,13,0.650000,7,5,3,8,4,1,3,1,2016,1,1,1,0,1,0,0,10,0,0,6.410274,1.100000,0.384615,0.400000,0.150000,0.200000,0.400000,0.600000,0,0,1,0.000000,[],0.230769,0.538462,"['P00036956', 'P00075400', 'P00075399', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00036956', 'P00073179', 'P00075400', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,7.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,1394.1,-1534.4,-1066.7,-3.17,5875.3,113.6,-479.9,NaN,306.0,306.0,9111.0,138.1,NaN,NaN,NaN,NaN,11.8,790.8,-3.9,NaN,3.9,-1561.5,NaN,42.1,NaN,-3.6,-144.83,58992840.0,241.87,0.00,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.20,12.87,84.33
28897,2776,ZYLOG,2017-03-31,22,3.091042,1,0.045455,1,65.125000,8,1,14,15,0.681818,7,6,2,9,5,1,3,1,2017,1,1,1,0,1,0,0,12,0,0,6.758655,1.590909,0.400000,0.409091,0.090909,0.227273,0.363636,0.636364,0,0,1,0.000000,[],0.200000,0.600000,"['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,9.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-145.22,58992840.0,259.57,-1.12,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,97.19,10.88,86.31
28898,2776,ZYLOG,2018-03-31,22,3.091042,1,0.045455,1,65.125000,6,1,16,15,0.681818,7,5,1,10,6,1,3,1,2018,1,1,1,0,1,0,0,11,22,1,7.758655,2.272727,0.333333,0.454545,0.045455,0.272727,0.272727,0.727273,0,0,1,0.066667,['P00062851'],0.200000,0.533333,[],"['P00007571', 'P00013013', 'P00001781', 'P0003...",[],"['P00007571', 'P00013013', 'P00001781', 'P0000...",1.0,8.0,22.0,1.0,20.0,0.909091,15.0,1.0,14.0,0.933333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,58992840.0,156.33,-3.64,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.19,10.40,86.79

In [37]:
merged2["BVCommonStock"] = merged2["BVPS"] * merged2["Shares Outstanding "]
merged2

,FirmID,Symbol,AsOnDate,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of fixed assets,Cash flow due to purchase of fixed assets,Net cash inflow or (outflow) from investing activities,Research & development expenses,Inter-corporate loans (Old Sch. VI),Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held,BVCommonStock
0,0,20MICRONS,2009-03-31,12,2.484907,0,0.000000,0,69.166667,4,0,8,0,0.000000,12,0,4,0,8,0,1,1,2009,0,0,0,0,0,0,0,6,0,0,6.419178,0.000000,0.000000,0.000000,0.333333,0.666667,0.333333,0.666667,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00032270'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,-94.1,4.2,94.1,-89.9,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90,3.578302e+08
1,0,20MICRONS,2010-03-31,13,2.564949,0,0.000000,0,69.461538,4,0,9,0,0.000000,13,0,4,0,9,0,1,1,2010,0,0,0,0,0,0,0,7,0,0,6.893994,0.000000,0.000000,0.000000,0.307692,0.692308,0.307692,0.692308,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00031581'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,-164.5,28.1,164.5,-196.5,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30,4.160297e+08
2,0,20MICRONS,2011-03-31,13,2.564949,0,0.000000,0,69.461538,2,0,11,0,0.000000,13,0,2,0,11,0,1,1,2011,0,0,0,0,0,0,0,6,0,0,7.893994,0.000000,0.000000,0.000000,0.153846,0.846154,0.153846,0.846154,0,0,0,0.000000,[],0.000000,0.000000,[],[],[],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,-154.0,8.3,154.0,-147.9,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46,4.459816e+08
3,0,20MICRONS,2012-03-31,14,2.639057,0,0.000000,0,69.461538,2,0,12,0,0.000000,14,0,2,0,12,0,1,1,2012,0,0,0,0,0,0,0,6,0,0,8.324658,0.000000,0.000000,0.000000,0.142857,0.857143,0.142857,0.857143,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00042601'],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,-414.7,15.6,414.7,-397.2,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35,5.213628e+08
4,0,20MICRONS,2013-03-31,14,2.639057,0,0.000000,0,69.461538,1,0,13,5,0.357143,9,0,1,5,8,4,1,1,2013,1,1,1,1,1,1,1,3,0,0,9.324658,0.000000,0.000000,0.357143,0.071429,0.571429,0.071429,0.928571,0,0,0,0.000000,[],0.200000,0.200000,[],"['P00027633', 'P00031581', 'P00027665', 'P0002...",[],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,-409.5,1.9,409.5,-361.2,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66,6.623702e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28894,2776,ZYLOG,2014-03-31,13,2.564949,0,0.000000,0,67.166667,2,0,11,7,0.538462,6,1,1,6,5,1,3,1,2014,1,1,1,1,1,0,0,5,0,0,7.496944,0.538462,0.142857,0.461538,0.076923,0.384615,0.153846,0.846154,0,1,0,0.000000,[],0.428571,0.428571,['P00062851'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00048642', 'P00062851']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,3.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,-2012.5,0.2,2012.5,-1354.6,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70,5.129427e+09
28895,2776,ZYLOG,2015-03-31,15,2.708050,0,0.000000,0,67.166667,4,1,11,8,0.533333,7,2,2,6,5,1,3,1,2015,1,1,1,0,1,0,0,6,0,0,7.412237,0.933333,0.250000,0.400000,0.133333,0.333333,0.266667,0.733333,0,0,1,0.000000,[],0.375000,0.500000,['P00067111'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00067112', 'P00067111']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,4.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,3131.3,-6284.1,-4542.8,-10.22,14773.4,-47.8,-1501.6,NaN,1726.5,833.9,9873.9,143.0,NaN,NaN,NaN,NaN,735.8,-78.6,-0.1,0.0,0.1,-23.5,NaN,985.1,171.5,171.5,-19.57,58992840.0,250.72,-4.49,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,83.84,12.26,71.58,-1.154490e+09
28896,2776,ZYLOG,2016-03-31,20,2.995732,0,0.000000,0,65.125000,8,1,12,13,0.650000,7,5,3,8,4,1,3,1,2016,1,1,1,0,1,0,0,10,0,0,6.410274,1.100000,0.384615,0.400000,0.150000,0.200000,0.400000,0.600000,0,0,1,0.000000,[],0.230769,0.538462,"['P00036956', 'P00075400', 'P00075399', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00036956', 'P00073179', 'P00075400', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,7.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,1394.1,-1534.4,-1066.7,-3.17,5875.3,113.6,-479.9,NaN,306.0,306.0,9111.0,138.1,NaN,NaN,NaN,NaN,11.8,790.8,-3.9,NaN,3.9,-1561.5,NaN,42.1,NaN,-3.6,-144.83,58992840.0,241.87,0.00,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.20,12.87,84.33,-8.543933e+09
28897,2776,ZYLOG,2017-03-31,22,3.091042,1,0.045455,1,65.125000,8,1,14,15,0.681818,7,6,2,9,5,1,3,1,2017,1,1,1,0,1,0,0,12,0,0,6.758655,1.590909,0.400000,0.409091,0.090909,0.227273,0.363636,0.636364,0,0,1,0.000000,[],0.200000,0.600000,"['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,9.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-145.22,58992840.0,259.57,-1.12,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,97.19,10.88,86.31,-8.566940e+09
28898,2776,ZYLOG,2018-03-31,22,3.091042,1,0.045455,1,65.125000,6,1,16,15,0.681818,7,5,1,10,6,1,3,1,2018,1,1,1,0,1,0,0,11,22,1,7.758655,2.272727,0.333333,0.454545,0.045455,0.272727,0.272727,0.727273,0,0,1,0.066667,['P00062851'],0.200000,0.533333,[],"['P00007571', 'P00013013', 'P00001781', 'P0003...",[],"['P00007571', 'P00013013', 'P00001781', 'P0000...",1.0,8.0,22.0,1.0,20.0,0.909091,15.0,1.0,14.0,0.933333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,58992840.0,156.33,-3.64,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.19,10.40,86.79,0.000000e+00

## Location Data

In [38]:
loc = pd.read_excel('Prowess IQ - Location Data.xlsx', skiprows = 5)
loc = loc.drop( ["Registrar Address", "Company Name"], axis = 1).dropna(how = "all")
loc

     Corporate Office Head Office Registered Office  Prowess company code
0              Mumbai    Vadodara          Vadodara                    11
1              Mumbai         NaN            Mumbai                384392
2              Mumbai         NaN       Navi Mumbai                 96387
3           Bengaluru         NaN         Bengaluru                 36277
4                 NaN      Mumbai              Pune                183396
...               ...         ...               ...                   ...
2542            Surat         NaN             Surat                275663
2543        Bengaluru         NaN               Goa                397515
2544         Gurugram         NaN               Goa                275679
2545        Ahmedabad   Ahmedabad         Ahmedabad                 41246
2546        Ahmedabad         NaN         Ahmedabad                 42684

[2547 rows x 4 columns]

In [39]:
loc["Office"] = np.where( pd.isnull(loc["Head Office"]), loc["Corporate Office"], loc["Head Office"])
loc["Office"] = np.where( pd.isnull(loc["Office"]), loc["Registered Office"], loc["Office"])
loc2 = loc.drop( ["Corporate Office", "Head Office", "Registered Office"], axis = 1).dropna(how = "all")
loc2

      Prowess company code     Office
0                       11   Vadodara
1                   384392     Mumbai
2                    96387     Mumbai
3                    36277  Bengaluru
4                   183396     Mumbai
...                    ...        ...
2542                275663      Surat
2543                397515  Bengaluru
2544                275679   Gurugram
2545                 41246  Ahmedabad
2546                 42684  Ahmedabad

[2547 rows x 2 columns]

In [40]:
firmLoc = merged2.merge(loc2, on = ["Prowess company code"], how = "left")

In [41]:
firmLoc

,FirmID,Symbol,AsOnDate,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted,Company Name,Sales,Profit after tax,PBDITA,Return on total assets,Total assets,Operating profit of non-financial companies,Operating profit of financial companies,Debt to equity ratio (times),Long term borrowings incl current portion,Long term borrowings excl current portion,Debt,Trade payables (Old Sch. VI),Subscribed preference capital,Paid up preference capital (net of forfeited preference capital) (Old Sch. VI),Paid up preference capital (net of forfeited preference capital),Paid up preference shares,Total other receivables,Net cash flow from operating activities,Cash (outflow) due to purchase of fixed assets,Cash inflow due to sale of fixed assets,Cash flow due to purchase of fixed assets,Net cash inflow or (outflow) from investing activities,Research & development expenses,Inter-corporate loans (Old Sch. VI),Deferred tax liability,Net deferred tax liabilities,BVPS,Shares Outstanding,Market Capitalisation,Total Returns,P/B,Market Capitalisation / Enterprise Value,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Total Shares (In %) - Shares held,Promoters (In %) - Shares held,Indian Promoters (In %) - Shares held,Foreign Promoters (In %) - Shares held,Non-promoters (In %) - Shares held,Non-promoter Institutions (In %) - Shares held,Non-promoter Non-institutions (In %) - Shares held,BVCommonStock,Office
0,0,20MICRONS,2009-03-31,12,2.484907,0,0.000000,0,69.166667,4,0,8,0,0.000000,12,0,4,0,8,0,1,1,2009,0,0,0,0,0,0,0,6,0,0,6.419178,0.000000,0.000000,0.000000,0.333333,0.666667,0.333333,0.666667,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00032270'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 Microns Ltd.,1454.8,13.4,144.7,4.38,1210.4,169.5,56.3,1.64,NaN,NaN,586.1,153.6,NaN,NaN,NaN,NaN,1.6,1.4,-94.1,4.2,94.1,-89.9,3.1,NaN,92.4,70.1,25.19,14205248.0,214.50,0.67,0.60,0.28,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,47.21,39.93,7.28,52.79,20.88,31.90,3.578302e+08,Vadodara
1,0,20MICRONS,2010-03-31,13,2.564949,0,0.000000,0,69.461538,4,0,9,0,0.000000,13,0,4,0,9,0,1,1,2010,0,0,0,0,0,0,0,7,0,0,6.893994,0.000000,0.000000,0.000000,0.307692,0.692308,0.307692,0.692308,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00031581'],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,1808.6,73.0,238.7,4.42,1583.7,218.6,95.5,2.03,NaN,NaN,843.3,158.4,NaN,NaN,NaN,NaN,41.4,32.7,-164.5,28.1,164.5,-196.5,2.4,NaN,100.7,98.7,29.03,14331028.0,559.63,-0.13,1.35,0.41,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,51.75,44.53,7.22,48.25,18.96,29.30,4.160297e+08,Vadodara
2,0,20MICRONS,2011-03-31,13,2.564949,0,0.000000,0,69.461538,2,0,11,0,0.000000,13,0,2,0,11,0,1,1,2011,0,0,0,0,0,0,0,6,0,0,7.893994,0.000000,0.000000,0.000000,0.153846,0.846154,0.153846,0.846154,0,0,0,0.000000,[],0.000000,0.000000,[],[],[],"['P00027662', 'P00027633', 'P00027664', 'P0002...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2408.3,55.0,256.1,3.02,1984.2,241.1,94.6,2.35,438.8,207.0,1048.9,232.8,NaN,NaN,NaN,NaN,0.6,73.5,-154.0,8.3,154.0,-147.9,3.2,7.3,109.6,104.8,31.12,14331028.0,532.40,-4.13,1.19,0.35,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,54.24,47.02,7.22,45.76,7.29,38.46,4.459816e+08,Vadodara
3,0,20MICRONS,2012-03-31,14,2.639057,0,0.000000,0,69.461538,2,0,12,0,0.000000,14,0,2,0,12,0,1,1,2012,0,0,0,0,0,0,0,6,0,0,8.324658,0.000000,0.000000,0.000000,0.142857,0.857143,0.142857,0.857143,0,0,0,0.000000,[],0.000000,0.000000,[],[],['P00042601'],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2678.4,107.8,368.5,4.40,2548.0,324.9,141.2,2.52,694.8,514.2,1447.7,216.0,NaN,NaN,NaN,NaN,32.2,117.9,-414.7,15.6,414.7,-397.2,3.9,22.7,112.8,109.2,36.38,14331028.0,1150.78,0.25,2.21,0.54,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,59.65,59.65,NaN,40.35,NaN,40.35,5.213628e+08,Vadodara
4,0,20MICRONS,2013-03-31,14,2.639057,0,0.000000,0,69.461538,1,0,13,5,0.357143,9,0,1,5,8,4,1,1,2013,1,1,1,1,1,1,1,3,0,0,9.324658,0.000000,0.000000,0.357143,0.071429,0.571429,0.071429,0.928571,0,0,0,0.000000,[],0.200000,0.200000,[],"['P00027633', 'P00031581', 'P00027665', 'P0002...",[],"['P00027662', 'P00027633', 'P00027664', 'P0004...",0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,2855.8,32.4,388.7,0.55,2805.9,343.7,43.2,2.21,831.7,647.1,1485.9,269.4,NaN,NaN,NaN,NaN,34.0,405.9,-409.5,1.9,409.5,-361.2,4.3,37.0,154.5,133.2,20.92,31662056.0,991.02,3.47,1.50,0.42,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,8.0,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",100.0,63.76,63.76,NaN,36.24,3.57,32.66,6.623702e+08,Vadodara
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28894,2776,ZYLOG,2014-03-31,13,2.564949,0,0.000000,0,67.166667,2,0,11,7,0.538462,6,1,1,6,5,1,3,1,2014,1,1,1,1,1,0,0,5,0,0,7.496944,0.538462,0.142857,0.461538,0.076923,0.384615,0.153846,0.846154,0,1,0,0.000000,[],0.428571,0.428571,['P00062851'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00048642', 'P00062851']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,3.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,10884.4,-4379.1,503.4,-25.56,16282.5,-402.7,-2108.7,1.88,3584.6,2692.0,9656.6,221.2,NaN,NaN,NaN,NaN,698.0,-1365.0,-2012.5,0.2,2012.5,-1354.6,NaN,964.7,286.2,285.5,86.95,58992840.0,634.17,1.42,0.12,0.06,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,52.95,6.25,46.70,5.129427e+09,NaN
28895,2776,ZYLOG,2015-03-31,15,2.708050,0,0.000000,0,67.166667,4,1,11,8,0.533333,7,2,2,6,5,1,3,1,2015,1,1,1,0,1,0,0,6,0,0,7.412237,0.933333,0.250000,0.400000,0.133333,0.333333,0.266667,0.733333,0,0,1,0.000000,[],0.375000,0.500000,['P00067111'],"['P00007571', 'P00013013', 'P00001781', 'P0002...","['P00067112', 'P00067111']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,4.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,3131.3,-6284.1,-4542.8,-10.22,14773.4,-47.8,-1501.6,NaN,1726.5,833.9,9873.9,143.0,NaN,NaN,NaN,NaN,735.8,-78.6,-0.1,0.0,0.1,-23.5,NaN,985.1,171.5,171.5,-19.57,58992840.0,250.72,-4.49,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,83.84,12.26,71.58,-1.154490e+09,NaN
28896,2776,ZYLOG,2016-03-31,20,2.995732,0,0.000000,0,65.125000,8,1,12,13,0.650000,7,5,3,8,4,1,3,1,2016,1,1,1,0,1,0,0,10,0,0,6.410274,1.100000,0.384615,0.400000,0.150000,0.200000,0.400000,0.600000,0,0,1,0.000000,[],0.230769,0.538462,"['P00036956', 'P00075400', 'P00075399', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00036956', 'P00073179', 'P00075400', 'P0007...","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,7.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,1394.1,-1534.4,-1066.7,-3.17,5875.3,113.6,-479.9,NaN,306.0,306.0,9111.0,138.1,NaN,NaN,NaN,NaN,11.8,790.8,-3.9,NaN,3.9,-1561.5,NaN,42.1,NaN,-3.6,-144.83,58992840.0,241.87,0.00,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.20,12.87,84.33,-8.543933e+09,NaN
28897,2776,ZYLOG,2017-03-31,22,3.091042,1,0.045455,1,65.125000,8,1,14,15,0.681818,7,6,2,9,5,1,3,1,2017,1,1,1,0,1,0,0,12,0,0,6.758655,1.590909,0.400000,0.409091,0.090909,0.227273,0.363636,0.636364,0,0,1,0.000000,[],0.200000,0.600000,"['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0003...","['P00081419', 'P00080494']","['P00007571', 'P00013013', 'P00001781', 'P0000...",0.0,9.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-145.22,58992840.0,259.57,-1.12,NaN,0.03,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.81,1.42,1.38,97.19,10.88,86.31,-8.566940e+09,NaN
28898,2776,ZYLOG,2018-03-31,22,3.091042,1,0.045455,1,65.125000,6,1,16,15,0.681818,7,5,1,10,6,1,3,1,2018,1,1,1,0,1,0,0,11,22,1,7.758655,2.272727,0.333333,0.454545,0.045455,0.272727,0.272727,0.727273,0,0,1,0.066667,['P00062851'],0.200000,0.533333,[],"['P00007571', 'P00013013', 'P00001781', 'P0003...",[],"['P00007571', 'P00013013', 'P00001781', 'P0000...",1.0,8.0,22.0,1.0,20.0,0.909091,15.0,1.0,14.0,0.933333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Zylog Systems Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,58992840.0,156.33,-3.64,NaN,0.02,275793.0,Public Ltd.,1.020302e+10,1995.0,Computer software,1.010408e+14,Providing software support and maintenance to ...,62013.0,2.010200e+10,Private (Indian),Between 1991 and 2013,ZYLOG,NaN,100.0,2.80,1.42,1.38,97.19,10.40,86.79,0.000000e+00,NaN

In [42]:
firmLoc.to_csv("Main_Firm_No Loc_Fin v140924.csv")