In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from tqdm import tqdm
tqdm.pandas()
from datetime import datetime

from dateutil.relativedelta import relativedelta
pd.set_option("display.max_columns", None)

# Date format = "%Y-%m-%d" @ datetime type

In [2]:
old = pd.read_csv("Dirlevel_with CAR and briefs_from 2013_81917.csv")
new = pd.read_csv("Main_Director_complete v160225.csv", index_col = 0)

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_860\977218778.py:1: DtypeWarning: Columns (28,32,42,53,54,55,56,57,58,115,116,117,118,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232) have mixed types. Specify dtype option on import or set low_memory=False.
  old = pd.read_csv("Dirlevel_with CAR and briefs_from 2013_81917.csv")
C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_860\977218778.py:2: DtypeWarning: Columns (26,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47) have mixed types. Specify dtype option on import or set low_memory=False.
  new = pd.read_csv("Main_Director_complete v160225.csv", index_col = 0)

In [3]:
old["AsOnDate"].unique()

array(['31-03-2015', '31-03-2014', '31-03-2013', '31-03-2016',
       '31-03-2017', '31-03-2018', '31-03-2019', '31-03-2020'],
      dtype=object)

In [4]:
new["AsOnDate"] = pd.to_datetime(new["AsOnDate"], format = "%Y-%m-%d")
new2 = new.loc[ (new["AsOnDate"]>= "2013-03-31") & (new["AsOnDate"] <= "2020-03-31"), :].copy().reset_index(drop = True)
new2["DirFullName"] = new2["Director First Name"] + " " + new2["Director Middle Name"] + " " + new2["Director Surname"]
new2 = new2.drop( ['Member of Civil Services', 'Education1', 'Education2', 'Education3', 'Education4', 'Education5', 'Education6',
                   'Education7', 'Education8', 'Education9', 'Education10', 'Occupation', 'Other Directorship 1',
                   'Other Directorship 2', 'Other Directorship 3', 'Other Directorship 4', 'Other Directorship 5', 'Other Directorship 6',
                   'Other Directorship 7', 'Other Directorship 8', 'Other Directorship 9', 'Other Directorship 10', 'Other Directorship 11',
                   'Other Directorship 12', 'Other Directorship 13', 'Other Directorship 14', 'Other Directorship 15',
                   'Tenure Valid till','cumsum_U', 'cumsum_Y', 'cumsum_N'], axis = 1)
new2.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Appointment Date',
 'Skills/Competencies',
 'Cessation Date',
 'Cessation Reason',
 'Brief Profile',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'PrevLastServed',
 'Indep',
 'OpBalUnc',
 'OpBalIndep',
 'OpBalNonIndep',
 'OpBalTotal',
 'CloBalUnc',
 'CloBalIndep',
 'CloBalNonIndep',
 'CloBalTotal',
 'YOE',
 'YOEmax',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManaged',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsIndep',
 'TenureInYearsTotal',
 'IsFirstTermIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'AsOnYear',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'DirFullName']

In [5]:
old["AsOnDate"] = pd.to_datetime(old["AsOnDate"], format = "%d-%m-%Y")

old2 = old.drop(['Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110',
                 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117',
                 'TradingDays', 'MM-3', 'MM-5', 'MM-11', 'FF3F-3', 'FF3F-5', 'FF3F-11', 'CM-3', 'CM-5', 'CM-11', 'MM-3-180', 'MM-5-180',
                 'MM-11-180', 'FF3F-3-180', 'FF3F-5-180', 'FF3F-11-180', 'CM-3-180', 'CM-5-180', 'CM-11-180', 'MM-3-200', 'MM-5-200',
                 'MM-11-200', 'FF3F-3-200', 'FF3F-5-200', 'FF3F-11-200', 'CM-3-200', 'CM-5-200', 'CM-11-200', 'MM-1+2-180', 'MM-1+4-180',
                 'MM-1+6-180', 'MM-1+8-180', 'MM-1+10-180', 'MM-1+12-180', 'FF3F-1+2-180', 'FF3F-1+4-180', 'FF3F-1+6-180', 'FF3F-1+8-180',
                 'FF3F-1+10-180', 'FF3F-1+12-180', 'CM-1+2-180', 'CM-1+4-180', 'CM-1+6-180', 'CM-1+8-180', 'CM-1+10-180', 'CM-1+12-180',
                 'MM-1+2-200', 'MM-1+4-200', 'MM-1+6-200', 'MM-1+8-200', 'MM-1+10-200', 'MM-1+12-200', 'FF3F-1+2-200', 'FF3F-1+4-200',
                 'FF3F-1+6-200', 'FF3F-1+8-200', 'FF3F-1+10-200', 'FF3F-1+12-200', 'CM-1+2-200', 'CM-1+4-200', 'CM-1+6-200', 'CM-1+8-200',
                 'CM-1+10-200', 'CM-1+12-200', 'CAR_250_3', 'CAR_210_3', 'CAR_180_3', 'CAR_150_3', 'CAR_250_5', 'CAR_210_5', 'CAR_180_5',
                 'CAR_150_5', 'CAR_250_7', 'CAR_210_7', 'CAR_180_7', 'CAR_150_7', 'CAR_250_11', 'CAR_210_11', 'CAR_180_11', 'CAR_150_11',
                 'CAR_250_21', 'CAR_210_21', 'CAR_180_21', 'CAR_150_21', 'CARFF_250_3', 'CARFF_210_3', 'CARFF_180_3', 'CARFF_150_3',
                 'CARFF_250_5', 'CARFF_210_5', 'CARFF_180_5', 'CARFF_150_5', 'CARFF_250_7', 'CARFF_210_7', 'CARFF_180_7', 'CARFF_150_7',
                 'CARFF_250_11', 'CARFF_210_11', 'CARFF_180_11', 'CARFF_150_11', 'CARFF_250_21', 'CARFF_210_21', 'CARFF_180_21',
                 'CARFF_150_21', 'Other Directorship 1', 'Other Directorship 2', 'Other Directorship 3', 'Other Directorship 4', 'Other Directorship 5',
                 'Other Directorship 6', 'Other Directorship 7', 'Other Directorship 8', 'Other Directorship 9', 'Other Directorship 10',
                 'Other Directorship 11', 'Other Directorship 12', 'Other Directorship 13', 'Other Directorship 14',
                 'Other Directorship 15','Education1_degree', 'Education1_branch', 'Unnamed: 28', 'Education1_college', 'Education1_city',
                 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Education2', 'Education3', 'Education4', 'Education5', 'Education6', 'Education7',
                 'Education8', 'Education9', 'Education10', 'Occupation', ], axis = 1)

old.columns.to_list()

['ResultId',
 'mRowId',
 'YearRowId',
 'SourceSheet',
 'AsOnDate',
 'ProfileRowId',
 'Symbol',
 'ISIN',
 'FirmDirectorMatch',
 'Company',
 'FinancialServices',
 'Person Code',
 'DirFullName',
 'DirCompId',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Appointment Date',
 'AppointmentDate_year',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Education1_degree',
 'Education1_branch',
 'Unnamed: 28',
 'Education1_college',
 'Education1_city',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Occupation',
 'Cessation Date',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'IsIndepStr',
 'eRowId',
 'PrevLastServed',
 'PrevLastServedMrowId',
 'OpBalUnclear',
 'OpBalIndep',
 'OpBalNonIndep',
 'OpBalTotal',
 'CloBalUnclear',
 'CloBalIndep',
 'ClobalNonIndep',
 'CloBalTotal',
 'CountOtherPastUnclear',
 'CountOtherPastIndep',
 'CountOtherPastNonIndep',
 'CompCountOtherPastTotal',
 'CountCurrUnclear',
 'CountCurrIndep',
 'CountCurrNonIndep',
 'CompCountCurrTotal',
 'CountCompaniesTotal',
 'IsConsidered',
 'IsMultiComp',
 'ProwLookUpIndepStatus',
 'IsRookie',
 'IsNonRookie',
 'IsIndep',
 'IsNonIndep',
 'IsTermLimitRetirement',
 'HasTermLimitRetirement',
 'IsRetires5y',
 'HasRetires5y',
 'AsOnYear',
 'IsCeoMD',
 'IsChairman',
 'IsPromoter2',
 'IsDualityChairmanMD',
 'IsFamilyManaged',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsFirstTermIndep',
 'TenureInYearsIndep',
 'TenureInYearsTotal',
 'NatLogDirships',
 'IsTurnOverIndep',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'Age',
 'IsFemale',
 'RawIsPromoterStatus',
 'IsBusy',
 'Dir_Brief_Profile',
 'Unnamed: 104',
 'Unnamed: 105',
 'Unnamed: 106',
 'Unnamed: 107',
 'Unnamed: 108',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Unnamed: 112',
 'Unnamed: 113',
 'Unnamed: 114',
 'Unnamed: 115',
 'Unnamed: 116',
 'Unnamed: 117',
 'TradingDays',
 'MM-3',
 'MM-5',
 'MM-11',
 'FF3F-3',
 'FF3F-5',
 'FF3F-11',
 'CM-3',
 'CM-5',
 'CM-11',
 'MM-3-180',
 'MM-5-180',
 'MM-11-180',
 'FF3F-3-180',
 'FF3F-5-180',
 'FF3F-11-180',
 'CM-3-180',
 'CM-5-180',
 'CM-11-180',
 'MM-3-200',
 'MM-5-200',
 'MM-11-200',
 'FF3F-3-200',
 'FF3F-5-200',
 'FF3F-11-200',
 'CM-3-200',
 'CM-5-200',
 'CM-11-200',
 'MM-1+2-180',
 'MM-1+4-180',
 'MM-1+6-180',
 'MM-1+8-180',
 'MM-1+10-180',
 'MM-1+12-180',
 'FF3F-1+2-180',
 'FF3F-1+4-180',
 'FF3F-1+6-180',
 'FF3F-1+8-180',
 'FF3F-1+10-180',
 'FF3F-1+12-180',
 'CM-1+2-180',
 'CM-1+4-180',
 'CM-1+6-180',
 'CM-1+8-180',
 'CM-1+10-180',
 'CM-1+12-180',
 'MM-1+2-200',
 'MM-1+4-200',
 'MM-1+6-200',
 'MM-1+8-200',
 'MM-1+10-200',
 'MM-1+12-200',
 'FF3F-1+2-200',
 'FF3F-1+4-200',
 'FF3F-1+6-200',
 'FF3F-1+8-200',
 'FF3F-1+10-200',
 'FF3F-1+12-200',
 'CM-1+2-200',
 'CM-1+4-200',
 'CM-1+6-200',
 'CM-1+8-200',
 'CM-1+10-200',
 'CM-1+12-200',
 'CAR_250_3',
 'CAR_210_3',
 'CAR_180_3',
 'CAR_150_3',
 'CAR_250_5',
 'CAR_210_5',
 'CAR_180_5',
 'CAR_150_5',
 'CAR_250_7',
 'CAR_210_7',
 'CAR_180_7',
 'CAR_150_7',
 'CAR_250_11',
 'CAR_210_11',
 'CAR_180_11',
 'CAR_150_11',
 'CAR_250_21',
 'CAR_210_21',
 'CAR_180_21',
 'CAR_150_21',
 'CARFF_250_3',
 'CARFF_210_3',
 'CARFF_180_3',
 'CARFF_150_3',
 'CARFF_250_5',
 'CARFF_210_5',
 'CARFF_180_5',
 'CARFF_150_5',
 'CARFF_250_7',
 'CARFF_210_7',
 'CARFF_180_7',
 'CARFF_150_7',
 'CARFF_250_11',
 'CARFF_210_11',
 'CARFF_180_11',
 'CARFF_150_11',
 'CARFF_250_21',
 'CARFF_210_21',
 'CARFF_180_21',
 'CARFF_150_21']

In [6]:
new2 = new2.sort_values( by = ["DirFullName"])
old2 = old2.sort_values( by = ["DirFullName"])

In [7]:
old2

,ResultId,mRowId,YearRowId,SourceSheet,AsOnDate,ProfileRowId,Symbol,ISIN,FirmDirectorMatch,Company,FinancialServices,Person Code,DirFullName,DirCompId,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Cessation Date,Cessation Reason,IsIndepStr,eRowId,PrevLastServed,PrevLastServedMrowId,OpBalUnclear,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnclear,CloBalIndep,ClobalNonIndep,CloBalTotal,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie,IsNonRookie,IsIndep,IsNonIndep,IsTermLimitRetirement,HasTermLimitRetirement,IsRetires5y,HasRetires5y,AsOnYear,IsCeoMD,IsChairman,IsPromoter2,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsFirstTermIndep,TenureInYearsIndep,TenureInYearsTotal,NatLogDirships,IsTurnOverIndep,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,Age,IsFemale,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
60336,167090,250976,2.020000e+12,MasterProfile_20190331,2019-03-31,19727,ORIENTBANK,INE141A01014,8191,oriental bank of commerce,1,P00068720,A. ALSE BALAKRISHNA,ORIENTBANK_P00068720,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,26-12-2018,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,167090,NaN,0,0,0,3,3,0,0,15,15,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,NaN,0,0,0,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...
40270,146903,229237,2.020000e+12,MasterProfile_20180331,2018-03-31,26512,TVSSRICHAK,INE421C01016,4241,tvs srichakra ltd.,0,P00028579,A. ARUMUGAM,TVSSRICHAK_P00028579,MR.,A.,NaN,ARUMUGAM,NaN,M,NaN,03-12-2014,2014,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,146903,31-03-2017,200852,0,39,0,39,0,51,0,51,0,0,0,0,0,1,0,1,1,True,False,NaN,0,1,1,0,0,0,0,0,2018,0,0,0,0,0,0,0,1,4,4,0.0,0,0,0,1,0,NaN,0,0,0,"TILL 2012, HE WAS MD AT JRE PARTNERS, AN ASIAN..."
33524,146901,174591,2.020000e+12,MasterProfile_20160331,2016-03-31,22788,TVSSRICHAK,INE421C01016,4557,tvs srichakra ltd.,0,P00028579,A. ARUMUGAM,TVSSRICHAK_P00028579,MR.,A.,NaN,ARUMUGAM,NaN,M,NaN,03-12-2014,2014,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,146901,31-03-2015,150222,0,15,0,15,0,27,0,27,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2016,0,0,0,0,0,0,0,1,2,2,0.0,0,1,0,0,0,NaN,0,0,0,"TILL 2012, HE WAS MD AT JRE PARTNERS, AN ASIAN..."
23136,146900,150222,2.020000e+12,MasterProfile_20150331,2015-03-31,21285,TVSSRICHAK,INE421C01016,3987,tvs srichakra ltd.,0,P00028579,A. ARUMUGAM,TVSSRICHAK_P00028579,MR.,A.,NaN,ARUMUGAM,NaN,M,NaN,03-12-2014,2014,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,146900,NaN,0,0,3,0,3,0,15,0,15,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2015,0,0,0,0,0,0,0,1,1,1,0.0,1,1,0,0,0,NaN,0,0,0,"TILL 2012, HE WAS MD AT JRE PARTNERS, AN ASIAN..."
33525,146902,200852,2.020000e+12,MasterProfile_20170331,2017-03-31,24522,TVSSRICHAK,INE421C01016,4557,tvs srichakra ltd.,0,P00028579,A. ARUMUGAM,TVSSRICHAK_P00028579,MR.,A.,NaN,ARUMUGAM,NaN,M,NaN,03-12-2014,2014,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,146902,31-03-2016,174591,0,27,0,27,0,39,0,39,0,0,0,0,0,1,0,1,1,True,False,NaN,0,1,1,0,0,0,0,0,2017,0,0,0,0,0,0,0,1,3,3,0.0,0,0,0,1,0,NaN,0,0,0,"TILL 2012, HE WAS MD AT JRE PARTNERS, AN ASIAN..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76981,9616,208384,2.020000e+12,MasterProfile_20180331,2018-03-31,5659,CREATIVEYE,INE230B01021,6773,creative eye ltd.,0,P00005282,ZUBY DHEERAJKUMAR KOCHHAR,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9616,31-03-2017,181457,320,0,60,380,320,0,72,392,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2018,0,0,1,0,0,0,0,0,0,32,0.0,0,0,0,0,1,67.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
76982,9617,237279,2.020000e+12,MasterProfile_20190331,2019-03-31,6030,CREATIVEYE,INE230B01021,6773,creative eye ltd.,0,P00005282,ZUBY DHEERAJKUMAR KOCHHAR,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9617,31-03-2018,208384,320,0,72,392,320,0,84,404,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2019,0,0,1,0,0,0,0,0,0,33,0.0,0,0,0,0,1,68.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
72687,9615,181457,2.020000e+12,MasterProfile_20170331,2017-03-31,5127,CREATIVEYE,INE230B01021,6180,creative eye ltd.,0,P00005282,ZUBY DHEERAJKUMAR KOCHHAR,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9615,31-03-2016,156557,320,0,48,368,320,0,60,380,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2017,0,0,1,0,0,0,0,0,0,31,0.0,0,0,0,0,1,66.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
72686,9614,156557,2.020000e+12,MasterProfile_20160331,2016-03-31,4754,CREATIVEYE,INE230B01021,7023,creative eye ltd.,0,P00005282,ZUBY DHEERAJKUMAR KOCHHAR,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9614,31-03-2015,133384,320,0,36,356,320,0,48,368,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2016,0,0,1,0,0,0,0,0,0,30,0.0,0,0,0,0,1,65.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
66229,9613,133384,2.020000e+12,MasterProfile_20150331,2015-03-31,4447,CREATIVEYE,INE230B01021,4959,creative eye ltd.,0,P00005282,ZUBY DHEERAJKUMAR KOCHHAR,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9613,31-03-2014,111852,320,0,24,344,320,0,36,356,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2015,0,0,1,0,0,0,0,0,0,29,0.0,0,0,0,0,1,64.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...

In [8]:
old2.loc[ old2["TenureInYearsTotal"] >= 3][["OpBalTotal", "TenureInYearsTotal"]]

       OpBalTotal  TenureInYearsTotal
40270          39                   4
33525          27                   3
8035           51                   5
8034           39                   4
41041          89                   8
...           ...                 ...
76981         380                  32
76982         392                  33
72687         368                  31
72686         356                  30
66229         344                  29

[64317 rows x 2 columns]

In [9]:
old2.loc[ old2["IsRookie"] == 0]["OpBalTotal"].value_counts()

OpBalTotal
31     876
34     857
25     707
28     703
30     699
      ...
602      1
554      1
566      1
648      1
589      1
Name: count, Length: 672, dtype: int64

In [10]:
old2.loc[ old2["CloBalTotal"] > 36 ]["IsRookie"].value_counts()

IsRookie
0    63639
Name: count, dtype: int64

In [11]:
new2.loc[ new2["CloBalTotal"] < 48 ]["IsRookie"].value_counts()

Series([], Name: count, dtype: int64)

In [44]:
old2["IsRookie"].value_counts()

IsRookie
0    64317
1    17599
Name: count, dtype: int64

In [45]:
new2["IsRookie"].value_counts()

IsRookie
0    73649
1    25938
Name: count, dtype: int64

In [12]:
merged = new2.merge( old2, on = ["DirFullName", "AsOnDate", "Symbol"] , how = "inner")
merged

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
0,ORIENTBANK,ORIENTAL BANK OF COMMERCE,2019-03-31,P00091605,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,2018-12-26,NaN,NaN,NaN,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...,NO,EXECUTIVE DIRECTOR,NO,NaN,N,95.0,0,0,95.0,95.0,0,365,460.0,95.0,95.0,(),"(('ORIENTAL BANK OF COMMERCE', 'N'),)","(('ORIENTAL BANK OF COMMERCE', 'N'),)",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,0.0,0.260274,0,0,0,0,2019,1,0,0,0,A. ALSE BALAKRISHNA,167090,250976,2.020000e+12,MasterProfile_20190331,19727,INE141A01014,8191,oriental bank of commerce,1,P00068720,ORIENTBANK_P00068720,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,26-12-2018,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,167090,NaN,0,0,0,3,3,0,0,15,15,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,NaN,0,0,0,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...
1,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2014-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2013-03-31,N,885.0,0,365,1250.0,885.0,0,730,1615.0,1251.0,1251.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,3.424658,0,0,0,0,2014,0,0,0,0,A. J. SURIYANARAYANA,120190,118128,2.010000e+12,MasterProfile_20140331,10289,INE036D01028,3665,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,27-10-2010,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120190,31-03-2013,97671,29,0,12,41,29,0,24,53,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2014,0,0,1,0,0,0,0,0,0,4,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
2,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2015-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2014-03-31,N,885.0,0,730,1615.0,885.0,0,1095,1980.0,1616.0,1616.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,4.424658,0,1,0,0,2015,0,0,0,0,A. J. SURIYANARAYANA,120191,140296,2.020000e+12,MasterProfile_20150331,11359,INE036D01028,3665,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,27-10-2010,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120191,31-03-2014,118128,29,0,24,53,29,0,36,65,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2015,0,0,1,0,0,0,0,0,0,5,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
3,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2018-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2017-03-31,N,885.0,0,1825,2710.0,885.0,0,2190,3075.0,2712.0,2712.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,7.424658,0,0,0,0,2018,1,0,0,0,A. J. SURIYANARAYANA,120194,216640,2.020000e+12,MasterProfile_20180331,13915,INE036D01028,486,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,27-10-2010,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120194,31-03-2017,189234,29,0,60,89,29,0,72,101,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2018,0,0,1,0,0,0,0,0,0,8,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
4,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2017-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2016-03-31,N,885.0,0,1460,2345.0,885.0,0,1825,2710.0,2347.0,2347.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,6.424658,0,0,0,0,2017,0,0,0,0,A. J. SURIYANARAYANA,120193,189234,2.020000e+12,MasterProfile_20170331,12904,INE036D01028,1903,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,27-10-2010,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120193,31-03-2016,163793,29,0,48,77,29,0,60,89,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2017,0,0,1,0,0,0,0,0,0,7,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50209,CREATIVEYE,CREATIVE EYE LTD.,2014-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"WHOLETIME DIRECTOR, EXECUTIVE DIRECTOR, PROMOT...",NO,2013-03-31,N,9741.0,0,365,10106.0,9741.0,0,730,10471.0,10108.0,10108.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,27.687671,0,0,0,1,2014,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9612,111852,2.010000e+12,MasterProfile_20140331,4013,INE230B01021,4959,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"WHOLETIME DIRECTOR, EXECUTIVE DIRECTOR, PROMOT...",NaN,NaN,N,9612,31-03-2013,91729,320,0,12,332,320,0,24,344,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2014,0,0,1,0,0,0,0,0,0,28,0.0,0,0,0,0,1,63.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50210,CREATIVEYE,CREATIVE EYE LTD.,2016-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2015-03-31,N,9741.0,0,1095,10836.0,9741.0,0,1460,11201.0,10839.0,10839.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,29.687671,0,0,0,1,2016,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9614,156557,2.020000e+12,MasterProfile_20160331,4754,INE230B01021,7023,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9614,31-03-2015,133384,320,0,36,356,320,0,48,368,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2016,0,0,1,0,0,0,0,0,0,30,0.0,0,0,0,0,1,65.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50211,CREATIVEYE,CREATIVE EYE LTD.,2015-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2014-03-31,N,9741.0,0,730,10471.0,9741.0,0,1095,10836.0,10473.0,10473.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,28.687671,0,0,0,1,2015,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9613,133384,2.020000e+12,MasterProfile_20150331,4447,INE230B01021,4959,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9613,31-03-2014,111852,320,0,24,344,320,0,36,356,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2015,0,0,1,0,0,0,0,0,0,29,0.0,0,0,0,0,1,64.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50212,CREATIVEYE,CREATIVE EYE LTD.,2013-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,PROMOTER-DIRECTOR,NO,2012-03-31,N,9741.0,0,0,9741.0,9741.0,0,365,10106.0,9743.0,9743.0,"(('CREATIVEYE', 'U'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'),)","(('CREATIVEYE', 'U'),)",1,0,0,1,1,0,0,1,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,26.687671,0,0,0,1,2013,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9611,91729,2.010000e+12,MasterProfile_20130331,3760,INE230B01021,4959,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,PROMOTER-DIRECTOR,NaN,NaN,N,9611,31-03-2012,73089,320,0,0,320,320,0,12,332,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2013,0,0,1,0,0,0,0,0,0,27,0.0,0,0,0,0,1,62.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50213,CREATIVEYE,CREATIVE EYE LTD.,2018-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2017-03-31,N,9741.0,0,1825,11566.0,9741.0,0,2190,11931.0,11569.0,11569.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,31.687671,0,0,0,1,2018,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9616,208384,2.020000e+12,MasterProfile_20180331,5659,INE230B01021,6773,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,28-07-1986,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9616,31-03-2017,181457,320,0,60,380,320,0,72,392,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2018,0,0,1,0,0,0,0,0,0,32,0.0,0,0,0,0,1,67.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...

# IsRookie

In [13]:
# IsRookie_y	IsNonRookie_y	IsIndep_y	IsNonIndep_y	
# IsTermLimitRetirement_y	HasTermLimitRetirement_y	IsRetires5y_y	HasRetires5y_y	
# IsCeoMD_y	IsChairman_y	
# IsPromoter2	
# IsDualityChairmanMD_y	IsFamilyManaged_y	IsFamilyChairman_y	 IsFamilyChairmanAndCEO_y	
# IsFirstTermIndep_y	TenureInYearsIndep_y	TenureInYearsTotal_y	
# IsTurnOverIndep_y	
# IsRookieIndep_y	IsRookieNonIndep_y	IsNonRookieIndep_y	IsNonRookieNonIndep_y
# Age_y	IsFemale_y

In [14]:
IsRookieMatchIndex = (merged["IsRookie_y"] == merged["IsRookie_x"]).to_frame()
IsRookieMatchIndex.loc[ IsRookieMatchIndex[0] == False, :]

           0
6      False
17     False
18     False
31     False
33     False
...      ...
50132  False
50136  False
50144  False
50163  False
50195  False

[4648 rows x 1 columns]

In [15]:
IsRookieNoMatch = merged.iloc[IsRookieMatchIndex.loc[ IsRookieMatchIndex[0] == False, :].index, ][["YOE", "YOEmax", "TenureInYearsTotal_x", "TenureInYearsTotal_y", "IsRookie_x", "IsRookie_y"]]
IsRookieNoMatch

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
6,1034.0,1034.0,2.830137,3,1,0
17,996.0,996.0,2.726027,3,1,0
18,775.0,775.0,2.123288,3,1,0
31,1095.0,1095.0,2.997260,3,1,0
33,878.0,878.0,2.405479,3,1,0
...,...,...,...,...,...,...
50132,1053.0,1053.0,2.884932,3,1,0
50136,871.0,1053.0,2.386301,3,1,0
50144,977.0,977.0,2.676712,3,1,0
50163,1002.0,1002.0,2.742466,3,1,0
50195,266.0,3627.0,0.728767,1,0,1

In [16]:
IsRookieNoMatch.loc[ (IsRookieNoMatch["IsRookie_x"] == 1)]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
6,1034.0,1034.0,2.830137,3,1,0
17,996.0,996.0,2.726027,3,1,0
18,775.0,775.0,2.123288,3,1,0
31,1095.0,1095.0,2.997260,3,1,0
33,878.0,878.0,2.405479,3,1,0
...,...,...,...,...,...,...
50122,793.0,793.0,2.169863,3,1,0
50132,1053.0,1053.0,2.884932,3,1,0
50136,871.0,1053.0,2.386301,3,1,0
50144,977.0,977.0,2.676712,3,1,0
50163,1002.0,1002.0,2.742466,3,1,0

In [17]:
IsRookieNoMatch.loc[ (IsRookieNoMatch["IsRookie_y"] == 1)]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
93,3256.0,3256.0,8.915068,2,0,1
94,2891.0,2891.0,7.915068,1,0,1
139,528.0,2763.0,1.446575,2,0,1
252,538.0,11743.0,1.471233,2,0,1
259,172.0,11377.0,0.471233,1,0,1
...,...,...,...,...,...,...
49895,411.0,3004.0,1.126027,2,0,1
49899,639.0,1178.0,1.750685,2,0,1
49905,55.0,3369.0,0.150685,1,0,1
49906,421.0,1142.0,1.150685,2,0,1
50195,266.0,3627.0,0.728767,1,0,1

In [18]:
IsRookieNoMatch.loc[ (IsRookieNoMatch["TenureInYearsTotal_x"] < 3) & (IsRookieNoMatch["TenureInYearsTotal_y"] == 3)]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
6,1034.0,1034.0,2.830137,3,1,0
17,996.0,996.0,2.726027,3,1,0
18,775.0,775.0,2.123288,3,1,0
31,1095.0,1095.0,2.997260,3,1,0
33,878.0,878.0,2.405479,3,1,0
...,...,...,...,...,...,...
50122,793.0,793.0,2.169863,3,1,0
50132,1053.0,1053.0,2.884932,3,1,0
50136,871.0,1053.0,2.386301,3,1,0
50144,977.0,977.0,2.676712,3,1,0
50163,1002.0,1002.0,2.742466,3,1,0

In [19]:
IsRookieNoMatch.loc[ (IsRookieNoMatch["TenureInYearsTotal_x"] >3 )]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
93,3256.0,3256.0,8.915068,2,0,1
94,2891.0,2891.0,7.915068,1,0,1
18969,1924.0,7363.0,5.268493,2,0,1
24481,1859.0,1859.0,5.090411,2,0,1
26732,1914.0,1914.0,5.241096,2,0,1
34771,1439.0,3750.0,3.939726,2,0,1
39044,1161.0,1161.0,3.178082,1,0,1

In [20]:
IsRookieNoMatch.loc[ (IsRookieNoMatch["IsRookie_x"] == 1 ) & (IsRookieNoMatch["TenureInYearsTotal_x"] >= 3 )]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
2043,1095.0,1095.0,3.0,3,1,0
6553,1095.0,1095.0,3.0,3,1,0
8297,1095.0,1095.0,3.0,4,1,0
8705,1095.0,1095.0,3.0,3,1,0
16857,1095.0,1095.0,3.0,3,1,0
21681,1095.0,1095.0,3.0,3,1,0
25318,1095.0,1095.0,3.0,3,1,0
25972,1095.0,1095.0,3.0,3,1,0
26515,1095.0,1095.0,3.0,3,1,0
28363,1095.0,1095.0,3.0,4,1,0
32353,1095.0,1095.0,3.0,4,1,0
39016,1095.0,1095.0,3.0,3,1,0
42073,1095.0,1095.0,3.0,4,1,0
48182,1095.0,1095.0,3.0,3,1,0

In [21]:
IsRookieNoMatch.IsRookie_x.value_counts()

IsRookie_x
1    3174
0    1474
Name: count, dtype: int64

In [22]:
IsRookieNoMatch.loc[ ~ ((IsRookieNoMatch["TenureInYearsTotal_x"] < 3) & (IsRookieNoMatch["TenureInYearsTotal_y"] >= 3))]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
93,3256.0,3256.0,8.915068,2,0,1
94,2891.0,2891.0,7.915068,1,0,1
139,528.0,2763.0,1.446575,2,0,1
252,538.0,11743.0,1.471233,2,0,1
259,172.0,11377.0,0.471233,1,0,1
...,...,...,...,...,...,...
49895,411.0,3004.0,1.126027,2,0,1
49899,639.0,1178.0,1.750685,2,0,1
49905,55.0,3369.0,0.150685,1,0,1
49906,421.0,1142.0,1.150685,2,0,1
50195,266.0,3627.0,0.728767,1,0,1

In [23]:
merged.iloc[[94]]

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
94,J&KBANK,"JAMMU & KASHMIR BANK LTD.,THE",2016-03-31,P00038706,MR.,ABDUL,MAJID,MIR,1951-06-07,M,INDIA,2008-05-01,NaN,NaN,NaN,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC...",NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NO,2015-03-31,N,2889.0,0,0,2889.0,2889.0,0,365,3254.0,2891.0,2891.0,"(('J&KBANK', 'U'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'), ('JAM...","(('J&KBANK', 'U'),)","(('J&KBANK', 'U'),)",1,0,0,1,1,0,0,1,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,73.0,0.0,7.915068,0,0,0,0,2016,0,0,0,0,ABDUL MAJID MIR,153100,162790,2.020000e+12,MasterProfile_20160331,10987,INE168A01041,1409,"jammu & kashmir bank ltd.,the",1,P00037718,J&KBANK_P00037718,MR.,ABDUL,MAJID,MIR,07-06-1951,M,INDIA,22-08-2015,2015,NONE,NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NaN,NaN,N,153100,NaN,0,0,0,7,7,0,0,19,19,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,65.0,0,0,0,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC..."

In [24]:
IsRookieNoMatch.loc[(~ ((IsRookieNoMatch["TenureInYearsTotal_x"] < 3) & (IsRookieNoMatch["TenureInYearsTotal_y"] >= 3))) & (IsRookieNoMatch["YOE"] != IsRookieNoMatch["YOEmax"])]

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
139,528.0,2763.0,1.446575,2,0,1
252,538.0,11743.0,1.471233,2,0,1
259,172.0,11377.0,0.471233,1,0,1
299,679.0,1553.0,1.857534,2,0,1
348,525.0,2716.0,1.438356,2,0,1
...,...,...,...,...,...,...
49895,411.0,3004.0,1.126027,2,0,1
49899,639.0,1178.0,1.750685,2,0,1
49905,55.0,3369.0,0.150685,1,0,1
49906,421.0,1142.0,1.150685,2,0,1
50195,266.0,3627.0,0.728767,1,0,1

In [25]:
merged["Appointment Date_y"] = pd.to_datetime(merged["Appointment Date_y"], format = "%d-%m-%Y")
merged["Appointment Date_x"] = pd.to_datetime(merged["Appointment Date_x"], format = "%Y-%m-%d")

merged.loc[ merged["Appointment Date_y"] != merged["Appointment Date_x"] ]

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
92,J&KBANK,"JAMMU & KASHMIR BANK LTD.,THE",2018-03-31,P00038706,MR.,ABDUL,MAJID,MIR,1951-06-07,M,INDIA,2008-05-01,NaN,NaN,NaN,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC...",NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NO,2017-03-31,N,2889.0,0,730,3619.0,2889.0,0,1095,3984.0,3621.0,3621.0,"(('J&KBANK', 'U'), ('J&KBANK', 'N'))","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'), ('JAM...","(('J&KBANK', 'U'), ('J&KBANK', 'N'))","(('J&KBANK', 'U'), ('J&KBANK', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,73.0,0.0,9.915068,0,0,1,0,2018,1,0,1,0,ABDUL MAJID MIR,153102,215568,2.020000e+12,MasterProfile_20180331,12843,INE168A01041,2905,"jammu & kashmir bank ltd.,the",1,P00037718,J&KBANK_P00037718,MR.,ABDUL,MAJID,MIR,07-06-1951,M,INDIA,2015-08-22,2015,NONE,NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NaN,NaN,N,153102,31-03-2017,188204,0,0,31,31,0,0,43,43,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2018,0,0,0,0,0,0,0,0,0,3,0.000000,0,0,0,0,1,67.0,0,0,0,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC..."
93,J&KBANK,"JAMMU & KASHMIR BANK LTD.,THE",2017-03-31,P00038706,MR.,ABDUL,MAJID,MIR,1951-06-07,M,INDIA,2008-05-01,NaN,NaN,NaN,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC...",NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NO,2016-03-31,N,2889.0,0,365,3254.0,2889.0,0,730,3619.0,3256.0,3256.0,"(('J&KBANK', 'U'), ('J&KBANK', 'N'))","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'), ('JAM...","(('J&KBANK', 'U'), ('J&KBANK', 'N'))","(('J&KBANK', 'U'), ('J&KBANK', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,73.0,0.0,8.915068,0,0,0,0,2017,0,0,0,0,ABDUL MAJID MIR,153101,188204,2.020000e+12,MasterProfile_20170331,11874,INE168A01041,1409,"jammu & kashmir bank ltd.,the",1,P00037718,J&KBANK_P00037718,MR.,ABDUL,MAJID,MIR,07-06-1951,M,INDIA,2015-08-22,2015,NONE,NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NaN,NaN,N,153101,31-03-2016,162790,0,0,19,19,0,0,31,31,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2017,0,0,0,0,0,0,0,0,0,2,0.000000,0,0,1,0,0,66.0,0,0,0,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC..."
94,J&KBANK,"JAMMU & KASHMIR BANK LTD.,THE",2016-03-31,P00038706,MR.,ABDUL,MAJID,MIR,1951-06-07,M,INDIA,2008-05-01,NaN,NaN,NaN,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC...",NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NO,2015-03-31,N,2889.0,0,0,2889.0,2889.0,0,365,3254.0,2891.0,2891.0,"(('J&KBANK', 'U'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'),)","(('JAMMU & KASHMIR BANK LTD.,THE', 'N'), ('JAM...","(('J&KBANK', 'U'),)","(('J&KBANK', 'U'),)",1,0,0,1,1,0,0,1,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,73.0,0.0,7.915068,0,0,0,0,2016,0,0,0,0,ABDUL MAJID MIR,153100,162790,2.020000e+12,MasterProfile_20160331,10987,INE168A01041,1409,"jammu & kashmir bank ltd.,the",1,P00037718,J&KBANK_P00037718,MR.,ABDUL,MAJID,MIR,07-06-1951,M,INDIA,2015-08-22,2015,NONE,NO,"SHAREHOLDERS DIRECTOR, NON-EXECUTIVE DIRECTOR",NaN,NaN,N,153100,NaN,0,0,0,7,7,0,0,19,19,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,1,0.000000,0,0,1,0,0,65.0,0,0,0,"MR. ABDUL MAJID MIR, HAS 40 YEARS OF EXPERIENC..."
8628,SBIN,STATE BANK OF INDIA,2020-03-31,P00096953,MR.,CHALLA,SREENIVASULU,SETTY,1965-09-26,M,NaN,2020-01-20,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,E...",NaN,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,N,71.0,0,0,71.0,71.0,0,365,436.0,71.0,71.0,(),"(('STATE BANK OF INDIA', 'N'),)","(('STATE BANK OF INDIA', 'N'), ('STATE BANK OF...",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,Y,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,59.0,0.0,0.194521,0,0,0,0,2020,0,0,0,0,CHALLA SREENIVASULU SETTY,169440,287868,2.020000e+12,MasterProfile_20200331,26660,INE062A01020,2184,state bank of india,1,P00068933,SBIN_P00068933,MR.,CHALLA,SREENIVASULU,SETTY,26-09-1965,M,NaN,2020-01-21,2020,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NaN,NaN,N,169440,NaN,0,0,0,2,2,0,0,14,14,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2020,1,0,0,0,0,0,0,0,0,1,0.000000,0,0,1,0,0,55.0,0,0,0,NaN
8783,HIL,HIL LTD.,2013-03-31,P00000439,MR.,CHANDRA,KANT,BIRLA,1955-01-09,M,INDIA,1980-02-02,"ACCOUNTS/AUDIT/TAXATION,COMMODITIES,CONSUMER D...",NaN,NaN,MR. CK BIRLA IS AN INDIAN INDUSTRIALIST HAVING...,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,2012-03-31,N,12109.0,0,0,12109.0,12109.0,0,365,12474.0,12111.0,12602.0,"(('FKONCO', 'U'), ('ORIENTPPR', 'U'), ('HIL', ...","(('HIL LTD.', 'N'), ('HINDUSTAN MOTORS LTD.', ...","(('HIL LTD.', 'N'), ('HINDUSTAN MOTORS LTD.', ...","(('FKONCO', 'U'), ('ORIENTPPR', 'U'), ('HIL', ...","(('FKONCO', 'U'), ('ORIENTPPR', 'U'), ('HIL', ...",4,0,0,4,4,0,0,4,0,0,3,3,1,0,3,4,N,0,1,0,1,0,1,1,1,1,0,0,1,0,0,0,0,1,0,70.0,0.0,33.175342,0,0,0,1,2013,0,0,0,0,CHANDRA KANT BIRLA,3849,95002,2.010000e+12,MasterProfile_20130331,7033,INE557A01011,4669,hil ltd.,0,P00014204,HIL_P00014204,MR.,CHANDRA,KANT,BIRLA,09-01-1955,M,INDIA,1980-02-04,1980,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NaN,NaN,N,3849,31-03-2012,76131,397,0,0,397,397,0,12,409,1,0,0,1,0,0,3,3,4,True,True,NaN,0,1,0,1,0,0,0,0,2013,0,1,1,0,0,1,1,0,0,34,1.098612,0,0,0,0,1,58.0,0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43280,SHIVAMAUTO,SHIVAM AUTOTECH LTD.,2019-03-31,P00002378,MR.,SUNIL,KANT,MUNJAL,1957-12-14,M,INDIA,2006-02-14,"CONSUMER DISCRETIONARY,CORPORATE GOVERNANCE,DI...",NaN,NaN,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",YES,2018-03-31,Y,2600.0,1460,730,4790.0,2600.0,1825,730,5155.0,4793.0,5801.0,"(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('DCM SHRIRAM ...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('DCM SHRIRAM ...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...",4,2,2,8,4,2,2,8,0,2,0,2,1,2,0,3,N,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,67.0,4.0,13.123288,0,0,0,1,2019,0,0,0,0,SUNIL KANT MUNJAL,85291,255158,2.020000e+12,MasterProfile_20190331,23909,INE637H01024,6147,shivam autotech ltd.,0,P00001110,SHIVAMAUTO_P00001110,MR.,SUNIL,KANT,MUNJAL,14-12-1957,M,INDIA,2006-09-20,2006,NONE,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",NaN,NaN,Y,85291,31-03-2018,225428,78,48,24,150,78,60,24,162,2,0,1,3,0,2,0,2,5,True,True,NaN,0,1,1,0,0,0,0,0,2019,0,1,0,0,0,0,0,0,5,13,0.693147,0,0,0,1,0,62.0,0,0,0,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...
43287,SHIVAMAUTO,SHIVAM AUTOTECH LTD.,2020-03-31,P00002378,MR.,SUNIL,KANT,MUNJAL,1957-12-14,M,INDIA,2006-02-14,"CONSUMER DISCRETIONARY,CORPORATE GOVERNANCE,DI...",NaN,NaN,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",YES,2019-03-31,Y,2600.0,1825,730,5155.0,2600.0,2190,730,5520.0,5159.0,6167.0,"(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('ESCORTS KUBO...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('ESCORTS KUBO...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...",4,2,2,8,4,2,2,8,0,3,0,3,1,3,0,4,N,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,67.0,5.0,14.123288,0,0,0,1,2020,1,0,0,1,SUNIL KANT MUNJAL,85292,286407,2.020000e+12,MasterProfile_20200331,25199,INE637H01024,2001,shivam autotech ltd.,0,P00001110,SHIVAMAUTO_P00001110,MR.,SUNIL,KANT,MUNJAL,14-12-1957,M,INDIA,2006-09-20,2006,NONE,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",NaN,NaN,Y,85292,31-03-2019,255158,78,60,24,162,78,72,24,174,2,0,1,3,0,3,0,3,6,True,True,NaN,0,1,1,0,0,0,0,0,2020,0,1,0,0,0,0,0,0,6,14,1.098612,0,0,0,1,0,63.0,0,0,1,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...
43288,SHIVAMAUTO,SHIVAM AUTOTECH LTD.,2018-03-31,P00002378,MR.,SUNIL,KANT,MUNJAL,1957-12-14,M,INDIA,2006-02-14,"CONSUMER DISCRETIONARY,CORPORATE GOVERNANCE,DI...",NaN,NaN,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",YES,2017-03-31,Y,2600.0,1095,730,4425.0,2600.0,1460,730,4790.0,4428.0,5436.0,"(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('DCM SHRIRAM ...","(('SHIVAM AUTOTECH LTD.', 'Y'), ('DCM SHRIRAM ...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...","(('SHIVAMAUTO', 'Y'), ('DCMSHRIRAM', 'U'), ('P...",4,2,2,8,4,2,2,8,0,2,0,2,1,2,0,3,N,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,67.0,3.0,12.123288,0,0,0,1,2018,0,0,0,0,SUNIL KANT MUNJAL,85290,225428,2.020000e+12,MasterProfile_20180331,22703,INE637H01024,6147,shivam autotech ltd.,0,P00001110,SHIVAMAUTO_P00001110,MR.,SUNIL,KANT,MUNJAL,14-12-1957,M,INDIA,2006-09-20,2006,NONE,NO,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR",NaN,NaN,Y,85290,31-03-2017,197341,78,36,24,138,78,48,24,150,2,0,1,3,0,2,0,2,5,True,True,NaN,0,1,1,0,0,0,0,0,2018,0,1,0,0,0,0,0,0,4,12,0.693147,0,0,0,1,0,61.0,0,0,0,MR.SUNIL KANT MUNJAL IS A COMMERCE GRADUATE AN...
46149,SBIN,STATE BANK OF INDIA,2016-03-31,P00064581,MR.,V.,G.,KANNAN,NaN,M,NaN,2014-07-17,NaN,NaN,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,2015-03-31,N,257.0,0,365,622.0,257.0,0,730,987.0,623.0,623.0,"(('SBIN', 'N'), ('SBBJ', 'N'), ('SBT', 'U'), (...","(('STATE BANK OF INDIA', 'N'), ('STATE BANK OF...","(('STATE BANK OF INDIA', 'N'), ('STATE BANK OF...","(('SBIN', 'N'), ('SBBJ', 'N'), ('SBT', 'U'), (...","(('SBIN', 'N'), ('SBBJ', 'N'), ('SBT', 'U'), (...",1,0,3,4,1,0,3,4,1,0,3,4,2,0,3,5,Y,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,0.0,1.704110,0,0,0,0,2016,1,0,0,0,V. G. KANNAN,142254,172159,2.020000e+12,MasterProfile_20160331,20356,INE062A01020,4210,state bank of india,1,P00067115,SBIN_P00067115,MR.,V.,G.,KANNAN,NaN,M,NaN,2014-07-18,2014,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NaN,NaN,N,142254,31-03-2015,147965,0,0,20,20,0,0,32,32,0,0,0,0,1,0,3,4,4,True,True,NaN,1,0,0,1,0,0,0,0,2016,1,0,0,0,0,0,0,0,0,2,1.386294,0,0,1,0,0,NaN,0,0,0,NaN
46151,SBIN,STATE BANK OF INDIA,2015-03-31,P00064581,MR.,V.,G.,KANNAN,NaN,M,NaN,2014-07-17,NaN,NaN,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,N,257.0,0,0,257.0,257.0,0,365,622.0,257.0,257.0,(),"(('STATE BANK OF INDIA', 'N'), ('STATE BANK OF...","(('STATE BANK OF INDIA', 'N'), ('STATE BANK OF...",(),(),0,0,0,0,0,0,0,0,1,0,3,4,2,0,3,5,Y,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,0.0,0.704110,0,0,0,0,2015,0,0,0,0,V. G. KANNAN,142253,147965,2.020000e+12,MasterProfile_20150331,19028,INE062A01020,1216,state bank of india,1,P00067115,SBIN_P00067115,MR.,V.,G.,KANNAN,NaN,M,NaN,2014-07-18,2014,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NaN,NaN,N,142253,NaN,0,0,0,8,8,0,0,20,20,0,0,0,0,1,0,3,4,4,True,True,NaN,1,0,0,1,0,0,0,0,2015,1,0,0,0,0,0,0,0,0,1,1.386294,0,0,1,0,0,NaN,0,0,0,NaN

In [26]:
merged.iloc[[139]]

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
139,HEXAWARE,HEXAWARE TECHNOLOGIES LTD.,2013-03-31,P00006320,MR.,ABHAY,PRABHAKAR,HAVALDAR,1961-12-05,M,INDIA,2011-10-20,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,ABHAY HAVALDAR IS A MANAGING DIRECTOR AT GENER...,NO,"NOMINEE DIRECTOR OF GENERAL ATLANTIC, NON-EXEC...",NO,2012-03-31,N,528.0,0,0,528.0,528.0,0,365,893.0,528.0,2763.0,"(('GEOMETRIC', 'U'), ('JUBLPHARMA', 'U'), ('CY...","(('JUBILANT PHARMOVA LTD.', 'Y'), ('HEXAWARE T...","(('JUBILANT PHARMOVA LTD.', 'Y'), ('HEXAWARE T...","(('GEOMETRIC', 'U'), ('JUBLPHARMA', 'U'), ('CY...","(('GEOMETRIC', 'U'), ('JUBLPHARMA', 'U'), ('CY...",4,0,0,4,4,0,0,4,0,2,1,3,1,2,1,4,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,63.0,0.0,1.446575,0,0,0,0,2013,1,0,0,0,ABHAY PRABHAKAR HAVALDAR,126565,94969,2.010000e+12,MasterProfile_20130331,7000,INE093A01033,4571,hexaware technologies ltd.,0,P00014182,HEXAWARE_P00014182,MR.,ABHAY,PRABHAKAR,HAVALDAR,05-12-1961,M,INDIA,2011-10-20,2011,NONE,NO,"NOMINEE DIRECTOR OF GENERAL ATLANTIC, NON-EXEC...",NaN,NaN,N,126565,31-03-2012,76098,17,0,0,17,17,0,12,29,1,0,0,1,0,1,2,3,4,True,True,NaN,1,0,0,1,0,0,0,0,2013,0,0,0,0,0,0,0,0,0,2,1.098612,0,0,1,0,0,52.0,0,0,0,ABHAY HAVALDAR IS A MANAGING DIRECTOR AT GENER...

In [27]:
old.loc[ (old["DirFullName"] == "ABHAY PRABHAKAR HAVALDAR") & (old["AsOnDate"] == "2013-03-31")]

,ResultId,mRowId,YearRowId,SourceSheet,AsOnDate,ProfileRowId,Symbol,ISIN,FirmDirectorMatch,Company,FinancialServices,Person Code,DirFullName,DirCompId,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Education1_degree,Education1_branch,Unnamed: 28,Education1_college,Education1_city,Unnamed: 31,Unnamed: 32,Unnamed: 33,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Occupation,Cessation Date,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,IsIndepStr,eRowId,PrevLastServed,PrevLastServedMrowId,OpBalUnclear,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnclear,CloBalIndep,ClobalNonIndep,CloBalTotal,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie,IsNonRookie,IsIndep,IsNonIndep,IsTermLimitRetirement,HasTermLimitRetirement,IsRetires5y,HasRetires5y,AsOnYear,IsCeoMD,IsChairman,IsPromoter2,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsFirstTermIndep,TenureInYearsIndep,TenureInYearsTotal,NatLogDirships,IsTurnOverIndep,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,Age,IsFemale,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,TradingDays,MM-3,MM-5,MM-11,FF3F-3,FF3F-5,FF3F-11,CM-3,CM-5,CM-11,MM-3-180,MM-5-180,MM-11-180,FF3F-3-180,FF3F-5-180,FF3F-11-180,CM-3-180,CM-5-180,CM-11-180,MM-3-200,MM-5-200,MM-11-200,FF3F-3-200,FF3F-5-200,FF3F-11-200,CM-3-200,CM-5-200,CM-11-200,MM-1+2-180,MM-1+4-180,MM-1+6-180,MM-1+8-180,MM-1+10-180,MM-1+12-180,FF3F-1+2-180,FF3F-1+4-180,FF3F-1+6-180,FF3F-1+8-180,FF3F-1+10-180,FF3F-1+12-180,CM-1+2-180,CM-1+4-180,CM-1+6-180,CM-1+8-180,CM-1+10-180,CM-1+12-180,MM-1+2-200,MM-1+4-200,MM-1+6-200,MM-1+8-200,MM-1+10-200,MM-1+12-200,FF3F-1+2-200,FF3F-1+4-200,FF3F-1+6-200,FF3F-1+8-200,FF3F-1+10-200,FF3F-1+12-200,CM-1+2-200,CM-1+4-200,CM-1+6-200,CM-1+8-200,CM-1+10-200,CM-1+12-200,CAR_250_3,CAR_210_3,CAR_180_3,CAR_150_3,CAR_250_5,CAR_210_5,CAR_180_5,CAR_150_5,CAR_250_7,CAR_210_7,CAR_180_7,CAR_150_7,CAR_250_11,CAR_210_11,CAR_180_11,CAR_150_11,CAR_250_21,CAR_210_21,CAR_180_21,CAR_150_21,CARFF_250_3,CARFF_210_3,CARFF_180_3,CARFF_150_3,CARFF_250_5,CARFF_210_5,CARFF_180_5,CARFF_150_5,CARFF_250_7,CARFF_210_7,CARFF_180_7,CARFF_150_7,CARFF_250_11,CARFF_210_11,CARFF_180_11,CARFF_150_11,CARFF_250_21,CARFF_210_21,CARFF_180_21,CARFF_150_21
9506,72665,97377,2.010000e+12,MasterProfile_20130331,2013-03-31,9408,JUBILANT,NaN,4236,jubilant life sciences ltd.,0,P00014182,ABHAY PRABHAKAR HAVALDAR,JUBILANT_P00014182,MR.,ABHAY,PRABHAKAR,HAVALDAR,05-12-1961,M,INDIA,06-09-2005,2005,NONE,NO,NOMINEE DIRECTOR OF GA EUROPEAN INVESTMENTS LT...,B.E.,ELECTRICAL,NaN,UNIVERSITY OF MUMBAI,MUMBAI,NaN,NaN,NaN,"M.SC.-MANAGEMENT,LONDON BUSINESS SCHOOL,LONDON",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MANAGING DIRECTOR, GENERAL ATLANTIC LLC",NaN,NaN,CYIENT LTD.,HEXAWARE TECHNOLOGIES LTD.,JUBILANT LIFE SCIENCES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,72665,31-03-2012,78349,90,0,0,90,90,0,12,102,1,0,0,1,0,1,2,3,4,True,True,NaN,0,1,0,1,0,0,0,0,2013,0,0,0,0,0,0,0,0,0,8,1.098612,0,0,0,0,1,52.0,0,0,0,ABHAY HAVALDAR IS AN ADVISORY DIRECTOR AT GENE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24118,117885,91852,2.010000e+12,MasterProfile_20130331,2013-03-31,3883,CYIENT,INE136B01020,7880,cyient ltd.,0,P00014182,ABHAY PRABHAKAR HAVALDAR,CYIENT_P00014182,MR.,ABHAY,PRABHAKAR,HAVALDAR,05-12-1961,M,INDIA,14-07-2010,2010,NONE,NO,NON-EXECUTIVE DIRECTOR,B.E.,ELECTRICAL,NaN,UNIVERSITY OF MUMBAI,MUMBAI,NaN,NaN,NaN,"M.SC.-MANAGEMENT,LONDON BUSINESS SCHOOL,LONDON",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MANAGING DIRECTOR, GENERAL ATLANTIC LLC",NaN,NaN,CYIENT LTD.,HEXAWARE TECHNOLOGIES LTD.,JUBILANT LIFE SCIENCES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,117885,31-03-2012,73204,32,0,0,32,32,12,0,44,1,0,0,1,0,1,2,3,4,True,True,NaN,0,1,1,0,0,0,0,0,2013,0,0,0,0,0,0,0,1,1,3,1.098612,1,0,0,1,0,52.0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5224,-1.444,-1.269667,-5.129444,-1.351,-0.916,-5.4431,-1.302,-1.096,-5.2592,-1.334,-1.088333,-5.597273,-1.305,-2.853,-5.0075,-1.207,-0.957,-5.197545,-1.372,-1.162667,-5.4042,-1.347,-1.020667,-5.3596,-1.251,-1.04,-5.0763,-1.334,-1.334,-1.334,-1.334,-7.2695,-7.2695,-1.305,-5.2515,-7.9505,-9.373833,-9.894571,-9.894571,-1.207,-1.207,-6.1535,-6.1535,-1.207,-1.207,-1.372,-1.372,-1.372,-1.372,-1.372,-1.372,-1.347,-5.5695,-7.275333,-7.275333,-7.275333,-7.275333,-1.251,-1.251,-1.251,-1.251,-1.251,-1.251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.20%,-3.71%,-3.80%,NaN,-6.30%,NaN,-5.56%,NaN,-6.30%,NaN,-8.86%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.74%,-3.61%,-3.67%,NaN,-5.85%,NaN,-5.55%,NaN,NaN,NaN,-8.92%,NaN
26661,126565,94969,2.010000e+12,MasterProfile_20130331,2013-03-31,7000,HEXAWARE,INE093A01033,4571,hexaware technologies ltd.,0,P00014182,ABHAY PRABHAKAR HAVALDAR,HEXAWARE_P00014182,MR.,ABHAY,PRABHAKAR,HAVALDAR,05-12-1961,M,INDIA,20-10-2011,2011,NONE,NO,"NOMINEE DIRECTOR OF GENERAL ATLANTIC, NON-EXEC...",B.E.,ELECTRICAL,NaN,UNIVERSITY OF MUMBAI,MUMBAI,NaN,NaN,NaN,"M.SC.-MANAGEMENT,LONDON BUSINESS SCHOOL,LONDON",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MANAGING DIRECTOR, GENERAL ATLANTIC LLC",NaN,NaN,CYIENT LTD.,HEXAWARE TECHNOLOGIES LTD.,JUBILANT LIFE SCIENCES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,126565,31-03-2012,76098,17,0,0,17,17,0,12,29,1,0,0,1,0,1,2,3,4,True,True,NaN,1,0,0,1,0,0,0,0,2013,0,0,0,0,0,0,0,0,0,2,1.098612,0,0,1,0,0,52.0,0,0,0,ABHAY HAVALDAR IS A MANAGING DIRECTOR AT GENER...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
old.loc[ old["TenureInYearsTotal"] < 3]["IsRookie"].value_counts()

IsRookie
1    17599
Name: count, dtype: int64

In [29]:
old.loc[ old["TenureInYearsTotal"] >= 3]["IsRookie"].value_counts()

IsRookie
0    64317
Name: count, dtype: int64

In [30]:
IsRookieMatchIndex.loc[ IsRookieMatchIndex[0] == True, :]

          0
0      True
1      True
2      True
3      True
4      True
...     ...
50209  True
50210  True
50211  True
50212  True
50213  True

[45566 rows x 1 columns]

In [31]:
IsRookieMatch = merged.iloc[IsRookieMatchIndex.loc[ IsRookieMatchIndex[0] == True, :].index, ][["YOE", "YOEmax", "TenureInYearsTotal_x", "TenureInYearsTotal_y", "IsRookie_x", "IsRookie_y"]]
IsRookieMatch

,YOE,YOEmax,TenureInYearsTotal_x,TenureInYearsTotal_y,IsRookie_x,IsRookie_y
0,95.0,95.0,0.260274,1,1,1
1,1251.0,1251.0,3.424658,4,0,0
2,1616.0,1616.0,4.424658,5,0,0
3,2712.0,2712.0,7.424658,8,0,0
4,2347.0,2347.0,6.424658,7,0,0
...,...,...,...,...,...,...
50209,10108.0,10108.0,27.687671,28,0,0
50210,10839.0,10839.0,29.687671,30,0,0
50211,10473.0,10473.0,28.687671,29,0,0
50212,9743.0,9743.0,26.687671,27,0,0
50213,11569.0,11569.0,31.687671,32,0,0

In [32]:
IsRookieMatch.IsRookie_x.value_counts()

IsRookie_x
0    38038
1     7528
Name: count, dtype: int64

In [33]:
merged.loc[ merged["IsRookie_x"] == merged["IsRookie_y"]].sort_values(by = ["DirFullName", "AsOnDate"])

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile
0,ORIENTBANK,ORIENTAL BANK OF COMMERCE,2019-03-31,P00091605,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,2018-12-26,NaN,NaN,NaN,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...,NO,EXECUTIVE DIRECTOR,NO,NaN,N,95.0,0,0,95.0,95.0,0,365,460.0,95.0,95.0,(),"(('ORIENTAL BANK OF COMMERCE', 'N'),)","(('ORIENTAL BANK OF COMMERCE', 'N'),)",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,0.0,0.260274,0,0,0,0,2019,1,0,0,0,A. ALSE BALAKRISHNA,167090,250976,2.020000e+12,MasterProfile_20190331,19727,INE141A01014,8191,oriental bank of commerce,1,P00068720,ORIENTBANK_P00068720,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,2018-12-26,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,167090,NaN,0,0,0,3,3,0,0,15,15,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,NaN,0,0,0,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...
1,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2014-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2013-03-31,N,885.0,0,365,1250.0,885.0,0,730,1615.0,1251.0,1251.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,3.424658,0,0,0,0,2014,0,0,0,0,A. J. SURIYANARAYANA,120190,118128,2.010000e+12,MasterProfile_20140331,10289,INE036D01028,3665,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120190,31-03-2013,97671,29,0,12,41,29,0,24,53,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2014,0,0,1,0,0,0,0,0,0,4,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
2,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2015-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2014-03-31,N,885.0,0,730,1615.0,885.0,0,1095,1980.0,1616.0,1616.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,4.424658,0,1,0,0,2015,0,0,0,0,A. J. SURIYANARAYANA,120191,140296,2.020000e+12,MasterProfile_20150331,11359,INE036D01028,3665,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120191,31-03-2014,118128,29,0,24,53,29,0,36,65,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2015,0,0,1,0,0,0,0,0,0,5,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
5,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2016-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2015-03-31,N,885.0,0,1095,1980.0,885.0,0,1460,2345.0,1982.0,1982.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,5.424658,0,0,0,0,2016,0,0,0,0,A. J. SURIYANARAYANA,120192,163793,2.020000e+12,MasterProfile_20160331,11990,INE036D01028,1903,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120192,31-03-2015,140296,29,0,36,65,29,0,48,77,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2016,0,0,1,0,0,0,0,0,0,6,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
4,KARURVYSYA,"KARUR VYSYA BANK LTD.,THE",2017-03-31,P00043875,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,NaN,NaN,NaN,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2016-03-31,N,885.0,0,1460,2345.0,885.0,0,1825,2710.0,2347.0,2347.0,"(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARUR VYSYA BANK LTD.,THE', 'N'),)","(('KARUR VYSYA BANK LTD.,THE', 'N'), ('KARUR V...","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))","(('KARURVYSYA', 'N'), ('KARURVYSYA', 'U'))",1,0,1,2,1,0,1,2,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,NaN,0.0,6.424658,0,0,0,0,2017,0,0,0,0,A. J. SURIYANARAYANA,120193,189234,2.020000e+12,MasterProfile_20170331,12904,INE036D01028,1903,"karur vysya bank ltd.,the",1,P00038307,KARURVYSYA_P00038307,MR.,A.,J.,SURIYANARAYANA,NaN,M,INDIA,2010-10-27,2010,NONE,YES,"NON-EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,120193,31-03-2016,163793,29,0,48,77,29,0,60,89,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2017,0,0,1,0,0,0,0,0,0,7,0.0,0,0,0,0,1,NaN,0,1,0,SHRI A J SURIYANARAYANA IS A DIRECTOR OF THE B...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50210,CREATIVEYE,CREATIVE EYE LTD.,2016-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2015-03-31,N,9741.0,0,1095,10836.0,9741.0,0,1460,11201.0,10839.0,10839.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,29.687671,0,0,0,1,2016,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9614,156557,2.020000e+12,MasterProfile_20160331,4754,INE230B01021,7023,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,1986-07-28,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9614,31-03-2015,133384,320,0,36,356,320,0,48,368,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2016,0,0,1,0,0,0,0,0,0,30,0.0,0,0,0,0,1,65.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50206,CREATIVEYE,CREATIVE EYE LTD.,2017-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2016-03-31,N,9741.0,0,1460,11201.0,9741.0,0,1825,11566.0,11204.0,11204.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,30.687671,0,0,0,1,2017,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9615,181457,2.020000e+12,MasterProfile_20170331,5127,INE230B01021,6180,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,1986-07-28,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9615,31-03-2016,156557,320,0,48,368,320,0,60,380,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2017,0,0,1,0,0,0,0,0,0,31,0.0,0,0,0,0,1,66.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50213,CREATIVEYE,CREATIVE EYE LTD.,2018-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2017-03-31,N,9741.0,0,1825,11566.0,9741.0,0,2190,11931.0,11569.0,11569.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,31.687671,0,0,0,1,2018,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9616,208384,2.020000e+12,MasterProfile_20180331,5659,INE230B01021,6773,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,1986-07-28,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9616,31-03-2017,181457,320,0,60,380,320,0,72,392,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2018,0,0,1,0,0,0,0,0,0,32,0.0,0,0,0,0,1,67.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50207,CREATIVEYE,CREATIVE EYE LTD.,2019-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2018-03-31,N,9741.0,0,2190,11931.0,9741.0,0,2555,12296.0,11934.0,11934.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,32.687671,0,0,0,1,2019,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9617,237279,2.020000e+12,MasterProfile_20190331,6030,INE230B01021,6773,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,1986-07-28,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9617,31-03-2018,208384,320,0,72,392,320,0,84,404,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2019,0,0,1,0,0,0,0,0,0,33,0.0,0,0,0,0,1,68.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...
50208,CREATIVEYE,CREATIVE EYE LTD.,2020-03-31,P00007721,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,1951-03-15,F,INDIA,1986-07-28,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,2019-03-31,N,9741.0,0,2555,12296.0,9741.0,0,2920,12661.0,12300.0,12300.0,"(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVE EYE LTD.', 'N'),)","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))","(('CREATIVEYE', 'U'), ('CREATIVEYE', 'N'))",1,0,1,2,1,0,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,73.0,0.0,33.687671,0,0,0,1,2020,0,0,0,0,ZUBY DHEERAJKUMAR KOCHHAR,9618,267440,2.020000e+12,MasterProfile_20200331,6232,INE230B01021,6081,creative eye ltd.,0,P00005282,CREATIVEYE_P00005282,MS.,ZUBY,DHEERAJKUMAR,KOCHHAR,15-03-1951,F,INDIA,1986-07-28,1986,NONE,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NaN,NaN,N,9618,31-03-2019,237279,320,0,84,404,320,0,96,416,0,0,0,0,0,0,1,1,1,True,False,NaN,0,1,0,1,0,0,0,0,2020,0,0,1,0,0,0,0,0,0,34,0.0,0,0,0,0,1,69.0,1,1,0,MRS. ZUBY KOCHHAR IS THE PROMOTER DIRECTOR OF ...

In [34]:
def MultiComp(frame):
    if frame.Symbol.nunique() > 1:
        return "Multi"
    else:
        return "No"

In [35]:
multi = merged.sort_values(
    by = ["DirFullName", "AsOnDate"]).groupby(["DirFullName", "AsOnDate"]).progress_apply(MultiComp)

100%|██████████████████████████████████████████████████████████████████████████| 40231/40231 [00:04<00:00, 9195.27it/s]

In [36]:
multiComp = multi.to_frame().rename({0:"Multi"}, axis = 1)
multiComp.loc[ multiComp["Multi"] == "Multi"]

                               Multi
DirFullName        AsOnDate
A. R. MURALIDHARAN 2017-03-31  Multi
                   2018-03-31  Multi
AARTI ARUN SATHE   2015-03-31  Multi
                   2016-03-31  Multi
                   2017-03-31  Multi
...                              ...
ZUBIN SOLI DUBASH  2016-03-31  Multi
                   2017-03-31  Multi
                   2018-03-31  Multi
                   2019-03-31  Multi
                   2020-03-31  Multi

[6320 rows x 1 columns]

In [37]:
multiMerge = merged.merge(multiComp.reset_index(), on = ["DirFullName", "AsOnDate"], how = "left")
multiMerge["Appointment Date_y"] = pd.to_datetime(multiMerge["Appointment Date_y"], format = "%d-%m-%Y")
multiMergeRookieMatched = multiMerge.loc[ (multiMerge["IsRookie_x"] == multiMerge["IsRookie_y"]) & (multiMerge["IsRookie_x"] == 1)].copy()
multiMergeRookieMatched

,Symbol,Company_x,AsOnDate,Person Code_x,Director Salutation_x,Director First Name_x,Director Middle Name_x,Director Surname_x,Date of Birth_x,Gender_x,Nationality_x,Appointment Date_x,Skills/Competencies,Cessation Date_x,Cessation Reason_x,Brief Profile,Promoter Director (Yes/No)_x,Position on Board_x,Independent (Yes/No),PrevLastServed_x,Indep,OpBalUnc,OpBalIndep_x,OpBalNonIndep_x,OpBalTotal_x,CloBalUnc,CloBalIndep_x,CloBalNonIndep,CloBalTotal_x,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep_x,IsNonIndep_x,IsRookie_x,IsNonRookie_x,IsCeoMD_x,IsChairman_x,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD_x,IsFamilyManaged_x,IsFamilyChairman_x,IsFamilyChairmanAndCEO_x,IsRookieIndep_x,IsRookieNonIndep_x,IsNonRookieIndep_x,IsNonRookieNonIndep_x,IsFemale_x,Age_x,TenureInYearsIndep_x,TenureInYearsTotal_x,IsFirstTermIndep_x,IsRetires5y_x,IsTermLimitRetirement_x,IsDefaultTerm,AsOnYear_x,IsTurnOver,HasRetires5y_x,HasTermLimitRetirement_x,IsTurnOverIndep_x,DirFullName,ResultId,mRowId,YearRowId,SourceSheet,ProfileRowId,ISIN,FirmDirectorMatch,Company_y,FinancialServices,Person Code_y,DirCompId,Director Salutation_y,Director First Name_y,Director Middle Name_y,Director Surname_y,Date of Birth_y,Gender_y,Nationality_y,Appointment Date_y,AppointmentDate_year,Member of Civil Services,Promoter Director (Yes/No)_y,Position on Board_y,Cessation Date_y,Cessation Reason_y,IsIndepStr,eRowId,PrevLastServed_y,PrevLastServedMrowId,OpBalUnclear,OpBalIndep_y,OpBalNonIndep_y,OpBalTotal_y,CloBalUnclear,CloBalIndep_y,ClobalNonIndep,CloBalTotal_y,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,IsConsidered,IsMultiComp,ProwLookUpIndepStatus,IsRookie_y,IsNonRookie_y,IsIndep_y,IsNonIndep_y,IsTermLimitRetirement_y,HasTermLimitRetirement_y,IsRetires5y_y,HasRetires5y_y,AsOnYear_y,IsCeoMD_y,IsChairman_y,IsPromoter2,IsDualityChairmanMD_y,IsFamilyManaged_y,IsFamilyChairman_y,IsFamilyChairmanAndCEO_y,IsFirstTermIndep_y,TenureInYearsIndep_y,TenureInYearsTotal_y,NatLogDirships,IsTurnOverIndep_y,IsRookieIndep_y,IsRookieNonIndep_y,IsNonRookieIndep_y,IsNonRookieNonIndep_y,Age_y,IsFemale_y,RawIsPromoterStatus,IsBusy,Dir_Brief_Profile,Multi
0,ORIENTBANK,ORIENTAL BANK OF COMMERCE,2019-03-31,P00091605,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,2018-12-26,NaN,NaN,NaN,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...,NO,EXECUTIVE DIRECTOR,NO,NaN,N,95.0,0,0,95.0,95.0,0,365,460.0,95.0,95.0,(),"(('ORIENTAL BANK OF COMMERCE', 'N'),)","(('ORIENTAL BANK OF COMMERCE', 'N'),)",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,NaN,0.0,0.260274,0,0,0,0,2019,1,0,0,0,A. ALSE BALAKRISHNA,167090,250976,2.020000e+12,MasterProfile_20190331,19727,INE141A01014,8191,oriental bank of commerce,1,P00068720,ORIENTBANK_P00068720,MR.,A.,ALSE,BALAKRISHNA,NaN,M,NaN,2018-12-26,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,167090,NaN,0,0,0,3,3,0,0,15,15,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,NaN,0,0,0,SHRI BALAKRISHMA ALSE S IS A B.SC. IN AGRICULT...,No
8,SUNDARMFIN,SUNDARAM FINANCE LTD.,2016-03-31,P00063836,MR.,A.,N.,RAJU,1959-05-15,M,INDIA,2014-06-01,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,NaN,HAS LONG EXPERIENCE IN RETAIL ASSET FINANCING ...,NO,"DIRECTOR-OPERATIONS, EXECUTIVE DIRECTOR",NO,2015-03-31,N,303.0,0,365,668.0,303.0,0,730,1033.0,669.0,669.0,"(('SUNDARMFIN', 'N'),)","(('SUNDARAM FINANCE LTD.', 'N'),)","(('SUNDARAM FINANCE LTD.', 'N'),)","(('SUNDARMFIN', 'N'),)","(('SUNDARMFIN', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,65.0,0.0,1.830137,0,0,0,0,2016,0,0,0,0,A. N. RAJU,141627,172668,2.020000e+12,MasterProfile_20160331,20865,INE660A01013,2308,sundaram finance ltd.,2,P00007953,SUNDARMFIN_P00007953,MR.,A.,N.,RAJU,15-05-1959,M,INDIA,2014-06-01,2014,NONE,NO,"DIRECTOR-OPERATIONS, EXECUTIVE DIRECTOR",NaN,NaN,N,141627,31-03-2015,148440,0,0,21,21,0,0,33,33,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,2,0.0,0,0,1,0,0,57.0,0,0,0,HAS LONG EXPERIENCE IN RETAIL ASSET FINANCING ...,No
9,SUNDARMFIN,SUNDARAM FINANCE LTD.,2015-03-31,P00063836,MR.,A.,N.,RAJU,1959-05-15,M,INDIA,2014-06-01,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,NaN,HAS LONG EXPERIENCE IN RETAIL ASSET FINANCING ...,NO,"DIRECTOR-OPERATIONS, EXECUTIVE DIRECTOR",NO,NaN,N,303.0,0,0,303.0,303.0,0,365,668.0,303.0,303.0,(),"(('SUNDARAM FINANCE LTD.', 'N'),)","(('SUNDARAM FINANCE LTD.', 'N'),)",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,65.0,0.0,0.830137,0,0,0,0,2015,0,0,0,0,A. N. RAJU,141626,148440,2.020000e+12,MasterProfile_20150331,19503,INE660A01013,6730,sundaram finance ltd.,2,P00007953,SUNDARMFIN_P00007953,MR.,A.,N.,RAJU,15-05-1959,M,INDIA,2014-06-01,2014,NONE,NO,"DIRECTOR-OPERATIONS, EXECUTIVE DIRECTOR",NaN,NaN,N,141626,NaN,0,0,0,9,9,0,0,21,21,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2015,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,56.0,0,0,0,HAS LONG EXPERIENCE IN RETAIL ASSET FINANCING ...,No
10,SUPERSPIN,SUPER SPINNING MILLS LTD.,2018-03-31,P00082779,MR.,A.,R.,BALASUNDHARAM,1963-06-06,M,NaN,2017-06-01,NaN,NaN,NaN,MORE THAN THREE DECADES OF EXPERIENCE AS A TEX...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,Y,303.0,0,0,303.0,303.0,365,0,668.0,303.0,303.0,(),"(('SUPER SPINNING MILLS LTD.', 'Y'),)","(('SUPER SPINNING MILLS LTD.', 'Y'),)",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,61.0,0.0,0.830137,1,0,0,0,2018,0,0,0,0,A. R. BALASUNDHARAM,161484,227188,2.020000e+12,MasterProfile_20180331,24463,INE662A01027,2586,super spinning mills ltd.,0,P00059443,SUPERSPIN_P00059443,MR.,A.,R.,BALASUNDHARAM,06-06-1963,M,NaN,2017-06-01,2017,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,161484,NaN,0,0,9,0,9,0,21,0,21,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2018,0,0,0,0,0,0,0,1,1,1,0.0,1,1,0,0,0,55.0,0,0,0,MORE THAN THREE DECADES OF EXPERIENCE AS A TEX...,No
11,SUPERSPIN,SUPER SPINNING MILLS LTD.,2019-03-31,P00082779,MR.,A.,R.,BALASUNDHARAM,1963-06-06,M,NaN,2017-06-01,NaN,NaN,NaN,MORE THAN THREE DECADES OF EXPERIENCE AS A TEX...,NO,NON-EXECUTIVE DIRECTOR,NO,2018-03-31,N,303.0,365,0,668.0,303.0,365,365,1033.0,668.0,668.0,"(('SUPERSPIN', 'Y'),)","(('SUPER SPINNING MILLS LTD.', 'N'),)","(('SUPER SPINNING MILLS LTD.', 'N'),)","(('SUPERSPIN', 'Y'),)","(('SUPERSPIN', 'Y'),)",0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,61.0,1.0,1.830137,0,0,0,0,2019,1,0,0,0,A. R. BALASUNDHARAM,161485,257039,2.020000e+12,MasterProfile_20190331,25790,INE662A01027,2586,super spinning mills ltd.,0,P00059443,SUPERSPIN_P00059443,MR.,A.,R.,BALASUNDHARAM,06-06-1963,M,NaN,2017-06-01,2017,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,N,161485,31-03-2018,227188,0,21,0,21,0,21,12,33,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,2,0.0,0,0,1,0,0,56.0,0,0,0,MORE THAN THREE DECADES OF EXPERIENCE AS A TEX...,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50171,PSPPROJECT,PSP PROJECTS LTD.,2020-03-31,P00095956,LATE MS.,ZARANA,PRATIK,PATEL,NaN,F,NaN,2019-10-22,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,NaN,"MRS. ZARANA PRATIK PATEL, AGED 31, IS A CHARTE...",NO,NON-EXECUTIVE DIRECTOR,YES,NaN,Y,161.0,0,0,161.0,161.0,365,0,526.0,161.0,161.0,(),"(('PSP PROJECTS LTD.', 'Y'),)","(('PSP PROJECTS LTD.', 'Y'), ('PSP PROJECTS LT...",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,NaN,0.0,0.441096,1,0,0,0,2020,0,0,0,0,ZARANA PRATIK PATEL,169053,283608,2.020000e+12,MasterProfile_20200331,22400,INE488V01015,1541,psp projects ltd.,0,P00028275,PSPPROJECT_P00028275,MS.,ZARANA,PRATIK,PATEL,NaN,F,NaN,2019-10-22,2019,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,169053,NaN,0,0,5,0,5,0,17,0,17,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2020,0,0,0,0,0,0,0,1,1,1,0.0,1,1,0,0,0,NaN,1,0,0,"MRS. ZARANA PRATIK PATEL, AGED 31, IS A CHARTE...",No
50173,TATACHEM,TATA CHEMICALS LTD.,2020-03-31,P00087144,MR.,ZARIR,NOSHIR,LANGRANA,1959-02-12,M,NaN,2018-04-01,"COMMODITIES,CORPORATE GOVERNANCE,CORPORATE SOC...",NaN,NaN,MR. ZARIR LANGRANA CURRENTLY HEADS THE GLOBAL ...,NO,EXECUTIVE DIRECTOR,NO,2019-03-31,N,364.0,0,365,729.0,364.0,0,730,1094.0,730.0,730.0,"(('TATACHEM', 'N'),)","(('TATA CHEMICALS LTD.', 'N'),)","(('TATA CHEMICALS LTD.', 'N'),)","(('TATACHEM', 'N'),)","(('TATACHEM', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,66.0,0.0,1.997260,0,0,0,0,2020,0,0,0,0,ZARIR NOSHIR LANGRANA,164999,289173,2.020000e+12,MasterProfile_20200331,27965,INE092A01019,4669,tata chemicals ltd.,0,P00048679,TATACHEM_P00048679,MR.,ZARIR,NOSHIR,LANGRANA,12-02-1959,M,NaN,2018-04-01,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,164999,31-03-2019,257779,0,0,23,23,0,0,35,35,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2020,0,0,0,0,0,0,0,0,0,2,0.0,0,0,1,0,0,61.0,0,0,0,MR. ZARIR LANGRANA CURRENTLY HEADS THE GLOBAL ...,No
50174,TATACHEM,TATA CHEMICALS LTD.,2019-03-31,P00087144,MR.,ZARIR,NOSHIR,LANGRANA,1959-02-12,M,NaN,2018-04-01,"COMMODITIES,CORPORATE GOVERNANCE,CORPORATE SOC...",NaN,NaN,MR. ZARIR LANGRANA CURRENTLY HEADS THE GLOBAL ...,NO,EXECUTIVE DIRECTOR,NO,NaN,N,364.0,0,0,364.0,364.0,0,365,729.0,364.0,364.0,(),"(('TATA CHEMICALS LTD.', 'N'),)","(('TATA CHEMICALS LTD.', 'N'),)",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,66.0,0.0,0.997260,0,0,0,0,2019,0,0,0,0,ZARIR NOSHIR LANGRANA,164998,257779,2.020000e+12,MasterProfile_20190331,26530,INE092A01019,1268,tata chemicals ltd.,0,P00048679,TATACHEM_P00048679,MR.,ZARIR,NOSHIR,LANGRANA,12-02-1959,M,NaN,2018-04-01,2018,NaN,NO,EXECUTIVE DIRECTOR,NaN,NaN,N,164998,NaN,0,0,0,11,11,0,0,23,23,0,0,0,0,0,0,1,1,1,True,False,NaN,1,0,0,1,0,0,0,0,2019,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,0,0,60.0,0,0,0,MR. ZARIR LANGRANA CURRENTLY HEADS THE GLOBAL ...,No
50187,SUMEETINDS,SUMEET INDUSTRIES LTD.,2020-03-31,P00091286,MS.,ZEEL,SURESHKUMAR,MODI,1994-06-03,F,NaN,2018-11-30,"CORPORATE SOCIAL RESPONSIBILITY,LEADERSHIP/MAN...",NaN,NaN,MS. ZEEL SURESHKUMAR MODI IS A GRADUATE ENGINE...,NO,NON-EXECUTIVE DIRECTOR,YES,2019-03-31,Y,121.0,365,0,486.0,121.0,730,0,851.0,487.0,487.0,"(('SUMEETINDS', 'Y'),)","(('SUMEET INDUSTRIES LTD.', 'Y'),)","(('SUMEET INDUSTRIES LTD.', 'Y'), ('SUMEET IND...","(('SUMEETINDS', 'Y'),)","(('SUMEETINDS', 'Y'),)",0,1,0,1,0,1,0,1,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,30.0,1.0,1.331507,1,0,0,0,2020,0,0,0,0,ZEEL SURESHKUMAR MODI,166956,288275,2.020000e+12,MasterProfile_20200331,27067,INE235C01010,6687,sumeet industries ltd.,0,P00062330,SUMEETINDS_P00062330,MS.,ZEEL,SURESHKUMAR,MODI,03-06-1994,F,NaN,2018-11-30,2018,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,166956,31-03-2019,256854,0,16,0,16,0,28,0,28,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2020,0,0,0,0,0,0,0,1,2,2,0.0,0,1,0,0,0,26.0,1,0,0,MS. ZEEL SURESHKUMAR MODI IS A GRADUATE ENGINE...,No
50188,SUMEETINDS,SUMEET INDUSTRIES LTD.,2019-03-31,P00091286,MS.,ZEEL,SURESHKUMAR,MODI,1994-06-03,F,NaN,2018-11-30,"CORPORATE SOCIAL RESPONSIBILITY,LEADERSHIP/MAN...",NaN,NaN,MS. ZEEL SURESHKUMAR MODI IS A GRADUATE ENGINE...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,Y,121.0,0,0,121.0,121.0,365,0,486.0,121.0,121.0,(),"(('SUMEET INDUSTRIES LTD.', 'Y'),)","(('SUMEET INDUSTRIES LTD.', 'Y'), ('SUMEET IND...",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,30.0,0.0,0.331507,1,0,0,0,2019,0,0,0,0,ZEEL SURESHKUMAR MODI,166955,256854,2.020000e+12,MasterProfile_20190331,25605,INE235C01010,4553,sumeet industries ltd.,0,P00062330,SUMEETINDS_P00062330,MS.,ZEEL,SURESHKUMAR,MODI,03-06-1994,F,NaN,2018-11-30,2018,NaN,NO,NON-EXECUTIVE DIRECTOR,NaN,NaN,Y,166955,NaN,0,0,4,0,4,0,16,0,16,0,0,0,0,0,1,0,1,1,True,False,NaN,1,0,1,0,0,0,0,0,2019,0,0,0,0,0,0,0,1,1,1,0.0,1,1,0,0,0,25.0,1,0,0,MS. ZEEL SURESHKUMAR MODI IS A GRADUATE ENGINE...,No

In [38]:
len(multiMerge.loc[ (multiMerge["IsRookie_x"] == 1 )].index)

10702

In [39]:
len(multiMerge.loc[ (multiMerge["IsRookie_y"] == 1 )].index)

9002

In [40]:
len(multiMerge.loc[ (multiMerge["IsRookie_x"] == multiMerge["IsRookie_y"]) & (multiMerge["IsRookie_x"] == 1)].index)

7528

In [41]:
len(multiMerge.loc[ (multiMerge["IsRookie_x"] != multiMerge["IsRookie_y"]) & (multiMerge["IsRookie_x"] == 1)].index)

3174

In [42]:
len(multiMerge.loc[ (multiMerge["IsRookie_x"] != multiMerge["IsRookie_y"]) & (multiMerge["IsRookie_y"] == 1)].index)

1474

In [43]:
test3.loc[ (test3["Multi"] == "Multi") & (test3["IsRookie_y"] == 1) & ((test3["AsOnDate"] - test3["Appointment Date_y"]) < pd.Timedelta(days=365*3))]

NameError: name 'test3' is not defined

In [ ]:
test3.loc[ (test3["Multi"] == "Multi") & (test3["IsRookie_x"] == 1) ]