In [6]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [7]:
import_folder_path = "car_output3"
output_folder_path = "car_output4"
filtering_folder_path = rf"..\..\[IN USE] Rookie Directors\[4] FF3 CAR precode\car_filtering"
supporting_folder_path = "supporting_datafiles"

## Data Reading

In [8]:
dir120CAR = pd.read_pickle(rf"{import_folder_path}\dir120CAR_2.pkl")
dir150CAR = pd.read_pickle(rf"{import_folder_path}\dir150CAR_2.pkl")
dir180CAR = pd.read_pickle(rf"{import_folder_path}\dir180CAR_2.pkl")
dir210CAR = pd.read_pickle(rf"{import_folder_path}\dir210CAR_2.pkl")

In [9]:
dir180CAR.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Prowess company code',
 'CompanyName',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Academic',
 'Manufacturing',
 'Outside Board',
 'Company Business',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'combined_entrepreneurial',
 'combined_compensation',
 'combined_conglomerate_experience',
 'combined_hr',
 'combined_technology',
 'combined_finance_accounting',
 'combined_governance',
 'combined_government_policy',
 'combined_international',
 'combined_leadership',
 'combined_legal',
 'combined_marketing',
 'combined_risk_management',
 'combined_scientific',
 'combined_strategic_planning',
 'combined_manufacturing_supply_chain',
 'NumSkills_dummies',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11']

In [10]:
comCol = list(dir150CAR.columns[0:135])
comCol

['Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep']

In [11]:
dirCAR = pd.concat([dir120CAR, dir150CAR, dir180CAR, dir210CAR], axis = 1)
dirCAR = dirCAR.loc[:, ~dirCAR.columns.duplicated()].copy()
dirCAR

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Prowess company code,CompanyName,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Academic,Manufacturing,Outside Board,Company Business,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,combined_entrepreneurial,combined_compensation,combined_conglomerate_experience,combined_hr,combined_technology,combined_finance_accounting,combined_governance,combined_government_policy,combined_international,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,NumSkills_dummies,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,nan,nan,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,NOMINATION ENDED,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,U,2005-04-29,2009-03-02,NaT,2010-03-31,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.00000,3.843836,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,{},GRADUATE: B.SC. nan nan nan nan nan nan nan na...,0,0,{},{08},{08},{08},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,1.465753,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,"{finance, strategy, human resources, leadershi...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 29301, 08}","{29209, 29301, 08}","{29209, 29301, 08}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BANCOINDIA,BANCO PRODUCTS (INDIA) LTD.,2009-03-31,2009,INE213C01025,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. RAM DEVIDAYAL HOLDS MASTER DEGREE IN COMME...,NaT,U,2001-07-30,NaT,2008-03-31,2010-03-31,0,0.0,0.0,1.0,0,0.0,0.0,0.0,365.0,0.0,0.0,2436.0,0.0,0.0,2436.0,2801.0,0.0,0.0,2801.0,2436.0,0.0,0.0,2436.0,2801.0,0.0,0.0,2801.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,7.673973,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,BANCOINDIA,29301,Public Ltd.,Private (Foreign),29909.0,Banco Products (India) Ltd.,"{finance, strategy, human resources, leadershi...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 29301, 08}","{29209, 29301, 08}","{29209, 29301, 08}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MUNJALAU,MUNJAL AUTO INDUSTRIES LTD.,2009-03-31,2009,INE672B01032,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,U,2008-07-26,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,0.0,0.0,248.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,248.0,0.0,0.0,248.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}","{(MUNJALAU, U), (BANCOINDIA, U), (20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,0.679452,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,MUNJALAU,29209,Public Ltd.,Hero (Munjals) Group,86677.0,Munjal Auto Inds. Ltd.,"{finance, strategy, human resources, leadershi...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 29301, 08}","{29209, 29301, 08}","{29209, 29301, 08}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,47,0.00000,1.605479,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258252,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00081419,MR.,ASHOK,K.,KOHLI,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2017-02-10,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,49.0,0.0,0.0,49.0,49.0,365.0,0.0,414.0,49.0,0.0,0.0,49.0,49.0,365.0,0.0,414.0,414,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,<NA>,1.00000,1.134247,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.021262,0.007799,0.018200,0.009880,0.141807,0.042647,0.032314,-0.025294,-0.13034,-0.022281,0.008887,0.024759,0.018170,0.054476,0.045621,0.035374,-0.020473,-0.127947,-0.023243,0.006936,0.015210,0.009678,0.099061,0.048657,0.038255,-0.020749,-0.123870,-0.024955,0.006593,0.015668,0.010935,0.070267,0.053818,0.043389,-0.016170,-0.118526
258253,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00114429,MR.,JITENDRA,KUMAR,PAL,1971-07-08,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...","GRADUATE: LL.B.,UTKAL UNIVERSITY,BHUBANESWAR",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,U,2003-12-30,2018-03-31,2017-03-31,NaT,1,0.0,0.0,2.0,0,0.0,0.0,0.0,365.0,0.0,0.0,1643.0,0.0,0.0,1643.0,2008.0,0.0,0.0,2008.0,3165.0,0.0,0.0,3165.0,3530.0,0.0,0.0,3530.0,5202,"((ZYLOG, U),)","{(ZYLOG, U)}","{(ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.00000,9.671233,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258254,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00080494,MS.,KAMALA,NaN,R.,NaT,F,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2016-11-23,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,128.0,0.0,0.0,128.0,128.0,365.0,0.0,493.0,128.0,0.0,0.0,128.0,128.0,365.0,0.0,493.0,493,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,<NA>,1.00000,1.350685,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.028364,0.006545,0.020030,0.011725,0.123099,0.025903,-0.107993,-0.208582,-0.08690,-0.029032,0.004966,0.013618,0.006953,0.154986,0.031027,-0.103373,-0.202336,-0.079376,-0.030786,0.004640,0.014079,0.008541,0.112633,0.036935,-0.097569,-0.196195,-0.072971,-0.027389,0.004182,0.010090,0.005331,0.146882,0.027651,-0.106999,-0.205153,-0.081559
258255,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,132.0,731.0,0.0,863.0,132.0,1096.0,0.0,1228.0,132.0,731.0,0.0,863.0,132.0,1096.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.00274,3.364384,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,7.70,-0.025316,0.021860,-0.741569,-0.719709,0.280029,-0.546563,-0.037219,0.014717,0.059441,0.051470,0.007287,-0.111834,-0.170415,-0.192669,-0.35466,-0.038134,0.016314,0.070138,0.063855,0.001056,-0.108154,-0.167737,-0.191004,-0.351279,-0.037386,0.015785,0.067294,0.062054,0.000437,-0.110707,-0.169957,-0.192889,-0.353733,-0.037284,0.014662,0.059576,0.055055,0.000357,-0.111669,-0.170216,-0.192435,-0.354486

In [12]:
dirCAR.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'AppointDummy',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'NSE symbol',
 'NIC code',
 'Entity type',
 'Ownership group',
 'Prowess company code',
 'CompanyName',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'IsExecCurrent',
 'NumExecAll',
 'IsOutsideExecXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'skilllist_sustainability',
 'skilllist_entrepreneurial',
 'skilllist_compensation',
 'skilllist_conglomerate_experience',
 'skilllist_hr',
 'skilllist_technology',
 'skilllist_finance_accounting',
 'skilllist_governance',
 'skilllist_government_policy',
 'skilllist_international',
 'skilllist_leadership',
 'skilllist_legal',
 'skilllist_marketing',
 'skilllist_risk_management',
 'skilllist_scientific',
 'skilllist_strategic_planning',
 'skilllist_manufacturing_supply_chain',
 'Academic',
 'Manufacturing',
 'Outside Board',
 'Company Business',
 'profile_sustainability',
 'profile_entrepreneurial',
 'profile_compensation',
 'profile_conglomerate_experience',
 'profile_hr',
 'profile_technology',
 'profile_finance_accounting',
 'profile_governance',
 'profile_government_policy',
 'profile_international',
 'profile_leadership',
 'profile_legal',
 'profile_marketing',
 'profile_risk_management',
 'profile_scientific',
 'profile_strategic_planning',
 'profile_manufacturing_supply_chain',
 'Committee Name',
 'committee_sustainability',
 'committee_entrepreneurial',
 'committee_compensation',
 'committee_conglomerate_experience',
 'committee_hr',
 'committee_technology',
 'committee_finance_accounting',
 'committee_governance',
 'committee_government_policy',
 'committee_international',
 'committee_leadership',
 'committee_legal',
 'committee_marketing',
 'committee_risk_management',
 'committee_scientific',
 'committee_strategic_planning',
 'committee_manufacturing_supply_chain',
 'combined_sustainability',
 'combined_entrepreneurial',
 'combined_compensation',
 'combined_conglomerate_experience',
 'combined_hr',
 'combined_technology',
 'combined_finance_accounting',
 'combined_governance',
 'combined_government_policy',
 'combined_international',
 'combined_leadership',
 'combined_legal',
 'combined_marketing',
 'combined_risk_management',
 'combined_scientific',
 'combined_strategic_planning',
 'combined_manufacturing_supply_chain',
 'NumSkills_dummies',
 'Total No.of Board Meetings Held',
 'No.of Meetings Attended',
 'percent_board_absence',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11',
 'OLS210_intercept',
 'OLS210_RMRF',
 'OLS210_r_squared',
 'OLS210_adjusted_r_squared',
 'OLS210_f_p_value',
 '210CAR3',
 '210CAR5',
 '210CAR7',
 '210CAR11']

In [13]:
dirCAR.loc[ (dirCAR["Person Code"] == "P00000256") & (dirCAR["AsOnDate"] == "2006-03-31") ]

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Prowess company code,CompanyName,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Academic,Manufacturing,Outside Board,Company Business,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,combined_entrepreneurial,combined_compensation,combined_conglomerate_experience,combined_hr,combined_technology,combined_finance_accounting,combined_governance,combined_government_policy,combined_international,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,NumSkills_dummies,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11
4038,ACC,ACC LTD.,2006-03-31,2006,INE012A01025,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,nan,nan,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.TARUN DAS, AS DIRECTOR GENERAL OF THE CONFE...",NaT,U,2000-04-26,2006-01-01,NaT,2007-03-31,1,0.0,1.0,1.0,0,0.0,0.0,0.0,2076.0,0.0,0.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,1711.0,0.0,0.0,1711.0,2076.0,0.0,0.0,2076.0,2164,(),"{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}","{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,5.687671,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,ACC,23941,Public Ltd.,Adani Group,23354.0,A C C Ltd.,{},GRADUATE: B.A.(HONS.)-ECONOMICS nan nan nan na...,0,0,{},"{6020, 64300, 23941}","{6020, 64300, 23941}","{6020, 64300, 23941}","{64, 23, 60}",1,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4039,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,nan,nan,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,HE HAS SPENT HIS ENTIRE WORKING CAREER IN INDU...,NaT,U,2004-09-15,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,562.0,0.0,0.0,197.0,0.0,0.0,197.0,562.0,0.0,0.0,562.0,197.0,0.0,0.0,197.0,562.0,0.0,0.0,562.0,2164,(),"{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}","{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,1.539726,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,BAJAJHLDNG,64300,Public Ltd.,Bajaj Group,28899.0,Bajaj Holdings & Invst. Ltd.,{},GRADUATE: B.A.(HONS.)-ECONOMICS nan nan nan na...,0,0,{},"{6020, 64300, 23941}","{6020, 64300, 23941}","{6020, 64300, 23941}","{64, 23, 60}",1,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,5,NaN,NaN,NaN,28899.0,1.4,-0.066667,0.012454,-0.201723,-0.189269,-0.599788,-0.057796,-0.015254,0.003666,0.009104,0.000707,0.299889,-0.118986,-0.209977,-0.232322,-0.037078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4040,NDTV,NEW DELHI TELEVISION LTD.,2006-03-31,2006,INE155G01029,P00000256,DR.(MR.),TARUN,NaN,DAS,1939-02-16,M,NaN,NaN,NaN,nan,nan,GRADUATE: B.A.(HONS.)-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.TARUN DAS IS THE CHIEF MENTOR OF CONFEDERAT...,NaT,U,2004-05-14,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,686.0,0.0,0.0,321.0,0.0,0.0,321.0,686.0,0.0,0.0,686.0,321.0,0.0,0.0,321.0,686.0,0.0,0.0,686.0,2164,(),"{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}","{(NDTV, U), (BAJAJHLDNG, U), (ACC, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,86,0.0,1.879452,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,NDTV,6020,Public Ltd.,Adani Group,158295.0,New Delhi Television Ltd.,{},GRADUATE: B.A.(HONS.)-ECONOMICS nan nan nan na...,0,0,{},"{6020, 64300, 23941}","{6020, 64300, 23941}","{6020, 64300, 23941}","{64, 23, 60}",1,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Importing CAR filters and Filtering

In [14]:
CARs = [120, 150, 180, 210]

insuffDataLong = []
for i,CAR in enumerate(CARs):
    frame = pd.read_pickle(rf"{filtering_folder_path}\Insufficient Data for {CAR}CAR.pkl")
    dirCAR = dirCAR.merge(frame,
                          right_on = ["CompanyName", "AsOnDate"],
                          left_on = ["CompanyName", "Appointment Date"],
                          how = "left")
    dirCAR.drop(["AsOnDate_y"], axis = 1, inplace = True)
    dirCAR.rename({"insufficient_data_dummy":f"insufficient_data_dummy_{CAR}", "AsOnDate_x":"AsOnDate", "na_trading_days":f"na_trading_days_{CAR}"},
                  axis = 1, inplace = True)
    dirCAR[f"insufficient_data_dummy_{CAR}"].fillna(0, inplace = True)

    event_periods = [3, 5, 7, 11]
    for event_period in event_periods:
        dirCAR.loc[ dirCAR[f"insufficient_data_dummy_{CAR}"] == 1, f"{CAR}CAR{event_period}"] = pd.NA

FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\[IN USE] Rookie Directors\\[4] FF3 CAR precode\\car_filtering\\Insufficient Data for 120CAR.pkl'

## Filtered Data Points

In [ ]:
filter_row_list = [
    dirCAR.loc[ (dirCAR["Person Code"] == "P00093327") & 
    (dirCAR["Symbol"] == "ATNINTER") & (dirCAR["AsOnDate"] == "2020-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00095015") & 
    (dirCAR["Symbol"] == "HNDFDS") & (dirCAR["AsOnDate"] == "2024-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00100475") & 
    (dirCAR["Symbol"] == "ROUTE") & (dirCAR["AsOnDate"] == "2021-03-31")],

    dirCAR.loc[ (dirCAR["Person Code"] == "P00013751") & 
    (dirCAR["Symbol"] == "LLOYDSME") & (dirCAR["AsOnDate"] == "2024-03-31")]
]

filter_df = pd.concat(filter_row_list, axis = 0)

In [ ]:
dirCAR2 = dirCAR.iloc[ dirCAR.index.difference(filter_df.index)  ].reset_index(drop = True)

In [ ]:
dirCAR2.to_pickle(rf"{output_folder_path}\Director Level_MF_CAR.pkl")

In [ ]:
# dirCAR.to_pickle(rf"{output_folder_path}\Director Level_MF_CAR.pkl")

In [22]:
dirCAR2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,AppointDummy,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,NSE symbol,NIC code,Entity type,Ownership group,Prowess company code,CompanyName,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,IsExecCurrent,NumExecAll,IsOutsideExecXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,skilllist_sustainability,skilllist_entrepreneurial,skilllist_compensation,skilllist_conglomerate_experience,skilllist_hr,skilllist_technology,skilllist_finance_accounting,skilllist_governance,skilllist_government_policy,skilllist_international,skilllist_leadership,skilllist_legal,skilllist_marketing,skilllist_risk_management,skilllist_scientific,skilllist_strategic_planning,skilllist_manufacturing_supply_chain,Academic,Manufacturing,Outside Board,Company Business,profile_sustainability,profile_entrepreneurial,profile_compensation,profile_conglomerate_experience,profile_hr,profile_technology,profile_finance_accounting,profile_governance,profile_government_policy,profile_international,profile_leadership,profile_legal,profile_marketing,profile_risk_management,profile_scientific,profile_strategic_planning,profile_manufacturing_supply_chain,Committee Name,committee_sustainability,committee_entrepreneurial,committee_compensation,committee_conglomerate_experience,committee_hr,committee_technology,committee_finance_accounting,committee_governance,committee_government_policy,committee_international,committee_leadership,committee_legal,committee_marketing,committee_risk_management,committee_scientific,committee_strategic_planning,committee_manufacturing_supply_chain,combined_sustainability,combined_entrepreneurial,combined_compensation,combined_conglomerate_experience,combined_hr,combined_technology,combined_finance_accounting,combined_governance,combined_government_policy,combined_international,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,NumSkills_dummies,Total No.of Board Meetings Held,No.of Meetings Attended,percent_board_absence,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11,OLS210_intercept,OLS210_RMRF,OLS210_r_squared,OLS210_adjusted_r_squared,OLS210_f_p_value,210CAR3,210CAR5,210CAR7,210CAR11,insufficient_data_dummy_120,na_trading_days_120,insufficient_data_dummy_150,na_trading_days_150,insufficient_data_dummy_180,na_trading_days_180,insufficient_data_dummy_210,na_trading_days_210
0,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,1955-12-09,M,NaN,NaN,NaN,nan,nan,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,NOMINATION ENDED,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaT,U,2005-04-29,2009-03-02,NaT,2010-03-31,1,0.0,1.0,1.0,0,0.0,0.0,0.0,1403.0,0.0,0.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1038.0,0.0,0.0,1038.0,1403.0,0.0,0.0,1403.0,1402,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69,0.00000,3.843836,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,{},GRADUATE: B.SC. nan nan nan nan nan nan nan na...,0,0,{},{08},{08},{08},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
1,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,U,2007-10-13,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,535.0,0.0,0.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,170.0,0.0,0.0,170.0,535.0,0.0,0.0,535.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,1.465753,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,"{marketing, accounts/audit/taxation, finance, ...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
2,BANCOINDIA,BANCO PRODUCTS (INDIA) LTD.,2009-03-31,2009,INE213C01025,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. RAM DEVIDAYAL HOLDS MASTER DEGREE IN COMME...,NaT,U,2001-07-30,NaT,2008-03-31,2010-03-31,0,0.0,0.0,1.0,0,0.0,0.0,0.0,365.0,0.0,0.0,2436.0,0.0,0.0,2436.0,2801.0,0.0,0.0,2801.0,2436.0,0.0,0.0,2436.0,2801.0,0.0,0.0,2801.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,7.673973,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,BANCOINDIA,29301,Public Ltd.,Private (Foreign),29909.0,Banco Products (India) Ltd.,"{marketing, accounts/audit/taxation, finance, ...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,MUNJALAU,MUNJAL AUTO INDUSTRIES LTD.,2009-03-31,2009,INE672B01032,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,U,2008-07-26,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,1,0.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,0.0,0.0,248.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,248.0,0.0,0.0,248.0,2799,"((BANCOINDIA, U),)","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}","{(MUNJALAU, U), (20MICRONS, U), (BANCOINDIA, U)}",(),(),0,0,0,0,0,0,0,0,3,0,0,3,3,0,0,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,74,0.00000,0.679452,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,MUNJALAU,29209,Public Ltd.,Hero (Munjals) Group,86677.0,Munjal Auto Inds. Ltd.,"{marketing, accounts/audit/taxation, finance, ...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,{29301},"{29209, 08, 29301}","{29209, 08, 29301}","{29209, 08, 29301}","{08, 29}",0,0,0,0,0,0,0,0,0,0,0,{},{},"{'operations', 'consumer discretionary', 'info...",1,1,{BANCOINDIA},15,1,1,0,1,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
4,20MICRONS,20 MICRONS LTD.,2009-03-31,2009,INE144J01027,P00027664,MR.,MIHIR,ARVIND,JOSHI,1977-06-12,M,NaN,NaN,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaT,U,2007-08-23,NaT,NaT,2010-03-31,0,0.0,1.0,1.0,0,0.0,0.0,0.0,586.0,0.0,0.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,221.0,0.0,0.0,221.0,586.0,0.0,0.0,586.0,586,(),"{(20MICRONS, U)}","{(20MICRONS, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,47,0.00000,1.605479,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20MICRONS,08,Public Ltd.,20 Microns Group,11.0,20 Microns Ltd.,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{},{08},{08},{08},{08},0,0,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,<NA>,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258248,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00081419,MR.,ASHOK,K.,KOHLI,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2017-02-10,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,49.0,0.0,0.0,49.0,49.0,365.0,0.0,414.0,49.0,0.0,0.0,49.0,49.0,365.0,0.0,414.0,414,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,<NA>,1.00000,1.134247,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,5.05,0.041237,0.016234,-0.042546,-0.026312,0.204566,-0.756680,-0.021262,0.007799,0.018200,0.009880,0.141807,0.042647,0.032314,-0.025294,-0.13034,-0.022281,0.008887,0.024759,0.018170,0.054476,0.045621,0.035374,-0.020473,-0.127947,-0.023243,0.006936,0.015210,0.009678,0.099061,0.048657,0.038255,-0.020749,-0.123870,-0.024955,0.006593,0.015668,0.010935,0.070267,0.053818,0.043389,-0.016170,-0.118526,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
258249,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00114429,MR.,JITENDRA,KUMAR,PAL,1971-07-08,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...","GRADUATE: LL.B.,UTKAL UNIVERSITY,BHUBANESWAR",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,U,2003-12-30,2018-03-31,2017-03-31,NaT,1,0.0,0.0,2.0,0,0.0,0.0,0.0,365.0,0.0,0.0,1643.0,0.0,0.0,1643.0,2008.0,0.0,0.0,2008.0,3165.0,0.0,0.0,3165.0,3530.0,0.0,0.0,3530.0,5202,"((ZYLOG, U),)","{(ZYLOG, U)}","{(ZYLOG, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.00000,9.671233,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
258250,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00080494,MS.,KAMALA,NaN,R.,NaT,F,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZYLOG SYSTEMS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2016-11-23,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,128.0,0.0,0.0,128.0,128.0,365.0,0.0,493.0,128.0,0.0,0.0,128.0,128.0,365.0,0.0,493.0,493,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,<NA>,1.00000,1.350685,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,4.25,-0.022989,0.015807,1.118596,1.134402,0.640072,1.506896,-0.028364,0.006545,0.020030,0.011725,0.123099,0.025903,-0.107993,-0.208582,-0.08690,-0.029032,0.004966,0.013618,0.006953,0.154986,0.031027,-0.103373,-0.202336,-0.079376,-0.030786,0.004640,0.014079,0.008541,0.112633,0.036935,-0.097569,-0.196195,-0.072971,-0.027389,0.004182,0.010090,0.005331,0.146882,0.027651,-0.106999,-0.205153,-0.081559,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
258251,ZYLOG,ZYLOG SYSTEMS LTD.,2018-03-31,2018,INE225I01026,P00067111,MR.,P.,NaN,RAMARATHINAM,NaT,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,Y,2014-11-19,2018-03-31,2017-03-31,NaT,1,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,365.0,0.0,132.0,731.0,0.0,863.0,132.0,1096.0,0.0,1228.0,132.0,731.0,0.0,863.0,132.0,1096.0,0.0,1228.0,1227,"((ZYLOG, Y),)","{(ZYLOG, Y)}","{(ZYLOG, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,<NA>,3.00274,3.364384,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,ZYLOG,62013,Public Ltd.,Private (Indian),275793.0,Zylog Systems Ltd.,{},nan nan nan nan nan nan nan nan nan nan,0,0,{62013},{62013},{62013},{62013},{62},0,1,0,0,0,0,0,0,0,0,0,{},{},set(),0,0,{ZYLOG},0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,275793.0,7.70,-0.025316,0.021860,-0.741569,-0.719709,0.280029,-0.546563,-0.037219,0.014717,0.059441,0.051470,0.007287,-0.111834,-0.170415,-0.192669,-0.35466,-0.038134,0.016314,0.070138,0.063855,0.001056,-0.108154,-0.167737,-0.191004,-0.351279,-0.037386,0.015785,0.067294,0.062054,0.000437,-0.110707,-0.169957,-0.192889,-0.353733,-0.037284,0.014662,0.059576,0.055055,0.000357,-0.111669,-0.170216,-0.192435,-0.354486,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN