In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Data Reading

In [2]:
car = pd.read_pickle("Director Level CAR_on_appointment_2 v170325.pkl").rename({"Symbol_x":"Symbol", "AsOnDate_x":"AsOnDate"}, axis = 1)

In [3]:
car

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64,0.000000,3.687671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1,0,{},{22209},{22209},{22209},{22},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,3,0,0,0,0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,4.263014,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,5.679452,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaT,U,1997-03-29,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3289.0,0.0,0.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,9.010959,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,2.010101e+10,Bajaj Group,Before 1950,BAJAJHLDNG,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaT,U,2004-01-17,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,804.0,0.0,0.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,2.202740,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912,2.010103e+10,Graphite India Group,Between 1972 and 1985,GRAPHITE,"31, Chowringhee Road, Kolkata West Bengal","{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259413,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,2027-03-31,N,1997-08-01,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46,0.000000,26.682192,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Lifesciences Ltd.,41246.0,Public Ltd.,1.020302e+10,1995.0,Drugs & pharmaceuticals,1.010120e+14,Manufacture of allopathic pharmaceutical prepa...,21002,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSLIFE,"'Saffron', 2nd Floor, Ambawadi, Ahmedabad Guj...","{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259414,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,0,46,0.000000,14.936986,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
259415,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.000000,8.887671,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0,0,{10409},{10409},{10409},{10409},{10},0,0,0,1,1,0,1,0,{},{},"{leadership/management, finance, marketing, op...",0,1,{ZYDUSWELL},5,1,1,0,1,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

In [4]:
car.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'AsOnYear',
 'ISIN',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Member of Civil Services',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Occupation',
 'Cessation Reason',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Brief Profile',
 'Tenure Valid till',
 'Indep',
 'Appointment Date',
 'Cessation Date',
 'PrevLastServed',
 'NextServed',
 'CessationDummy',
 'ReappointDummy',
 'TermStartDummy',
 'TermNumber',
 'CumOpBalUnc',
 'CumOpBalIndep',
 'CumOpBalNonIndep',
 'CumCloBalUnc',
 'CumCloBalIndep',
 'CumCloBalNonIndep',
 'TermOpBalUnc',
 'TermOpBalIndep',
 'TermOpBalNonIndep',
 'TermOpBalTotal',
 'TermCloBalUnc',
 'TermCloBalIndep',
 'TermCloBalNonIndep',
 'TermCloBalTotal',
 'CompOpBalUnc',
 'CompOpBalIndep',
 'CompOpBalNonIndep',
 'CompOpBalTotal',
 'CompCloBalUnc',
 'CompCloBalIndep',
 'CompCloBalNonIndep',
 'CompCloBalTotal',
 'CloBalTotalXP',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMDPosition',
 'IsChairmanPosition',
 'IsCeoMDOccupation',
 'IsChairmanOccupation',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManager',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsinCompIndep',
 'TenureInYearsinCompTotal',
 'IsFirstTerm',
 'IsFirstTermIndep',
 'IsOneYear',
 'IsOneYearIndep',
 'IsTwoYear',
 'IsTwoYearIndep',
 'IsThreeYear',
 'IsThreeYearIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'IsBusy',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'CompanyName',
 'Prowess company code',
 'Entity type',
 'Entity type code',
 'Incorporation year',
 'Industry group',
 'Industry group code',
 'NIC name',
 'NIC code',
 'Ownership group code',
 'Ownership group',
 'Age group',
 'NSE symbol',
 'Head office address',
 'Skills',
 'EducationAll',
 'IsMBA',
 'IsPhD',
 'AllPastDirectNIC',
 'CurrDirectANIC',
 'CurrDirectABNIC',
 'AllNIC',
 'AllNIC_Industry',
 'HasFinanceXP',
 'HasTechXP',
 'HasRelatedIndustryXP',
 'HasExecXP',
 'PublicExecXPDummy',
 'PrivateExecXPDummy',
 'HasPublicExecXP',
 'HasPrivateExecXP',
 'SkillsInPositiononBoard',
 'SkillsInOccupation',
 'AllSkills',
 'HasTechSkill',
 'HasFinanceSkill',
 'FirmsPast',
 'NumSkills',
 'NumFirmsPast',
 'NumIndustryPast',
 'HasCeoMDChairXP',
 'HasConglomerateXP',
 'General Ability Index',
 'ProwessCode',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_SMB',
 'OLS120_HML',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_SMB',
 'OLS150_HML',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_SMB',
 'OLS180_HML',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11']

In [5]:
# columns = ["Symbol", "

### Non govt firms

In [6]:
nonGovFirm = car.loc[ car["Ownership group code"] >= 20000000000, :].copy()
car1 = nonGovFirm.copy()

In [7]:
car1

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64,0.000000,3.687671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1,0,{},{22209},{22209},{22209},{22},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,3,0,0,0,0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,4.263014,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,5.679452,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaT,U,1997-03-29,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3289.0,0.0,0.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,9.010959,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,2.010101e+10,Bajaj Group,Before 1950,BAJAJHLDNG,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaT,U,2004-01-17,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,804.0,0.0,0.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,2.202740,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912,2.010103e+10,Graphite India Group,Between 1972 and 1985,GRAPHITE,"31, Chowringhee Road, Kolkata West Bengal","{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259413,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,2027-03-31,N,1997-08-01,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46,0.000000,26.682192,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Lifesciences Ltd.,41246.0,Public Ltd.,1.020302e+10,1995.0,Drugs & pharmaceuticals,1.010120e+14,Manufacture of allopathic pharmaceutical prepa...,21002,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSLIFE,"'Saffron', 2nd Floor, Ambawadi, Ahmedabad Guj...","{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259414,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,0,46,0.000000,14.936986,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
259415,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.000000,8.887671,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0,0,{10409},{10409},{10409},{10409},{10},0,0,0,1,1,0,1,0,{},{},"{leadership/management, finance, marketing, op...",0,1,{ZYDUSWELL},5,1,1,0,1,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

# 2013 - 2020

In [8]:
carS1 = car1.loc[ (car1["AsOnDate"] <= "2020-03-31") & (car1["AsOnDate"] >= "2013-03-31"), : ].copy()
carS1 = carS1.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)
carS1

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,5.468493,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,1,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BANCOINDIA,BANCO PRODUCTS (INDIA) LTD.,2013-03-31,2013,INE213C01025,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. RAM DEVIDAYAL HOLDS MASTER DEGREE IN COMME...,NaT,Y,2001-07-30,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,3897.0,0.0,0.0,3897.0,3897.0,365.0,0.0,4262.0,3897.0,0.0,0.0,3897.0,3897.0,365.0,0.0,4262.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,11.676712,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,Banco Products (India) Ltd.,29909.0,Public Ltd.,1.020302e+10,1961.0,Other automobile ancillaries,1.010145e+14,Manufacture of diverse parts and accessories f...,29301,2.020200e+10,Private (Foreign),Between 1951 and 1971,BANCOINDIA,NaN,"{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MUNJALAU,MUNJAL AUTO INDUSTRIES LTD.,2013-03-31,2013,INE672B01032,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2008-07-26,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1344.0,0.0,0.0,1344.0,1344.0,365.0,0.0,1709.0,1344.0,0.0,0.0,1344.0,1344.0,365.0,0.0,1709.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,4.682192,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,Munjal Auto Inds. Ltd.,86677.0,Public Ltd.,1.020302e+10,1985.0,Other automobile ancillaries,1.010145e+14,Manufacture of other attachments to motor vehi...,29209,2.010101e+10,Hero (Munjals) Group,Between 1972 and 1985,MUNJALAU,NaN,"{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,2,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,<NA>,0.0,1.923288,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0,0,{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,{},{},{},0,0,{20MICRONS},0,1,1,0,1,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.002290,0.182078,0.160925,0.000033,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.001840,0.177502,0.160602,0.000003,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,0.000002,0.146649,0.058915,0.007006,-0.113460
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,1,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,47,0.0,12.175342,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,{},{},"{research & development, accounts/audit/taxati...",1,1,{20MICRONS},11,1,1,0,1,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26185,ZOTA,ZOTA HEALTH CARE LTD.,2020-03-31,2020,INE358U01012,P00082465,MR.,MANUKANT,CHANDULAL,ZOTA,1951-04-17,M,INDIA,NaN,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,"POST GRADUATE: M.SC.-MATHEMATICS,SARDAR PATEL ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,INTERNATIONAL BUS...","EXECUTIVE DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. MANUKANT CHANDULAL ZOLA HAS DONE MASTERS O...,2025-03-31,N,2000-07-12,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,7202.0,0.0,0.0,7202.0,0.0,0.0,7202.0,7202.0,0.0,0.0,7202.0,7202.0,0.0,0.0,7202.0,7202.0,0.0,0.0,7202.0,7197,(),"{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,73,0.0,19.731507,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","POST GRADUATE: M.SC.-MATHEMATICS,SARDAR PATEL ...",0,0,{},{46497},{46497},{46497},{46},0,0,0,0,0,0,0,0,{},{},"{international business, diversity, healthcare...",0,1,NaN,7,0,0,0,0,-1.526336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26186,ZOTA,ZOTA HEALTH CARE LTD.,2020-03-31,2020,INE358U01012,P00082472,MR.,MOXESH,KETAN,ZOTA,1990-11-12,M,INDIA,NaN,YES,"MANAGING DIRECTOR, NOMINEE DIRECTOR OF ZOTA HE...",NO,"GRADUATE: BACHELORS-PHARMACY,GUJARAT TECHNOLOG...",POST GRADUATE: M.SC.-INTERNATIONAL MARKETING &...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,DIVERSITY,FINANCE,HEAL...","MANAGING DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. MOXESH KETANBHAI ZOTA HAS DONE BACHELOR OF...,2026-10-06,N,2016-10-07,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1271.0,0.0,0.0,1271.0,0.0,0.0,1271.0,1271.0,0.0,0.0,1271.0,1271.0,0.0,0.0,1271.0,1271.0,0.0,0.0,1271.0,1270,(),"{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,34,0.0,3.482192,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","GRADUATE: BACHELORS-PHARMACY,GUJARAT TECHNOLOG...",0,0,{},{46497},{46497},{46497},{46},0,0,0,0,0,0,0,0,{healthcare},{},"{international business, diversity, healthcare...",0,1,NaN,8,0,0,0,0,-1.456844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26187,ZUARIIND,ZUARI INDUSTRIES LTD.,2020-03-31,2020,INE217A01012,P00097876,MS.,MANJU,NaN,GUPTA,1951-11-29,F,INDIA,NaN,NaN,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.A.(HONS.),PANJAB UNIVERSITY,PUNJAB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LEADERSHIP/MANAGEMENT,STRATEGY",nan,nan,ZUARI INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MRS. MANJU GUPTA, AGED 70 YEARS, IS A B.A. (HO...",2028-03-27,Y,2020-03-28,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,3.0,3,(),"{(ZUARIIND, Y)}","{(ZUARIIND, Y), (ZUARIIND, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,73,0.0,0.008219,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,Zuari Industries Ltd.,275679.0,Public Ltd.,1.020302e+10,1967.0,Sugar,1.010111e+14,Manufacture or refining of sugar (sucrose) fro...,10721,2.010101e+10,Birla K.K. Group,Between 1951 and 1971,ZUARIIND,NaN,"{leadership/management, strategy}","GRADUATE: B.A.(HONS.),PANJAB UNIVERSITY,PUNJAB...",0,0,{},{10721},{10721},{10721},{10},0,0,0,0,0,0,0,0,{},{},"{leadership/management, strategy}",0,0,NaN,2,0,0,0,1,-1.176947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26188,ZUARIIND,ZUARI INDUSTRIES LTD.,2020-03-31,2020,INE217A01012,P00096747,MR.,VIJAY,VYANKATESH,PARANJAPE,1952-05-24,M,INDIA,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.E.,REGIONAL ENGINEERING COLLEGE,NA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,OPERATIONS",nan,nan,ZUARI INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. VIJAY PARANJAPE HOLDS BACHELOR'S DEGREE IN...,2027-12-26,Y,2019-12-27,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,95.0,0.0,0.0,95.0,0.0,0.0,95.0,95.0,0.0,0.0,95.0,95.0,0.0,0.0,95.0,95.0,0.0,0.0,95.0,95,(),"{(ZUARIIND, Y)}","{(ZUARIIND, Y), (ZUARIIND, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,72,0.0,0.260274,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,Zuari Industries Ltd.,275679.0,Public Ltd.,1.020302e+10,1967.0,Sugar,1.010111e+14,Manufacture or refining of sugar (sucrose) fro...,10721,2.010101e+10,Birla K.K. Group,Between 1951 and 1971,ZUARIIND,NaN,"{operations, fast moving consumer goods, finance}","GRADUATE: B.E.,REGIONAL ENGINEERING COLLEGE,NA...",0,0,{},{10721},{10721},{10721},{10},0,0,0,0,0,0,0,0,{},{},"{operations, fast moving consumer goods, finance}",0,1,NaN,3,0,0,0,1,-1.107455,275679.0,52.65,0.123799,0.013426,0.651835,0.665261,0.189779,-0.090375,-0.025355,0.012273,0.008696,0.001335,0.135864,0.113516,0.000703,0.205191,0.166579,0.030519,0.268617,-0.025348,0.011187,0.009011,0.002295,0.145263,0.127700,0.000041,0.203766,0.163725,0.027571,0.265944,-0.025643,0.012256,0.009647,0.001578,0.140492,0.125841,0.000007,0.204517,0.164963,0.028186,0.265536
26189,ZUARIIND,ZUARI INDUSTRIES LTD.,2020-03-31,2020,INE217A01012,P00098115,MR.,SOUNDARARAGHAVAN,NaN,RANGACHARI,1948-10-28,M,INDIA,NONE,NaN,nan,nan,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,ZUARI INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. R.S. RAGHAVAN IS ONE OF THE PIONEERS IN TH...,NaT,U,2020-02-15,NaT,NaT,2021-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,0.0,0.0,45.0,0.0,0.0,0.0,0.0,45.0,0.0,0.0,45.0,45,(),"{(ZUARIIND, U)}","{(ZUARIIND, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,76,0.0,0.123288,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,Zuari Industries Ltd.,275679.0,Public Ltd.,1.020302e+10,1967.0,Sugar,1.010111e+14,Manufacture or refining of sugar (sucrose) fro...,10721,2.010101e+10,Birla K.K. Group,Between 1951 and 1971,ZUARIIND,NaN,"{leadership/management, accounts/audit/taxatio...",POST GRADUATE: C.A.(CHARTERED ACCOUNTANT) nan ...,0,0,{},{10721},{10721},{10721},{10},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,7,0,0,0,1,-0.829486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 120 Days

### 120 CAR 3

In [9]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [10]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.1899107]  P Value: [0.8493844]
Mean1: [-0.00296285]  Mean2: [-0.00242994]  Diff: [-0.00053291]
N_1: 3792 ; N_2: 3508

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.11947513]  P Value: [0.26300201]
Mean1: [-0.00237489]  Mean2: [9.66190505e-05]  Diff: [-0.00247151]
N_1: 3589 ; N_2: 1834

### 120 CAR 5

In [11]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [12]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.13355164]  P Value: [0.03291346]
Mean1: [-0.06076618]  Mean2: [-0.05388699]  Diff: [-0.00687919]
N_1: 3792 ; N_2: 3508

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.0866616]  P Value: [0.00203844]
Mean1: [-0.05697375]  Mean2: [-0.04905815]  Diff: [-0.00791559]
N_1: 3589 ; N_2: 1834

### 120 CAR 7

In [13]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [14]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-3.81729729]  P Value: [0.00013605]
Mean1: [-0.11780244]  Mean2: [-0.10429441]  Diff: [-0.01350803]
N_1: 3792 ; N_2: 3508

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.34037743]  P Value: [1.45885222e-05]
Mean1: [-0.11206242]  Mean2: [-0.09829036]  Diff: [-0.01377207]
N_1: 3589 ; N_2: 1834

### 120 CAR 11

In [15]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [16]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-5.97247244]  P Value: [2.45013373e-09]
Mean1: [-0.23143452]  Mean2: [-0.20617728]  Diff: [-0.02525724]
N_1: 3792 ; N_2: 3508

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.74568308]  P Value: [9.90422288e-09]
Mean1: [-0.22384026]  Mean2: [-0.19954147]  Diff: [-0.0242988]
N_1: 3589 ; N_2: 1834

## 150 Days

### 150 CAR 3

In [17]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [18]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.70758054]  P Value: [0.47922865]
Mean1: [-0.00332278]  Mean2: [-0.00153206]  Diff: [-0.00179072]
N_1: 3780 ; N_2: 3451

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.65489368]  P Value: [0.09802186]
Mean1: [-0.00241061]  Mean2: [0.00097143]  Diff: [-0.00338204]
N_1: 3569 ; N_2: 1805

### 150 CAR 5

In [19]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [20]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.5751138]  P Value: [0.01004133]
Mean1: [-0.0612138]  Mean2: [-0.05357972]  Diff: [-0.00763407]
N_1: 3780 ; N_2: 3451

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.57583692]  P Value: [0.00035348]
Mean1: [-0.05691754]  Mean2: [-0.04793194]  Diff: [-0.00898561]
N_1: 3569 ; N_2: 1805

### 150 CAR 7

In [21]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [22]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-4.47952485]  P Value: [7.59656226e-06]
Mean1: [-0.11878671]  Mean2: [-0.1037934]  Diff: [-0.01499331]
N_1: 3780 ; N_2: 3451

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.76123504]  P Value: [1.99915376e-06]
Mean1: [-0.11208688]  Mean2: [-0.09692089]  Diff: [-0.01516599]
N_1: 3569 ; N_2: 1805

### 150 CAR 11

In [23]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [24]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-7.14741339]  P Value: [9.70848352e-13]
Mean1: [-0.23188431]  Mean2: [-0.20453653]  Diff: [-0.02734778]
N_1: 3780 ; N_2: 3451

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.88406818]  P Value: [4.43542852e-09]
Mean1: [-0.22373236]  Mean2: [-0.19662077]  Diff: [-0.02711158]
N_1: 3569 ; N_2: 1805

## 180 Days

### 180 CAR 3

In [25]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [26]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.99383511]  P Value: [0.32036421]
Mean1: [-0.00362844]  Mean2: [-0.01034321]  Diff: [0.00671477]
N_1: 3768 ; N_2: 3391

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.1729107]  P Value: [0.02984258]
Mean1: [-0.00283723]  Mean2: [0.00152988]  Diff: [-0.00436711]
N_1: 3559 ; N_2: 1787

### 180 CAR 5

In [27]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [28]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.11266809]  P Value: [0.91029906]
Mean1: [-0.06213961]  Mean2: [-0.06299085]  Diff: [0.00085124]
N_1: 3768 ; N_2: 3391

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.96014636]  P Value: [7.62259521e-05]
Mean1: [-0.05763669]  Mean2: [-0.04766458]  Diff: [-0.00997211]
N_1: 3559 ; N_2: 1787

### 180 CAR 7

In [29]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [30]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.40803156]  P Value: [0.15918607]
Mean1: [-0.11960679]  Mean2: [-0.1109152]  Diff: [-0.00869159]
N_1: 3768 ; N_2: 3391

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.19304593]  P Value: [2.17703906e-07]
Mean1: [-0.11299548]  Mean2: [-0.0965747]  Diff: [-0.01642078]
N_1: 3559 ; N_2: 1787

### 180 CAR 11

In [31]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [32]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-3.12894667]  P Value: [0.00176376]
Mean1: [-0.23319528]  Mean2: [-0.21319672]  Diff: [-0.01999856]
N_1: 3768 ; N_2: 3391

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-6.20753798]  P Value: [6.07286857e-10]
Mean1: [-0.22463855]  Mean2: [-0.19720336]  Diff: [-0.02743519]
N_1: 3559 ; N_2: 1787

# 2013 - 2024

In [33]:
carS2 = car1.loc[ (car1["AsOnDate"] <= "2024-03-31") & (car1["AsOnDate"] >= "2013-03-31"), : ].copy()
carS2 = carS2.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)
carS2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,5.468493,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,1,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BANCOINDIA,BANCO PRODUCTS (INDIA) LTD.,2013-03-31,2013,INE213C01025,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. RAM DEVIDAYAL HOLDS MASTER DEGREE IN COMME...,NaT,Y,2001-07-30,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,3897.0,0.0,0.0,3897.0,3897.0,365.0,0.0,4262.0,3897.0,0.0,0.0,3897.0,3897.0,365.0,0.0,4262.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,11.676712,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,Banco Products (India) Ltd.,29909.0,Public Ltd.,1.020302e+10,1961.0,Other automobile ancillaries,1.010145e+14,Manufacture of diverse parts and accessories f...,29301,2.020200e+10,Private (Foreign),Between 1951 and 1971,BANCOINDIA,NaN,"{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MUNJALAU,MUNJAL AUTO INDUSTRIES LTD.,2013-03-31,2013,INE672B01032,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2008-07-26,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1344.0,0.0,0.0,1344.0,1344.0,365.0,0.0,1709.0,1344.0,0.0,0.0,1344.0,1344.0,365.0,0.0,1709.0,4259,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3,0,0,3,2,0,0,2,0,3,0,3,1,3,0,4,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74,1.0,4.682192,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,Munjal Auto Inds. Ltd.,86677.0,Public Ltd.,1.020302e+10,1985.0,Other automobile ancillaries,1.010145e+14,Manufacture of other attachments to motor vehi...,29209,2.010101e+10,Hero (Munjals) Group,Between 1972 and 1985,MUNJALAU,NaN,"{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1,0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",1,1,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15,3,3,0,1,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,2,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,<NA>,0.0,1.923288,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0,0,{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,{},{},{},0,0,{20MICRONS},0,1,1,0,1,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.00229,0.182078,0.160925,0.000033,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.00184,0.177502,0.160602,0.000003,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,0.000002,0.146649,0.058915,0.007006,-0.113460
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1,0,0,1,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,1,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,47,0.0,12.175342,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1,0,{08},{08},{08},{08},{08},0,0,1,0,0,0,0,0,{},{},"{research & development, accounts/audit/taxati...",1,1,{20MICRONS},11,1,1,0,1,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39279,ZENITHDRUG,ZENITH DRUGS LTD.,2024-03-31,2024,INE0QWN01013,P00116777,MR.,BHUPESH,NaN,SONI,1978-10-05,M,INDIA,NaN,NaN,EXECUTIVE DIRECTOR,NO,"GRADUATE: BACHELORS-PHARMACY,SHRI GOVINDRAM SE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,"EXECUTIVE DIRECTOR, ZENITH DRUGS LTD.",nan,ZENITH DRUGS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. BHUPESH SONI, AGED 44 YEARS, IS THE PROMOT...",NaT,N,2001-03-15,2024-03-31,NaT,NaT,1,0.0,1.0,1.0,0.0,0.0,0.0,8417.0,0.0,0.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8411,(),"{(ZENITHDRUG, N)}","{(ZENITHDRUG, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,46,0.0,23.060274,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zenith Drugs Ltd.,275216.0,Public Ltd.,1.020302e+10,2000.0,Drugs & pharmaceuticals,1.010120e+14,"Manufacture of pharmaceuticals, medicinal chem...",2100,2.010200e+10,Private (Indian),Between 1991 and 2013,ZENITHDRUG,NaN,{},"GRADUATE: BACHELORS-PHARMACY,SHRI GOVINDRAM SE...",0,0,{},{2100},{2100},{2100},{21},0,0,0,0,0,0,0,0,{},{},{},0,0,<NA>,0,0,0,0,0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39280,ZENITHSTL,ZENITH STEEL PIPES & INDUSTRIES LTD.,2024-03-31,2024,INE318D01020,P00113631,MR.,GANESH,RAMESH,MAHENDRAKAR,1980-10-20,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,D...",nan,nan,ZENITH STEEL PIPES & INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. GANESH MAHENDRAKAR HOLDS B.COM FROM MUMBAI...,NaT,Y,2023-07-15,2024-03-31,NaT,NaT,1,0.0,1.0,1.0,0.0,0.0,0.0,260.0,0.0,0.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,365,(),"{(ZENITHSTL, Y)}","{(ZENITHSTL, Y), (ZENITHSTL, U)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,44,0.0,0.712329,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,Zenith Steel Pipes & Inds. Ltd.,275251.0,Public Ltd.,1.020302e+10,1960.0,Steel pipes & tubes,1.010135e+14,"Manufacture of tubes, pipes and hollow profile...",24311,2.010101e+10,Birla Ashok Group,Between 1951 and 1971,ZENITHSTL,NaN,"{leadership/management, diversity, accounts/au...","GRADUATE: B.COM.,UNIVERSITY OF MUMBAI,MUMBAI n...",1,0,{},{24311},{24311},{24311},{24},0,0,0,0,0,0,0,0,{},{},"{leadership/management, diversity, accounts/au...",0,1,<NA>,11,0,0,0,1,-0.551518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39281,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024,INE358U01012,P00114239,MR.,DHAVAL,CHANDU,PATWA,1990-05-13,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",GRADUATE: DIPLOMA-INFORMATION SYSTEMS AUDIT,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,DIVERSITY,FINANCE,INTE...",nan,nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. DHAVAL CHANDUBHAI PATWA IS FELLOW MEMBER O...,2028-08-25,Y,2023-08-26,2024-03-31,NaT,NaT,1,0.0,1.0,1.0,0.0,0.0,0.0,218.0,0.0,0.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,365,(),"{(ZOTA, Y)}","{(ZOTA, U), (ZOTA, Y)}",(),(),0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,2,Y,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,34,0.0,0.597260,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,1,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, accounts/a...","GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",0,0,{},{46497},{46497},{46497},{46},0,0,0,0,0,0,0,0,{},{},"{international business, diversity, accounts/a...",0,1,<NA>,5,0,0,0,0,-1.665321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39282,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024,INE358U01012,P00114238,MR.,LAXMI,KANT,SHARMA,1975-10-15,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,"GRADUATE: B.SC.-BIOLOGY,RAJASTHAN UNIVERSITY,J...","GRADUATE: DIPLOMA-PHARMACY,BOARD OF TECHNICAL ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,LEGAL/COMPLIANCE,...","EXECUTIVE DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. LAXMI KANT SHARMA HOLDS BACHELOR’S DEGREE ...,2028-08-25,N,2023-08-26,2024-03-31,NaT,NaT,1,0.0,1.0,1.0,0.0,0.0,0.0,218.0,0.0,0.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,365,(),"{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,Y,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,49,0.0,0.597260,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{diversity, healthcare, legal/compliance, fina...","GRADUATE: B.SC.-BIOLOGY,RAJASTHAN UNIVERSITY,J...",0,0,{},{46497},{46497},{46497},{46},0,0,0,0,0,0,0,0,{},{},"{diversity, healthcare, legal/compliance, fina...",0,1,<NA>,5,0,0,0,0,-1.665321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 120 Days

### 120 CAR 3

In [34]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [35]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.06118817]  P Value: [0.95121066]
Mean1: [-0.00311591]  Mean2: [-0.00297429]  Diff: [-0.00014162]
N_1: 6040 ; N_2: 4894

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.54557578]  P Value: [0.58537908]
Mean1: [-0.00303317]  Mean2: [-0.0019587]  Diff: [-0.00107447]
N_1: 5517 ; N_2: 2728

### 120 CAR 5

In [36]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [37]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.27801244]  P Value: [0.78100849]
Mean1: [-0.05343825]  Mean2: [-0.0526949]  Diff: [-0.00074335]
N_1: 6038 ; N_2: 4892

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.91702286]  P Value: [0.35916681]
Mean1: [-0.05177252]  Mean2: [-0.04980687]  Diff: [-0.00196565]
N_1: 5516 ; N_2: 2727

### 120 CAR 7

In [38]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [39]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.61545237]  P Value: [0.53827106]
Mean1: [-0.1034176]  Mean2: [-0.10155855]  Diff: [-0.00185905]
N_1: 6036 ; N_2: 4891

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.48219067]  P Value: [0.13834076]
Mean1: [-0.10108081]  Mean2: [-0.0971649]  Diff: [-0.0039159]
N_1: 5515 ; N_2: 2727

### 120 CAR 11

In [40]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [41]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.38034169]  P Value: [0.16751813]
Mean1: [-0.20243891]  Mean2: [-0.19683082]  Diff: [-0.00560809]
N_1: 6029 ; N_2: 4888

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.15570314]  P Value: [0.87627116]
Mean1: [-0.19433466]  Mean2: [-0.19534135]  Diff: [0.00100668]
N_1: 5509 ; N_2: 2727

## 150 Days

### 150 CAR 3

In [42]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [43]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.29501242]  P Value: [0.76799033]
Mean1: [-0.00324622]  Mean2: [-0.00267188]  Diff: [-0.00057433]
N_1: 6017 ; N_2: 4832

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.10559316]  P Value: [0.26894812]
Mean1: [-0.00272687]  Mean2: [-0.00078101]  Diff: [-0.00194586]
N_1: 5492 ; N_2: 2698

### 150 CAR 5

In [44]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [45]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.43950236]  P Value: [0.66030652]
Mean1: [-0.05359631]  Mean2: [-0.05256324]  Diff: [-0.00103307]
N_1: 6015 ; N_2: 4830

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.35134506]  P Value: [0.17663513]
Mean1: [-0.05132971]  Mean2: [-0.04857904]  Diff: [-0.00275066]
N_1: 5491 ; N_2: 2697

### 150 CAR 7

In [46]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [47]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.07145862]  P Value: [0.2839889]
Mean1: [-0.10391414]  Mean2: [-0.10094479]  Diff: [-0.00296935]
N_1: 6014 ; N_2: 4829

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.82843356]  P Value: [0.06753475]
Mean1: [-0.10050555]  Mean2: [-0.09582765]  Diff: [-0.0046779]
N_1: 5490 ; N_2: 2697

### 150 CAR 11

In [48]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [49]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.98311487]  P Value: [0.04738478]
Mean1: [-0.20251243]  Mean2: [-0.19513826]  Diff: [-0.00737418]
N_1: 6007 ; N_2: 4826

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.0716773]  P Value: [0.94286058]
Mean1: [-0.19328466]  Mean2: [-0.19281666]  Diff: [-0.000468]
N_1: 5484 ; N_2: 2697

## 180 Days

### 180 CAR 3

In [50]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [51]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.11557872]  P Value: [0.26465143]
Mean1: [-0.00349575]  Mean2: [-0.00890879]  Diff: [0.00541305]
N_1: 5988 ; N_2: 4762

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.18443694]  P Value: [0.85368078]
Mean1: [-0.00287485]  Mean2: [-0.00237482]  Diff: [-0.00050003]
N_1: 5482 ; N_2: 2679

### 180 CAR 5

In [52]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [53]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.86319959]  P Value: [0.38806332]
Mean1: [-0.0543475]  Mean2: [-0.0590482]  Diff: [0.00470071]
N_1: 5986 ; N_2: 4760

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.68147495]  P Value: [0.49560238]
Mean1: [-0.05137373]  Mean2: [-0.04969042]  Diff: [-0.0016833]
N_1: 5481 ; N_2: 2678

### 180 CAR 7

In [54]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [55]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.22642171]  P Value: [0.82088042]
Mean1: [-0.10461504]  Mean2: [-0.10564705]  Diff: [0.00103201]
N_1: 5985 ; N_2: 4759

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.05738888]  P Value: [0.29039017]
Mean1: [-0.10076684]  Mean2: [-0.09738974]  Diff: [-0.00337709]
N_1: 5480 ; N_2: 2678

### 180 CAR 11

In [56]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [57]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.52898618]  P Value: [0.59683155]
Mean1: [-0.20363106]  Mean2: [-0.20092191]  Diff: [-0.00270915]
N_1: 5978 ; N_2: 4756

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.28638281]  P Value: [0.77459222]
Mean1: [-0.19377862]  Mean2: [-0.19580253]  Diff: [0.00202391]
N_1: 5474 ; N_2: 2678

## Family Firms: IsFamilyChairmanAndCEO	 == 1 and Non Govt. Firms

In [58]:
nonGovFirm = car.loc[ (car["Ownership group code"] >= 20000000000), :].copy()

In [59]:
car

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64,0.000000,3.687671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1,0,{},{22209},{22209},{22209},{22},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,3,0,0,0,0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,4.263014,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,5.679452,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaT,U,1997-03-29,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3289.0,0.0,0.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,9.010959,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,2.010101e+10,Bajaj Group,Before 1950,BAJAJHLDNG,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaT,U,2004-01-17,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,804.0,0.0,0.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,2.202740,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912,2.010103e+10,Graphite India Group,Between 1972 and 1985,GRAPHITE,"31, Chowringhee Road, Kolkata West Bengal","{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259413,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,2027-03-31,N,1997-08-01,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46,0.000000,26.682192,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Lifesciences Ltd.,41246.0,Public Ltd.,1.020302e+10,1995.0,Drugs & pharmaceuticals,1.010120e+14,Manufacture of allopathic pharmaceutical prepa...,21002,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSLIFE,"'Saffron', 2nd Floor, Ambawadi, Ahmedabad Guj...","{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259414,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,0,46,0.000000,14.936986,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
259415,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.000000,8.887671,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0,0,{10409},{10409},{10409},{10409},{10},0,0,0,1,1,0,1,0,{},{},"{leadership/management, finance, marketing, op...",0,1,{ZYDUSWELL},5,1,1,0,1,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

In [60]:
familyChairCEOFirm = car.loc[ car["IsFamilyChairmanAndCEO"] == 1, ["Symbol", "Company", "AsOnDate"]].drop_duplicates()
familyChairCEOFirm

            Symbol                     Company   AsOnDate
73118    20MICRONS             20 MICRONS LTD. 2013-03-31
73147       3PLAND       3P LAND HOLDINGS LTD. 2013-03-31
73166      63MOONS  63 MOONS TECHNOLOGIES LTD. 2013-03-31
73209   AARTIDRUGS            AARTI DRUGS LTD. 2013-03-31
73210     AARTIIND       AARTI INDUSTRIES LTD. 2013-03-31
...            ...                         ...        ...
259273        YCCL     YASONS CHEMEX CARE LTD. 2024-03-31
259333      ZENTEC       ZEN TECHNOLOGIES LTD. 2024-03-31
259366      ZIMLAB       ZIM LABORATORIES LTD. 2024-03-31
259385      ZODIAC          ZODIAC ENERGY LTD. 2024-03-31
259414   ZYDUSWELL         ZYDUS WELLNESS LTD. 2024-03-31

[7353 rows x 3 columns]

In [61]:
car2 = familyChairCEOFirm.merge(nonGovFirm, on = ["Symbol", "Company", "AsOnDate"], how = "left").reset_index(drop = True)
car2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259.0,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3.0,0.0,0.0,3.0,2.0,0.0,0.0,2.0,0.0,3.0,0.0,3.0,1.0,3.0,0.0,4.0,N,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,74,1.000000,5.468493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1.0,0.0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",1.0,1.0,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15.0,3.0,3.0,0.0,1.0,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,0.000000,1.923288,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,{20MICRONS},0.0,1.0,1.0,0.0,1.0,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.002290,0.182078,0.160925,3.311803e-05,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.001840,0.177502,0.160602,2.684035e-06,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,1.552181e-06,0.146649,0.058915,0.007006,-0.113460
2,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,47,0.000000,12.175342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, MANAGING DIRECTOR, EXECUTIVE DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,N,1988-03-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,9127.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79,0.000000,25.021918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",POST GRADUATE: M.SC.-CHEMISTRY nan nan nan nan...,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,1.0,1.0,0.503581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027666,MR.,RAJESH,CHANDRESH,PARIKH,1971-12-28,M,INDIA,NaN,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,GRADUATE: B.E.-MECHANICAL,POST GRADUATE: M.B.A.-FINANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.RAJESH C. PARIKH, (DIRECTOR) HAS GRADUATED ...",NaT,N,1998-07-02,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5382.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.000000,14.756164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",GRADUATE: B.E.-MECHANICAL POST GRADUATE: M.B.A...,1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61719,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00022618,MR.,GANESH,NARAYAN,NAYAK,1955-05-18,M,INDIA,NONE,NO,"NOMINEE DIRECTOR OF CADILA HEALTHCARE LTD., NO...",NO,"GRADUATE: B.SC.,UNIVERSITY OF MYSORE,MYSURU","POST GRADUATE: M.B.A.,NEWPORT UNIVERSITY,CALIF...","POST GRADUATE: P.G.-GENERAL MANAGEMENT,HARVARD...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,HEALTHCARE,LEADERSH...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. GANESH NAYAK, THE EXECUTIVE DIRECTOR OF ZY...",NaT,N,2006-07-27,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,2074.0,0.0,4018.0,6092.0,2074.0,0.0,4383.0,6457.0,2074.0,0.0,4018.0,6092.0,2074.0,0.0,4383.0,6457.0,6452.0,"((ZYDUSWELL, U), (ZYDUSLIFE, N), (ZYDUSWELL, N))","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSWELL, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,2.0,3.0,N,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,69,0.000000,17.690411,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, healthcare, marketing,...","GRADUATE: B.SC.,UNIVERSITY OF MYSORE,MYSURU PO...",1.0,0.0,"{10409, 21002}","{10409, 21002}","{10409, 21002}","{10409, 21002}","{21, 10}",0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,{healthcare},{},"{leadership/management, healthcare, marketing,...",0.0,0.0,"{ZYDUSLIFE, ZYDUSWELL}",5.0,2.0,2.0,0.0,1.0,0.142308,42684.0,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023966,-0.000438,-0.001534,-0.000275,0.017751,-0.007652,5.546472e-01,0.025529,-0.039495,-0.111142,-0.180133,-0.023648,-0.000479,-0.001826,0.000462,0.026400,0.006395,2.702863e-01,0.025770,-0.038398,-0.111312,-0.181065,-0.023591,-0.000528,-0.002276,-0.000210,0.029542,0.013000,1.515805e-01,0.026477,-0.037134,-0.110531,-0.180143
61720,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732.0,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,2.0,3.0,N,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,46,0.000000,14.936986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0.0,1.0,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",0.0,0.0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7.0,3.0,3.0,1.0,1.0,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
61721,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242.0,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.000000,8.887671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0.0,0.0,{10409},{10409},{10409},{10409},{10},0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,{},{},"{leadership/management, finance, marketing, op...",0.0,1.0,{ZYDUSWELL},5.0,1.0,1.0,0.0,1.0,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

# 2013 - 2020

In [62]:
carS1 = car2.loc[ (car2["AsOnDate"] <= "2020-03-31") & (car2["AsOnDate"] >= "2013-03-31"), : ].copy()
carS1 = carS1.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)

## 120 Days

### 120 CAR 3

In [63]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [64]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.17263214]  P Value: [0.86295539]
Mean1: [-0.00063363]  Mean2: [-0.0013226]  Diff: [0.00068897]
N_1: 1525 ; N_2: 1480

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.83065798]  P Value: [0.40629284]
Mean1: [-0.00503611]  Mean2: [-0.00113664]  Diff: [-0.00389947]
N_1: 1009 ; N_2: 637

### 120 CAR 5

In [65]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [66]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.8786364]  P Value: [0.37968835]
Mean1: [-0.05801807]  Mean2: [-0.05372726]  Diff: [-0.00429082]
N_1: 1525 ; N_2: 1480

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.68139887]  P Value: [0.09288738]
Mean1: [-0.06037429]  Mean2: [-0.05217285]  Diff: [-0.00820143]
N_1: 1009 ; N_2: 637

### 120 CAR 7

In [67]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [68]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.67852195]  P Value: [0.09338335]
Mean1: [-0.11512046]  Mean2: [-0.10503297]  Diff: [-0.01008749]
N_1: 1525 ; N_2: 1480

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.4198158]  P Value: [0.01565593]
Mean1: [-0.11642654]  Mean2: [-0.10280626]  Diff: [-0.01362028]
N_1: 1009 ; N_2: 637

### 120 CAR 11

In [69]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [70]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.73168428]  P Value: [0.00634528]
Mean1: [-0.22776295]  Mean2: [-0.20820482]  Diff: [-0.01955814]
N_1: 1525 ; N_2: 1480

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.04782395]  P Value: [0.00234377]
Mean1: [-0.23233807]  Mean2: [-0.20840691]  Diff: [-0.02393116]
N_1: 1009 ; N_2: 637

## 150 Days

### 150 CAR 3

In [71]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [72]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.26057058]  P Value: [0.79444281]
Mean1: [-0.00194568]  Mean2: [-0.00096102]  Diff: [-0.00098466]
N_1: 1519 ; N_2: 1454

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.48167647]  P Value: [0.13862362]
Mean1: [-0.00580878]  Mean2: [0.00031966]  Diff: [-0.00612844]
N_1: 1000 ; N_2: 626

### 150 CAR 5

In [73]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [74]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.52473256]  P Value: [0.12743791]
Mean1: [-0.05954691]  Mean2: [-0.05271779]  Diff: [-0.00682912]
N_1: 1519 ; N_2: 1454

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.28501204]  P Value: [0.02244484]
Mean1: [-0.06137451]  Mean2: [-0.05101402]  Diff: [-0.01036049]
N_1: 1000 ; N_2: 626

### 150 CAR 7

In [75]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [76]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.18747302]  P Value: [0.02879154]
Mean1: [-0.11737678]  Mean2: [-0.1045879]  Diff: [-0.01278888]
N_1: 1519 ; N_2: 1454

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.96419992]  P Value: [0.00308293]
Mean1: [-0.11743001]  Mean2: [-0.10181485]  Diff: [-0.01561516]
N_1: 1000 ; N_2: 626

### 150 CAR 11

In [77]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [78]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-3.49115445]  P Value: [0.00048818]
Mean1: [-0.22922018]  Mean2: [-0.20685579]  Diff: [-0.02236439]
N_1: 1519 ; N_2: 1454

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.69693226]  P Value: [0.00022565]
Mean1: [-0.23308456]  Mean2: [-0.20720954]  Diff: [-0.02587502]
N_1: 1000 ; N_2: 626

## 180 Days

### 180 CAR 3

In [79]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [80]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.24579229]  P Value: [0.21303689]
Mean1: [-0.00186972]  Mean2: [-0.02092175]  Diff: [0.01905203]
N_1: 1516 ; N_2: 1425

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.93280159]  P Value: [0.05343767]
Mean1: [-0.00573899]  Mean2: [0.00168146]  Diff: [-0.00742044]
N_1: 997 ; N_2: 618

### 180 CAR 5

In [81]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [82]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.91119803]  P Value: [0.36233761]
Mean1: [-0.05948172]  Mean2: [-0.07492653]  Diff: [0.01544481]
N_1: 1516 ; N_2: 1425

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.72057954]  P Value: [0.00658928]
Mean1: [-0.0616777]  Mean2: [-0.04987369]  Diff: [-0.01180401]
N_1: 997 ; N_2: 618

### 180 CAR 7

In [83]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [84]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.25814982]  P Value: [0.79632415]
Mean1: [-0.11708568]  Mean2: [-0.12054618]  Diff: [0.0034605]
N_1: 1516 ; N_2: 1425

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.35082413]  P Value: [0.00082581]
Mean1: [-0.11800783]  Mean2: [-0.10102124]  Diff: [-0.01698659]
N_1: 997 ; N_2: 618

### 180 CAR 11

In [85]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [86]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.64630885]  P Value: [0.51816486]
Mean1: [-0.22874759]  Mean2: [-0.22051072]  Diff: [-0.00823687]
N_1: 1516 ; N_2: 1425

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.93718176]  P Value: [8.60357389e-05]
Mean1: [-0.23347268]  Mean2: [-0.20751196]  Diff: [-0.02596072]
N_1: 997 ; N_2: 618

# 2013 - 2024

In [87]:
carS2 = car2.loc[ (car2["AsOnDate"] <= "2024-03-31") & (car2["AsOnDate"] >= "2013-03-31"), : ].copy()
carS2 = carS2.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)
carS2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259.0,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3.0,0.0,0.0,3.0,2.0,0.0,0.0,2.0,0.0,3.0,0.0,3.0,1.0,3.0,0.0,4.0,N,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,74,1.0,5.468493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1.0,0.0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",1.0,1.0,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15.0,3.0,3.0,0.0,1.0,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,0.0,1.923288,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,{20MICRONS},0.0,1.0,1.0,0.0,1.0,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.002290,0.182078,0.160925,0.000033,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.001840,0.177502,0.160602,0.000003,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,0.000002,0.146649,0.058915,0.007006,-0.113460
2,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,47,0.0,12.175342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, MANAGING DIRECTOR, EXECUTIVE DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,N,1988-03-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,9127.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79,0.0,25.021918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",POST GRADUATE: M.SC.-CHEMISTRY nan nan nan nan...,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,1.0,1.0,0.503581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027666,MR.,RAJESH,CHANDRESH,PARIKH,1971-12-28,M,INDIA,NaN,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,GRADUATE: B.E.-MECHANICAL,POST GRADUATE: M.B.A.-FINANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.RAJESH C. PARIKH, (DIRECTOR) HAS GRADUATED ...",NaT,N,1998-07-02,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5382.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.0,14.756164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",GRADUATE: B.E.-MECHANICAL POST GRADUATE: M.B.A...,1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15797,YCCL,YASONS CHEMEX CARE LTD.,2024-03-31,2024.0,INE08S201019,P00114156,MS.,SILVA,KRIYANG,SHAH,NaT,F,NaN,NaN,NaN,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.COM.,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),POST GRADUATE: COMPANY SECRETARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,YASONS CHEMEX CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,SHE IS QUALIFIED CHARTERED ACCOUNTANT AND COMP...,2028-08-20,Y,2023-08-21,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,223.0,0.0,0.0,223.0,0.0,0.0,223.0,223.0,0.0,0.0,223.0,223.0,0.0,0.0,223.0,223.0,0.0,0.0,223.0,365.0,(),"{(YCCL, Y)}","{(YCCL, Y), (YCCL, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,<NA>,0.0,0.610959,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Yasons Chemex Care Ltd.,574609.0,Public Ltd.,1.020302e+10,2017.0,Dyes & pigments,1.010120e+14,Manufacture of dyes and pigments from any sour...,20114,2.010200e+10,Private (Indian),After 2014,YCCL,NaN,{},GRADUATE: B.COM. POST GRADUATE: C.A.(CHARTERED...,0.0,0.0,{},{20114},{20114},{20114},{20},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15798,YCCL,YASONS CHEMEX CARE LTD.,2024-03-31,2024.0,INE08S201019,P00113817,MR.,SMIT,KUMARPAL,SHAH,1990-06-12,M,INDIA,NaN,NaN,NON-EXECUTIVE DIRECTOR,YES,"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,"PARTNER, SHAH & SHAH",nan,YASONS CHEMEX CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,SMIT KUMARPAL SHAH IS A NON-EXECUTIVE INDEPEND...,NaT,Y,2022-12-08,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,479.0,0.0,0.0,479.0,0.0,0.0,479.0,479.0,0.0,0.0,479.0,479.0,0.0,0.0,479.0,479.0,0.0,0.0,479.0,478.0,(),"{(YCCL, Y)}","{(YCCL, Y), (YCCL, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34,0.0,1.312329,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Yasons Chemex Care Ltd.,574609.0,Public Ltd.,1.020302e+10,2017.0,Dyes & pigments,1.010120e+14,Manufacture of dyes and pigments from any sour...,20114,2.010200e+10,Private (Indian),After 2014,YCCL,NaN,{},"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",0.0,0.0,{},{20114},{20114},{20114},{20},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15799,ZENTEC,ZEN TECHNOLOGIES LTD.,2024-03-31,2024.0,INE251B01027,P00116093,MR.,SANJAY,VIJAY SINGH,JESRANI,1965-05-25,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.COM.,POST GRADUATE: C.F.A.(CHARTERED FINANCIAL ANAL...,"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZEN TECHNOLOGIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. SANJAY VIJAY SINGH JESRANI HOLDS A BACHELO...,2027-01-26,Y,2024-01-27,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,64.0,0.0,0.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,365.0,(),"{(ZENTEC, Y)}","{(ZENTEC, Y), (ZENTEC, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,59,0.0,0.175342,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zen Technologies Ltd.,275155.0,Public Ltd.,1.020302e+10,1993.0,"Computers, peripherals & storage devices",1.010140e+14,"Manufacture of desktop computers, laptop compu...",26201,2.010104e+10,Zen Technologies Group,Between 1991 and 2013,ZENTEC,NaN,{},GRADUATE: B.COM. POST GRADUATE: C.F.A.(CHARTER...,0.0,0.0,{},{26201},{26201},{26201},{26},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,<NA>,0.0,0.0,0.0,0.0,1.0,-1.315932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15800,ZODIAC,ZODIAC ENERGY LTD.,2024-03-31,2024.0,INE761Y01019,P00082169,MR.,JAIMIN,JAGDISH,SHAH,1973-04-25,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.E.-COMPUTER SCIENCE,DHARMSINH DESA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,DIVERSITY,FINANCE,INDUSTR...","CO-FOUNDER & MANAGING DIRECTOR, DEV INFORMATIO...",nan,DEV INFORMATION TECHNOLOGY LTD.,ZODIAC ENERGY LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. JAIMIN SHAH HAS MORE THAN 25 YEARS OF EXPE...,2028-09-07,Y,2023-09-08,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,205.0,0.0,0.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,9588.0,"((DEVIT, N),)","{(ZODIAC, Y), (DEVIT, N)}","{(ZODIAC, Y), (DEVIT, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0,2.0,N,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,51,0.0,0.561644,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zodiac Energy Ltd.,275567.0,Public Ltd.,1.020302e+10,1992.0,Industrial construction,1.010602e+14,Construction and maintenance of power plants,42201,2.010200e+10,Private (Indian),Between 1991 and 2013,ZODIAC,"U G F 4-5-6, Milestone Building, Near Khodiyar...","{leadership/management, diversity, research & ...","GRADUATE: B.E.-COMPUTER SCIENCE,DHARMSINH DESA...",0.0,0.0,{62013},"{42201, 62013}","{42201, 62013}","{42201, 62013}","{42, 62}",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{information technology},"{leadership/management, diversity, research & ...",1.0,1.0,{DEVIT},12.0,1.0,1.0,0.0,0.0,-0.623486,275567.0,126.90,-0.001574,0.018014,0.422633,0.440646,-0.289091,0.388448,-0.027673,0.009355,0.013963,-0.000751,0.083652,0.059953,0.017121,0.050536,0.072523,-0.003342,-0.134505,-0.027514,0.011262,0.011705,0.001796,0.106280,0.087916,0.000912,0.042471,0.070028,-0.011012,-0.155503,-0.027063,0.008801,0.010281,0.001935,0.105275,0.090024,0.000202,0.043852,0.064780,-0.013468,-0.152510

## 120 Days

### 120 CAR 3

In [88]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [89]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.29386041]  P Value: [0.76888141]
Mean1: [-0.00154841]  Mean2: [-0.00069974]  Diff: [-0.00084867]
N_1: 2496 ; N_2: 2167

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.66185245]  P Value: [0.50812625]
Mean1: [-0.00333727]  Mean2: [-0.00119805]  Diff: [-0.00213922]
N_1: 1571 ; N_2: 1012

### 120 CAR 5

In [90]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [91]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.07982738]  P Value: [0.93637893]
Mean1: [-0.05109115]  Mean2: [-0.05080781]  Diff: [-0.00028334]
N_1: 2496 ; N_2: 2167

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.39327961]  P Value: [0.69414632]
Mean1: [-0.05212882]  Mean2: [-0.05075541]  Diff: [-0.0013734]
N_1: 1571 ; N_2: 1012

### 120 CAR 7

In [92]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [93]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.29135098]  P Value: [0.77079995]
Mean1: [-0.10059184]  Mean2: [-0.09931399]  Diff: [-0.00127785]
N_1: 2496 ; N_2: 2167

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.88299488]  P Value: [0.37732933]
Mean1: [-0.10184566]  Mean2: [-0.09822432]  Diff: [-0.00362134]
N_1: 1571 ; N_2: 1012

### 120 CAR 11

In [94]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [95]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.82475235]  P Value: [0.40957087]
Mean1: [-0.19788221]  Mean2: [-0.19263499]  Diff: [-0.00524722]
N_1: 2493 ; N_2: 2166

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.16940383]  P Value: [0.86549265]
Mean1: [-0.19965262]  Mean2: [-0.19866509]  Diff: [-0.00098754]
N_1: 1569 ; N_2: 1012

## 150 Days

### 150 CAR 3

In [96]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [97]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.73741351]  P Value: [0.46091189]
Mean1: [-0.00232237]  Mean2: [-0.00031817]  Diff: [-0.0020042]
N_1: 2482 ; N_2: 2139

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.20165563]  P Value: [0.22960898]
Mean1: [-0.00347524]  Mean2: [1.99746881e-05]  Diff: [-0.00349522]
N_1: 1560 ; N_2: 999

### 150 CAR 5

In [98]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [99]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.63135623]  P Value: [0.52784124]
Mean1: [-0.05197204]  Mean2: [-0.04991638]  Diff: [-0.00205566]
N_1: 2482 ; N_2: 2139

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.80375144]  P Value: [0.42161605]
Mean1: [-0.05232963]  Mean2: [-0.04967335]  Diff: [-0.00265628]
N_1: 1560 ; N_2: 999

### 150 CAR 7

In [100]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [101]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.79075633]  P Value: [0.429131]
Mean1: [-0.10202873]  Mean2: [-0.09868817]  Diff: [-0.00334056]
N_1: 2482 ; N_2: 2139

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.18792442]  P Value: [0.2349784]
Mean1: [-0.10199678]  Mean2: [-0.09735362]  Diff: [-0.00464316]
N_1: 1560 ; N_2: 999

### 150 CAR 11

In [102]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [103]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.30398803]  P Value: [0.1923198]
Mean1: [-0.19895627]  Mean2: [-0.19115636]  Diff: [-0.00779991]
N_1: 2479 ; N_2: 2138

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.39418765]  P Value: [0.69347575]
Mean1: [-0.1995322]  Mean2: [-0.19741198]  Diff: [-0.00212021]
N_1: 1558 ; N_2: 999

## 180 Days

### 180 CAR 3

In [104]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [105]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.13043017]  P Value: [0.25841797]
Mean1: [-0.00221467]  Mean2: [-0.01399252]  Diff: [0.01177785]
N_1: 2471 ; N_2: 2100

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.29104032]  P Value: [0.77106885]
Mean1: [-0.00296586]  Mean2: [-0.00483377]  Diff: [0.00186791]
N_1: 1557 ; N_2: 990

### 180 CAR 5

In [106]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [107]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.11582598]  P Value: [0.26461689]
Mean1: [-0.05208519]  Mean2: [-0.0649905]  Diff: [0.01290531]
N_1: 2471 ; N_2: 2100

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.32261768]  P Value: [0.74702239]
Mean1: [-0.0511017]  Mean2: [-0.05277537]  Diff: [0.00167367]
N_1: 1557 ; N_2: 990

### 180 CAR 7

In [108]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [109]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.81569856]  P Value: [0.4147525]
Mean1: [-0.10204434]  Mean2: [-0.10956526]  Diff: [0.00752093]
N_1: 2471 ; N_2: 2100

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.10166295]  P Value: [0.91903809]
Mean1: [-0.10145089]  Mean2: [-0.10212568]  Diff: [0.00067479]
N_1: 1557 ; N_2: 990

### 180 CAR 11

In [110]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [111]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.15671815]  P Value: [0.87547921]
Mean1: [-0.19904021]  Mean2: [-0.20054691]  Diff: [0.00150671]
N_1: 2468 ; N_2: 2099

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.6098117]  P Value: [0.54208527]
Mean1: [-0.19955093]  Mean2: [-0.20527409]  Diff: [0.00572315]
N_1: 1555 ; N_2: 990

## Family Firms: IsFamilyManager == 1 and Non Govt. Firms

In [112]:
nonGovFirm = car.loc[ (car["Ownership group code"] >= 20000000000), :].copy()

In [113]:
car

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64,0.000000,3.687671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1,0,{},{22209},{22209},{22209},{22},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,3,0,0,0,0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,4.263014,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,5.679452,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaT,U,1997-03-29,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3289.0,0.0,0.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,9.010959,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,2.010101e+10,Bajaj Group,Before 1950,BAJAJHLDNG,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaT,U,2004-01-17,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,804.0,0.0,0.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,2.202740,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912,2.010103e+10,Graphite India Group,Between 1972 and 1985,GRAPHITE,"31, Chowringhee Road, Kolkata West Bengal","{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259413,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,2027-03-31,N,1997-08-01,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46,0.000000,26.682192,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Lifesciences Ltd.,41246.0,Public Ltd.,1.020302e+10,1995.0,Drugs & pharmaceuticals,1.010120e+14,Manufacture of allopathic pharmaceutical prepa...,21002,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSLIFE,"'Saffron', 2nd Floor, Ambawadi, Ahmedabad Guj...","{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259414,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,0,46,0.000000,14.936986,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
259415,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.000000,8.887671,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0,0,{10409},{10409},{10409},{10409},{10},0,0,0,1,1,0,1,0,{},{},"{leadership/management, finance, marketing, op...",0,1,{ZYDUSWELL},5,1,1,0,1,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

In [114]:
familyManaged = car.loc[ car["IsFamilyManager"] == 1, ["Symbol", "Company", "AsOnDate"]].drop_duplicates()
familyManaged

            Symbol                          Company   AsOnDate
73117    20MICRONS                  20 MICRONS LTD. 2013-03-31
73141      3MINDIA                    3M INDIA LTD. 2013-03-31
73147       3PLAND            3P LAND HOLDINGS LTD. 2013-03-31
73151      SOMATEX  SOMA TEXTILES & INDUSTRIES LTD. 2013-03-31
73166      63MOONS       63 MOONS TECHNOLOGIES LTD. 2013-03-31
...            ...                              ...        ...
259378  ZODIACLOTH          ZODIAC CLOTHING CO.LTD. 2024-03-31
259385      ZODIAC               ZODIAC ENERGY LTD. 2024-03-31
259401        ZOTA            ZOTA HEALTH CARE LTD. 2024-03-31
259413   ZYDUSLIFE          ZYDUS LIFESCIENCES LTD. 2024-03-31
259414   ZYDUSWELL              ZYDUS WELLNESS LTD. 2024-03-31

[12519 rows x 3 columns]

In [115]:
car3 = familyManaged.merge(nonGovFirm, on = ["Symbol", "Company", "AsOnDate"], how = "left").reset_index(drop = True)
car3

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259.0,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3.0,0.0,0.0,3.0,2.0,0.0,0.0,2.0,0.0,3.0,0.0,3.0,1.0,3.0,0.0,4.0,N,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,74,1.000000,5.468493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1.0,0.0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",1.0,1.0,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15.0,3.0,3.0,0.0,1.0,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,0.000000,1.923288,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,{20MICRONS},0.0,1.0,1.0,0.0,1.0,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.002290,0.182078,0.160925,3.311803e-05,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.001840,0.177502,0.160602,2.684035e-06,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,1.552181e-06,0.146649,0.058915,0.007006,-0.113460
2,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,47,0.000000,12.175342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, MANAGING DIRECTOR, EXECUTIVE DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,N,1988-03-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,9127.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79,0.000000,25.021918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",POST GRADUATE: M.SC.-CHEMISTRY nan nan nan nan...,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,1.0,1.0,0.503581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027666,MR.,RAJESH,CHANDRESH,PARIKH,1971-12-28,M,INDIA,NaN,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,GRADUATE: B.E.-MECHANICAL,POST GRADUATE: M.B.A.-FINANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.RAJESH C. PARIKH, (DIRECTOR) HAS GRADUATED ...",NaT,N,1998-07-02,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5382.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.000000,14.756164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",GRADUATE: B.E.-MECHANICAL POST GRADUATE: M.B.A...,1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107709,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00022618,MR.,GANESH,NARAYAN,NAYAK,1955-05-18,M,INDIA,NONE,NO,"NOMINEE DIRECTOR OF CADILA HEALTHCARE LTD., NO...",NO,"GRADUATE: B.SC.,UNIVERSITY OF MYSORE,MYSURU","POST GRADUATE: M.B.A.,NEWPORT UNIVERSITY,CALIF...","POST GRADUATE: P.G.-GENERAL MANAGEMENT,HARVARD...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,HEALTHCARE,LEADERSH...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. GANESH NAYAK, THE EXECUTIVE DIRECTOR OF ZY...",NaT,N,2006-07-27,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,2074.0,0.0,4018.0,6092.0,2074.0,0.0,4383.0,6457.0,2074.0,0.0,4018.0,6092.0,2074.0,0.0,4383.0,6457.0,6452.0,"((ZYDUSWELL, U), (ZYDUSLIFE, N), (ZYDUSWELL, N))","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSWELL, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,2.0,3.0,N,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,69,0.000000,17.690411,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, healthcare, marketing,...","GRADUATE: B.SC.,UNIVERSITY OF MYSORE,MYSURU PO...",1.0,0.0,"{10409, 21002}","{10409, 21002}","{10409, 21002}","{10409, 21002}","{21, 10}",0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,{healthcare},{},"{leadership/management, healthcare, marketing,...",0.0,0.0,"{ZYDUSLIFE, ZYDUSWELL}",5.0,2.0,2.0,0.0,1.0,0.142308,42684.0,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023966,-0.000438,-0.001534,-0.000275,0.017751,-0.007652,5.546472e-01,0.025529,-0.039495,-0.111142,-0.180133,-0.023648,-0.000479,-0.001826,0.000462,0.026400,0.006395,2.702863e-01,0.025770,-0.038398,-0.111312,-0.181065,-0.023591,-0.000528,-0.002276,-0.000210,0.029542,0.013000,1.515805e-01,0.026477,-0.037134,-0.110531,-0.180143
107710,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732.0,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2.0,1.0,0.0,3.0,1.0,1.0,0.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,2.0,3.0,N,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,46,0.000000,14.936986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0.0,1.0,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",0.0,0.0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7.0,3.0,3.0,1.0,1.0,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
107711,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024.0,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242.0,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.000000,8.887671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0.0,0.0,{10409},{10409},{10409},{10409},{10},0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,{},{},"{leadership/management, finance, marketing, op...",0.0,1.0,{ZYDUSWELL},5.0,1.0,1.0,0.0,1.0,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

# 2013 - 2020

In [116]:
carS1 = car3.loc[ (car3["AsOnDate"] <= "2020-03-31") & (car3["AsOnDate"] >= "2013-03-31"), : ].copy()
carS1 = carS1.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)

## 120 Days

### 120 CAR 3

In [117]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [118]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.09496444]  P Value: [0.92434748]
Mean1: [-0.00086284]  Mean2: [-0.00114391]  Diff: [0.00028107]
N_1: 2549 ; N_2: 2269

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.3081144]  P Value: [0.19097878]
Mean1: [-0.00338478]  Mean2: [0.00029492]  Diff: [-0.0036797]
N_1: 1741 ; N_2: 1055

### 120 CAR 5

In [119]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [120]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.7318871]  P Value: [0.08336856]
Mean1: [-0.05932164]  Mean2: [-0.05323513]  Diff: [-0.00608651]
N_1: 2549 ; N_2: 2269

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-3.34744786]  P Value: [0.00082907]
Mean1: [-0.06027119]  Mean2: [-0.04938281]  Diff: [-0.01088838]
N_1: 1741 ; N_2: 1055

### 120 CAR 7

In [121]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [122]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.76598025]  P Value: [0.00570231]
Mean1: [-0.11686384]  Mean2: [-0.10512026]  Diff: [-0.01174359]
N_1: 2549 ; N_2: 2269

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.2982593]  P Value: [1.79604772e-05]
Mean1: [-0.11604276]  Mean2: [-0.09859122]  Diff: [-0.01745154]
N_1: 1741 ; N_2: 1055

### 120 CAR 11

In [123]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [124]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-4.37436043]  P Value: [1.24767137e-05]
Mean1: [-0.23006052]  Mean2: [-0.20765206]  Diff: [-0.02240847]
N_1: 2549 ; N_2: 2269

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.27885361]  P Value: [1.41355682e-07]
Mean1: [-0.23072517]  Mean2: [-0.20131449]  Diff: [-0.02941067]
N_1: 1741 ; N_2: 1055

## 150 Days

### 150 CAR 3

In [125]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [126]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.2895626]  P Value: [0.7721639]
Mean1: [-0.00149383]  Mean2: [-0.00069725]  Diff: [-0.00079658]
N_1: 2540 ; N_2: 2227

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.19432217]  P Value: [0.0283124]
Mean1: [-0.00415305]  Mean2: [0.00158329]  Diff: [-0.00573633]
N_1: 1727 ; N_2: 1036

### 150 CAR 5

In [127]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [128]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-2.35694213]  P Value: [0.01846785]
Mean1: [-0.06015483]  Mean2: [-0.05256575]  Diff: [-0.00758908]
N_1: 2540 ; N_2: 2227

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.16322411]  P Value: [3.25789227e-05]
Mean1: [-0.06109214]  Mean2: [-0.04761318]  Diff: [-0.01347897]
N_1: 1727 ; N_2: 1036

### 150 CAR 7

In [129]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [130]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-3.28555585]  P Value: [0.00102576]
Mean1: [-0.1181375]  Mean2: [-0.10467702]  Diff: [-0.01346048]
N_1: 2540 ; N_2: 2227

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.87472551]  P Value: [1.17185838e-06]
Mean1: [-0.11695814]  Mean2: [-0.09652774]  Diff: [-0.0204304]
N_1: 1727 ; N_2: 1036

### 150 CAR 11

In [131]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [132]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-5.19144197]  P Value: [2.17723747e-07]
Mean1: [-0.23035094]  Mean2: [-0.20639065]  Diff: [-0.02396028]
N_1: 2540 ; N_2: 2227

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.37358549]  P Value: [8.68004192e-08]
Mean1: [-0.23125348]  Mean2: [-0.19678069]  Diff: [-0.03447279]
N_1: 1727 ; N_2: 1036

## 180 Days

### 180 CAR 3

In [133]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [134]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.19982962]  P Value: [0.23032833]
Mean1: [-0.0012966]  Mean2: [-0.01335465]  Diff: [0.01205805]
N_1: 2533 ; N_2: 2183

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.77735373]  P Value: [0.00552161]
Mean1: [-0.00473042]  Mean2: [0.00252813]  Diff: [-0.00725855]
N_1: 1719 ; N_2: 1021

### 180 CAR 5

In [135]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [136]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.61469342]  P Value: [0.53881717]
Mean1: [-0.0599818]  Mean2: [-0.06683114]  Diff: [0.00684934]
N_1: 2533 ; N_2: 2183

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-4.53493904]  P Value: [6.05253521e-06]
Mean1: [-0.06180654]  Mean2: [-0.0471368]  Diff: [-0.01466974]
N_1: 1719 ; N_2: 1021

### 180 CAR 7

In [137]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [138]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.3292599]  P Value: [0.7419864]
Mean1: [-0.11779057]  Mean2: [-0.11486752]  Diff: [-0.00292304]
N_1: 2533 ; N_2: 2183

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.23933309]  P Value: [1.76111057e-07]
Mean1: [-0.11809352]  Mean2: [-0.09632596]  Diff: [-0.02176756]
N_1: 1719 ; N_2: 1021

### 180 CAR 11

In [139]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [140]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.72192686]  P Value: [0.0851949]
Mean1: [-0.22998759]  Mean2: [-0.21528813]  Diff: [-0.01469946]
N_1: 2533 ; N_2: 2183

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-5.71574006]  P Value: [1.25793768e-08]
Mean1: [-0.23191969]  Mean2: [-0.19799047]  Diff: [-0.03392921]
N_1: 1719 ; N_2: 1021

# 2013 - 2024

In [141]:
carS2 = car3.loc[ (car3["AsOnDate"] <= "2024-03-31") & (car3["AsOnDate"] >= "2013-03-31"), : ].copy()
carS2 = carS2.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)
carS2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259.0,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3.0,0.0,0.0,3.0,2.0,0.0,0.0,2.0,0.0,3.0,0.0,3.0,1.0,3.0,0.0,4.0,N,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,74,1.0,5.468493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1.0,0.0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",1.0,1.0,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15.0,3.0,3.0,0.0,1.0,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,0.0,1.923288,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,{20MICRONS},0.0,1.0,1.0,0.0,1.0,-0.760543,11.0,20.48,-0.016330,0.019851,-0.595940,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.002290,0.182078,0.160925,0.000033,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.001840,0.177502,0.160602,0.000003,0.161651,0.072536,0.025170,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,0.000002,0.146649,0.058915,0.007006,-0.113460
2,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,47,0.0,12.175342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, MANAGING DIRECTOR, EXECUTIVE DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,N,1988-03-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,9127.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79,0.0,25.021918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",POST GRADUATE: M.SC.-CHEMISTRY nan nan nan nan...,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,1.0,1.0,0.503581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027666,MR.,RAJESH,CHANDRESH,PARIKH,1971-12-28,M,INDIA,NaN,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,GRADUATE: B.E.-MECHANICAL,POST GRADUATE: M.B.A.-FINANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.RAJESH C. PARIKH, (DIRECTOR) HAS GRADUATED ...",NaT,N,1998-07-02,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5382.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.0,14.756164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",GRADUATE: B.E.-MECHANICAL POST GRADUATE: M.B.A...,1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25280,ZENTEC,ZEN TECHNOLOGIES LTD.,2024-03-31,2024.0,INE251B01027,P00116093,MR.,SANJAY,VIJAY SINGH,JESRANI,1965-05-25,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.COM.,POST GRADUATE: C.F.A.(CHARTERED FINANCIAL ANAL...,"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZEN TECHNOLOGIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. SANJAY VIJAY SINGH JESRANI HOLDS A BACHELO...,2027-01-26,Y,2024-01-27,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,64.0,0.0,0.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,64.0,0.0,0.0,64.0,365.0,(),"{(ZENTEC, Y)}","{(ZENTEC, Y), (ZENTEC, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,59,0.0,0.175342,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zen Technologies Ltd.,275155.0,Public Ltd.,1.020302e+10,1993.0,"Computers, peripherals & storage devices",1.010140e+14,"Manufacture of desktop computers, laptop compu...",26201,2.010104e+10,Zen Technologies Group,Between 1991 and 2013,ZENTEC,NaN,{},GRADUATE: B.COM. POST GRADUATE: C.F.A.(CHARTER...,0.0,0.0,{},{26201},{26201},{26201},{26},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,<NA>,0.0,0.0,0.0,0.0,1.0,-1.315932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25281,ZODIAC,ZODIAC ENERGY LTD.,2024-03-31,2024.0,INE761Y01019,P00082169,MR.,JAIMIN,JAGDISH,SHAH,1973-04-25,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.E.-COMPUTER SCIENCE,DHARMSINH DESA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,DIVERSITY,FINANCE,INDUSTR...","CO-FOUNDER & MANAGING DIRECTOR, DEV INFORMATIO...",nan,DEV INFORMATION TECHNOLOGY LTD.,ZODIAC ENERGY LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. JAIMIN SHAH HAS MORE THAN 25 YEARS OF EXPE...,2028-09-07,Y,2023-09-08,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,205.0,0.0,0.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,205.0,0.0,0.0,205.0,9588.0,"((DEVIT, N),)","{(ZODIAC, Y), (DEVIT, N)}","{(ZODIAC, Y), (DEVIT, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0,2.0,N,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,51,0.0,0.561644,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zodiac Energy Ltd.,275567.0,Public Ltd.,1.020302e+10,1992.0,Industrial construction,1.010602e+14,Construction and maintenance of power plants,42201,2.010200e+10,Private (Indian),Between 1991 and 2013,ZODIAC,"U G F 4-5-6, Milestone Building, Near Khodiyar...","{leadership/management, diversity, research & ...","GRADUATE: B.E.-COMPUTER SCIENCE,DHARMSINH DESA...",0.0,0.0,{62013},"{42201, 62013}","{42201, 62013}","{42201, 62013}","{42, 62}",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{information technology},"{leadership/management, diversity, research & ...",1.0,1.0,{DEVIT},12.0,1.0,1.0,0.0,0.0,-0.623486,275567.0,126.90,-0.001574,0.018014,0.422633,0.440646,-0.289091,0.388448,-0.027673,0.009355,0.013963,-0.000751,0.083652,0.059953,0.017121,0.050536,0.072523,-0.003342,-0.134505,-0.027514,0.011262,0.011705,0.001796,0.106280,0.087916,0.000912,0.042471,0.070028,-0.011012,-0.155503,-0.027063,0.008801,0.010281,0.001935,0.105275,0.090024,0.000202,0.043852,0.064780,-0.013468,-0.152510
25282,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00114239,MR.,DHAVAL,CHANDU,PATWA,1990-05-13,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",GRADUATE: DIPLOMA-INFORMATION SYSTEMS AUDIT,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,DIVERSITY,FINANCE,INTE...",nan,nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. DHAVAL CHANDUBHAI PATWA IS FELLOW MEMBER O...,2028-08-25,Y,2023-08-26,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,218.0,0.0,0.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,365.0,(),"{(ZOTA, Y)}","{(ZOTA, U), (ZOTA, Y)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34,0.0,0.597260,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, accounts/a...","GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",0.0,0.0,{},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, diversity, accounts/a...",0.0,1.0,<NA>,5.0,0.0,0.0,0.0,0.0,-1.665321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25283,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00114238,MR.,LAXMI,KANT,SHARMA,1975-10-15,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,"GRADUATE: B.SC.-BIOLOGY,RAJASTHAN UNIVERSITY,J...","GRADUATE: DIPLOMA-PHARMACY,BOARD OF TECHNICAL ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,LEGAL/COMPLIANCE,...","EXECUTIVE DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. LAXMI KANT SHARMA HOLDS BACHELOR’S DEGREE ...,2028-08-25,N,2023-08-26,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,218.0,0.0,0.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,365.0,(),"{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,49,0.0,0.597260,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{diversity, healthcare, legal/compliance, fina...","GRADUATE: B.SC.-BIOLOGY,RAJASTHAN UNIVERSITY,J...",0.0,0.0,{},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{diversity, healthcare, legal/compliance, fina...",0.0,1.0,<NA>,5.0,0.0,0.0,0.0,0.0,-1.665321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 120 Days

### 120 CAR 3

In [142]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [143]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.50089474]  P Value: [0.61646739]
Mean1: [-0.0023082]  Mean2: [-0.0009277]  Diff: [-0.0013805]
N_1: 4065 ; N_2: 3174

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.34639946]  P Value: [0.17825294]
Mean1: [-0.00394875]  Mean2: [-0.00075568]  Diff: [-0.00319307]
N_1: 2685 ; N_2: 1613

### 120 CAR 5

In [144]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [145]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.5320226]  P Value: [0.5947336]
Mean1: [-0.05277393]  Mean2: [-0.05110922]  Diff: [-0.0016647]
N_1: 4063 ; N_2: 3174

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.03299538]  P Value: [0.04211704]
Mean1: [-0.05389826]  Mean2: [-0.0483825]  Diff: [-0.00551575]
N_1: 2685 ; N_2: 1613

### 120 CAR 7

In [146]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [147]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.22413394]  P Value: [0.82266193]
Mean1: [-0.10240803]  Mean2: [-0.10161102]  Diff: [-0.00079701]
N_1: 4062 ; N_2: 3174

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.21166003]  P Value: [0.0270452]
Mean1: [-0.10318386]  Mean2: [-0.09568114]  Diff: [-0.00750272]
N_1: 2684 ; N_2: 1613

### 120 CAR 11

In [148]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [149]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.05229165]  P Value: [0.29271521]
Mean1: [-0.20116101]  Mean2: [-0.19607186]  Diff: [-0.00508915]
N_1: 4058 ; N_2: 3172

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.27446649]  P Value: [0.78374478]
Mean1: [-0.19110888]  Mean2: [-0.19439391]  Diff: [0.00328503]
N_1: 2680 ; N_2: 1613

## 150 Days

### 150 CAR 3

In [150]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [151]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.63701205]  P Value: [0.52414098]
Mean1: [-0.00261328]  Mean2: [-0.00118796]  Diff: [-0.00142532]
N_1: 4047 ; N_2: 3129

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.11172632]  P Value: [0.03477185]
Mean1: [-0.00401983]  Mean2: [0.00055522]  Diff: [-0.00457505]
N_1: 2669 ; N_2: 1593

### 150 CAR 5

In [152]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [153]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.87708325]  P Value: [0.38047578]
Mean1: [-0.05325982]  Mean2: [-0.05094042]  Diff: [-0.00231939]
N_1: 4045 ; N_2: 3129

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.71564629]  P Value: [0.00664284]
Mean1: [-0.05404258]  Mean2: [-0.04687255]  Diff: [-0.00717004]
N_1: 2669 ; N_2: 1593

### 150 CAR 7

In [154]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [155]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.63969721]  P Value: [0.52239392]
Mean1: [-0.10324745]  Mean2: [-0.10114509]  Diff: [-0.00210236]
N_1: 4044 ; N_2: 3129

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-2.67726889]  P Value: [0.00745375]
Mean1: [-0.10312549]  Mean2: [-0.09411365]  Diff: [-0.00901184]
N_1: 2668 ; N_2: 1593

### 150 CAR 11

In [156]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [157]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.46494325]  P Value: [0.14299356]
Mean1: [-0.20138963]  Mean2: [-0.19483537]  Diff: [-0.00655426]
N_1: 4040 ; N_2: 3127

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.07620223]  P Value: [0.93926297]
Mean1: [-0.19023099]  Mean2: [-0.19115777]  Diff: [0.00092678]
N_1: 2664 ; N_2: 1593

## 180 Days

### 180 CAR 3

In [158]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [159]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.0797196]  P Value: [0.28034656]
Mean1: [-0.00253762]  Mean2: [-0.01031262]  Diff: [0.00777501]
N_1: 4028 ; N_2: 3075

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.39947302]  P Value: [0.68958505]
Mean1: [-0.00417437]  Mean2: [-0.0024907]  Diff: [-0.00168366]
N_1: 2661 ; N_2: 1577

### 180 CAR 5

In [160]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [161]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.9536617]  P Value: [0.34032451]
Mean1: [-0.05343211]  Mean2: [-0.06106401]  Diff: [0.0076319]
N_1: 4026 ; N_2: 3075

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.26504709]  P Value: [0.20595061]
Mean1: [-0.05369915]  Mean2: [-0.04910456]  Diff: [-0.00459459]
N_1: 2661 ; N_2: 1577

### 180 CAR 7

In [162]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [163]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.76447253]  P Value: [0.44463533]
Mean1: [-0.10333764]  Mean2: [-0.1082765]  Diff: [0.00493886]
N_1: 4025 ; N_2: 3075

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.23340612]  P Value: [0.21753245]
Mean1: [-0.10330245]  Mean2: [-0.09745208]  Diff: [-0.00585037]
N_1: 2660 ; N_2: 1577

### 180 CAR 11

In [164]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [165]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.05880569]  P Value: [0.95310988]
Mean1: [-0.20158161]  Mean2: [-0.20118266]  Diff: [-0.00039895]
N_1: 4021 ; N_2: 3073

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.47185247]  P Value: [0.63705908]
Mean1: [-0.19069461]  Mean2: [-0.19684794]  Diff: [0.00615333]
N_1: 2656 ; N_2: 1577

## Non Family Firms: IsFamilyManager != 1 AND IsFamilyChairmanAndCEO != 0 and Non Govt. Firms

In [166]:
nonGovFirm = car.loc[ (car["Ownership group code"] >= 20000000000), :].copy()

In [167]:
car

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64,0.000000,3.687671,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1,0,{},{22209},{22209},{22209},{22},0,0,0,0,0,0,0,0,{},{},"{leadership/management, accounts/audit/taxatio...",0,1,NaN,3,0,0,0,0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,4.263014,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,5.679452,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaT,U,1997-03-29,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,3289.0,0.0,0.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,2924.0,0.0,0.0,2924.0,3289.0,0.0,0.0,3289.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,9.010959,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300,2.010101e+10,Bajaj Group,Before 1950,BAJAJHLDNG,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaT,U,2004-01-17,NaT,NaT,2007-03-31,0,0.0,1.0,1.0,0.0,0.0,0.0,804.0,0.0,0.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,439.0,0.0,0.0,439.0,804.0,0.0,0.0,804.0,3287,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85,0.000000,2.202740,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912,2.010103e+10,Graphite India Group,Between 1972 and 1985,GRAPHITE,"31, Chowringhee Road, Kolkata West Bengal","{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1,0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1,0,0,0,0,0,0,0,{},{},"{international business, corporate social resp...",1,1,NaN,19,0,0,0,1,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259413,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,2027-03-31,N,1997-08-01,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,5356.0,0.0,4018.0,9374.0,5356.0,0.0,4383.0,9739.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46,0.000000,26.682192,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Lifesciences Ltd.,41246.0,Public Ltd.,1.020302e+10,1995.0,Drugs & pharmaceuticals,1.010120e+14,Manufacture of allopathic pharmaceutical prepa...,21002,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSLIFE,"'Saffron', 2nd Floor, Ambawadi, Ahmedabad Guj...","{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259414,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",GRADUATE: CERTIFICATE-LEADERSHIP,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"GRADUATE: GRADUATE-EXECUTIVE PROGRAMME,SINGULA...","DOCTORATE: PH.D.-BREAST CANCER,JOHNS HOPKINS U...",NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",nan,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,NaT,N,2009-04-27,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,1069.0,0.0,4018.0,5087.0,1069.0,0.0,4383.0,5452.0,9732,"((ZYDUSLIFE, U), (ZYDUSLIFE, N), (ZYDUSWELL, U...","{(ZYDUSWELL, N), (ZYDUSLIFE, N)}","{(ZYDUSWELL, N), (ZYDUSWELL, U), (ZYDUSLIFE, N)}","((ZYDUSLIFE, U), (ZYDUSWELL, U), (PRIVISCL, Y))","((ZYDUSLIFE, U), (PRIVISCL, Y))",2,1,0,3,1,1,0,2,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,0,46,0.000000,14.936986,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{research & development, leadership/management...","SCHOOLING: SECONDARY EDUCATION,ST.LAWRENCE SCH...",0,1,"{10409, 20119, 21002}","{10409, 21002}","{10409, 21002}","{10409, 20119, 21002}","{21, 10, 20}",0,0,0,0,0,0,0,0,{},{},"{research & development, leadership/management...",0,0,"{ZYDUSLIFE, PRIVISCL, ZYDUSWELL}",7,3,3,1,1,1.336391,42684.0,15.65,0.000000,0.027124,-0.703543,-0.676419,0.213648,0.770117,-0.023759,0.000632,0.002731,0.001452,0.042294,0.017526,1.692973e-01,0.024205,0.008954,-0.042891,-0.107529,-0.025435,0.000845,0.002749,0.003141,0.042196,0.022516,9.721458e-02,0.027172,0.010252,-0.042229,-0.105523,-0.027180,0.000543,0.001812,0.003073,0.021693,0.005017,2.757455e-01,0.032196,0.014148,-0.039161,-0.100043
259415,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,NaN,NO,EXECUTIVE DIRECTOR,NO,GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...","CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",nan,ZYDUS WELLNESS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. TARUN ARORA HAS BEEN LEADING THE COMPANY’S...,2030-05-06,N,2015-05-14,2024-03-31,2023-03-31,NaT,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,322.0,0.0,2557.0,2879.0,322.0,0.0,2922.0,3244.0,3242,"((ZYDUSWELL, N),)","{(ZYDUSWELL, N)}","{(ZYDUSWELL, U), (ZYDUSWELL, N)}",(),(),0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,2,N,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,53,0.000000,8.887671,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,ZYDUSWELL,NaN,"{leadership/management, finance, marketing, op...",GRADUATE: GRADUATE-ADVANCED MANAGEMENT PROGRAM...,0,0,{10409},{10409},{10409},{10409},{10},0,0,0,1,1,0,1,0,{},{},"{leadership/management, finance, marketing, op...",0,1,{ZYDUSWELL},5,1,1,0,1,-0.413082,42684.0,1000.35,0.007503,0.021015,0.397166,0.418180,0.269741,0.455472,-0.029040,0.011537,0.002071,-0.010285,0.053490,0.029012,9.351624e-02,0.010302,-0.070495,-0.151540,-0.260413,-0.030584,0.012329,0.003189,-0.009742,0.066177,0.046989,1.830959e-02,0.012588,-0.066750,-0.149672,-0.258131,-0.031597,0.009426,0.003665,-0.008127,0.042842,0.026526,5.197714e-02,0.019546,-0.059772,-0.141382,-0.246554

In [168]:
nonFamilyManaged = car.loc[ (car["IsFamilyManager"] == 0) & (car["IsFamilyChairmanAndCEO"] == 0), ["Symbol", "Company", "AsOnDate"]].drop_duplicates()
nonFamilyManaged

            Symbol                               Company   AsOnDate
0          3MINDIA                         3M INDIA LTD. 2006-03-31
2         ASHOKLEY                    ASHOK LEYLAND LTD. 2006-03-31
3       BAJAJHLDNG      BAJAJ HOLDINGS & INVESTMENT LTD. 2006-03-31
4         GRAPHITE                   GRAPHITE INDIA LTD. 2006-03-31
5        SEAMECLTD                           SEAMEC LTD. 2006-03-31
...            ...                                   ...        ...
259341  ZENITHDRUG                     ZENITH DRUGS LTD. 2024-03-31
259348  ZENITHEXPO                   ZENITH EXPORTS LTD. 2024-03-31
259354   ZENITHSTL  ZENITH STEEL PIPES & INDUSTRIES LTD. 2024-03-31
259367      ZIMLAB                 ZIM LABORATORIES LTD. 2024-03-31
259390        ZOTA                 ZOTA HEALTH CARE LTD. 2024-03-31

[28903 rows x 3 columns]

In [169]:
car4 = nonFamilyManaged.merge(nonGovFirm, on = ["Symbol", "Company", "AsOnDate"], how = "left").reset_index(drop = True)
car4

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,2006.0,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,NONE,NaN,nan,nan,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaT,U,2002-07-24,NaT,NaT,2007-03-31,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1346.0,0.0,0.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,981.0,0.0,0.0,981.0,1346.0,0.0,0.0,1346.0,1345.0,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,64,0.0,3.687671,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{leadership/management, accounts/audit/taxatio...",GRADUATE: B.COM. POST GRADUATE: M.B.A.-FINANCE...,1.0,0.0,{},{22209},{22209},{22209},{22},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{leadership/management, accounts/audit/taxatio...",0.0,1.0,NaN,3.0,0.0,0.0,0.0,0.0,-1.804305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,2006.0,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,3287.0,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,5.0,5.0,0.0,0.0,5.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,85,0.0,4.263014,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1.0,0.0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, corporate social resp...",1.0,1.0,NaN,19.0,0.0,0.0,0.0,1.0,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3MINDIA,3M INDIA LTD.,2006-03-31,2006.0,INE470A01017,P00033331,MR.,BALASUBRAMANIAM,SOMASKANDAN,IYER,1949-10-13,M,INDIA,NONE,NaN,nan,nan,GRADUATE: DIPLOMA-MANAGERIAL ACCOUNTING,"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF COMP...","POST GRADUATE: M.COM.,UNIVERSITY OF MUMBAI,MUMBAI","POST GRADUATE: M.L.,UNIVERSITY OF MUMBAI,MUMBAI","POST GRADUATE: MEMBER,ALL INDIA MANAGEMENT ASS...",NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. B.S. IYER, 62, IS A POST GRADUATE IN COMME...",NaT,U,2001-12-26,NaT,NaT,2007-03-31,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1556.0,0.0,0.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1191.0,0.0,0.0,1191.0,1556.0,0.0,0.0,1556.0,1555.0,(),"{(3MINDIA, U)}","{(3MINDIA, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,75,0.0,4.263014,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209,2.020200e+10,Private (Foreign),Between 1986 and 1990,3MINDIA,NaN,{},GRADUATE: DIPLOMA-MANAGERIAL ACCOUNTING POST G...,1.0,0.0,{},{22209},{22209},{22209},{22},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006.0,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,NONE,NaN,nan,nan,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaT,U,2000-07-27,NaT,NaT,2007-03-31,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2073.0,0.0,0.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,1708.0,0.0,0.0,1708.0,2073.0,0.0,0.0,2073.0,3287.0,(),"{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...","{(GRAPHITE, U), (SEAMECLTD, U), (BAJAJHLDNG, U...",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,5.0,5.0,0.0,0.0,5.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,85,0.0,5.679452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,"{international business, corporate social resp...","GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...",1.0,0.0,{},"{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{23912, 64300, 77, 29102, 22209}","{22, 29, 23, 77, 64}",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, corporate social resp...",1.0,1.0,NaN,19.0,0.0,0.0,0.0,1.0,0.004420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006.0,INE208A01029,P00011353,MR.,KRISHNASWAMY,RAJAGOPALACHARI,SOCHANNAM,1944-06-08,M,NaN,NaN,NaN,nan,nan,POST GRADUATE: M.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR S R KRISHNASWAMY, S, IS A POST-GRADUATE IN ...",NaT,U,2002-07-26,NaT,NaT,2007-03-31,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1344.0,0.0,0.0,979.0,0.0,0.0,979.0,1344.0,0.0,0.0,1344.0,979.0,0.0,0.0,979.0,1344.0,0.0,0.0,1344.0,1343.0,(),"{(ASHOKLEY, U), (UTTAMSTL, U)}","{(ASHOKLEY, U), (UTTAMSTL, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,2.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,80,0.0,3.682192,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,ASHOKLEY,NaN,{},POST GRADUATE: M.SC. nan nan nan nan nan nan n...,0.0,0.0,{},"{29102, 24105}","{29102, 24105}","{29102, 24105}","{24, 29}",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,-1.315932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237673,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00082464,MR.,HIMANSHU,MUKTILAL,ZOTA,1974-05-30,M,INDIA,NaN,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,"GRADUATE: B.C.A.,APTECH,SURAT","GRADUATE: DIPLOMA-PHARMACY,BOARD OF TECHNICAL ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,DIVERSITY,FINANCE,HEAL...","EXECUTIVE DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. HIMANSHU MUKTILAL ZOTA HAS BEEN AWARDED WI...,2030-03-31,N,2000-07-12,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,8657.0,"((ZOTA, N),)","{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,50,0.0,23.734247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","GRADUATE: B.C.A.,APTECH,SURAT GRADUATE: DIPLOM...",0.0,0.0,{46497},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, diversity, healthcare...",0.0,1.0,{ZOTA},8.0,1.0,1.0,0.0,0.0,-0.901455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237674,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00082463,MR.,KAMLESH,RAJNIKANT,ZOTA,1973-01-17,M,INDIA,NaN,YES,"NOMINEE DIRECTOR OF ZOTA HEALTHCARE NIG.LTD., ...",NO,"GRADUATE: BACHELORS-PHARMACY,GUJARAT UNIVERSIT...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,INTERNATIONAL BUS...","EXECUTIVE DIRECTOR, ZOTA HEALTH CARE LTD.",nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. KAMLESH RAJANIKANT ZOTA HAS DONE BACHELOR ...,2030-03-31,N,2000-07-12,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,8657.0,"((ZOTA, N),)","{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,52,0.0,23.734247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","GRADUATE: BACHELORS-PHARMACY,GUJARAT UNIVERSIT...",0.0,0.0,{46497},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{healthcare},{},"{international business, diversity, healthcare...",0.0,1.0,{ZOTA},7.0,1.0,1.0,0.0,0.0,-0.970947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237675,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00082462,MR.,KETANKUMAR,CHANDULAL,ZOTA,1966-10-07,M,INDIA,NaN,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"GRADUATE: DIPLOMA-PHARMACY,GUJARAT UNIVERSITY,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,INTERNATIONAL BUS...",nan,nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. KETANKUMAR CHANDULAL ZOTA (BORN 07-10- 196...,NaT,N,2000-07-12,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,8657.0,"((ZOTA, N),)","{(ZOTA, N)}","{(ZOTA, U), (ZOTA, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,58,0.0,23.734247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","GRADUATE: DIPLOMA-PHARMACY,GUJARAT UNIVERSITY,...",0.0,0.0,{46497},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, diversity, healthcare...",0.0,1.0,{ZOTA},7.0,1.0,1.0,0.0,0.0,-0.970947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237676,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00082465,MR.,MANUKANT,CHANDULAL,ZOTA,1951-04-17,M,INDIA,NaN,YES,"EXECUTIVE DIRECTOR, PROMOTER-DIRECTOR",NO,"POST GRADUATE: M.SC.-MATHEMATICS,SARDAR PATEL ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DIVERSITY,FINANCE,HEALTHCARE,INTERNATIONAL BUS...",nan,RETIRED/SUPERANNUATED/TERM EXPIRED,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. MANUKANT CHANDULAL ZOLA HAS DONE MASTERS O...,2025-03-31,N,2000-07-12,2024-03-31,2023-03-31,NaT,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,366.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,7202.0,0.0,1096.0,8298.0,7202.0,0.0,1461.0,8663.0,8657.0,"((ZOTA, N),)","{(ZOTA, N)}","{(ZOTA, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,73,0.0,23.734247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, healthcare...","POST GRADUATE: M.SC.-MATHEMATICS,SARDAR PATEL ...",0.0,0.0,{46497},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, diversity, healthcare...",0.0,1.0,{ZOTA},7.0,1.0,1.0,0.0,0.0,-0.970947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2013 - 2020

In [170]:
carS1 = car4.loc[ (car3["AsOnDate"] <= "2020-03-31") & (car4["AsOnDate"] >= "2013-03-31"), : ].copy()
carS1 = carS1.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)

## 120 Days

### 120 CAR 3

In [171]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [172]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.62494135]  P Value: [0.55593468]
Mean1: [0.03768134]  Mean2: [0.01766507]  Diff: [0.02001627]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.43088967]  P Value: [0.67574877]
Mean1: [-0.00129995]  Mean2: [-0.01350035]  Diff: [0.0122004]
N_1: 9 ; N_2: 11

### 120 CAR 5

In [173]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [174]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.65101975]  P Value: [0.53709707]
Mean1: [-0.04297264]  Mean2: [-0.0205492]  Diff: [-0.02242345]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.136416]  P Value: [0.27278062]
Mean1: [-0.05234664]  Mean2: [-0.08290507]  Diff: [0.03055843]
N_1: 9 ; N_2: 11

### 120 CAR 7

In [175]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [176]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.06146048]  P Value: [0.31565951]
Mean1: [-0.09825928]  Mean2: [-0.05993247]  Diff: [-0.03832681]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.6740316]  P Value: [0.1117075]
Mean1: [-0.10526074]  Mean2: [-0.15969975]  Diff: [0.054439]
N_1: 9 ; N_2: 11

### 120 CAR 11

In [177]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [178]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.50601617]  P Value: [0.15199441]
Mean1: [-0.20577219]  Mean2: [-0.14221203]  Diff: [-0.06356016]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.77591835]  P Value: [0.44788334]
Mean1: [-0.23160903]  Mean2: [-0.26112508]  Diff: [0.02951605]
N_1: 9 ; N_2: 11

## 150 Days

### 150 CAR 3

In [179]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [180]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.45449464]  P Value: [0.66572728]
Mean1: [0.03369452]  Mean2: [0.01961337]  Diff: [0.01408115]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.42581675]  P Value: [0.67926182]
Mean1: [-0.00288366]  Mean2: [-0.01495965]  Diff: [0.01207599]
N_1: 9 ; N_2: 11

### 150 CAR 5

In [181]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [182]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.82385734]  P Value: [0.43786566]
Mean1: [-0.04752278]  Mean2: [-0.01912464]  Diff: [-0.02839814]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.24899734]  P Value: [0.22967073]
Mean1: [-0.05328285]  Mean2: [-0.08706724]  Diff: [0.03378439]
N_1: 9 ; N_2: 11

### 150 CAR 7

In [183]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [184]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.21824986]  P Value: [0.25161131]
Mean1: [-0.1033227]  Mean2: [-0.05882342]  Diff: [-0.04449928]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.78201028]  P Value: [0.09184952]
Mean1: [-0.10702387]  Mean2: [-0.16549279]  Diff: [0.05846892]
N_1: 9 ; N_2: 11

### 150 CAR 11

In [185]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [186]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.60102259]  P Value: [0.12945537]
Mean1: [-0.21098673]  Mean2: [-0.14121003]  Diff: [-0.0697767]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.87356838]  P Value: [0.39386635]
Mean1: [-0.2326564]  Mean2: [-0.26665835]  Diff: [0.03400195]
N_1: 9 ; N_2: 11

## 180 Days

### 180 CAR 3

In [187]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [188]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.39248624]  P Value: [0.70836817]
Mean1: [0.03283831]  Mean2: [0.02081846]  Diff: [0.01201986]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.32938554]  P Value: [0.74842125]
Mean1: [-0.0059296]  Mean2: [-0.01498238]  Diff: [0.00905278]
N_1: 9 ; N_2: 11

### 180 CAR 5

In [189]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [190]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.94974186]  P Value: [0.37370468]
Mean1: [-0.04952687]  Mean2: [-0.01777443]  Diff: [-0.03175243]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.00015146]  P Value: [0.33128338]
Mean1: [-0.05712074]  Mean2: [-0.08405632]  Diff: [0.02693557]
N_1: 9 ; N_2: 11

### 180 CAR 7

In [191]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [192]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.33331095]  P Value: [0.21110801]
Mean1: [-0.10501018]  Mean2: [-0.05768998]  Diff: [-0.0473202]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [1.38996201]  P Value: [0.18152282]
Mean1: [-0.11156312]  Mean2: [-0.15799657]  Diff: [0.04643345]
N_1: 9 ; N_2: 11

### 180 CAR 11

In [193]:
group1 = carS1.loc[ carS1["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS1.loc[ carS1["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS1.loc[ carS1["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS1.loc[ carS1["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [194]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.72038189]  P Value: [0.10334035]
Mean1: [-0.21405573]  Mean2: [-0.14107373]  Diff: [-0.072982]
N_1: 6 ; N_2: 19

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.57617618]  P Value: [0.57170023]
Mean1: [-0.23565055]  Mean2: [-0.25812937]  Diff: [0.02247882]
N_1: 9 ; N_2: 11

# 2013 - 2024

In [195]:
carS2 = car4.loc[ (car4["AsOnDate"] <= "2024-03-31") & (car4["AsOnDate"] >= "2013-03-31"), : ].copy()
carS2 = carS2.drop_duplicates( subset = ["Person Code", "Appointment Date"] ).reset_index(drop = True)
carS2

,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile,Tenure Valid till,Indep,Appointment Date,Cessation Date,PrevLastServed,NextServed,CessationDummy,ReappointDummy,TermStartDummy,TermNumber,CumOpBalUnc,CumOpBalIndep,CumOpBalNonIndep,CumCloBalUnc,CumCloBalIndep,CumCloBalNonIndep,TermOpBalUnc,TermOpBalIndep,TermOpBalNonIndep,TermOpBalTotal,TermCloBalUnc,TermCloBalIndep,TermCloBalNonIndep,TermCloBalTotal,CompOpBalUnc,CompOpBalIndep,CompOpBalNonIndep,CompOpBalTotal,CompCloBalUnc,CompCloBalIndep,CompCloBalNonIndep,CompCloBalTotal,CloBalTotalXP,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMDPosition,IsChairmanPosition,IsCeoMDOccupation,IsChairmanOccupation,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManager,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsinCompIndep,TenureInYearsinCompTotal,IsFirstTerm,IsFirstTermIndep,IsOneYear,IsOneYearIndep,IsTwoYear,IsTwoYearIndep,IsThreeYear,IsThreeYearIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,IsBusy,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,Prowess company code,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,NSE symbol,Head office address,Skills,EducationAll,IsMBA,IsPhD,AllPastDirectNIC,CurrDirectANIC,CurrDirectABNIC,AllNIC,AllNIC_Industry,HasFinanceXP,HasTechXP,HasRelatedIndustryXP,HasExecXP,PublicExecXPDummy,PrivateExecXPDummy,HasPublicExecXP,HasPrivateExecXP,SkillsInPositiononBoard,SkillsInOccupation,AllSkills,HasTechSkill,HasFinanceSkill,FirmsPast,NumSkills,NumFirmsPast,NumIndustryPast,HasCeoMDChairXP,HasConglomerateXP,General Ability Index,ProwessCode,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,1950-12-08,M,INDIA,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",nan,nan,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaT,Y,2007-10-13,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,365.0,0.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,1631.0,0.0,0.0,1631.0,1631.0,365.0,0.0,1996.0,4259.0,"((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y)}","{(20MICRONS, Y), (MUNJALAU, Y), (BANCOINDIA, Y...","((BANCOINDIA, U), (MUNJALAU, U), (20MICRONS, U))","((BANCOINDIA, U), (20MICRONS, U))",3.0,0.0,0.0,3.0,2.0,0.0,0.0,2.0,0.0,3.0,0.0,3.0,1.0,3.0,0.0,4.0,N,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,74,1.0,5.468493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, leadership/management...","POST GRADUATE: M.B.A. POST GRADUATE: M.COM.,MA...",1.0,0.0,"{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29209, 29301}","{08, 29}",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, leadership/management...",1.0,1.0,"{MUNJALAU, BANCOINDIA, 20MICRONS}",15.0,3.0,3.0,0.0,1.0,1.392619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00042601,MR.,NARESH,S.,MAKHIJA,NaT,M,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., EXECUTIVE ...",NO,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,N,2011-04-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,337.0,0.0,0.0,337.0,337.0,0.0,365.0,702.0,702.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,Y,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,0.0,1.923288,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...",{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,{20MICRONS},0.0,1.0,1.0,0.0,1.0,-0.760543,11.0,20.48,-0.01633,0.019851,-0.59594,-0.576089,-0.572908,-0.607305,-0.027582,0.010162,0.015819,-0.00229,0.182078,0.160925,0.000033,0.164278,0.074514,0.027817,-0.094913,-0.027218,0.010159,0.014966,-0.00184,0.177502,0.160602,0.000003,0.161651,0.072536,0.02517,-0.097096,-0.026257,0.008153,0.011899,0.003058,0.155157,0.140756,0.000002,0.146649,0.058915,0.007006,-0.11346
2,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00029006,MR.,ATIL,CHANDRESH,PARIKH,1977-09-04,M,INDIA,NaN,YES,"JT.MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROM...",NO,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaT,N,2001-01-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4079.0,0.0,0.0,4079.0,4079.0,0.0,365.0,4444.0,4441.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,47,0.0,12.175342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...","GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...",1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,1946-03-06,M,INDIA,NaN,YES,"CHAIRPERSON, MANAGING DIRECTOR, EXECUTIVE DIRE...",NO,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaT,N,1988-03-29,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,8768.0,0.0,0.0,8768.0,8768.0,0.0,365.0,9133.0,9127.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,79,0.0,25.021918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",POST GRADUATE: M.SC.-CHEMISTRY nan nan nan nan...,0.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,1.0,1.0,0.503581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,20 MICRONS LTD.,2013-03-31,2013.0,INE144J01027,P00027666,MR.,RAJESH,CHANDRESH,PARIKH,1971-12-28,M,INDIA,NaN,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,GRADUATE: B.E.-MECHANICAL,POST GRADUATE: M.B.A.-FINANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",nan,nan,20 MICRONS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR.RAJESH C. PARIKH, (DIRECTOR) HAS GRADUATED ...",NaT,N,1998-07-02,NaT,2012-03-31,2014-03-31,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,365.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5021.0,0.0,0.0,5021.0,5021.0,0.0,365.0,5386.0,5382.0,"((20MICRONS, U),)","{(20MICRONS, N)}","{(20MICRONS, U), (20MICRONS, N)}","((20MICRONS, U),)",(),1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,N,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,53,0.0,14.756164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,20 Microns Ltd.,11.0,Public Ltd.,1.020302e+10,1987.0,Minerals,1.010203e+14,Other mining and quarrying,08,2.010104e+10,20 Microns Group,Between 1986 and 1990,20MICRONS,"347, G I D C Industrial Estate, Waghodia, Vad...","{research & development, accounts/audit/taxati...",GRADUATE: B.E.-MECHANICAL POST GRADUATE: M.B.A...,1.0,0.0,{08},{08},{08},{08},{08},0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,{},{},"{research & development, accounts/audit/taxati...",1.0,1.0,{20MICRONS},11.0,1.0,1.0,0.0,1.0,0.003872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39280,ZENITHDRUG,ZENITH DRUGS LTD.,2024-03-31,2024.0,INE0QWN01013,P00123188,MR.,POONAM,CHAND,SHARMA,NaT,M,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,ZENITH DRUGS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT,U,2019-03-30,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1828.0,0.0,0.0,1463.0,0.0,0.0,1463.0,1828.0,0.0,0.0,1828.0,1463.0,0.0,0.0,1463.0,1828.0,0.0,0.0,1828.0,1826.0,(),"{(ZENITHDRUG, U)}","{(ZENITHDRUG, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,<NA>,0.0,5.008219,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Zenith Drugs Ltd.,275216.0,Public Ltd.,1.020302e+10,2000.0,Drugs & pharmaceuticals,1.010120e+14,"Manufacture of pharmaceuticals, medicinal chem...",2100,2.010200e+10,Private (Indian),Between 1991 and 2013,ZENITHDRUG,NaN,{},nan nan nan nan nan nan nan nan nan nan,0.0,0.0,{},{2100},{2100},{2100},{21},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39281,ZENITHDRUG,ZENITH DRUGS LTD.,2024-03-31,2024.0,INE0QWN01013,P00116777,MR.,BHUPESH,NaN,SONI,1978-10-05,M,INDIA,NaN,NaN,EXECUTIVE DIRECTOR,NO,"GRADUATE: BACHELORS-PHARMACY,SHRI GOVINDRAM SE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,"EXECUTIVE DIRECTOR, ZENITH DRUGS LTD.",nan,ZENITH DRUGS LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,"MR. BHUPESH SONI, AGED 44 YEARS, IS THE PROMOT...",NaT,N,2001-03-15,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,8417.0,0.0,0.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8417.0,0.0,0.0,8417.0,8411.0,(),"{(ZENITHDRUG, N)}","{(ZENITHDRUG, N)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,N,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,46,0.0,23.060274,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,Zenith Drugs Ltd.,275216.0,Public Ltd.,1.020302e+10,2000.0,Drugs & pharmaceuticals,1.010120e+14,"Manufacture of pharmaceuticals, medicinal chem...",2100,2.010200e+10,Private (Indian),Between 1991 and 2013,ZENITHDRUG,NaN,{},"GRADUATE: BACHELORS-PHARMACY,SHRI GOVINDRAM SE...",0.0,0.0,{},{2100},{2100},{2100},{21},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},{},0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,-2.012782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39282,ZENITHSTL,ZENITH STEEL PIPES & INDUSTRIES LTD.,2024-03-31,2024.0,INE318D01020,P00113631,MR.,GANESH,RAMESH,MAHENDRAKAR,1980-10-20,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.,UNIVERSITY OF MUMBAI,MUMBAI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,D...",nan,nan,ZENITH STEEL PIPES & INDUSTRIES LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. GANESH MAHENDRAKAR HOLDS B.COM FROM MUMBAI...,NaT,Y,2023-07-15,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,260.0,0.0,0.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,260.0,0.0,0.0,260.0,365.0,(),"{(ZENITHSTL, Y)}","{(ZENITHSTL, Y), (ZENITHSTL, U)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,44,0.0,0.712329,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zenith Steel Pipes & Inds. Ltd.,275251.0,Public Ltd.,1.020302e+10,1960.0,Steel pipes & tubes,1.010135e+14,"Manufacture of tubes, pipes and hollow profile...",24311,2.010101e+10,Birla Ashok Group,Between 1951 and 1971,ZENITHSTL,NaN,"{leadership/management, diversity, accounts/au...","GRADUATE: B.COM.,UNIVERSITY OF MUMBAI,MUMBAI n...",1.0,0.0,{},{24311},{24311},{24311},{24},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{leadership/management, diversity, accounts/au...",0.0,1.0,NaN,11.0,0.0,0.0,0.0,1.0,-0.551518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39283,ZOTA,ZOTA HEALTH CARE LTD.,2024-03-31,2024.0,INE358U01012,P00114239,MR.,DHAVAL,CHANDU,PATWA,1990-05-13,M,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",GRADUATE: DIPLOMA-INFORMATION SYSTEMS AUDIT,POST GRADUATE: C.A.(CHARTERED ACCOUNTANT),"POST GRADUATE: FELLOW-MEMBER,INSTITUTE OF CHAR...",NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,DIVERSITY,FINANCE,INTE...",nan,nan,ZOTA HEALTH CARE LTD.,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,MR. DHAVAL CHANDUBHAI PATWA IS FELLOW MEMBER O...,2028-08-25,Y,2023-08-26,2024-03-31,NaT,NaT,1.0,0.0,1.0,1.0,0.0,0.0,0.0,218.0,0.0,0.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,218.0,0.0,0.0,218.0,365.0,(),"{(ZOTA, Y)}","{(ZOTA, U), (ZOTA, Y)}",(),(),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,Y,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34,0.0,0.597260,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,Zota Health Care Ltd.,275663.0,Public Ltd.,1.020302e+10,2000.0,Wholesale trading,1.010404e+14,Wholesale of pharmaceutical and medical goods,46497,2.010200e+10,Private (Indian),Between 1991 and 2013,ZOTA,NaN,"{international business, diversity, accounts/a...","GRADUATE: B.COM.,VEER NARMAD SOUTH GUJARAT UNI...",0.0,0.0,{},{46497},{46497},{46497},{46},0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,{},{},"{international business, diversity, accounts/a...",0.0,1.0,NaN,5.0,0.0,0.0,0.0,0.0,-1.665321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 120 Days

### 120 CAR 3

In [196]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR3"]].dropna()

In [197]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.06390057]  P Value: [0.94905076]
Mean1: [-0.00315155]  Mean2: [-0.00300366]  Diff: [-0.00014789]
N_1: 6040 ; N_2: 4895

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.51909152]  P Value: [0.60371723]
Mean1: [-0.00301612]  Mean2: [-0.00199375]  Diff: [-0.00102237]
N_1: 5517 ; N_2: 2727

### 120 CAR 5

In [198]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR5"]].dropna()

In [199]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.27473155]  P Value: [0.7835281]
Mean1: [-0.05343186]  Mean2: [-0.05269736]  Diff: [-0.0007345]
N_1: 6038 ; N_2: 4893

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.9089888]  P Value: [0.3633919]
Mean1: [-0.05175182]  Mean2: [-0.04980257]  Diff: [-0.00194925]
N_1: 5516 ; N_2: 2726

### 120 CAR 7

In [200]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR7"]].dropna()

In [201]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.61940471]  P Value: [0.53566494]
Mean1: [-0.10340104]  Mean2: [-0.10153039]  Diff: [-0.00187065]
N_1: 6036 ; N_2: 4892

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.4484474]  P Value: [0.14754293]
Mean1: [-0.10106641]  Mean2: [-0.09724032]  Diff: [-0.00382609]
N_1: 5515 ; N_2: 2726

### 120 CAR 11

In [202]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["120CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["120CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["120CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["120CAR11"]].dropna()

In [203]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.34627289]  P Value: [0.17825079]
Mean1: [-0.2023047]  Mean2: [-0.19683773]  Diff: [-0.00546697]
N_1: 6029 ; N_2: 4889

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.18239716]  P Value: [0.85527593]
Mean1: [-0.19427838]  Mean2: [-0.19545768]  Diff: [0.0011793]
N_1: 5509 ; N_2: 2726

## 150 Days

### 150 CAR 3

In [204]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR3"]].dropna()

In [205]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.29544474]  P Value: [0.76766011]
Mean1: [-0.00327894]  Mean2: [-0.00270378]  Diff: [-0.00057515]
N_1: 6017 ; N_2: 4833

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.08336476]  P Value: [0.27869123]
Mean1: [-0.00271157]  Mean2: [-0.00080474]  Diff: [-0.00190683]
N_1: 5492 ; N_2: 2697

### 150 CAR 5

In [206]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR5"]].dropna()

In [207]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.43382287]  P Value: [0.66442588]
Mean1: [-0.05359167]  Mean2: [-0.05257203]  Diff: [-0.00101965]
N_1: 6015 ; N_2: 4831

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.34940895]  P Value: [0.1772559]
Mean1: [-0.05131281]  Mean2: [-0.04856493]  Diff: [-0.00274787]
N_1: 5491 ; N_2: 2696

### 150 CAR 7

In [208]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR7"]].dropna()

In [209]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.07444185]  P Value: [0.28265038]
Mean1: [-0.10390377]  Mean2: [-0.10092661]  Diff: [-0.00297716]
N_1: 6014 ; N_2: 4830

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.79786344]  P Value: [0.07224955]
Mean1: [-0.10049315]  Mean2: [-0.09589468]  Diff: [-0.00459847]
N_1: 5490 ; N_2: 2696

### 150 CAR 11

In [210]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["150CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["150CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["150CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["150CAR11"]].dropna()

In [211]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-1.94359968]  P Value: [0.0519747]
Mean1: [-0.20238646]  Mean2: [-0.19516269]  Diff: [-0.00722377]
N_1: 6007 ; N_2: 4827

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.04558532]  P Value: [0.96364195]
Mean1: [-0.19323254]  Mean2: [-0.19293489]  Diff: [-0.00029765]
N_1: 5484 ; N_2: 2696

## 180 Days

### 180 CAR 3

In [212]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR3"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR3"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR3"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR3"]].dropna()

In [213]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [1.11595432]  P Value: [0.26449062]
Mean1: [-0.00352638]  Mean2: [-0.00894027]  Diff: [0.0054139]
N_1: 5988 ; N_2: 4763

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.16984116]  P Value: [0.86514433]
Mean1: [-0.00285921]  Mean2: [-0.00239865]  Diff: [-0.00046056]
N_1: 5482 ; N_2: 2678

### 180 CAR 5

In [214]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR5"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR5"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR5"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR5"]].dropna()

In [215]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.86598524]  P Value: [0.38653395]
Mean1: [-0.05433957]  Mean2: [-0.0590546]  Diff: [0.00471503]
N_1: 5986 ; N_2: 4761

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-0.681957]  P Value: [0.49529757]
Mean1: [-0.05135678]  Mean2: [-0.0496716]  Diff: [-0.00168518]
N_1: 5481 ; N_2: 2677

### 180 CAR 7

In [216]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR7"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR7"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR7"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR7"]].dropna()

In [217]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [0.22576733]  P Value: [0.82138934]
Mean1: [-0.10460286]  Mean2: [-0.10563171]  Diff: [0.00102884]
N_1: 5985 ; N_2: 4760

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [-1.03500315]  P Value: [0.30072237]
Mean1: [-0.10075678]  Mean2: [-0.09745116]  Diff: [-0.00330562]
N_1: 5480 ; N_2: 2677

### 180 CAR 11

In [218]:
group1 = carS2.loc[ carS2["IsRookieIndep"] == 1, ["180CAR11"]].dropna()
group2 = carS2.loc[ carS2["IsNonRookieIndep"] == 1, ["180CAR11"]].dropna()

group3 = carS2.loc[ carS2["IsRookieNonIndep"] == 1, ["180CAR11"]].dropna()
group4 = carS2.loc[ carS2["IsNonRookieNonIndep"] == 1, ["180CAR11"]].dropna()

In [219]:
t_stat1, p_value1 = stats.ttest_ind(group1, group2, equal_var=False)  # Welch’s t-test (default)
t_stat2, p_value2 = stats.ttest_ind(group3, group4, equal_var=False)  # Welch’s t-test (default)


print("ROOKIE INDEP VS NON ROOKIE INDEP")
print("T Statistic:", t_stat1, " P Value:",p_value1)
print("Mean1:", group1.mean().values, " Mean2:", group2.mean().values, " Diff:", group1.mean().values - group2.mean().values)
print("N_1:", len(group1), "; N_2:", len(group2))
print()

print("ROOKIE NON INDEP VS NON ROOKIE NON INDEP")
print("T Statistic:", t_stat2, " P Value:",p_value2)
print("Mean1:", group3.mean().values, " Mean2:", group4.mean().values, " Diff:", group3.mean().values - group4.mean().values)
print("N_1:", len(group3), "; N_2:", len(group4))

ROOKIE INDEP VS NON ROOKIE INDEP
T Statistic: [-0.49921812]  P Value: [0.61764117]
Mean1: [-0.20350559]  Mean2: [-0.20094976]  Diff: [-0.00255582]
N_1: 5978 ; N_2: 4757

ROOKIE NON INDEP VS NON ROOKIE NON INDEP
T Statistic: [0.30953811]  P Value: [0.75692014]
Mean1: [-0.19372848]  Mean2: [-0.19591623]  Diff: [0.00218775]
N_1: 5474 ; N_2: 2677