In [1]:
import pandas as pd
df = pd.read_csv("Main_Director_Complete_Skillsets.csv")

/var/folders/cj/n529ywcn2tv783ff08sl87pm0000gn/T/ipykernel_18781/565912181.py:2: DtypeWarning: Columns (14,15,16,26,28,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,50,51,196) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Main_Director_Complete_Skillsets.csv")

In [69]:
import pandas as pd
df2 = pd.read_pickle("Main_Director_COMPLETE v170325.pkl")
df2['AllSkills']

0         {finance, accounts/audit/taxation, leadership/...
1         {legal/compliance, economics, international bu...
2         {legal/compliance, economics, international bu...
3         {legal/compliance, economics, international bu...
4         {legal/compliance, economics, international bu...
                                ...
259413    {leadership/management, corporate social respo...
259414    {leadership/management, corporate social respo...
259415    {marketing, leadership/management, operations,...
259416    {finance, corporate social responsibility, mar...
259417    {fast moving consumer goods, operations, marke...
Name: AllSkills, Length: 259418, dtype: object

In [70]:
df2['AllSkills'] = df2['AllSkills'].astype(str).str.lower()

skillset_keywords_map = { "sustainability": [
        "sustainability", "sustainable", "csr", "corporate social responsibility",
        "sustainability committee", "esg committee", "csr committee",
        "corporate social responsibility committee", "environment committee"
    ],
    "entrepreneurial": [
        "entrepreneur", "entrepreneurship", "startup", "founder", "co-founder",
        "innovation", "innovator", "venture", "investor"
    ],
    "compensation": [
        "compensation committee", "remuneration committee", "pay committee", "salary committee",
        "executive compensation", "incentive committee", "reward committee",
        "compensation and benefits", "compensation policy", "remuneration policy",
        "compensation", "salary", "remuneration", "pay", "bonus", "incentive",
        "performance bonus", "employee benefits", "wages", "rewards"
    ],
    "conglomerate_experience": [
        "conglomerate", "diversified group", "group company", "holding company",
        "multiple sectors", "business group", "corporate group", "inter-industry",
        "multi-industry", "parent-subsidiary structure", "group-wide strategy"
    ],
    "hr": [
        "human resources committee", "hr", "people management", "talent management",
        "organizational development", "performance management", "employee relations",
        "hr strategy", "compensation and benefits", "workforce planning",
        "succession planning", "human resource committee", "hr committee",
        "people committee", "talent committee", "organizational development committee",
        "compensation and benefits committee", "employee relations committee",
        "workforce planning committee", "succession planning committee",
        "diversities", "personal values"
    ],
    "technology": [
        "technology", "information technology", "it", "software engineering", "hardware", 
        "computer science", "tech", "digital transformation", "data science", "machine learning", 
        "ai", "artificial intelligence", "cybersecurity", "cloud computing", "systems architecture", 
        "technology strategy", "data analytics", "blockchain", "innovation", "info tech"
    ],
    "finance_accounting": [
        "finance", "financial", "accounting", "accounts", "chartered accountant", 
        "ca", "cfo", "chief financial officer", "auditor", "audit", "financial analysis", 
        "capital markets", "treasury", "banking", "investment", "equity", "debt", 
        "risk management", "taxation", "budgeting", "forecasting", "valuation", 
        "financial planning", "cost control", "internal controls", "compliance", 
        "financial reporting", "economics", "financial services", "commodities"
    ],
    "governance": [
        "governance", "corporate governance", "governance committee", "audit committee", 
        "risk committee", "ethics committee", "compliance committee", "board governance", 
        "regulatory affairs", "internal controls", "oversight", "governance and compliance", 
        "governance practices", "governance framework", "governance structure", 
        "governance responsibilities"
    ],
    "government_policy": [
        "government", "policy", "government affairs", "public policy", "government relations", 
        "legislative affairs", "policy making", "public sector", "regulations", 
        "government strategy", "public administration", "government services", 
        "policy development", "political affairs", "utilities"
    ],
    "international": [
        "international", "global", "international relations", "cross-border", "foreign affairs", 
        "multinational", "overseas", "global strategy", "global expansion", 
        "international business", "cross-cultural", "international markets", 
        "global trade", "global governance"
    ],
    "leadership": [
        "leadership", "executive leadership", "team leadership", "leadership development", 
        "strategic leadership", "leadership skills", "leadership team", 
        "senior leadership", "leadership strategy", "leadership responsibilities", 
        "visionary leadership", "leadership roles", "leadership training", 
        "leadership capabilities", "leadership and management", "senior management"
    ],
    "legal": [
        "legal", "legal affairs", "legal compliance", "legal counsel", "corporate legal", 
        "legal strategy", "legal advisor", "contract law", "intellectual property", 
        "regulatory compliance", "litigation", "legal framework", "lawsuit", 
        "legal governance", "legal risk", "compliance"
    ],
    "marketing": [
        "marketing", "marketing strategy", "digital marketing", "marketing campaign", 
        "marketing communications", "brand management", "customer engagement", 
        "marketing research", "social media marketing", "advertising", 
        "marketing manager", "market research", "content marketing", 
        "product marketing", "marketing analysis", "markets", 
        "fast moving consumer goods", "fmcg", "services", "consumer differentiation"
    ],
    "risk_management": [
        "risk management", "risk mitigation", "risk assessment", "risk committee", 
        "operational risk", "financial risk", "strategic risk", "compliance risk", 
        "risk control", "enterprise risk management", "risk governance", 
        "risk monitoring", "risk management strategy", "risk management framework", 
        "risk prevention"
    ],
    "scientific": [
        "scientific", "research and development", "r&d", "innovation", 
        "scientific research", "scientific committee", "technology research", 
        "science strategy", "scientific discovery", "scientific innovation", 
        "scientific analysis", "biotech", "scientific approach", "lab research", 
        "clinical research"
    ],
    "strategic_planning": [
        "strategic planning", "strategic development", "strategic initiatives", 
        "business strategy", "strategic goals", "long-term planning", 
        "corporate strategy", "strategic management", "strategic vision", 
        "strategic objectives", "strategy formulation", "strategic direction", 
        "strategic partnerships", "business planning", "strategic forecasting", 
        "strategy"
    ],
    "manufacturing_supply_chain": [
        "manufacturing", "production", "operations", "supply chain", "factory",
        "industrial", "plant", "manufacturing unit", "process engineering",
        "assembly line", "lean manufacturing", "six sigma", "quality control",
        "industrial engineering", "materials management", "shop floor",
        "production planning", "logistics", "automation", "mechanical engineering",
        "process optimization", "machinery", "manufacturing strategy",
        "supply chain management", "engineering operations",
        "operational management", "project management"
    ]
}


for col, keywords in skillset_keywords_map.items():
    if col in merged_df.columns and 'AllSkills' in df2.columns:
        merged_df[col] = merged_df[col].where(merged_df[col].notna(), 0).astype(int)

        match_mask = df2['AllSkills'].apply(
            lambda x: any(kw in str(x) for kw in keywords)
        ) & (df[col] == 0)

        merged_df.loc[match_mask, col] = 1

In [71]:
merged_df

,Unnamed: 0,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,...,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,Academic,Company Business,Outside Board
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,...,0,0,1,0,0,0,0,0,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259426,259426,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,1,1,0,0,1,1,0,1
259427,259427,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,0,1,0,0,0,1,0,1
259428,259428,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,...,1,0,1,0,1,1,1,0,0,0
259429,259429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00091934,MR.,ASHISH,NaN,...,0,0,0,0,0,0,1,0,0,1
259430,259430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00090966,MR.,SAVYASACHI,SANTOSH,...,0,0,0,0,0,0,0,0,0,0

In [48]:
import pandas as pd
df2 = pd.read_pickle("Main_Director_COMPLETE v170325.pkl")

In [49]:
import ast

def parse_nic_set(value):
    try:
        result = ast.literal_eval(value)
        return result if isinstance(result, set) else set()
    except:
        return set()

df2['AllPastDirectNIC'] = df2['AllPastDirectNIC'].apply(parse_nic_set)

df2['NIC code'] = df2['NIC code'].astype(str)
def check_same_industry(row):
    focal_nic = row['NIC code']
    past_nics = row['AllPastDirectNIC']
    
    filtered_past_nics = {str(nic) for nic in past_nics if str(nic) != focal_nic}

    past_prefixes = {nic[:2] for nic in filtered_past_nics}

    return 1 if focal_nic[:2] in past_prefixes else 0

df2['Company Business'] = df2.apply(check_same_industry, axis=1)

In [50]:
company_business_data = df2[['Person Code', 'Symbol', 'AsOnYear', 'Company Business']]
merged_df = merged_df.merge(company_business_data, on=['Person Code', 'Symbol', 'AsOnYear'], how='left')

In [45]:
import pandas as pd
committee_df = pd.read_excel(
    'Indian Boards Data as on 12-Feb-2025.xlsx',
    sheet_name='Committee Details',
    skiprows=1
)

keyword_categories = {
    "sustainability": [
        "sustainability", "sustainable", "csr", "corporate social responsibility",
        "sustainability committee", "esg committee", "csr committee",
        "corporate social responsibility committee", "environment committee"
    ],
    "entrepreneurial": [
        "entrepreneur", "entrepreneurship", "startup", "founder", "co-founder",
        "innovation", "innovator", "venture", "investor"
    ],
    "compensation": [
        "compensation committee", "remuneration committee", "pay committee", "salary committee",
        "executive compensation", "incentive committee", "reward committee",
        "compensation and benefits", "compensation policy", "remuneration policy",
        "compensation", "salary", "remuneration", "pay", "bonus", "incentive",
        "performance bonus", "employee benefits", "wages", "rewards"
    ],
    "conglomerate_experience": [
        "conglomerate", "diversified group", "group company", "holding company",
        "multiple sectors", "business group", "corporate group", "inter-industry",
        "multi-industry", "parent-subsidiary structure", "group-wide strategy"
    ],
    "hr": [
        "human resources committee", "hr", "people management", "talent management",
        "organizational development", "performance management", "employee relations",
        "hr strategy", "compensation and benefits", "workforce planning",
        "succession planning", "human resource committee", "hr committee",
        "people committee", "talent committee", "organizational development committee",
        "compensation and benefits committee", "employee relations committee",
        "workforce planning committee", "succession planning committee",
        "diversities", "personal values"
    ],
    "technology": [
        "technology", "information technology", "it", "software engineering", "hardware", 
        "computer science", "tech", "digital transformation", "data science", "machine learning", 
        "ai", "artificial intelligence", "cybersecurity", "cloud computing", "systems architecture", 
        "technology strategy", "data analytics", "blockchain", "innovation", "info tech"
    ],
    "finance_accounting": [
        "finance", "financial", "accounting", "accounts", "chartered accountant", 
        "ca", "cfo", "chief financial officer", "auditor", "audit", "financial analysis", 
        "capital markets", "treasury", "banking", "investment", "equity", "debt", 
        "risk management", "taxation", "budgeting", "forecasting", "valuation", 
        "financial planning", "cost control", "internal controls", "compliance", 
        "financial reporting", "economics", "financial services", "commodities"
    ],
    "governance": [
        "governance", "corporate governance", "governance committee", "audit committee", 
        "risk committee", "ethics committee", "compliance committee", "board governance", 
        "regulatory affairs", "internal controls", "oversight", "governance and compliance", 
        "governance practices", "governance framework", "governance structure", 
        "governance responsibilities"
    ],
    "government_policy": [
        "government", "policy", "government affairs", "public policy", "government relations", 
        "legislative affairs", "policy making", "public sector", "regulations", 
        "government strategy", "public administration", "government services", 
        "policy development", "political affairs", "utilities"
    ],
    "international": [
        "international", "global", "international relations", "cross-border", "foreign affairs", 
        "multinational", "overseas", "global strategy", "global expansion", 
        "international business", "cross-cultural", "international markets", 
        "global trade", "global governance"
    ],
    "leadership": [
        "leadership", "executive leadership", "team leadership", "leadership development", 
        "strategic leadership", "leadership skills", "leadership team", 
        "senior leadership", "leadership strategy", "leadership responsibilities", 
        "visionary leadership", "leadership roles", "leadership training", 
        "leadership capabilities", "leadership and management", "senior management"
    ],
    "legal": [
        "legal", "legal affairs", "legal compliance", "legal counsel", "corporate legal", 
        "legal strategy", "legal advisor", "contract law", "intellectual property", 
        "regulatory compliance", "litigation", "legal framework", "lawsuit", 
        "legal governance", "legal risk", "compliance"
    ],
    "marketing": [
        "marketing", "marketing strategy", "digital marketing", "marketing campaign", 
        "marketing communications", "brand management", "customer engagement", 
        "marketing research", "social media marketing", "advertising", 
        "marketing manager", "market research", "content marketing", 
        "product marketing", "marketing analysis", "markets", 
        "fast moving consumer goods", "fmcg", "services", "consumer differentiation"
    ],
    "risk_management": [
        "risk management", "risk mitigation", "risk assessment", "risk committee", 
        "operational risk", "financial risk", "strategic risk", "compliance risk", 
        "risk control", "enterprise risk management", "risk governance", 
        "risk monitoring", "risk management strategy", "risk management framework", 
        "risk prevention"
    ],
    "scientific": [
        "scientific", "research and development", "r&d", "innovation", 
        "scientific research", "scientific committee", "technology research", 
        "science strategy", "scientific discovery", "scientific innovation", 
        "scientific analysis", "biotech", "scientific approach", "lab research", 
        "clinical research"
    ],
    "strategic_planning": [
        "strategic planning", "strategic development", "strategic initiatives", 
        "business strategy", "strategic goals", "long-term planning", 
        "corporate strategy", "strategic management", "strategic vision", 
        "strategic objectives", "strategy formulation", "strategic direction", 
        "strategic partnerships", "business planning", "strategic forecasting", 
        "strategy"
    ],
    "manufacturing_supply_chain": [
        "manufacturing", "production", "operations", "supply chain", "factory",
        "industrial", "plant", "manufacturing unit", "process engineering",
        "assembly line", "lean manufacturing", "six sigma", "quality control",
        "industrial engineering", "materials management", "shop floor",
        "production planning", "logistics", "automation", "mechanical engineering",
        "process optimization", "machinery", "manufacturing strategy",
        "supply chain management", "engineering operations",
        "operational management", "project management"
    ]
}

keyword_categories = {
    category: [kw.lower() for kw in keywords]
    for category, keywords in keyword_categories.items()
}

for category, keywords in keyword_categories.items():
    col_name = f'committee_{category}'
    committee_df[col_name] = committee_df['Committee Name'].astype(str).str.lower().apply(
        lambda x: int(any(keyword in x for keyword in keywords))
    )

committee_flag_cols = [f'committee_{category}' for category in keyword_categories]

committee_flags = (
    committee_df[['Symbol', 'Person Code'] + committee_flag_cols]
    .groupby(['Symbol', 'Person Code'])
    .max()
    .reset_index()
)

for category, keywords in keyword_categories.items():
    col_name = f'profile_{category}'
    merged_df[col_name] = merged_df['Brief Profile'].astype(str).str.lower().apply(
        lambda x: int(any(keyword in x for keyword in keywords))
    )
merged_df = merged_df.merge(committee_flags, on=['Symbol', 'Person Code'], how='left')

for category in keyword_categories:
    committee_col = f'committee_{category}'
    profile_col = f'profile_{category}'
    combined_col = f'combined_{category}'

    merged_df[committee_col] = merged_df[committee_col].fillna(0).astype(int)
    merged_df[combined_col] = merged_df[[committee_col, profile_col]].max(axis=1)
    merged_df.drop(columns=[committee_col, profile_col], inplace=True)

In [46]:
merged_df

,Unnamed: 0,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,...,combined_governance,combined_government_policy,combined_international,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,...,0,0,0,0,0,1,0,0,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,0,0,0,1
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,0,0,0,1
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,0,0,0,1
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259426,259426,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,0,0,1,1,0,1,1,0,0,1
259427,259427,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,0,0,1,1,0,0,1,0,0,0
259428,259428,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,...,0,0,0,1,0,1,0,1,1,1
259429,259429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00091934,MR.,ASHISH,NaN,...,0,0,0,0,0,0,0,0,0,1
259430,259430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00090966,MR.,SAVYASACHI,SANTOSH,...,0,0,0,0,0,0,0,0,0,0

In [47]:
merged_df['Academic'] = merged_df['IsPhD']

In [51]:
merged_df['Outside Board'] = merged_df['CompCountOtherPastTotalAB'].apply(lambda x: 1 if x > 0 else 0)

In [ ]:
skillset_cols_to_update = [
    'Academic','combined_manufacturing_supply_chain','Outside Board',
    'combined_sustainability', 'combined_entrepreneurial', 'combined_compensation',
    'combined_governance', 'combined_government_policy', 'combined_international',
    'combined_leadership', 'combined_legal',
    'combined_marketing', 'combined_risk_management', 'combined_scientific',
    'combined_strategic_planning', 'combined_conglomerate_experience',
    'combined_hr', 'combined_technology', 'combined_finance_accounting','Company Business'
]
merged_df[skillset_cols_to_update] = merged_df[skillset_cols_to_update].fillna(0).astype(int)
merged_df[['HasFinanceXP', 'HasTechXP']] = merged_df[['HasFinanceXP', 'HasTechXP']].fillna(0).astype(int)
for col in skillset_cols_to_update:
    merged_df[col] = merged_df[col] | merged_df['HasFinanceXP'] | merged_df['HasTechXP']

In [61]:
merged_df

,Unnamed: 0,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,...,combined_leadership,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,Academic,Company Business,Outside Board
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,...,0,0,1,0,0,0,0,0,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,1,0,0,0
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,1,0,0,0
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,1,0,0,0
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259426,259426,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,1,1,0,0,1,1,0,1
259427,259427,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,0,1,0,0,0,1,0,1
259428,259428,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,...,1,0,1,0,1,1,1,0,0,0
259429,259429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00091934,MR.,ASHISH,NaN,...,0,0,0,0,0,0,1,0,0,1
259430,259430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00090966,MR.,SAVYASACHI,SANTOSH,...,0,0,0,0,0,0,0,0,0,0

In [53]:
print(merged_df.columns.tolist())

['Unnamed: 0', 'Symbol', 'Company', 'AsOnDate', 'AsOnYear', 'ISIN', 'Person Code', 'Director Salutation', 'Director First Name', 'Director Middle Name', 'Director Surname', 'Date of Birth', 'Gender', 'Nationality', 'Member of Civil Services', 'Promoter Director (Yes/No)', 'Position on Board', 'Independent (Yes/No)', 'Education1', 'Education2', 'Education3', 'Education4', 'Education5', 'Education6', 'Education7', 'Education8', 'Education9', 'Education10', 'Skills/Competencies', 'Occupation', 'Cessation Reason', 'Other Directorship 1', 'Other Directorship 2', 'Other Directorship 3', 'Other Directorship 4', 'Other Directorship 5', 'Other Directorship 6', 'Other Directorship 7', 'Other Directorship 8', 'Other Directorship 9', 'Other Directorship 10', 'Other Directorship 11', 'Other Directorship 12', 'Other Directorship 13', 'Other Directorship 14', 'Other Directorship 15', 'Brief Profile', 'Tenure Valid till', 'Indep', 'Appointment Date', 'Cessation Date', 'PrevLastServed', 'NextServed', 'CessationDummy', 'ReappointDummy', 'TermStartDummy', 'TermNumber', 'AppointDummy', 'CumOpBalUnc', 'CumOpBalIndep', 'CumOpBalNonIndep', 'CumCloBalUnc', 'CumCloBalIndep', 'CumCloBalNonIndep', 'TermOpBalUnc', 'TermOpBalIndep', 'TermOpBalNonIndep', 'TermOpBalTotal', 'TermCloBalUnc', 'TermCloBalIndep', 'TermCloBalNonIndep', 'TermCloBalTotal', 'CompOpBalUnc', 'CompOpBalIndep', 'CompOpBalNonIndep', 'CompOpBalTotal', 'CompCloBalUnc', 'CompCloBalIndep', 'CompCloBalNonIndep', 'CompCloBalTotal', 'CloBalTotalXP', 'CountOtherPastUnclearA', 'CountOtherPastIndepA', 'CountOtherPastNonIndepA', 'CompCountOtherPastTotalA', 'CountOtherPastUnclearAB', 'CountOtherPastIndepAB', 'CountOtherPastNonIndepAB', 'CompCountOtherPastTotalAB', 'CountCurrUnclearA', 'CountCurrIndepA', 'CountCurrNonIndepA', 'CompCountCurrTotalA', 'CountCurrUnclearAB', 'CountCurrIndepAB', 'CountCurrNonIndepAB', 'CompCountCurrTotalAB', 'Rookie', 'IsIndep', 'IsNonIndep', 'IsRookie', 'IsNonRookie', 'IsCeoMDPosition', 'IsChairmanPosition', 'IsCeoMDOccupation', 'IsChairmanOccupation', 'IsCeoMD', 'IsChairman', 'IsPromoterClassification', 'IsPromoterBoard', 'IsPromoter', 'IsDualityChairmanMD', 'IsFamilyManager', 'IsFamilyChairman', 'IsFamilyChairmanAndCEO', 'IsRookieIndep', 'IsRookieNonIndep', 'IsNonRookieIndep', 'IsNonRookieNonIndep', 'IsFemale', 'Age', 'TenureInYearsinCompIndep', 'TenureInYearsinCompTotal', 'IsFirstTerm', 'IsFirstTermIndep', 'IsOneYear', 'IsOneYearIndep', 'IsTwoYear', 'IsTwoYearIndep', 'IsThreeYear', 'IsThreeYearIndep', 'IsRetires5y', 'IsTermLimitRetirement', 'IsDefaultTerm', 'IsBusy', 'IsTurnOver', 'HasRetires5y', 'HasTermLimitRetirement', 'IsTurnOverIndep', 'Company Name', 'Prowess company code', 'Entity type', 'Entity type code', 'Incorporation year', 'Industry group', 'Industry group code', 'NIC name', 'NIC code', 'Ownership group code', 'Ownership group', 'Age group', 'NSE symbol', 'Head office address', 'EducationAll', 'IsMBA', 'IsPhD', 'HasFinanceXP', 'HasTechXP', 'HasRelatedIndustryXP', 'HasExecXP', 'PublicExecXPDummy', 'PrivateExecXPDummy', 'HasPublicExecXP', 'HasPrivateExecXP', 'HasTechSkill', 'HasFinanceSkill', 'NumSkills', 'NumFirmsPast', 'NumIndustryPast', 'HasCeoMDChairXP', 'HasConglomerateXP', 'NumSkillsScaled', 'NumFirmsPastScaled', 'NumIndustryPastScaled', 'HasCeoMDChairXPScaled', 'HasConglomerateXPScaled', 'General Ability Index', 'General Ability Index_scaled', 'FactorLoading1', 'FactorLoading2', 'FactorLoading3', 'FactorLoading4', 'FactorLoading5', 'Eigenvalue', 'NumSkillsScaled_2013', 'NumFirmsPastScaled_2013', 'NumIndustryPastScaled_2013', 'HasCeoMDChairXPScaled_2013', 'HasConglomerateXPScaled_2013', 'General Ability Index_2013', 'General Ability Index_scaled_2013', 'FactorLoading1_2013', 'FactorLoading2_2013', 'FactorLoading3_2013', 'FactorLoading4_2013', 'FactorLoading5_2013', 'Eigenvalue2013', 'Meetings absent (%)', 'combined_sustainability', 'combined_entrepreneurial', 'combined_compensation', 'combined_conglomerate_experience', 'combined_hr', 'combined_technology', 'combined_finance_accounting', 'combined_governance', 'combined_government_policy', 'combined_international', 'combined_leadership', 'combined_legal', 'combined_marketing', 'combined_risk_management', 'combined_scientific', 'combined_strategic_planning', 'combined_manufacturing_supply_chain', 'Academic', 'Company Business', 'Outside Board']

In [74]:
merged_df['combined_leadership_outside_board'] = merged_df['combined_leadership'] | merged_df['Outside Board']

merged_df.drop(['combined_leadership', 'Outside Board'], axis=1, inplace=True)

In [75]:
merged_df

,Unnamed: 0,Symbol,Company,AsOnDate,AsOnYear,ISIN,Person Code,Director Salutation,Director First Name,Director Middle Name,...,combined_international,combined_legal,combined_marketing,combined_risk_management,combined_scientific,combined_strategic_planning,combined_manufacturing_supply_chain,Academic,Company Business,combined_leadership_outside_board
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,...,0,0,1,0,0,0,0,0,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,2006,INE470A01017,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,2006,INE208A01029,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,2006,INE118A01012,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,2006,INE371A01025,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259426,259426,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,2024,INE010B01027,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,1,1,0,0,1,1,0,1
259427,259427,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00013240,DR.(MR.),SHARVIL,PANKAJ,...,1,0,0,1,0,0,0,1,0,1
259428,259428,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00071607,MR.,TARUN,GIAN,...,0,0,1,0,1,1,1,0,0,1
259429,259429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00091934,MR.,ASHISH,NaN,...,0,0,0,0,0,0,1,0,0,1
259430,259430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,2024,INE768C01010,P00090966,MR.,SAVYASACHI,SANTOSH,...,0,0,0,0,0,0,0,0,0,0

In [84]:
merged_df = merged_df.drop(columns=['Unnamed: 0'], errors='ignore')

merged_df.reset_index(drop=True, inplace=True)

In [ ]:
selected_columns = [
    'Academic','combined_manufacturing_supply_chain',
    'combined_sustainability', 'combined_entrepreneurial', 'combined_compensation',
    'combined_governance', 'combined_government_policy', 'combined_international',
     'combined_legal','combined_leadership_outside_board',
    'combined_marketing', 'combined_risk_management', 'combined_scientific',
    'combined_strategic_planning', 'combined_conglomerate_experience',
    'combined_hr', 'combined_technology', 'combined_finance_accounting','Company Business'
]

for col in selected_columns:
    print(f"\nValue counts for {col}:")
    print(merged_df[col].value_counts(dropna=False))

summary = pd.DataFrame({
    col: merged_df[col].value_counts(dropna=False)
    for col in selected_columns
}).fillna(0).astype(int).T

summary.columns = [f'count_{col}' for col in summary.columns]

In [ ]:
merged_df.to_csv("Main_Director_Complete_SkillsetsFinal_1.csv")