In [1]:
import pandas_datareader.data as web #to collect data
import datetime as dt #to specify start and end dates

# import yfinance as yf

import eventstudy as es
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.regression.rolling import RollingOLS

from patsy import dmatrices
from tqdm.notebook import tqdm
tqdm.pandas()

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Data Reading

In [2]:
dir120CAR = pd.read_csv("dir120CAR.csv", index_col = 0)
dir150CAR = pd.read_csv("dir150CAR.csv", index_col = 0)
dir180CAR = pd.read_csv("dir180CAR.csv", index_col = 0)

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_17872\2553027090.py:1: DtypeWarning: Columns (22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  dir120CAR = pd.read_csv("dir120CAR.csv", index_col = 0)
C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_17872\2553027090.py:2: DtypeWarning: Columns (22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  dir150CAR = pd.read_csv("dir150CAR.csv", index_col = 0)
C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_17872\2553027090.py:3: DtypeWarning: Columns (22,23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  dir180CAR = pd.read_csv("dir180CAR.csv", index_col = 0)

In [3]:
dir120CAR

,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,ProwessCode,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,Head office address,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102.0,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,2.010101e+10,Bajaj Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912.0,2.010103e+10,Graphite India Group,Between 1972 and 1985,"31, Chowringhee Road, Kolkata West Bengal",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005980,MR.,BHARAT,VINAYAK,PATEL,1950-09-29,M,NaN,2003-04-29,NaN,GRADUATE: B.E.-MECHANICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN CHEMICAL MANUFACTURI...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,3623.0,4015,0,7638.0,3623.0,4380,0,8003.0,7642.0,7642.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74.0,11.0,20.926027,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00031583,MR.,JITENDRA,R.,PATEL,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-29,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,0,0,12,NaN,0,4015,NaN,NaN,0,4380,NaN,NaN,NaN,"(('ZYDUSWELL', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'N'),)","(('ZYDUSWELL', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,n,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,NaN,0.0,NaN,0,0,0,0,2024,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005982,MR.,MANU,PURSHOTTAM,PATEL,1936-04-21,M,NaN,1994-11-01,NaN,GRADUATE: B.COM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN TEA MANUFACTURING BU...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,6724.0,4015,0,10739.0,6724.0,4380,0,11104.0,10743.0,10743.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,88.0,11.0,29.421918,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00022619,DR.(MR.),MUKESH,RAOJI,PATEL,1947-09-13,M,NaN,2006-07-27,NaN,POST GRADUATE: M.PHARM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-04-27,NaN,HE IS A MASTER IN PHARMACY AND ALSO A PH.D. IN...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,2438.0,4015,0,6453.0,2438.0,4380,0,6818.0,6457.0,6457.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77.0,11.0,17.679452,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023964,-0.000399,-0.001528,-0.000381,0.017038,-0.008384,5.719998e-01,0.025329,0.008091,-0.015526,0.011386
446433,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00090966,MR.,SAVYASACHI,SANTOSH,SENGUPTA,1952-10-16,M,NaN,2018-11-02,NaN,GRADUATE: B.SC.-STATISTICS,"POST GRADUATE: P.G.DIPLOMA-MANAGEMENT,INDIAN I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,LEADERSHIP/MANAGEME...",2023-11-01,RETIRED/SUPERANNUATED/TERM EXPIRED,"MR. SAVYASACHI SENGUPTA, AGED ABOUT 66 YEARS I...",NO,NON-EXECUTIVE DIRECTOR,YES,MANAGEMENT CONSULTANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,0,6,0,149.0,1825,0,1974.0,149.0,2190,0,2339.0,1976.0,1976.0,"(('ZYDUSWELL', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'Y'),)","(('ZYDUSWELL', 'Y'),)",0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,71.0,5.0,5.408219,0,0,0,0,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,1180.15,-0.018301,0.018363,1.280998,1.299361,-0.382356,0.948342,-0.022766,0.013519,0.008227,-0.003051,0.239743,0.220081,5.417183e-07,-0.040112,-0.030899,-0.020614,-0.181446

In [4]:
dir150CAR

,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,ProwessCode,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,Head office address,ACP,pct,RF,RMRF,MF,SMB,HML,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102.0,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,2.010101e+10,Bajaj Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912.0,2.010103e+10,Graphite India Group,Between 1972 and 1985,"31, Chowringhee Road, Kolkata West Bengal",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005980,MR.,BHARAT,VINAYAK,PATEL,1950-09-29,M,NaN,2003-04-29,NaN,GRADUATE: B.E.-MECHANICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN CHEMICAL MANUFACTURI...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,3623.0,4015,0,7638.0,3623.0,4380,0,8003.0,7642.0,7642.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74.0,11.0,20.926027,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00031583,MR.,JITENDRA,R.,PATEL,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-29,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,0,0,12,NaN,0,4015,NaN,NaN,0,4380,NaN,NaN,NaN,"(('ZYDUSWELL', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'N'),)","(('ZYDUSWELL', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,n,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,NaN,0.0,NaN,0,0,0,0,2024,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005982,MR.,MANU,PURSHOTTAM,PATEL,1936-04-21,M,NaN,1994-11-01,NaN,GRADUATE: B.COM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN TEA MANUFACTURING BU...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,6724.0,4015,0,10739.0,6724.0,4380,0,11104.0,10743.0,10743.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,88.0,11.0,29.421918,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00022619,DR.(MR.),MUKESH,RAOJI,PATEL,1947-09-13,M,NaN,2006-07-27,NaN,POST GRADUATE: M.PHARM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-04-27,NaN,HE IS A MASTER IN PHARMACY AND ALSO A PH.D. IN...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,2438.0,4015,0,6453.0,2438.0,4380,0,6818.0,6457.0,6457.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77.0,11.0,17.679452,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023681,-0.000460,-0.001883,0.000408,0.027484,0.007501,2.526707e-01,0.025916,0.009138,-0.016500,0.008444
446433,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00090966,MR.,SAVYASACHI,SANTOSH,SENGUPTA,1952-10-16,M,NaN,2018-11-02,NaN,GRADUATE: B.SC.-STATISTICS,"POST GRADUATE: P.G.DIPLOMA-MANAGEMENT,INDIAN I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,LEADERSHIP/MANAGEME...",2023-11-01,RETIRED/SUPERANNUATED/TERM EXPIRED,"MR. SAVYASACHI SENGUPTA, AGED ABOUT 66 YEARS I...",NO,NON-EXECUTIVE DIRECTOR,YES,MANAGEMENT CONSULTANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,0,6,0,149.0,1825,0,1974.0,149.0,2190,0,2339.0,1976.0,1976.0,"(('ZYDUSWELL', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'Y'),)","(('ZYDUSWELL', 'Y'),)",0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,71.0,5.0,5.408219,0,0,0,0,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,1180.15,-0.018301,0.018363,1.280998,1.299361,-0.382356,0.948342,-0.023445,0.012825,0.007379,-0.003311,0.195702,0.179176,5.484724e-07,-0.036246,-0.024944,-0.011133,-0.167557

In [5]:
dir180CAR

,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,ProwessCode,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,Head office address,ACP,pct,RF,RMRF,MF,SMB,HML,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102.0,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,2.010101e+10,Bajaj Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912.0,2.010103e+10,Graphite India Group,Between 1972 and 1985,"31, Chowringhee Road, Kolkata West Bengal",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005980,MR.,BHARAT,VINAYAK,PATEL,1950-09-29,M,NaN,2003-04-29,NaN,GRADUATE: B.E.-MECHANICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN CHEMICAL MANUFACTURI...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,3623.0,4015,0,7638.0,3623.0,4380,0,8003.0,7642.0,7642.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74.0,11.0,20.926027,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00031583,MR.,JITENDRA,R.,PATEL,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-29,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,0,0,12,NaN,0,4015,NaN,NaN,0,4380,NaN,NaN,NaN,"(('ZYDUSWELL', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'N'),)","(('ZYDUSWELL', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,n,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,NaN,0.0,NaN,0,0,0,0,2024,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005982,MR.,MANU,PURSHOTTAM,PATEL,1936-04-21,M,NaN,1994-11-01,NaN,GRADUATE: B.COM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN TEA MANUFACTURING BU...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,6724.0,4015,0,10739.0,6724.0,4380,0,11104.0,10743.0,10743.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,88.0,11.0,29.421918,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00022619,DR.(MR.),MUKESH,RAOJI,PATEL,1947-09-13,M,NaN,2006-07-27,NaN,POST GRADUATE: M.PHARM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-04-27,NaN,HE IS A MASTER IN PHARMACY AND ALSO A PH.D. IN...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,2438.0,4015,0,6453.0,2438.0,4380,0,6818.0,6457.0,6457.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77.0,11.0,17.679452,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023612,-0.000521,-0.002284,-0.00029,0.029526,0.012984,1.517715e-01,0.026497,0.010076,-0.016052,0.008829
446433,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00090966,MR.,SAVYASACHI,SANTOSH,SENGUPTA,1952-10-16,M,NaN,2018-11-02,NaN,GRADUATE: B.SC.-STATISTICS,"POST GRADUATE: P.G.DIPLOMA-MANAGEMENT,INDIAN I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,LEADERSHIP/MANAGEME...",2023-11-01,RETIRED/SUPERANNUATED/TERM EXPIRED,"MR. SAVYASACHI SENGUPTA, AGED ABOUT 66 YEARS I...",NO,NON-EXECUTIVE DIRECTOR,YES,MANAGEMENT CONSULTANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,0,6,0,149.0,1825,0,1974.0,149.0,2190,0,2339.0,1976.0,1976.0,"(('ZYDUSWELL', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'Y'),)","(('ZYDUSWELL', 'Y'),)",0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,71.0,5.0,5.408219,0,0,0,0,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,1180.15,-0.018301,0.018363,1.280998,1.299361,-0.382356,0.948342,-0.022171,0.012003,0.008282,-0.00329,0.182234,0.168295,9.523301e-08,-0.039730,-0.029963,-0.019709,-0.181602

In [6]:
dir180CAR.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Appointment Date',
 'Member of Civil Services',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Cessation Date',
 'Cessation Reason',
 'Brief Profile',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Occupation',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Tenure Valid till',
 'PrevLastServed',
 'Indep',
 'cumsum_U',
 'cumsum_Y',
 'cumsum_N',
 'OpBalUnc',
 'OpBalIndep',
 'OpBalNonIndep',
 'OpBalTotal',
 'CloBalUnc',
 'CloBalIndep',
 'CloBalNonIndep',
 'CloBalTotal',
 'YOE',
 'YOEmax',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManaged',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsIndep',
 'TenureInYearsTotal',
 'IsFirstTermIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'AsOnYear',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'CompanyName',
 'ProwessCode',
 'Entity type',
 'Entity type code',
 'Incorporation year',
 'Industry group',
 'Industry group code',
 'NIC name',
 'NIC code',
 'Ownership group code',
 'Ownership group',
 'Age group',
 'Head office address',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_SMB',
 'OLS180_HML',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11']

In [7]:
comCol = list(dir150CAR.columns[0:134])
comCol

['Symbol',
 'Company',
 'AsOnDate',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Appointment Date',
 'Member of Civil Services',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Cessation Date',
 'Cessation Reason',
 'Brief Profile',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Occupation',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Tenure Valid till',
 'PrevLastServed',
 'Indep',
 'cumsum_U',
 'cumsum_Y',
 'cumsum_N',
 'OpBalUnc',
 'OpBalIndep',
 'OpBalNonIndep',
 'OpBalTotal',
 'CloBalUnc',
 'CloBalIndep',
 'CloBalNonIndep',
 'CloBalTotal',
 'YOE',
 'YOEmax',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManaged',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsIndep',
 'TenureInYearsTotal',
 'IsFirstTermIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'AsOnYear',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'CompanyName',
 'ProwessCode',
 'Entity type',
 'Entity type code',
 'Incorporation year',
 'Industry group',
 'Industry group code',
 'NIC name',
 'NIC code',
 'Ownership group code',
 'Ownership group',
 'Age group',
 'Head office address',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML']

In [8]:
dirCAR = pd.concat([dir120CAR, dir150CAR, dir180CAR], axis = 1)
dirCAR = dirCAR.loc[:, ~dirCAR.columns.duplicated()].copy()
dirCAR

,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,CompanyName,ProwessCode,Entity type,Entity type code,Incorporation year,Industry group,Industry group code,NIC name,NIC code,Ownership group code,Ownership group,Age group,Head office address,ACP,pct,RF,RMRF,MF,SMB,HML,OLS120_intercept,OLS120_RMRF,OLS120_SMB,OLS120_HML,OLS120_r_squared,OLS120_adjusted_r_squared,OLS120_f_p_value,120CAR3,120CAR5,120CAR7,120CAR11,OLS150_intercept,OLS150_RMRF,OLS150_SMB,OLS150_HML,OLS150_r_squared,OLS150_adjusted_r_squared,OLS150_f_p_value,150CAR3,150CAR5,150CAR7,150CAR11,OLS180_intercept,OLS180_RMRF,OLS180_SMB,OLS180_HML,OLS180_r_squared,OLS180_adjusted_r_squared,OLS180_f_p_value,180CAR3,180CAR5,180CAR7,180CAR11
0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,3M India Ltd.,36277.0,Public Ltd.,1.020302e+10,1987.0,"Plastic furniture, floorings & miscellaneous i...",1.010120e+14,Manufacture of other plastics products n.e.c.,22209.0,2.020200e+10,Private (Foreign),Between 1986 and 1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,Ashok Leyland Ltd.,22104.0,Public Ltd.,1.020302e+10,1948.0,Commercial vehicles,1.010145e+14,Manufacture of commercial vehicles such as van...,29102.0,2.020101e+10,Hinduja (Ashok Leyland) Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,Bajaj Holdings & Invst. Ltd.,28899.0,Public Ltd.,1.020302e+10,1945.0,Other fund based financial services,1.020400e+14,"Trusts, funds and other financial vehicles",64300.0,2.010101e+10,Bajaj Group,Before 1950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,84.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,Graphite India Ltd.,42434.0,Public Ltd.,1.020302e+10,1974.0,Refractories,1.010130e+14,"Manufacture of refractory bricks, blocks tiles...",23912.0,2.010103e+10,Graphite India Group,Between 1972 and 1985,"31, Chowringhee Road, Kolkata West Bengal",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005980,MR.,BHARAT,VINAYAK,PATEL,1950-09-29,M,NaN,2003-04-29,NaN,GRADUATE: B.E.-MECHANICAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN CHEMICAL MANUFACTURI...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,3623.0,4015,0,7638.0,3623.0,4380,0,8003.0,7642.0,7642.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,74.0,11.0,20.926027,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00031583,MR.,JITENDRA,R.,PATEL,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-29,NaN,NaN,NO,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,0,0,12,NaN,0,4015,NaN,NaN,0,4380,NaN,NaN,NaN,"(('ZYDUSWELL', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'N'),)","(('ZYDUSWELL', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,n,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,NaN,0.0,NaN,0,0,0,0,2024,1,0,0,0,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00005982,MR.,MANU,PURSHOTTAM,PATEL,1936-04-21,M,NaN,1994-11-01,NaN,GRADUATE: B.COM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-07-27,NaN,HE HAS VAST EXPERIENCE IN TEA MANUFACTURING BU...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,6724.0,4015,0,10739.0,6724.0,4380,0,11104.0,10743.0,10743.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,88.0,11.0,29.421918,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00022619,DR.(MR.),MUKESH,RAOJI,PATEL,1947-09-13,M,NaN,2006-07-27,NaN,POST GRADUATE: M.PHARM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-04-27,NaN,HE IS A MASTER IN PHARMACY AND ALSO A PH.D. IN...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,3,12,0,2438.0,4015,0,6453.0,2438.0,4380,0,6818.0,6457.0,6457.0,"(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))","(('ZYDUSWELL', 'U'), ('ZYDUSWELL', 'Y'))",1,1,0,2,1,1,0,2,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,77.0,11.0,17.679452,0,0,0,1,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,15.65,0.000000,0.017086,1.247630,1.264716,0.353752,-0.765796,-0.023964,-0.000399,-0.001528,-0.000381,0.017038,-0.008384,5.719998e-01,0.025329,0.008091,-0.015526,0.011386,-0.023681,-0.000460,-0.001883,0.000408,0.027484,0.007501,2.526707e-01,0.025916,0.009138,-0.016500,0.008444,-0.023612,-0.000521,-0.002284,-0.00029,0.029526,0.012984,1.517715e-01,0.026497,0.010076,-0.016052,0.008829
446433,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00090966,MR.,SAVYASACHI,SANTOSH,SENGUPTA,1952-10-16,M,NaN,2018-11-02,NaN,GRADUATE: B.SC.-STATISTICS,"POST GRADUATE: P.G.DIPLOMA-MANAGEMENT,INDIAN I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,LEADERSHIP/MANAGEME...",2023-11-01,RETIRED/SUPERANNUATED/TERM EXPIRED,"MR. SAVYASACHI SENGUPTA, AGED ABOUT 66 YEARS I...",NO,NON-EXECUTIVE DIRECTOR,YES,MANAGEMENT CONSULTANT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,Y,0,6,0,149.0,1825,0,1974.0,149.0,2190,0,2339.0,1976.0,1976.0,"(('ZYDUSWELL', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUS WELLNESS LTD.', 'Y'),)","(('ZYDUSWELL', 'Y'),)","(('ZYDUSWELL', 'Y'),)",0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,N,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,71.0,5.0,5.408219,0,0,0,0,2024,1,0,0,1,Zydus Wellness Ltd.,42684.0,Public Ltd.,1.020302e+10,1994.0,Vegetable oils & products,1.010111e+14,"Manufacture of other vegetable oil, animal oil...",10409.0,2.010104e+10,Zydus Cadila Group,Between 1991 and 2013,NaN,1180.15,-0.018301,0.018363,1.280998,1.299361,-0.382356,0.948342,-0.022766,0.013519,0.008227,-0.003051,0.239743,0.220081,5.417183e-07,-0.040112,-0.030899,-0.020614,-0.181446,-0.023445,0.012825,0.007379,-0.003311,0.195702,0.179176,5.484724e-07,-0.036246,-0.024944,-0.011133,-0.167557,-0.022171,0.012003,0.008282,-0.00329,0.182234,0.168295,9.523301e-08,-0.039730,-0.029963,-0.019709,-0.181602

In [9]:
dirCAR.columns.to_list()

['Symbol',
 'Company',
 'AsOnDate',
 'Person Code',
 'Director Salutation',
 'Director First Name',
 'Director Middle Name',
 'Director Surname',
 'Date of Birth',
 'Gender',
 'Nationality',
 'Appointment Date',
 'Member of Civil Services',
 'Education1',
 'Education2',
 'Education3',
 'Education4',
 'Education5',
 'Education6',
 'Education7',
 'Education8',
 'Education9',
 'Education10',
 'Skills/Competencies',
 'Cessation Date',
 'Cessation Reason',
 'Brief Profile',
 'Promoter Director (Yes/No)',
 'Position on Board',
 'Independent (Yes/No)',
 'Occupation',
 'Other Directorship 1',
 'Other Directorship 2',
 'Other Directorship 3',
 'Other Directorship 4',
 'Other Directorship 5',
 'Other Directorship 6',
 'Other Directorship 7',
 'Other Directorship 8',
 'Other Directorship 9',
 'Other Directorship 10',
 'Other Directorship 11',
 'Other Directorship 12',
 'Other Directorship 13',
 'Other Directorship 14',
 'Other Directorship 15',
 'Tenure Valid till',
 'PrevLastServed',
 'Indep',
 'cumsum_U',
 'cumsum_Y',
 'cumsum_N',
 'OpBalUnc',
 'OpBalIndep',
 'OpBalNonIndep',
 'OpBalTotal',
 'CloBalUnc',
 'CloBalIndep',
 'CloBalNonIndep',
 'CloBalTotal',
 'YOE',
 'YOEmax',
 'AllPastDirect',
 'CurrDirectA',
 'CurrDirectAB',
 'PastSiezedDirectA',
 'PastSiezedDirectAB',
 'CountOtherPastUnclearA',
 'CountOtherPastIndepA',
 'CountOtherPastNonIndepA',
 'CompCountOtherPastTotalA',
 'CountOtherPastUnclearAB',
 'CountOtherPastIndepAB',
 'CountOtherPastNonIndepAB',
 'CompCountOtherPastTotalAB',
 'CountCurrUnclearA',
 'CountCurrIndepA',
 'CountCurrNonIndepA',
 'CompCountCurrTotalA',
 'CountCurrUnclearAB',
 'CountCurrIndepAB',
 'CountCurrNonIndepAB',
 'CompCountCurrTotalAB',
 'Rookie',
 'IsIndep',
 'IsNonIndep',
 'IsRookie',
 'IsNonRookie',
 'IsCeoMD',
 'IsChairman',
 'IsPromoterClassification',
 'IsPromoterBoard',
 'IsPromoter',
 'IsDualityChairmanMD',
 'IsFamilyManaged',
 'IsFamilyChairman',
 'IsFamilyChairmanAndCEO',
 'IsRookieIndep',
 'IsRookieNonIndep',
 'IsNonRookieIndep',
 'IsNonRookieNonIndep',
 'IsFemale',
 'Age',
 'TenureInYearsIndep',
 'TenureInYearsTotal',
 'IsFirstTermIndep',
 'IsRetires5y',
 'IsTermLimitRetirement',
 'IsDefaultTerm',
 'AsOnYear',
 'IsTurnOver',
 'HasRetires5y',
 'HasTermLimitRetirement',
 'IsTurnOverIndep',
 'CompanyName',
 'ProwessCode',
 'Entity type',
 'Entity type code',
 'Incorporation year',
 'Industry group',
 'Industry group code',
 'NIC name',
 'NIC code',
 'Ownership group code',
 'Ownership group',
 'Age group',
 'Head office address',
 'ACP',
 'pct',
 'RF',
 'RMRF',
 'MF',
 'SMB',
 'HML',
 'OLS120_intercept',
 'OLS120_RMRF',
 'OLS120_SMB',
 'OLS120_HML',
 'OLS120_r_squared',
 'OLS120_adjusted_r_squared',
 'OLS120_f_p_value',
 '120CAR3',
 '120CAR5',
 '120CAR7',
 '120CAR11',
 'OLS150_intercept',
 'OLS150_RMRF',
 'OLS150_SMB',
 'OLS150_HML',
 'OLS150_r_squared',
 'OLS150_adjusted_r_squared',
 'OLS150_f_p_value',
 '150CAR3',
 '150CAR5',
 '150CAR7',
 '150CAR11',
 'OLS180_intercept',
 'OLS180_RMRF',
 'OLS180_SMB',
 'OLS180_HML',
 'OLS180_r_squared',
 'OLS180_adjusted_r_squared',
 'OLS180_f_p_value',
 '180CAR3',
 '180CAR5',
 '180CAR7',
 '180CAR11']

In [10]:
dirCAR.to_csv("Director Level CAR_on_appointment v010225.csv")