In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import numpy as np
import datetime as dt
import math as math
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_csv('Main_Director_complete v160225.csv')

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_7180\2577567172.py:1: DtypeWarning: Columns (26,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('Main_Director_complete v160225.csv')

In [3]:
df31 = df1.copy()

In [4]:
df31['IsBusy'] = np.where( df31['CompCountCurrTotalA'] > 2, 1,0)

In [5]:
df31['IsFirstTerm'] = np.where((df31['OpBalTotal'] < 365*5), 1, 0)
df31['IsFirstYear'] = np.where((df31['OpBalTotal'] < 365*1), 1, 0)
df31['IsFirstYearIndep'] = np.where( (df31['IsIndep'] == 1) & (df31['OpBalTotal'] < 365*1), 1, 0)

In [6]:
df31

,Unnamed: 0,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,IsBusy,IsFirstTerm,IsFirstYear,IsFirstYearIndep
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,0,1,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,1,1,0,0
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,1,0,0,0
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,1,0,0,0
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228550,228550,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00022618,MR.,GANESH,NARAYAN,NAYAK,1955-05-18,M,INDIA,2006-07-27,NONE,"GRADUATE: B.SC.,UNIVERSITY OF MYSORE,MYSURU","POST GRADUATE: M.B.A.,NEWPORT UNIVERSITY,CALIF...","POST GRADUATE: P.G.-GENERAL MANAGEMENT,HARVARD...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,HEALTHCARE,LEADERSH...",NaN,NaN,"MR. GANESH NAYAK, THE EXECUTIVE DIRECTOR OF ZY...",NO,"NOMINEE DIRECTOR OF CADILA HEALTHCARE LTD., NO...",NO,"MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,3,0,12,2438.0,0,4015,6453.0,2438.0,0,4380,6818.0,6457.0,6457.0,"(('ZYDUSWELL', 'U'), ('ZYDUSLIFE', 'N'), ('ZYD...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUSWELL', 'U'), ('ZYDUSLIFE', 'N'), ('ZYD...","(('ZYDUSWELL', 'U'), ('ZYDUSLIFE', 'N'), ('ZYD...",1,0,2,3,1,0,2,3,0,0,2,2,1,0,2,3,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,69.0,0.0,17.679452,0,0,0,1,2024,1,0,0,0,0,0,0,0
228551,228551,ZYDUSLIFE,ZYDUS LIFESCIENCES LTD.,2024-03-31,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,1997-08-01,NONE,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"DOCTORATE: PH.D.-BREAST CANCER,UNIVERSITY OF S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...",NaN,NaN,DR. SHARVIL PATEL IS THE MANAGING DIRECTOR OF ...,YES,"MANAGING DIRECTOR, EXECUTIVE DIRECTOR, PROMOTE...",NO,"MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2027-03-31,2023-03-31,N,7,0,12,5719.0,0,4015,9734.0,5719.0,0,4380,10099.0,9739.0,9739.0,"(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...","(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...",2,0,2,4,2,0,2,4,0,0,2,2,1,0,2,3,N,0,1,0,1,1,0,1,1,1,0,1,0,0,0,0,0,1,0,46.0,0.0,26.668493,0,0,0,1,2024,1,0,0,0,0,0,0,0
228552,228552,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,1978-10-13,M,INDIA,2009-04-27,NONE,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"DOCTORATE: PH.D.-BREAST CANCER,UNIVERSITY OF S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...",NaN,NaN,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,3,0,12,1433.0,0,4015,5448.0,1433.0,0,4380,5813.0,5452.0,9739.0,"(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUS LIFESCIENCES LTD.', 'N'), ('ZYDUS WEL...","(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...","(('ZYDUSLIFE', 'U'), ('ZYDUSWELL', 'U'), ('ZYD...",2,0,2,4,2,0,2,4,0,0,2,2,1,0,2,3,N,0,1,0,1,0,1,1,1,1,0,0,1,0,0,0,0,1,0,46.0,0.0,14.926027,0,0,0,1,2024,1,0,0,0,0,0,0,0
228553,228553,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00071607,MR.,TARUN,GIAN,ARORA,1972-01-11,M,NaN,2015-05-14,NaN,GRADUATE: B.SC.,POST GRADUATE: P.G.DIPLOMA-BUSINESS MANAGEMENT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,FINANCE,LEADERSHIP/...",NaN,NaN,"MR. TARUN ARORA, HAS BEEN LEADING THE ZYDUS WE...",NO,EXECUTIVE DIRECTOR,NO,"CHIEF EXECUTIVE OFFICER, ZYDUS WELLNESS LTD.",ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030-05-06,2023-03-31,N,0,0,9,322.0,0,2920,3242.0,322.0,0,3285,3607.0,3244.0,3244.0,"(('ZYDUSWELL', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'N'),)","(('ZYDUSWELL', 'N'),)",0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,53.0,0.0,8.882192,0,0,0,0,2024,1,0,0,0,0,0,0,0
228554,228554,ZYDUSWELL,ZYDUS WELLNESS LTD.,2024-03-31,P00091934,MR.,ASHISH,NaN,BHARGAVA,1971-08-18,M,NaN,2019-01-30,NaN,"GRADUATE: B.E.,INDIAN INSTITUTE OF TECHNOLOGY,...","POST GRADUATE: P.G.-MANAGEMENT,S.P.JAIN INSTIT...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FINANCE,LEADER...",NaN,NaN,MR. ASHISH BHARGAVA IS A PARTNER WITH LEADING ...,NO,"NOMINEE DIRECTOR OF THREPSI CARE LLP, NON-EXEC...",NO,NaN,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-31,N,0,1,5,60.0,365,1460,1885.0,60.0,365,1825,2250.0,1887.0,1887.0,"(('ZYDUSWELL', 'Y'), ('ZYDUSWELL', 'N'))","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUS WELLNESS LTD.', 'N'),)","(('ZYDUSWELL', 'Y'), ('ZYDUSWELL', 'N'))","(('ZYDUSWELL', 'Y'), ('ZYDUSWELL', 'N'))",0,1,1,2,0,1,1,2,0,0,1,1,0,0,1,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,53.0,1.0,5.164384,0,0,0,0,2024,1,0,0,0,0,0,0,0

In [7]:
df32 = df31.head(n = 500)
df32

,Unnamed: 0,Symbol,Company,AsOnDate,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till,PrevLastServed,Indep,cumsum_U,cumsum_Y,cumsum_N,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,YOE,YOEmax,AllPastDirect,CurrDirectA,CurrDirectAB,PastSiezedDirectA,PastSiezedDirectAB,CountOtherPastUnclearA,CountOtherPastIndepA,CountOtherPastNonIndepA,CompCountOtherPastTotalA,CountOtherPastUnclearAB,CountOtherPastIndepAB,CountOtherPastNonIndepAB,CompCountOtherPastTotalAB,CountCurrUnclearA,CountCurrIndepA,CountCurrNonIndepA,CompCountCurrTotalA,CountCurrUnclearAB,CountCurrIndepAB,CountCurrNonIndepAB,CompCountCurrTotalAB,Rookie,IsIndep,IsNonIndep,IsRookie,IsNonRookie,IsCeoMD,IsChairman,IsPromoterClassification,IsPromoterBoard,IsPromoter,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,IsRookieIndep,IsRookieNonIndep,IsNonRookieIndep,IsNonRookieNonIndep,IsFemale,Age,TenureInYearsIndep,TenureInYearsTotal,IsFirstTermIndep,IsRetires5y,IsTermLimitRetirement,IsDefaultTerm,AsOnYear,IsTurnOver,HasRetires5y,HasTermLimitRetirement,IsTurnOverIndep,IsBusy,IsFirstTerm,IsFirstYear,IsFirstYearIndep
0,0,3MINDIA,3M INDIA LTD.,2006-03-31,P00033272,MR.,SHANKARANARAYANA,VISHWANATHA RAO,BANAWARA,1960-05-14,M,INDIA,2002-07-24,NONE,GRADUATE: B.COM.,"POST GRADUATE: M.B.A.-FINANCE,BANGALORE UNIVER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,FINANCE,LEADERSHIP/MAN...",NaN,NaN,"MR. B.V. SHANKARANARAYANA RAO, 57, HOLDS A BAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1346.0,0,0,1346.0,1711.0,0,0,1711.0,1346.0,1346.0,(),"(('3M INDIA LTD.', 'U'),)","(('3M INDIA LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,64.0,0.0,3.687671,0,0,0,0,2006,0,0,0,0,0,1,0,0
1,1,3MINDIA,3M INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2001-12-26,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D.J. BALAJI RAO, 73, HOLDS A B.E DEGREE IN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1556.0,0,0,1556.0,1921.0,0,0,1921.0,1556.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,4.263014,0,1,0,0,2006,0,0,0,0,1,1,0,0
2,2,ASHOKLEY,ASHOK LEYLAND LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2000-07-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR D J BALAJI RAO, IS A FORMER DEPUTY MANAGING...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,2073.0,0,0,2073.0,2438.0,0,0,2438.0,2073.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,5.679452,0,0,0,0,2006,0,0,0,0,1,0,0,0
3,3,BAJAJHLDNG,BAJAJ HOLDINGS & INVESTMENT LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,1997-03-29,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"D. J. BALAJI RAO (BORN ON 15 DECEMBER 1939), H...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3289.0,0,0,3289.0,3654.0,0,0,3654.0,3289.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,9.010959,0,0,1,0,2006,0,0,0,0,1,0,0,0
4,4,GRAPHITE,GRAPHITE INDIA LTD.,2006-03-31,P00000249,LATE MR.,BALAJI RAO,JAGANNATH RAO,DOVETON,1939-12-15,M,INDIA,2004-01-17,NONE,"GRADUATE: ASSOCIATE MEMBER,INDIAN INSTITUTION ...","GRADUATE: B.E.-MECHANICAL,UNIVERSITY OF MADRAS...","POST GRADUATE: M.E.-MECHANICAL,UNIVERSITY OF M...",POST GRADUATE: P.G.-ADVANCED MANAGEMENT PROGRA...,POST GRADUATE: P.G.DIPLOMA-INDUSTRIAL ENGINEER...,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,"MR. D J BALAJI RAO, AGED 73 YEARS, HOLDS A DEG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,804.0,0,0,804.0,1169.0,0,0,1169.0,804.0,3289.0,(),"(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...","(('ASHOK LEYLAND LTD.', 'U'), ('3M INDIA LTD.'...",(),(),0,0,0,0,0,0,0,0,5,0,0,5,5,0,0,5,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,85.0,0.0,2.202740,0,0,0,0,2006,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,APARINDS,APAR INDUSTRIES LTD.,2006-03-31,P00007078,MR.,HIMATLAL,NAROTTAM,SHAH,1928-06-20,M,INDIA,2002-09-27,NONE,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF CHARTE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"BORN ON 20TH JUNE, 1928, MR.HIMATLAL N. SHAH I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1281.0,0,0,1281.0,1646.0,0,0,1646.0,1281.0,1281.0,(),"(('APAR INDUSTRIES LTD.', 'U'),)","(('APAR INDUSTRIES LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,96.0,0.0,3.509589,0,0,0,0,2006,0,0,0,0,0,1,0,0
496,496,APARINDS,APAR INDUSTRIES LTD.,2006-03-31,P00007082,DR.(MR.),NAVINCHANDRA,KRISHNAPPA,THINGALAYA,1937-11-04,M,INDIA,2001-07-27,NaN,DOCTORATE: PH.D.-ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"BORN ON 4TH NOVEMBER, 1937, DR.NAVINCHANDRA K....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1708.0,0,0,1708.0,2073.0,0,0,2073.0,1708.0,1708.0,(),"(('APAR INDUSTRIES LTD.', 'U'),)","(('APAR INDUSTRIES LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,87.0,0.0,4.679452,0,1,0,0,2006,0,0,0,0,0,1,0,0
497,497,APARINDS,APAR INDUSTRIES LTD.,2006-03-31,P00007081,MR.,FATTECHAND,BHAGWANDAS,VIRANI,1945-06-26,M,INDIA,2001-07-27,NONE,GRADUATE: B.E.-CHEMICAL,"POST GRADUATE: M.B.A.,U.S.A.","POST GRADUATE: M.S.-CHEMICAL,U.S.A.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"INDUSTRIALS,LEADERSHIP/MANAGEMENT",NaN,NaN,"BORN ON 26TH JUNE 1945, MR.FATTECHAND B.VIRANI...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,1708.0,0,0,1708.0,2073.0,0,0,2073.0,1708.0,1708.0,(),"(('APAR INDUSTRIES LTD.', 'U'),)","(('APAR INDUSTRIES LTD.', 'U'),)",(),(),0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,79.0,0.0,4.679452,0,1,0,0,2006,0,0,0,0,0,1,0,0
498,498,APCOTEXIND,APCOTEX INDUSTRIES LTD.,2006-03-31,P00004257,MR.,THIRUVILVAMALAI,NARAYAN VAIDEESWARAN,AYYAR,1961-04-21,M,INDIA,1997-11-21,NONE,GRADUATE: B.COM.,POST GRADUATE: F.C.A.(FELLOW CHARTERED ACCOUNT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MR. TNV AYYAR HAS MORE THAN TWO DECADES OF POS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,3052.0,0,0,3052.0,3417.0,0,0,3417.0,3052.0,4279.0,(),"(('GTL LTD.', 'U'), ('EMCO LTD.', 'U'), ('CRES...","(('GTL LTD.', 'U'), ('EMCO LTD.', 'U'), ('CRES...",(),(),0,0,0,0,0,0,0,0,4,0,0,4,4,0,0,4,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,63.0,0.0,8.361644,0,0,0,0,2006,0,0,0,0,1,0,0,0
499,499,CRESTANI,CREST ANIMATION STUDIOS LTD.,2006-03-31,P00004257,MR.,THIRUVILVAMALAI,NARAYAN VAIDEESWARAN,AYYAR,1961-04-21,M,INDIA,1994-07-13,NONE,GRADUATE: B.COM.,POST GRADUATE: F.C.A.(FELLOW CHARTERED ACCOUNT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MR.T.N.V.AYYAR IS A CHARTERD ACCOUNTANT AND HA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,U,1,0,0,4279.0,0,0,4279.0,4644.0,0,0,4644.0,4279.0,4279.0,(),"(('GTL LTD.', 'U'), ('EMCO LTD.', 'U'), ('CRES...","(('GTL LTD.', 'U'), ('EMCO LTD.', 'U'), ('CRES...",(),(),0,0,0,0,0,0,0,0,4,0,0,4,4,0,0,4,N,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,63.0,0.0,11.723288,0,0,0,1,2006,0,0,0,0,1,0,0,0

In [8]:
firmlev_col = ['TotDirCount',	'LnBoardSize',	'FemaleDirCount',	'PercentWomenDir',	
               'Women_dummy',	'AvgAge',	'CountRookie',	'Rookie_dummy',	
               'CountNonRookie',	'CountIndep',	'PercentIndep',	'CountNonIndep',	
               'CountRookieIndep',	'CountRookieNonIndep',	'CountNonRookieIndep',	
               'CountNonRookieNonIndep',	'CountPromoterDir',	'CountBusyDir',	'Busy_dummy',	
               'AsOnYear',	'IsCeoMD',	'HasChairman',	'HasPromoterOnBoard',	
               'IsDualityChairmanMD',	'IsFamilyManaged',	'IsFamilyChairman',	
               'IsFamilyChairmanAndCEO',	'CountFirstTermDir',	'CountTurnOverIndepDir',	
               'HasIndepTurnOver',	'AvgTenureInYearsALL',	'AvgTenureInYearsIndep',	
               'PercentRookieIndep',	'PercentNonRookieIndep',	'PercentRookieNonIndep',	
               'PercentNonRookieNonIndep',	'PercentRookie',	'PercentNonRookie',	'IsRookieBoard',	
               'JustOneRookie',	'TwoOrMoreRookies',	'PercentRetiringTermLimit', 
               'TermLimitRetireesPcodeList',	'PercentBusyDir',	'PercentFirstTermIndep',	
               'FirstYearIndepPCodeList', 'IndepPCodeList', 'FirstYearPCodeList', 'PCodeList']

In [9]:
def FirmLev(frame):
    
    dffirm = pd.DataFrame(index = [0], columns = firmlev_col)
    dffirm.at[0, 'TotDirCount'] = frame['Person Code'].shape[0]
    dffirm.at[0, 'LnBoardSize'] = math.log(dffirm.at[0, 'TotDirCount'])
    dffirm.at[0, 'FemaleDirCount'] = frame.loc[frame['IsFemale'] == 1].shape[0]
    dffirm.at[0, 'PercentWomenDir'] =  dffirm.at[0, 'FemaleDirCount'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'Women_dummy'] = np.where( dffirm.at[0, 'FemaleDirCount'] > 0, 1, 0)
    dffirm.at[0, 'AvgAge'] = frame['Age'].mean()
    dffirm.at[0, 'CountRookie'] = frame.loc[frame['IsRookie'] == 1].shape[0]
    dffirm.at[0, 'Rookie_dummy'] = np.where( frame.loc[frame['IsRookieIndep'] == 1].shape[0]>1,1,0)
    dffirm.at[0, 'CountNonRookie'] = frame.loc[frame['IsNonRookie'] == 1].shape[0]
    dffirm.at[0, 'CountIndep'] = frame.loc[frame['IsIndep'] == 1].shape[0]
    dffirm.at[0, 'PercentIndep'] = dffirm.at[0, 'CountIndep'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'CountNonIndep'] = frame.loc[frame['IsNonIndep'] == 1].shape[0]
    dffirm.at[0, 'CountRookieIndep'] = frame.loc[frame['IsRookieIndep'] == 1].shape[0]
    dffirm.at[0, 'CountRookieNonIndep'] = frame.loc[frame['IsRookieNonIndep'] == 1].shape[0]
    dffirm.at[0, 'CountNonRookieIndep'] = frame.loc[frame['IsNonRookieIndep'] == 1].shape[0]
    dffirm.at[0, 'CountNonRookieNonIndep'] = frame.loc[frame['IsNonRookieNonIndep'] == 1].shape[0]
    dffirm.at[0, 'CountPromoterDir'] = frame.loc[frame['IsPromoter'] == 1].shape[0]
    dffirm.at[0, 'CountBusyDir'] = frame.loc[frame['IsBusy'] == 1].shape[0]
    dffirm.at[0, 'Busy_dummy'] = np.where( dffirm.at[0, 'CountBusyDir']>0,1,0)

    dffirm.at[0, 'IsCeoMD'] = np.where( frame.loc[frame['IsCeoMD'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'HasChairman'] = np.where( frame.loc[frame['IsChairman'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'HasPromoterOnBoard'] = np.where( frame.loc[frame['IsPromoter'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'IsDualityChairmanMD'] = np.where( frame.loc[frame['IsDualityChairmanMD'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'IsFamilyManaged'] = np.where( frame.loc[frame['IsFamilyManaged'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'IsFamilyChairman'] = np.where( frame.loc[frame['IsFamilyChairman'] == 1].shape[0] >0,1,0)
    dffirm.at[0, 'IsFamilyChairmanAndCEO'] = np.where( frame.loc[frame['IsFamilyChairmanAndCEO'] == 1].shape[0] >0,1,0)
    
    dffirm.at[0, 'CountFirstTermDir'] = frame.loc[frame['IsFirstTerm'] == 1].shape[0]
    dffirm.at[0, 'CountTurnOverIndepDir'] = frame.loc[frame['IsTurnOver'] == 1].shape[0]
    dffirm.at[0, 'HasIndepTurnOver'] = np.where( dffirm.at[0, 'CountTurnOverIndepDir']>0, 1,0)
    dffirm.at[0, 'AvgTenureInYearsALL'] = frame['TenureInYearsTotal'].mean()
    dffirm.at[0, 'AvgTenureInYearsIndep'] = frame['TenureInYearsIndep'].mean()

    dffirm.at[0, 'PercentRookieIndep'] = dffirm.at[0, 'CountRookieIndep'] /  dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0
    
    dffirm.at[0, 'PercentNonRookieIndep'] = dffirm.at[0, 'CountNonRookieIndep'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'PercentRookieNonIndep'] =  dffirm.at[0, 'CountRookieNonIndep'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'PercentNonRookieNonIndep'] = dffirm.at[0, 'CountNonRookieNonIndep'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'PercentRookie'] = dffirm.at[0, 'CountRookie'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    dffirm.at[0, 'PercentNonRookie'] = dffirm.at[0, 'CountNonRookie'] / dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    
    dffirm.at[0, 'IsRookieBoard'] = np.where((dffirm.at[0, 'CountRookieIndep']/dffirm.at[0, 'CountIndep'])>0.5, 1, 0) if dffirm.at[0, 'CountIndep'] > 0 else 0
    
    dffirm.at[0, 'JustOneRookie'] = np.where( dffirm.at[0, 'CountRookieIndep'] == 1,1,0)
    dffirm.at[0, 'TwoOrMoreRookies'] = np.where( dffirm.at[0, 'CountRookieIndep'] > 1,1,0)
    
    dffirm.at[0, 'CountRetiringTermLimit'] = frame.loc[ (frame['IsIndep'] == 1) & ((frame['HasTermLimitRetirement'] == 1) | (frame['HasRetires5y'] == 1))].shape[0]
    dffirm.at[0, 'PercentRetiringTermLimit'] = dffirm.at[0, 'CountRetiringTermLimit'] / dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0
    dffirm.at[0, 'TermLimitRetireesPcodeList'] = list (frame.loc[(frame['IsIndep'] == 1) & ((frame['HasTermLimitRetirement'] == 1) | (frame['HasRetires5y'] == 1))]['Person Code'])
    
    dffirm.at[0, 'PercentBusyDir'] = dffirm.at[0, 'CountBusyDir'] /  dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0

    dffirm.at[0, 'CountFirstTermIndep'] = frame.loc[ frame['IsFirstTermIndep'] == 1].shape[0]
    dffirm.at[0, 'PercentFirstTermIndep'] = dffirm.at[0, 'CountFirstTermIndep'] /  dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0
    # ---------------------------------------------------
    dffirm.at[0, 'CountDirTurnOver_exits_retire'] = frame.loc[ (frame['IsTurnOver'] == 1)].shape[0]
    dffirm.at[0, 'PercentDirTurnOver_exits_retire'] = dffirm.at[0, 'CountDirTurnOver_exits_retire']/  dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0

    dffirm.at[0, 'CountDirTurnOver_real_exits'] = frame.loc[ (frame['IsTurnOver'] == 1) & ((frame['HasTermLimitRetirement'] == 0) & (frame['HasRetires5y'] == 0)) ].shape[0]
    dffirm.at[0, 'PercentDirTurnOver_real_exits'] = dffirm.at[0, 'CountDirTurnOver_real_exits']/  dffirm.at[0, 'TotDirCount'] if dffirm.at[0, 'TotDirCount'] > 0 else 0
    # ---------------------------------------------------
    dffirm.at[0, 'CountIndepDirTurnOver_exits_retire'] = frame.loc[ (frame['IsTurnOver'] == 1) & (frame['IsIndep'] == 1) ].shape[0]
    dffirm.at[0, 'PercentIndepDirTurnOver_exits_retire'] = dffirm.at[0, 'CountIndepDirTurnOver_exits_retire']/  dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0

    dffirm.at[0, 'CountIndepDirTurnOver_real_exits'] = frame.loc[ (frame['IsTurnOver'] == 1) & (frame['IsIndep'] == 1) & ((frame['HasTermLimitRetirement'] == 0) & (frame['HasRetires5y'] == 0)) ].shape[0]
    dffirm.at[0, 'PercentIndepDirTurnOver_real_exits'] = dffirm.at[0, 'CountIndepDirTurnOver_real_exits']/  dffirm.at[0, 'CountIndep'] if dffirm.at[0, 'CountIndep'] > 0 else 0
    # ---------------------------------------------------
    dffirm.at[0, 'FirstYearIndepPCodeList'] = list (frame.loc[(frame['IsFirstYearIndep'] == 1)]['Person Code'])
    dffirm.at[0, 'IndepPCodeList'] = list (frame.loc[(frame['IsIndep'] == 1)]['Person Code'])

    dffirm.at[0, 'FirstYearPCodeList'] = list (frame.loc[(frame['IsFirstYear'] == 1)]['Person Code'])
    dffirm.at[0, 'PCodeList'] = list (frame.loc[:, 'Person Code'])
    
    
    return dffirm

#you have to calc turnover%, by taking turnover data (with and without termlimit and 5 years exits) from previous year
#simple way to do this, is to first, count the trunover and shift it down by one row and then divide by year+1 directors
#actuialy, thats all, easy shit
# i think u gotta do the same for termlimitretireesPcodeList

In [10]:
df50 = df31.groupby(['Symbol', 'AsOnDate']).progress_apply(FirmLev)

100%|████████████████████████████████████████████████████████████████████████████| 28893/28893 [11:51<00:00, 40.60it/s]

In [11]:
df50

                       TotDirCount LnBoardSize FemaleDirCount PercentWomenDir  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0          11    2.397895              0             0.0
          2010-03-31 0          10    2.302585              0             0.0
          2011-03-31 0          10    2.302585              0             0.0
          2012-03-31 0           8    2.079442              0             0.0
          2013-03-31 0           8    2.079442              0             0.0
...                            ...         ...            ...             ...
ZYLOG     2014-03-31 0           4    1.386294              0             0.0
          2015-03-31 0           3    1.098612              0             0.0
          2016-03-31 0           6    1.791759              0             0.0
          2017-03-31 0           5    1.609438              1             0.2
          2018-03-31 0           5    1.609438              1             0.2

                       Women_dummy     AvgAge CountRookie Rookie_dummy  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0           0  69.636364           4            0
          2010-03-31 0           0       68.6           3            0
          2011-03-31 0           0       68.6           2            0
          2012-03-31 0           0  69.142857           2            0
          2013-03-31 0           0  69.142857           1            0
...                            ...        ...         ...          ...
ZYLOG     2014-03-31 0           0       67.0           1            0
          2015-03-31 0           0       69.0           1            0
          2016-03-31 0           0       64.5           4            1
          2017-03-31 0           1  61.333333           4            1
          2018-03-31 0           1  61.333333           4            1

                       CountNonRookie CountIndep PercentIndep CountNonIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0              7          0          0.0            11
          2010-03-31 0              7          0          0.0            10
          2011-03-31 0              8          0          0.0            10
          2012-03-31 0              6          0          0.0             8
          2013-03-31 0              7          3        0.375             5
...                               ...        ...          ...           ...
ZYLOG     2014-03-31 0              3          2          0.5             2
          2015-03-31 0              2          2     0.666667             1
          2016-03-31 0              2          6          1.0             0
          2017-03-31 0              1          5          1.0             0
          2018-03-31 0              1          5          1.0             0

                       CountRookieIndep CountRookieNonIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                0                   4
          2010-03-31 0                0                   3
          2011-03-31 0                0                   2
          2012-03-31 0                0                   2
          2013-03-31 0                0                   1
...                                 ...                 ...
ZYLOG     2014-03-31 0                1                   0
          2015-03-31 0                1                   0
          2016-03-31 0                4                   0
          2017-03-31 0                4                   0
          2018-03-31 0                4                   0

                       CountNonRookieIndep CountNonRookieNonIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                   0                      7
          2010-03-31 0                   0                      7
          2011-03-31 0                   0                      8
          2012-03-31 0                   0                      6
          2013-03-31 0                   3                      4
...                                    ...                    ...
ZYLOG     2014-03-31 0                   1                      2
          2015-03-31 0                   1                      1
          2016-03-31 0                   2                      0
          2017-03-31 0                   1                      0
          2018-03-31 0                   1                      0

                       CountPromoterDir CountBusyDir Busy_dummy AsOnYear  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                0            1          1      NaN
          2010-03-31 0                0            1          1      NaN
          2011-03-31 0                0            1          1      NaN
          2012-03-31 0                0            1          1      NaN
          2013-03-31 0                4            1          1      NaN
...                                 ...          ...        ...      ...
ZYLOG     2014-03-31 0                1            0          0      NaN
          2015-03-31 0                1            0          0      NaN
          2016-03-31 0                0            0          0      NaN
          2017-03-31 0                0            0          0      NaN
          2018-03-31 0                0            0          0      NaN

                       IsCeoMD HasChairman HasPromoterOnBoard  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0       0           0                  0
          2010-03-31 0       0           0                  0
          2011-03-31 0       0           0                  0
          2012-03-31 0       0           0                  0
          2013-03-31 0       1           1                  1
...                        ...         ...                ...
ZYLOG     2014-03-31 0       1           1                  1
          2015-03-31 0       1           0                  1
          2016-03-31 0       0           0                  0
          2017-03-31 0       0           0                  0
          2018-03-31 0       0           0                  0

                       IsDualityChairmanMD IsFamilyManaged IsFamilyChairman  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                   0               0                0
          2010-03-31 0                   0               0                0
          2011-03-31 0                   0               0                0
          2012-03-31 0                   0               0                0
          2013-03-31 0                   1               1                1
...                                    ...             ...              ...
ZYLOG     2014-03-31 0                   1               1                0
          2015-03-31 0                   0               1                0
          2016-03-31 0                   0               0                0
          2017-03-31 0                   0               0                0
          2018-03-31 0                   0               0                0

                       IsFamilyChairmanAndCEO CountFirstTermDir  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                      0                 5
          2010-03-31 0                      0                 5
          2011-03-31 0                      0                 5
          2012-03-31 0                      0                 3
          2013-03-31 0                      1                 2
...                                       ...               ...
ZYLOG     2014-03-31 0                      0                 1
          2015-03-31 0                      0                 1
          2016-03-31 0                      0                 5
          2017-03-31 0                      0                 5
          2018-03-31 0                      0                 5

                       CountTurnOverIndepDir HasIndepTurnOver  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                     2                1
          2010-03-31 0                     0                0
          2011-03-31 0                     3                1
          2012-03-31 0                     0                0
          2013-03-31 0                     0                0
...                                      ...              ...
ZYLOG     2014-03-31 0                     1                1
          2015-03-31 0                     1                1
          2016-03-31 0                     3                1
          2017-03-31 0                     0                0
          2018-03-31 0                     5                1

                       AvgTenureInYearsALL AvgTenureInYearsIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0            6.646077                   0.0
          2010-03-31 0             7.24137                   0.0
          2011-03-31 0             8.24137                   0.0
          2012-03-31 0            9.319863                   0.0
          2013-03-31 0           10.319863                   0.0
...                                    ...                   ...
ZYLOG     2014-03-31 0           12.202055                  0.25
          2015-03-31 0           10.989041                   1.0
          2016-03-31 0            2.920091              0.833333
          2017-03-31 0            0.905753                   0.6
          2018-03-31 0            1.905753                   1.6

                       PercentRookieIndep PercentNonRookieIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                  0                   0.0
          2010-03-31 0                  0                   0.0
          2011-03-31 0                  0                   0.0
          2012-03-31 0                  0                   0.0
          2013-03-31 0                0.0                 0.375
...                                   ...                   ...
ZYLOG     2014-03-31 0                0.5                  0.25
          2015-03-31 0                0.5              0.333333
          2016-03-31 0           0.666667              0.333333
          2017-03-31 0                0.8                   0.2
          2018-03-31 0                0.8                   0.2

                       PercentRookieNonIndep PercentNonRookieNonIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0              0.363636                 0.636364
          2010-03-31 0                   0.3                      0.7
          2011-03-31 0                   0.2                      0.8
          2012-03-31 0                  0.25                     0.75
          2013-03-31 0                 0.125                      0.5
...                                      ...                      ...
ZYLOG     2014-03-31 0                   0.0                      0.5
          2015-03-31 0                   0.0                 0.333333
          2016-03-31 0                   0.0                      0.0
          2017-03-31 0                   0.0                      0.0
          2018-03-31 0                   0.0                      0.0

                       PercentRookie PercentNonRookie IsRookieBoard  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0      0.363636         0.636364             0
          2010-03-31 0           0.3              0.7             0
          2011-03-31 0           0.2              0.8             0
          2012-03-31 0          0.25             0.75             0
          2013-03-31 0         0.125            0.875             0
...                              ...              ...           ...
ZYLOG     2014-03-31 0          0.25             0.75             0
          2015-03-31 0      0.333333         0.666667             0
          2016-03-31 0      0.666667         0.333333             1
          2017-03-31 0           0.8              0.2             1
          2018-03-31 0           0.8              0.2             1

                       JustOneRookie TwoOrMoreRookies  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0             0                0
          2010-03-31 0             0                0
          2011-03-31 0             0                0
          2012-03-31 0             0                0
          2013-03-31 0             0                0
...                              ...              ...
ZYLOG     2014-03-31 0             1                0
          2015-03-31 0             1                0
          2016-03-31 0             0                1
          2017-03-31 0             0                1
          2018-03-31 0             0                1

                       PercentRetiringTermLimit TermLimitRetireesPcodeList  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                        0                         []
          2010-03-31 0                        0                         []
          2011-03-31 0                        0                         []
          2012-03-31 0                        0                         []
          2013-03-31 0                      0.0                         []
...                                         ...                        ...
ZYLOG     2014-03-31 0                      0.0                         []
          2015-03-31 0                      0.0                         []
          2016-03-31 0                      0.0                         []
          2017-03-31 0                      0.0                         []
          2018-03-31 0                      0.0                         []

                       PercentBusyDir PercentFirstTermIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0              0                     0
          2010-03-31 0              0                     0
          2011-03-31 0              0                     0
          2012-03-31 0              0                     0
          2013-03-31 0       0.333333              0.333333
...                               ...                   ...
ZYLOG     2014-03-31 0            0.0                   0.5
          2015-03-31 0            0.0                   0.5
          2016-03-31 0            0.0              0.833333
          2017-03-31 0            0.0                   1.0
          2018-03-31 0            0.0                   1.0

                                             FirstYearIndepPCodeList  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                                            []
          2010-03-31 0                                            []
          2011-03-31 0                                            []
          2012-03-31 0                                            []
          2013-03-31 0                                            []
...                                                              ...
ZYLOG     2014-03-31 0                                   [P00062851]
          2015-03-31 0                                            []
          2016-03-31 0  [P00036956, P00075400, P00075399, P00075398]
          2017-03-31 0                        [P00081419, P00080494]
          2018-03-31 0                                            []

                                                           IndepPCodeList  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                                                 []
          2010-03-31 0                                                 []
          2011-03-31 0                                                 []
          2012-03-31 0                                                 []
          2013-03-31 0                  [P00027633, P00031581, P00027665]
...                                                                   ...
ZYLOG     2014-03-31 0                             [P00027508, P00062851]
          2015-03-31 0                             [P00027508, P00062851]
          2016-03-31 0  [P00036956, P00027508, P00075400, P00075399, P...
          2017-03-31 0  [P00036956, P00075400, P00081419, P00080494, P...
          2018-03-31 0  [P00036956, P00075400, P00081419, P00080494, P...

                                                  FirstYearPCodeList  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                                   [P00032270]
          2010-03-31 0                                   [P00031581]
          2011-03-31 0                                            []
          2012-03-31 0                                   [P00042601]
          2013-03-31 0                                            []
...                                                              ...
ZYLOG     2014-03-31 0                                   [P00062851]
          2015-03-31 0                                            []
          2016-03-31 0  [P00036956, P00075400, P00075399, P00075398]
          2017-03-31 0                        [P00081419, P00080494]
          2018-03-31 0                                            []

                                                                PCodeList  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0  [P00027633, P00027664, P00029006, P00027661, P...
          2010-03-31 0  [P00027633, P00027664, P00029006, P00027661, P...
          2011-03-31 0  [P00027633, P00027664, P00029006, P00027661, P...
          2012-03-31 0  [P00027633, P00042601, P00029006, P00027661, P...
          2013-03-31 0  [P00027633, P00042601, P00029006, P00027661, P...
...                                                                   ...
ZYLOG     2014-03-31 0       [P00027508, P00027524, P00062851, P00027523]
          2015-03-31 0                  [P00027508, P00027524, P00062851]
          2016-03-31 0  [P00036956, P00027508, P00075400, P00075399, P...
          2017-03-31 0  [P00036956, P00075400, P00081419, P00080494, P...
          2018-03-31 0  [P00036956, P00075400, P00081419, P00080494, P...

                        CountRetiringTermLimit  CountFirstTermIndep  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                     0.0                  0.0
          2010-03-31 0                     0.0                  0.0
          2011-03-31 0                     0.0                  0.0
          2012-03-31 0                     0.0                  0.0
          2013-03-31 0                     0.0                  1.0
...                                        ...                  ...
ZYLOG     2014-03-31 0                     0.0                  1.0
          2015-03-31 0                     0.0                  1.0
          2016-03-31 0                     0.0                  5.0
          2017-03-31 0                     0.0                  5.0
          2018-03-31 0                     0.0                  5.0

                        CountDirTurnOver_exits_retire  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                            2.0
          2010-03-31 0                            0.0
          2011-03-31 0                            3.0
          2012-03-31 0                            0.0
          2013-03-31 0                            0.0
...                                               ...
ZYLOG     2014-03-31 0                            1.0
          2015-03-31 0                            1.0
          2016-03-31 0                            3.0
          2017-03-31 0                            0.0
          2018-03-31 0                            5.0

                        PercentDirTurnOver_exits_retire  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                         0.181818
          2010-03-31 0                         0.000000
          2011-03-31 0                         0.300000
          2012-03-31 0                         0.000000
          2013-03-31 0                         0.000000
...                                                 ...
ZYLOG     2014-03-31 0                         0.250000
          2015-03-31 0                         0.333333
          2016-03-31 0                         0.500000
          2017-03-31 0                         0.000000
          2018-03-31 0                         1.000000

                        CountDirTurnOver_real_exits  \
Symbol    AsOnDate
20MICRONS 2009-03-31 0                          2.0

In [12]:
df51 = df50.reset_index(drop = False).sort_values( by = ['Symbol', 'AsOnDate'])

In [13]:
df51["AsOnDate"] = pd.to_datetime(df51["AsOnDate"], format = "%Y-%m-%d")
df51["AsOnYear"] = df51["AsOnDate"].dt.year

In [14]:
def TurnOverShift(frame):
    frame['CountDirTurnOver_exits_retire_shifted'] = frame['CountDirTurnOver_exits_retire'].shift(1, axis=0) 
    frame['PercentIndepDirTurnOver_exits_retire_shifted'] = frame['PercentIndepDirTurnOver_exits_retire'].shift(1, axis=0) 

    frame['CountDirTurnOver_real_exits_shifted'] = frame['CountDirTurnOver_real_exits'].shift(1, axis=0) 
    frame['PercentDirTurnOver_real_exits_shifted'] = frame['PercentDirTurnOver_real_exits'].shift(1, axis=0)
# ---------------------------------------------------------------------------------------
    frame['CountIndepDirTurnOver_exits_retire_shifted'] = frame['CountIndepDirTurnOver_exits_retire'].shift(1, axis=0) 
    frame['PercentIndepDirTurnOver_exits_retire_shifted'] = frame['PercentIndepDirTurnOver_exits_retire'].shift(1, axis=0) 

    frame['CountIndepDirTurnOver_real_exits_shifted'] = frame['CountIndepDirTurnOver_real_exits'].shift(1, axis=0) 
    frame['PercentIndepDirTurnOver_real_exits_shifted'] = frame['PercentIndepDirTurnOver_real_exits'].shift(1, axis=0)
    return frame

In [15]:
df52 = df51.groupby(['Symbol']).progress_apply(TurnOverShift)

100%|█████████████████████████████████████████████████████████████████████████████| 2777/2777 [00:07<00:00, 377.86it/s]

In [16]:
df52

                    Symbol   AsOnDate  level_2 TotDirCount LnBoardSize  \
Symbol
20MICRONS 0      20MICRONS 2009-03-31        0          11    2.397895
          1      20MICRONS 2010-03-31        0          10    2.302585
          2      20MICRONS 2011-03-31        0          10    2.302585
          3      20MICRONS 2012-03-31        0           8    2.079442
          4      20MICRONS 2013-03-31        0           8    2.079442
...                    ...        ...      ...         ...         ...
ZYLOG     28888      ZYLOG 2014-03-31        0           4    1.386294
          28889      ZYLOG 2015-03-31        0           3    1.098612
          28890      ZYLOG 2016-03-31        0           6    1.791759
          28891      ZYLOG 2017-03-31        0           5    1.609438
          28892      ZYLOG 2018-03-31        0           5    1.609438

                FemaleDirCount PercentWomenDir Women_dummy     AvgAge  \
Symbol
20MICRONS 0                  0             0.0           0  69.636364
          1                  0             0.0           0       68.6
          2                  0             0.0           0       68.6
          3                  0             0.0           0  69.142857
          4                  0             0.0           0  69.142857
...                        ...             ...         ...        ...
ZYLOG     28888              0             0.0           0       67.0
          28889              0             0.0           0       69.0
          28890              0             0.0           0       64.5
          28891              1             0.2           1  61.333333
          28892              1             0.2           1  61.333333

                CountRookie Rookie_dummy CountNonRookie CountIndep  \
Symbol
20MICRONS 0               4            0              7          0
          1               3            0              7          0
          2               2            0              8          0
          3               2            0              6          0
          4               1            0              7          3
...                     ...          ...            ...        ...
ZYLOG     28888           1            0              3          2
          28889           1            0              2          2
          28890           4            1              2          6
          28891           4            1              1          5
          28892           4            1              1          5

                PercentIndep CountNonIndep CountRookieIndep  \
Symbol
20MICRONS 0              0.0            11                0
          1              0.0            10                0
          2              0.0            10                0
          3              0.0             8                0
          4            0.375             5                0
...                      ...           ...              ...
ZYLOG     28888          0.5             2                1
          28889     0.666667             1                1
          28890          1.0             0                4
          28891          1.0             0                4
          28892          1.0             0                4

                CountRookieNonIndep CountNonRookieIndep  \
Symbol
20MICRONS 0                       4                   0
          1                       3                   0
          2                       2                   0
          3                       2                   0
          4                       1                   3
...                             ...                 ...
ZYLOG     28888                   0                   1
          28889                   0                   1
          28890                   0                   2
          28891                   0                   1
          28892                   0                   1

                CountNonRookieNonIndep CountPromoterDir CountBusyDir  \
Symbol
20MICRONS 0                          7                0            1
          1                          7                0            1
          2                          8                0            1
          3                          6                0            1
          4                          4                4            1
...                                ...              ...          ...
ZYLOG     28888                      2                1            0
          28889                      1                1            0
          28890                      0                0            0
          28891                      0                0            0
          28892                      0                0            0

                Busy_dummy  AsOnYear IsCeoMD HasChairman HasPromoterOnBoard  \
Symbol
20MICRONS 0              1      2009       0           0                  0
          1              1      2010       0           0                  0
          2              1      2011       0           0                  0
          3              1      2012       0           0                  0
          4              1      2013       1           1                  1
...                    ...       ...     ...         ...                ...
ZYLOG     28888          0      2014       1           1                  1
          28889          0      2015       1           0                  1
          28890          0      2016       0           0                  0
          28891          0      2017       0           0                  0
          28892          0      2018       0           0                  0

                IsDualityChairmanMD IsFamilyManaged IsFamilyChairman  \
Symbol
20MICRONS 0                       0               0                0
          1                       0               0                0
          2                       0               0                0
          3                       0               0                0
          4                       1               1                1
...                             ...             ...              ...
ZYLOG     28888                   1               1                0
          28889                   0               1                0
          28890                   0               0                0
          28891                   0               0                0
          28892                   0               0                0

                IsFamilyChairmanAndCEO CountFirstTermDir  \
Symbol
20MICRONS 0                          0                 5
          1                          0                 5
          2                          0                 5
          3                          0                 3
          4                          1                 2
...                                ...               ...
ZYLOG     28888                      0                 1
          28889                      0                 1
          28890                      0                 5
          28891                      0                 5
          28892                      0                 5

                CountTurnOverIndepDir HasIndepTurnOver AvgTenureInYearsALL  \
Symbol
20MICRONS 0                         2                1            6.646077
          1                         0                0             7.24137
          2                         3                1             8.24137
          3                         0                0            9.319863
          4                         0                0           10.319863
...                               ...              ...                 ...
ZYLOG     28888                     1                1           12.202055
          28889                     1                1           10.989041
          28890                     3                1            2.920091
          28891                     0                0            0.905753
          28892                     5                1            1.905753

                AvgTenureInYearsIndep PercentRookieIndep  \
Symbol
20MICRONS 0                       0.0                  0
          1                       0.0                  0
          2                       0.0                  0
          3                       0.0                  0
          4                       0.0                0.0
...                               ...                ...
ZYLOG     28888                  0.25                0.5
          28889                   1.0                0.5
          28890              0.833333           0.666667
          28891                   0.6                0.8
          28892                   1.6                0.8

                PercentNonRookieIndep PercentRookieNonIndep  \
Symbol
20MICRONS 0                       0.0              0.363636
          1                       0.0                   0.3
          2                       0.0                   0.2
          3                       0.0                  0.25
          4                     0.375                 0.125
...                               ...                   ...
ZYLOG     28888                  0.25                   0.0
          28889              0.333333                   0.0
          28890              0.333333                   0.0
          28891                   0.2                   0.0
          28892                   0.2                   0.0

                PercentNonRookieNonIndep PercentRookie PercentNonRookie  \
Symbol
20MICRONS 0                     0.636364      0.363636         0.636364
          1                          0.7           0.3              0.7
          2                          0.8           0.2              0.8
          3                         0.75          0.25             0.75
          4                          0.5         0.125            0.875
...                                  ...           ...              ...
ZYLOG     28888                      0.5          0.25             0.75
          28889                 0.333333      0.333333         0.666667
          28890                      0.0      0.666667         0.333333
          28891                      0.0           0.8              0.2
          28892                      0.0           0.8              0.2

                IsRookieBoard JustOneRookie TwoOrMoreRookies  \
Symbol
20MICRONS 0                 0             0                0
          1                 0             0                0
          2                 0             0                0
          3                 0             0                0
          4                 0             0                0
...                       ...           ...              ...
ZYLOG     28888             0             1                0
          28889             0             1                0
          28890             1             0                1
          28891             1             0                1
          28892             1             0                1

                PercentRetiringTermLimit TermLimitRetireesPcodeList  \
Symbol
20MICRONS 0                            0                         []
          1                            0                         []
          2                            0                         []
          3                            0                         []
          4                          0.0                         []
...                                  ...                        ...
ZYLOG     28888                      0.0                         []
          28889                      0.0                         []
          28890                      0.0                         []
          28891                      0.0                         []
          28892                      0.0                         []

                PercentBusyDir PercentFirstTermIndep  \
Symbol
20MICRONS 0                  0                     0
          1                  0                     0
          2                  0                     0
          3                  0                     0
          4           0.333333              0.333333
...                        ...                   ...
ZYLOG     28888            0.0                   0.5
          28889            0.0                   0.5
          28890            0.0              0.833333
          28891            0.0                   1.0
          28892            0.0                   1.0

                                      FirstYearIndepPCodeList  \
Symbol
20MICRONS 0                                                []
          1                                                []
          2                                                []
          3                                                []
          4                                                []
...                                                       ...
ZYLOG     28888                                   [P00062851]
          28889                                            []
          28890  [P00036956, P00075400, P00075399, P00075398]
          28891                        [P00081419, P00080494]
          28892                                            []

                                                    IndepPCodeList  \
Symbol
20MICRONS 0                                                     []
          1                                                     []
          2                                                     []
          3                                                     []
          4                      [P00027633, P00031581, P00027665]
...                                                            ...
ZYLOG     28888                             [P00027508, P00062851]
          28889                             [P00027508, P00062851]
          28890  [P00036956, P00027508, P00075400, P00075399, P...
          28891  [P00036956, P00075400, P00081419, P00080494, P...
          28892  [P00036956, P00075400, P00081419, P00080494, P...

                                           FirstYearPCodeList  \
Symbol
20MICRONS 0                                       [P00032270]
          1                                       [P00031581]
          2                                                []
          3                                       [P00042601]
          4                                                []
...                                                       ...
ZYLOG     28888                                   [P00062851]
          28889                                            []
          28890  [P00036956, P00075400, P00075399, P00075398]
          28891                        [P00081419, P00080494]
          28892                                            []

                                                         PCodeList  \
Symbol
20MICRONS 0      [P00027633, P00027664, P00029006, P00027661, P...
          1      [P00027633, P00027664, P00029006, P00027661, P...
          2      [P00027633, P00027664, P00029006, P00027661, P...
          3      [P00027633, P00042601, P00029006, P00027661, P...
          4      [P00027633, P00042601, P00029006, P00027661, P...
...                                                            ...
ZYLOG     28888       [P00027508, P00027524, P00062851, P00027523]
          28889                  [P00027508, P00027524, P00062851]
          28890  [P00036956, P00027508, P00075400, P00075399, P...
          28891  [P00036956, P00075400, P00081419, P00080494, P...
          28892  [P00036956, P00075400, P00081419, P00080494, P...

                 CountRetiringTermLimit  CountFirstTermIndep  \
Symbol
20MICRONS 0                         0.0                  0.0
          1                         0.0                  0.0
          2                         0.0                  0.0
          3                         0.0                  0.0
          4                         0.0                  1.0
...                                 ...                  ...
ZYLOG     28888                     0.0                  1.0
          28889                     0.0                  1.0
          28890                     0.0                  5.0
          28891                     0.0                  5.0
          28892                     0.0                  5.0

                 CountDirTurnOver_exits_retire  \
Symbol
20MICRONS 0                                2.0
          1                                0.0
          2                                3.0
          3                                0.0
          4                                0.0
...                                        ...
ZYLOG     28888                            1.0
          28889                            1.0
          28890                            3.0
          28891                            0.0
          28892                            5.0

                 PercentDirTurnOver_exits_retire  CountDirTurnOver_real_exits  \
Symbol
20MICRONS 0                             0.181818                          2.0
          1                             0.000000                          0.0
          2                             0.300000                          3.0
          3                             0.000000                          0.0
          4                             0.000000                          0.0
...                                          ...                          ...
ZYLOG     28888                         0.250000                          1.0
          28889                         0.333333                          1.0
          28890                         0.500000                          3.0
          28891                         0.000000                          0.0
          28892                         1.000000                          5.0

                 PercentDirTurnOver_real_exits  \
Symbol
20MICRONS 0                           0.181818
          1                           0.000000
          2                           0.300000
          3                           0.000000
          4                           0.000000
...                                        ...
ZYLOG     28888                       0.250000
          28889                       0.333333
          28890                       0.500000
          28891                       0.000000
          28892                       1.000000

                 CountIndepDirTurnOver_exits_retire  \
Symbol
20MICRONS 0                                     0.0
          1                                     0.0
          2                                     0.0
          3                                     0.0
          4                                     0.0
...                                             ...
ZYLOG     28888                                 0.0
          28889                                 0.0
          28890                                 3.0
          28891                                 0.0
          28892                                 5.0

                 PercentIndepDirTurnOver_exits_retire  \
Symbol
20MICRONS 0                                       0.0
          1                                       0.0
          2                                       0.0
          3                                       0.0
          4                                       0.0
...                                               ...
ZYLOG     28888                                   0.0
          28889                                   0.0
          28890                                   0.5
          28891                                   0.0
          28892                                   1.0

                 CountIndepDirTurnOver_real_exits  \

In [17]:
    #frame['CountIndepDirTurnOver_w_exits_shifted'] = np.where( frame['CountIndepDirTurnOver_w_exits_shifted'].isna(), 0, frame['CountIndepDirTurnOver_w_exits_shifted'])
    #frame['PercentIndepDirTurnOver_w_exits_shifted'] = np.where( frame['PercentIndepDirTurnOver_w_exits_shifted'].isna(), 0, frame['PercentIndepDirTurnOver_w_exits_shifted'])

    #frame['CountIndepDirTurnOver_wo_exits_shifted'] = np.where( frame['CountIndepDirTurnOver_wo_exits_shifted'].isna(), 0, frame['CountIndepDirTurnOver_wo_exits_shifted'])
    #frame['PercentIndepDirTurnOver_wo_exits_shifted'] = np.where( frame['PercentIndepDirTurnOver_wo_exits_shifted'].isna(), 0, frame['PercentIndepDirTurnOver_wo_exits_shifted'])

In [18]:
df53 = df52["Symbol"].drop_duplicates().reset_index(drop = True).to_frame().reset_index().rename( {"index":"Company Index"}, axis = 1)
df53

      Company Index      Symbol
0                 0   20MICRONS
1                 1  21STCENMGM
2                 2      360ONE
3                 3   3IINFOLTD
4                 4     3MINDIA
...             ...         ...
2772           2772       ZUARI
2773           2773    ZUARIIND
2774           2774   ZYDUSLIFE
2775           2775   ZYDUSWELL
2776           2776       ZYLOG

[2777 rows x 2 columns]

In [19]:
df54 = df53.merge(df52.reset_index(drop = True).drop(["level_2"], axis = 1), on = ["Symbol"])

In [20]:
df54

,Company Index,Symbol,AsOnDate,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted
0,0,20MICRONS,2009-03-31,11,2.397895,0,0.0,0,69.636364,4,0,7,0,0.0,11,0,4,0,7,0,1,1,2009,0,0,0,0,0,0,0,5,2,1,6.646077,0.0,0,0.0,0.363636,0.636364,0.363636,0.636364,0,0,0,0,[],0,0,[],[],[P00032270],"[P00027633, P00027664, P00029006, P00027661, P...",0.0,0.0,2.0,0.181818,2.0,0.181818,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,20MICRONS,2010-03-31,10,2.302585,0,0.0,0,68.6,3,0,7,0,0.0,10,0,3,0,7,0,1,1,2010,0,0,0,0,0,0,0,5,0,0,7.24137,0.0,0,0.0,0.3,0.7,0.3,0.7,0,0,0,0,[],0,0,[],[],[P00031581],"[P00027633, P00027664, P00029006, P00027661, P...",0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,2.0,0.000000,2.0,0.181818,0.0,0.0,0.000000
2,0,20MICRONS,2011-03-31,10,2.302585,0,0.0,0,68.6,2,0,8,0,0.0,10,0,2,0,8,0,1,1,2011,0,0,0,0,0,0,0,5,3,1,8.24137,0.0,0,0.0,0.2,0.8,0.2,0.8,0,0,0,0,[],0,0,[],[],[],"[P00027633, P00027664, P00029006, P00027661, P...",0.0,0.0,3.0,0.300000,3.0,0.300000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
3,0,20MICRONS,2012-03-31,8,2.079442,0,0.0,0,69.142857,2,0,6,0,0.0,8,0,2,0,6,0,1,1,2012,0,0,0,0,0,0,0,3,0,0,9.319863,0.0,0,0.0,0.25,0.75,0.25,0.75,0,0,0,0,[],0,0,[],[],[P00042601],"[P00027633, P00042601, P00029006, P00027661, P...",0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,3.0,0.000000,3.0,0.300000,0.0,0.0,0.000000
4,0,20MICRONS,2013-03-31,8,2.079442,0,0.0,0,69.142857,1,0,7,3,0.375,5,0,1,3,4,4,1,1,2013,1,1,1,1,1,1,1,2,0,0,10.319863,0.0,0.0,0.375,0.125,0.5,0.125,0.875,0,0,0,0.0,[],0.333333,0.333333,[],"[P00027633, P00031581, P00027665]",[],"[P00027633, P00042601, P00029006, P00027661, P...",0.0,1.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28888,2776,ZYLOG,2014-03-31,4,1.386294,0,0.0,0,67.0,1,0,3,2,0.5,2,1,0,1,2,1,0,0,2014,1,1,1,1,1,0,0,1,1,1,12.202055,0.25,0.5,0.25,0.0,0.5,0.25,0.75,0,1,0,0.0,[],0.0,0.5,[P00062851],"[P00027508, P00062851]",[P00062851],"[P00027508, P00027524, P00062851, P00027523]",0.0,1.0,1.0,0.250000,1.0,0.250000,0.0,0.0,0.0,0.0,2.0,0.666667,2.0,0.400000,2.0,2.0,0.666667
28889,2776,ZYLOG,2015-03-31,3,1.098612,0,0.0,0,69.0,1,0,2,2,0.666667,1,1,0,1,1,1,0,0,2015,1,0,1,0,1,0,0,1,1,1,10.989041,1.0,0.5,0.333333,0.0,0.333333,0.333333,0.666667,0,1,0,0.0,[],0.0,0.5,[],"[P00027508, P00062851]",[],"[P00027508, P00027524, P00062851]",0.0,1.0,1.0,0.333333,1.0,0.333333,0.0,0.0,0.0,0.0,1.0,0.000000,1.0,0.250000,0.0,0.0,0.000000
28890,2776,ZYLOG,2016-03-31,6,1.791759,0,0.0,0,64.5,4,1,2,6,1.0,0,4,0,2,0,0,0,0,2016,0,0,0,0,0,0,0,5,3,1,2.920091,0.833333,0.666667,0.333333,0.0,0.0,0.666667,0.333333,1,0,1,0.0,[],0.0,0.833333,"[P00036956, P00075400, P00075399, P00075398]","[P00036956, P00027508, P00075400, P00075399, P...","[P00036956, P00075400, P00075399, P00075398]","[P00036956, P00027508, P00075400, P00075399, P...",0.0,5.0,3.0,0.500000,3.0,0.500000,3.0,0.5,3.0,0.5,1.0,0.000000,1.0,0.333333,0.0,0.0,0.000000
28891,2776,ZYLOG,2017-03-31,5,1.609438,1,0.2,1,61.333333,4,1,1,5,1.0,0,4,0,1,0,0,0,0,2017,0,0,0,0,0,0,0,5,0,0,0.905753,0.6,0.8,0.2,0.0,0.0,0.8,0.2,1,0,1,0.0,[],0.0,1.0,"[P00081419, P00080494]","[P00036956, P00075400, P00081419, P00080494, P...","[P00081419, P00080494]","[P00036956, P00075400, P00081419, P00080494, P...",0.0,5.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,3.0,0.500000,3.0,0.500000,3.0,3.0,0.500000
28892,2776,ZYLOG,2018-03-31,5,1.609438,1,0.2,1,61.333333,4,1,1,5,1.0,0,4,0,1,0,0,0,0,2018,0,0,0,0,0,0,0,5,5,1,1.905753,1.6,0.8,0.2,0.0,0.0,0.8,0.2,1,0,1,0.0,[],0.0,1.0,[],"[P00036956, P00075400, P00081419, P00080494, P...",[],"[P00036956, P00075400, P00081419, P00080494, P...",0.0,5.0,5.0,1.000000,5.0,1.000000,5.0,1.0,5.0,1.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000

In [21]:
df52.to_csv('Main_Firm_No Loc_No Fin v160225.csv')

# TESTING

In [49]:
df54.loc[ df54["TotDirCount"] >= 20]

,Company Index,Symbol,AsOnDate,TotDirCount,LnBoardSize,FemaleDirCount,PercentWomenDir,Women_dummy,AvgAge,CountRookie,Rookie_dummy,CountNonRookie,CountIndep,PercentIndep,CountNonIndep,CountRookieIndep,CountRookieNonIndep,CountNonRookieIndep,CountNonRookieNonIndep,CountPromoterDir,CountBusyDir,Busy_dummy,AsOnYear,IsCeoMD,HasChairman,HasPromoterOnBoard,IsDualityChairmanMD,IsFamilyManaged,IsFamilyChairman,IsFamilyChairmanAndCEO,CountFirstTermDir,CountTurnOverIndepDir,HasIndepTurnOver,AvgTenureInYearsALL,AvgTenureInYearsIndep,PercentRookieIndep,PercentNonRookieIndep,PercentRookieNonIndep,PercentNonRookieNonIndep,PercentRookie,PercentNonRookie,IsRookieBoard,JustOneRookie,TwoOrMoreRookies,PercentRetiringTermLimit,TermLimitRetireesPcodeList,PercentBusyDir,PercentFirstTermIndep,FirstYearIndepPCodeList,IndepPCodeList,FirstYearPCodeList,PCodeList,CountRetiringTermLimit,CountFirstTermIndep,CountDirTurnOver_exits_retire,PercentDirTurnOver_exits_retire,CountDirTurnOver_real_exits,PercentDirTurnOver_real_exits,CountIndepDirTurnOver_exits_retire,PercentIndepDirTurnOver_exits_retire,CountIndepDirTurnOver_real_exits,PercentIndepDirTurnOver_real_exits,CountDirTurnOver_exits_retire_shifted,PercentIndepDirTurnOver_exits_retire_shifted,CountDirTurnOver_real_exits_shifted,PercentDirTurnOver_real_exits_shifted,CountIndepDirTurnOver_exits_retire_shifted,CountIndepDirTurnOver_real_exits_shifted,PercentIndepDirTurnOver_real_exits_shifted
12353,1163,JAGRAN,2009-03-31,20,2.995732,0,0.0,0,69.1,6,0,14,0,0.0,20,0,6,0,14,0,1,1,2009,0,0,0,0,0,0,0,15,2,1,7.373973,0.0,0,0.0,0.3,0.7,0.3,0.7,0,0,0,0,[],0,0,[],[],"[P00022410, P00028327, P00027485, P00027484, P...","[P00011376, P00018449, P00002481, P00022410, P...",0.0,0.0,2.0,0.100000,2.0,0.100000,0.0,0.000000,0.0,0.000000,1.0,0.000000,1.0,0.066667,0.0,0.0,0.0
13049,1217,JPASSOCIAT,2007-03-31,20,2.995732,0,0.0,0,74.705882,11,0,9,0,0.0,20,0,11,0,9,0,3,1,2007,0,0,0,0,0,0,0,17,5,1,3.259863,0.0,0,0.0,0.55,0.45,0.55,0.45,0,0,0,0,[],0,0,[],[],"[P00004059, P00036306, P00042430, P00028847, P...","[P00007595, P00011266, P00017909, P00004059, P...",0.0,0.0,5.0,0.250000,4.0,0.200000,0.0,0.000000,0.0,0.000000,3.0,0.000000,3.0,0.166667,0.0,0.0,0.0
13053,1217,JPASSOCIAT,2011-03-31,21,3.044522,0,0.0,0,74.857143,4,0,17,0,0.0,21,0,4,0,17,0,8,1,2011,0,0,0,0,0,0,0,11,1,1,5.430659,0.0,0,0.0,0.190476,0.809524,0.190476,0.809524,0,0,0,0,[],0,0,[],[],"[P00041534, P00042500, P00008762]","[P00007595, P00001483, P00004059, P00026200, P...",0.0,0.0,1.0,0.047619,1.0,0.047619,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
13054,1217,JPASSOCIAT,2012-03-31,21,3.044522,1,0.047619,1,74.571429,3,0,18,0,0.0,21,0,3,0,18,0,9,1,2012,0,0,0,0,0,0,0,9,2,1,6.345727,0.0,0,0.0,0.142857,0.857143,0.142857,0.857143,0,0,0,0,[],0,0,[],[],[P00036580],"[P00007595, P00036580, P00001483, P00026200, P...",0.0,0.0,2.0,0.095238,2.0,0.095238,0.0,0.000000,0.0,0.000000,1.0,0.000000,1.0,0.047619,0.0,0.0,0.0
13093,1220,JPPOWER,2009-03-31,20,2.995732,0,0.0,0,80.55,5,0,15,0,0.0,20,0,5,0,15,0,4,1,2009,0,0,0,0,0,0,0,10,3,1,6.342055,0.0,0,0.0,0.25,0.75,0.25,0.75,0,0,0,0,[],0,0,[],[],"[P00004384, P00040936]","[P00011266, P00008371, P00024662, P00020142, P...",0.0,0.0,3.0,0.150000,3.0,0.150000,0.0,0.000000,0.0,0.000000,1.0,0.000000,1.0,0.052632,0.0,0.0,0.0
13094,1220,JPPOWER,2010-03-31,21,3.044522,0,0.0,0,78.857143,5,0,16,0,0.0,21,0,5,0,16,0,4,1,2010,0,0,0,0,0,0,0,9,2,1,5.451794,0.0,0,0.0,0.238095,0.761905,0.238095,0.761905,0,0,0,0,[],0,0,[],[],"[P00007595, P00026200, P00040929, P00020169]","[P00024662, P00007595, P00008371, P00026200, P...",0.0,0.0,2.0,0.095238,2.0,0.095238,0.0,0.000000,0.0,0.000000,3.0,0.000000,3.0,0.150000,0.0,0.0,0.0
13095,1220,JPPOWER,2011-03-31,20,2.995732,0,0.0,0,76.8,4,0,16,0,0.0,20,0,4,0,16,0,8,1,2011,0,0,0,0,0,0,0,10,4,1,5.629315,0.0,0,0.0,0.2,0.8,0.2,0.8,0,0,0,0,[],0,0,[],[],[P00040932],"[P00024662, P00007595, P00008371, P00026200, P...",0.0,0.0,4.0,0.200000,4.0,0.200000,0.0,0.000000,0.0,0.000000,2.0,0.000000,2.0,0.095238,0.0,0.0,0.0
13096,1220,JPPOWER,2012-03-31,20,2.995732,0,0.0,0,75.15,6,0,14,0,0.0,20,0,6,0,14,0,7,1,2012,0,0,0,0,0,0,0,12,0,0,4.662329,0.0,0,0.0,0.3,0.7,0.3,0.7,0,0,0,0,[],0,0,[],[],"[P00041898, P00040933, P00040930, P00041534]","[P00024662, P00007595, P00008371, P00026200, P...",0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,4.0,0.000000,4.0,0.200000,0.0,0.0,0.0
13097,1220,JPPOWER,2013-03-31,20,2.995732,0,0.0,0,75.15,5,1,15,11,0.55,9,2,3,9,6,3,7,1,2013,1,1,1,0,1,1,0,10,1,1,5.662329,0.0,0.181818,0.45,0.15,0.3,0.25,0.75,0,0,1,0.0,[],0.636364,0.545455,[],"[P00024662, P00007595, P00008371, P00026200, P...",[],"[P00024662, P00007595, P00008371, P00026200, P...",0.0,6.0,1.0,0.050000,1.0,0.050000,1.0,0.090909,1.0,0.090909,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
13100,1220,JPPOWER,2016-03-31,20,2.995732,1,0.05,1,74.166667,6,1,14,10,0.5,10,4,2,6,8,1,5,1,2016,1,1,1,0,0,0,0,10,1,1,5.817397,1.05,0.4,0.3,0.1,0.4,0.3,0.7,0,0,1,0.0,[],0.5,0.6,[P00036253],"[P00020811, P00024662, P00026200, P00036253, P...",[P00036253],"[P00020811, P00024662, P00026200, P00020142, P...",0.0,6.0,1.0,0.050000,1.0,0.050000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
13101,1220,JPPOWER,2017-03-31,20,2.995732,1,0.05,1,74.0,7,1,13,10,0.5,10,4,3,6,7,0,6,1,2017,1,1,0,0,0,0,0,8,4,1,6.207123,1.45,0.4,0.3,0.15,0.35,0.35,0.65,0,0,1,0.0,[],0.6,0.5,[],"[P00020811, P00024662, P00026200, P00036253, P...",[P00080649],"[P00020811, P00024662, P00026200, P00020142, P...",0.0,5.0,4.0,0.200000,4.0,0.200000,2.0,0.200000,2.0,0.200000,1.0,0.000000,1.0,0.050000,0.0,0.0,0.0
15038,1418,LT,2016-03-31,20,2.995732,2,0.1,1,70.95,8,1,12,10,0.5,10,4,4,6,6,0,8,1,2016,1,1,0,0,0,0,0,16,2,1,4.269589,0.85,0.4,0.3,0.2,0.3,0.4,0.6,0,0,1,0.0,[],0.8,0.7,"[P00047177, P00025663]","[P00004462, P00009909, P00047177, P00049539, P...","[P00047177, P00073122, P00076184, P00074020, P...","[P00004462, P00009909, P00047177, P00049539, P...",0.0,7.0,2.0,0.100000,2.0,0.100000,1.0,0.100000,1.0,0.100000,3.0,0.000000,2.0,0.133333,0.0,0.0,0.0
15039,1418,LT,2017-03-31,20,2.995732,2,0.1,1,71.6,6,1,14,11,0.55,9,3,3,8,6,0,10,1,2017,1,1,0,0,0,0,0,13,0,0,5.148356,1.25,0.272727,0.4,0.15,0.3,0.3,0.7,0,0,1,0.0,[],0.909091,0.727273,"[P00000163, P00008189]","[P00004462, P00009909, P00027207, P00047177, P...","[P00000163, P00008189]","[P00004462, P00009909, P00027207, P00047177, P...",0.0,8.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,2.0,0.100000,2.0,0.100000,1.0,1.0,0.1
15040,1418,LT,2018-03-31,22,3.091042,2,0.090909,1,70.727273,8,1,14,11,0.5,11,2,6,9,5,0,10,1,2018,1,1,0,0,0,0,0,12,1,1,5.65741,1.636364,0.181818,0.409091,0.272727,0.227273,0.363636,0.636364,0,0,1,0.0,[],0.909091,0.545455,[],"[P00004462, P00009909, P00027207, P00047177, P...","[P00078214, P00082794]","[P00004462, P00009909, P00027207, P00047177, P...",0.0,6.0,1.0,0.045455,1.0,0.045455,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
15041,1418,LT,2019-03-31,22,3.091042,2,0.090909,1,70.5,3,0,19,11,0.5,11,0,3,11,8,0,11,1,2019,1,1,0,0,0,0,0,13,2,1,6.409714,2.045455,0.0,0.5,0.136364,0.363636,0.136364,0.863636,0,0,0,0.090909,[P00025894],1.0,0.545455,[],"[P00004462, P00009909, P00027207, P00047177, P...",[P00035293],"[P00004462, P00009909, P00027207, P00047177, P...",1.0,6.0,2.0,0.090909,1.0,0.045455,1.0,0.090909,0.0,0.000000,1.0,0.000000,1.0,0.045455,0.0,0.0,0.0
15042,1418,LT,2020-03-31,20,2.995732,2,0.1,1,71.25,2,0,18,10,0.5,10,0,2,10,8,0,12,1,2020,1,1,0,0,0,0,0,9,4,1,7.735479,2.55,0.0,0.5,0.1,0.4,0.1,0.9,0,0,0,0.2,"[P00047177, P00025663]",1.2,0.4,[],"[P00004462, P00009909, P00027207, P00047177, P...",[],"[P00004462, P00009909, P00027207, P00047177, P...",2.0,4.0,4.0,0.200000,2.0,0.100000,3.0,0.300000,1.0,0.100000,2.0,0.090909,1.0,0.045455,1.0,0.0,0.0
16731,1589,MRF,2024-03-31,20,2.995732,3,0.15,1,62.058824,6,1,14,13,0.65,7,6,0,7,7,6,1,1,2024,1,1,1,1,1,0,0,6,20,1,12.709041,3.5,0.461538,0.35,0.0,0.35,0.3,0.7,0,0,1,0.0,[],0.076923,0.461538,"[P00111757, P00111758, P00111755]","[P00110652, P00000166, P00091389, P00111757, P...","[P00111757, P00111758, P00111755]","[P00110652, P00000166, P00091389, P00111757, P...",0.0,6.0,20.0,1.000000,19.0,0.950000,13.0,1.000000,13.0,1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
21874,2087,SAIL,2007-03-31,20,2.995732,0,0.0,0,76.9375,18,0,2,0,0.0,20,0,18,0,2,0,1,1,2007,0,0,0,0,0,0,0,20,4,1,1.102603,0.0,0,0.0,0.9,0.1,0.9,0.1,0,0,0,0,[],0,0,[],[],"[P00018702, P00001975, P00024730, P00024738, P...","[P00018702, P00001975, P00024730, P00022473, P...",0.0,0.0,4.0,0.200000,4.0,0.200000,0.0,0.000000,0.0,0.000000,3.0,0.000000,3.0,0.272727,0.0,0.0,0.0
21875,2087,SAIL,2008-03-31,20,2.995732,0,0.0,0,75.9375,18,0,2,0,0.0,20,0,18,0,2,0,2,1,2008,0,0,0,0,0,0,0,20,5,1,1.639726,0.0,0,0.0,0.9,0.1,0.9,0.1,0,0,0,0,[],0,0,[],[],"[P00025989, P00024734, P00025991, P00025990]","[P00025989, P00018702, P00001975, P00024734, P...",0.0,0.0,5.0,0.250000,5.0,0.250000,0.0,0.000000,0.0,0.000000,4.0,0.000000,4.0,0.200000,0.0,0.0,0.0

In [50]:
test1["NAME"] = np.where( pd.isnull(test1["Director First Name"]), "", test1["Director First Name"])\
                + np.where( pd.isnull(test1["Director Middle Name"]), "", test1["Director Middle Name"])\
                + np.where( pd.isnull(test1["Director Surname"]), "", test1["Director Surname"])

In [51]:
test1

,AsOnDate,Person Code,Director First Name,Director Middle Name,Director Surname,NAME
160782,2020-03-31,P00097813,VIJOY,KUMAR,SINGH,VIJOYKUMARSINGH
164743,2020-03-31,P00042765,ANIL,KUMAR,CHAUDHARY,ANILKUMARCHAUDHARY
164744,2020-03-31,P00084451,KARTAR,SINGH,CHAUHAN,KARTARSINGHCHAUHAN
164745,2020-03-31,P00097133,ANIRBAN,NaN,DASGUPTA,ANIRBANDASGUPTA
164746,2020-03-31,P00037850,KRISHAN,KUMAR,GUPTA,KRISHANKUMARGUPTA
164747,2020-03-31,P00092849,VIVEK,NaN,GUPTA,VIVEKGUPTA
164748,2020-03-31,P00088056,PUNEET,NaN,KANSAL,PUNEETKANSAL
164749,2020-03-31,P00063145,SOMA,NaN,MONDAL,SOMAMONDAL
164750,2020-03-31,P00089443,HARINAND,NaN,RAI,HARINANDRAI
164751,2020-03-31,P00096093,AMIT,NaN,SEN,AMITSEN
164752,2020-03-31,P00096206,NIDGURTI,NaN,SHANKARAPPA,NIDGURTISHANKARAPPA
164753,2020-03-31,P00086991,ATUL,NaN,SRIVASTAVA,ATULSRIVASTAVA
164754,2020-03-31,P00084452,NARENDRA,KUMAR,TANEJA,NARENDRAKUMARTANEJA

In [52]:
test1["NAME"].nunique()

13

In [27]:
dff1 = pd.read_csv("Firm level data_locationRavi_21226_final(in).csv")

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_7180\3956496350.py:1: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  dff1 = pd.read_csv("Firm level data_locationRavi_21226_final(in).csv")

In [28]:
dff2 = pd.read_csv("Dirlevel_with CAR and briefs_from 2013_81917.csv")

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_7180\2399263687.py:1: DtypeWarning: Columns (28,32,42,53,54,55,56,57,58,115,116,117,118,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232) have mixed types. Specify dtype option on import or set low_memory=False.
  dff2 = pd.read_csv("Dirlevel_with CAR and briefs_from 2013_81917.csv")

In [29]:
test1 = df1.loc[ (df1["Symbol"] == "SAIL") & (df1["AsOnDate"] == "2020-03-31"), ["AsOnDate", "Person Code", "Director First Name", "Director Middle Name", "Director Surname"] ]
test1

,AsOnDate,Person Code,Director First Name,Director Middle Name,Director Surname
160782,2020-03-31,P00097813,VIJOY,KUMAR,SINGH
164743,2020-03-31,P00042765,ANIL,KUMAR,CHAUDHARY
164744,2020-03-31,P00084451,KARTAR,SINGH,CHAUHAN
164745,2020-03-31,P00097133,ANIRBAN,NaN,DASGUPTA
164746,2020-03-31,P00037850,KRISHAN,KUMAR,GUPTA
164747,2020-03-31,P00092849,VIVEK,NaN,GUPTA
164748,2020-03-31,P00088056,PUNEET,NaN,KANSAL
164749,2020-03-31,P00063145,SOMA,NaN,MONDAL
164750,2020-03-31,P00089443,HARINAND,NaN,RAI
164751,2020-03-31,P00096093,AMIT,NaN,SEN
164752,2020-03-31,P00096206,NIDGURTI,NaN,SHANKARAPPA
164753,2020-03-31,P00086991,ATUL,NaN,SRIVASTAVA
164754,2020-03-31,P00084452,NARENDRA,KUMAR,TANEJA

In [30]:
test2 = dff2.loc[ (dff2["Symbol"] == "SAIL") & (dff2["AsOnDate"] == "31-03-2020"), ["AsOnDate", "Person Code", "Director First Name", "Director Middle Name", "Director Surname"] ]
test2

,AsOnDate,Person Code,Director First Name,Director Middle Name,Director Surname
45760,31-03-2020,P00044441,ANIL,KUMAR,CHAUDHARY
61392,31-03-2020,P00051832,SOMA,NaN,MONDAL
62042,31-03-2020,P00059485,KARTAR,SINGH,CHAUHAN
62043,31-03-2020,P00060203,NARENDRA,KUMAR,TANEJA
62483,31-03-2020,P00060310,ATUL,NaN,SRIVASTAVA
62615,31-03-2020,P00055318,PUNEET,NaN,KANSAL
62904,31-03-2020,P00061774,HARINAND,NaN,RAI
63289,31-03-2020,P00045512,KRISHAN,KUMAR,GUPTA
63541,31-03-2020,P00062659,VIVEK,NaN,GUPTA
64499,31-03-2020,P00063819,NIDGURTI,NaN,SHANKARAPPA
64734,31-03-2020,P00051744,ANIRBAN,NaN,DASGUPTA

In [31]:
dff3 = pd.read_excel("Indian Boards Data as on 31-Mar-2020.xlsx", skiprows = 1)
dff3

,Symbol,Company,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Tenure Valid till,Member of Civil Services,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Occupation,Cessation Date,Cessation Reason,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Brief Profile
0,20MICRONS,20 MICRONS LTD.,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,09-DEC-1955,M,NaN,29-APR-2005,NaN,NaN,NO,"NOMINEE DIRECTOR, EXECUTIVE DIRECTOR",NO,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02-MAR-2009,NOMINATION ENDED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO..."
1,20MICRONS,20 MICRONS LTD.,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,08-DEC-1950,M,INDIA,13-OCT-2007,12-AUG-2024,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",INDUSTRIALIST,NaN,NaN,20 MICRONS LTD.,BANCO PRODUCTS (INDIA) LTD.,MUNJAL AUTO INDUSTRIES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...
2,20MICRONS,20 MICRONS LTD.,P00027664,MR.,MIHIR,ARVIND,JOSHI,12-JUN-1977,M,NaN,23-AUG-2007,NaN,NaN,NO,NOMINEE DIRECTOR OF GUJARAT VENTURA FINANCE LT...,NO,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22-OCT-2011,RESIGNED (NO REASON STATED),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D..."
3,20MICRONS,20 MICRONS LTD.,P00064917,MS.,DARSHA,RAJESH,KIKANI,01-SEP-1957,F,INDIA,06-AUG-2014,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,"GRADUATE: FELLOW-MEMBER,INSTITUTE OF COMPANY S...",GRADUATE: LL.B.,"POST GRADUATE: COMPANY SECRETARY,INSTITUTE OF ...","POST GRADUATE: M.B.A.,GUJARAT UNIVERSITY,AHMED...","POST GRADUATE: MEMBER,INSTITUTE OF CHARTERED S...","POST GRADUATE: P.G.PROGRAM-EXECUTIVE,INDIAN IN...",NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,04-MAY-2017,RESIGNED (DUE TO PRE-OCCUPATION),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MRS. DARSHA R. KIKANI, THE INDEPENDENT DIRECTO..."
4,20MICRONS,20 MICRONS LTD.,P00042601,MR.,NARESH,S.,MAKHIJA,NaN,M,NaN,29-APR-2011,NaN,NaN,NO,"NOMINEE DIRECTOR OF IDBI BANK LTD., NON-EXECUT...",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05-FEB-2015,NOMINATION ENDED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31429,ZYDUSWELL,ZYDUS WELLNESS LTD.,P00013236,MR.,PANKAJ,RAMAN,PATEL,16-MAR-1953,M,INDIA,27-APR-2009,NaN,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,"GRADUATE: B.E.,UNIVERSITY OF MUMBAI,MUMBAI","GRADUATE: LL.B.,UNIVERSITY OF MUMBAI,MUMBAI","POST GRADUATE: MASTERS-PHARMACEUTICAL SCIENCE,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,COMMODITIES,CORPORATE ...","PRESIDENT, FEDERATION OF INDIAN CHAMBERS OF CO...",14-JUL-2014,RETIRED/SUPERANNUATED/TERM EXPIRED,TORRENT POWER LTD.,ZYDUS LIFESCIENCES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MR. PANKAJ PATEL SPEARHEADS ZYDUS CADILA, ONE ..."
31430,ZYDUSWELL,ZYDUS WELLNESS LTD.,P00013240,DR.(MR.),SHARVIL,PANKAJ,PATEL,13-OCT-1978,M,INDIA,27-APR-2009,NaN,NONE,YES,"CHAIRPERSON, NON-EXECUTIVE DIRECTOR, PROMOTER-...",NO,GRADUATE: GRADUATE-CHEMICAL & PHARMACEUTICAL S...,"DOCTORATE: PH.D.-BREAST CANCER,UNIVERSITY OF S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE SOCIAL RESPONSIBILITY,FAST MOVING CO...","JT.MANAGING DIRECTOR, ZYDUS LIFESCIENCES LTD.",NaN,NaN,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DR. SHARVIL P. PATEL IS THE MANAGING DIRECTOR ...
31431,ZYDUSWELL,ZYDUS WELLNESS LTD.,P00005675,MR.,SHEKHAR,GOVIND,PATEL,09-AUG-1971,M,INDIA,25-MAR-2003,NaN,NONE,NO,NaN,NaN,"POST GRADUATE: P.G.DIPLOMA-CIVIL,BHARTIYA VIDH...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CONSUMER DISCRETIONARY,CORPORATE GOVERNANCE,CO...","MANAGING DIRECTOR, GANESH HOUSING CORP.LTD.",27-JUL-2006,NaN,GANESH HOUSING CORP.LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RICH AND VARIED EXPERIENCE OF MORE THAN 12 YEA...
31432,ZYDUSWELL,ZYDUS WELLNESS LTD.,P00053258,MS.,DHARMISHTA,NARENDRAPRASAD,RAVAL,12-JAN-1956,F,INDIA,11-MAR-2019,10-MAR-2029,NONE,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.SC.,GRADUATE: LL.B.,POST GRADUATE: LL.M.,POST GRADUATE: MASTERS-LEGISLATIVE LAW,NaN,NaN,NaN,NaN,NaN,NaN,"COMMODITIES,CORPORATE GOVERNANCE,DIVERSITY,FAS...","SECRETARY, INDIAN LAW INSTITUTE OF GUJARAT STA...",NaN,NaN,NOCIL LTD.,TORRENT POWER LTD.,ZYDUS LIFESCIENCES LTD.,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MS. DHARMISHTABEN N. RAVAL, AN EMINENT LAWYER ..."
31433,ZYDUSWELL,ZYDUS WELLNESS LTD.,P00090966,MR.,SAVYASACHI,SANTOSH,SENGUPTA,16-OCT-1952,M,NaN,02-NOV-2018,NaN,NaN,NO,NON-EXECUTIVE DIRECTOR,YES,GRADUATE: B.SC.-STATISTICS,"POST GRADUATE: P.G.DIPLOMA-MANAGEMENT,INDIAN I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FAST MOVING CONSUMER GOODS,LEADERSHIP/MANAGEME...",MANAGEMENT CONSULTANT,NaN,NaN,ZYDUS WELLNESS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MR. SAVYASACHI SENGUPTA, AGED ABOUT 66 YEARS I..."

In [32]:
test2 = dff3.loc[ (dff3["Symbol"] == "SAIL"), ["Person Code", "Director First Name", "Director Middle Name", "Director Surname"] ]
test2

      Person Code Director First Name Director Middle Name Director Surname
26550   P00021232               VIJAI                KUMAR          AGARWAL
26551   P00022736               ISHER                JUDGE        AHLUWALIA
26552   P00024734               SHOEB                 SYED            AHMED
26553   P00024730              JAVAID                  NaN           AKHTAR
26554   P00022473                VELU                  NaN        ANNAMALAI
...           ...                 ...                  ...              ...
26636   P00084452            NARENDRA                KUMAR           TANEJA
26637   P00022144               VINOD                KUMAR          THAKRAL
26638   P00075301               ANSHU                  NaN            VAISH
26639   P00018278             CHANDRA              SHEKHAR            VERMA
26640   P00075817              GANESH                  NaN      VISHWAKARMA

[91 rows x 4 columns]

In [33]:
#Firm Dir City

In [34]:
#dfl1 = pd.read_excel('Prowess IQ - Location Data.xlsx', skiprows = 5)

In [35]:
#dfl1.drop( ["Head Office", "Registered Office", "Registrar Address"], axis = 1)

In [36]:
#dfl2 = dfl1.dropna()
#dfl2.loc[:, 'Company Name'] = dfl2['Company Name'].str.upper()
#dfl2 = dfl2.rename({'Company Name': 'Company'}, axis = 1)
#dfl2

In [37]:
#dfl3 = df31.loc[:, ['Company', 'Symbol']].drop_duplicates().reset_index(drop = True)
#dfl3

In [38]:
#dfl4 = dfl2.merge(dfl3, on = 'Company').drop(['Company'], axis = 1)
#dfl4

In [39]:
#df53 = df52.copy()
#df54 = df53.reset_index(drop = True)
#df55 = df54.drop(['level_2'], axis = 1)
#df55

In [40]:
#df60 = df55.merge(dfl4, on = 'Symbol', how = 'outer')

In [41]:
#df60

In [42]:
#df61 = df60.loc[:, ['City', 'AsOnDate', 'Symbol', 'FirstYearIndepPCodeList', 'IndepPCodeList']]

In [43]:
# '''
# df61['CountOtherFirstYearIndepPCode'] = 0
# df61['CountTotalIndepPCode'] = 0
# df61['FirstYearDirCityIndep'] = 0

# df61['CountOtherFirstYearPCode'] = 0
# df61['CountTotalPCode'] = 0
# df61['FirstYearDirCity'] = 0

# df61['CountOtherFirstYearPCodeIndepExcl'] = 0
# df61['CountTotalPCodeIndepExcl'] = 0
# df61['FirstYearDirCityIndepExcl'] = 0

# df61['CountOtherFirstYearPCodeExcl'] = 0
# df61['CountTotalPCodeExcl'] = 0
# df61['FirstYearDirCityExcl'] = 0
# '''

In [44]:
# '''
# def FirDirCity(frame):
#     for Symbol in frame['Symbol']:
#         # P Code list First year and Total INDEP directors of CURR company in the same city
#         pcodecompfirstindep = set(frame.loc[ frame['Symbol'] == Symbol]['FirstYearIndepPCodeList'].explode())
#         pcodecomptotindep = set(frame.loc[ frame['Symbol'] == Symbol]['IndepPCodeList'].explode())

#         # P Code list First year and Total directors of CURR company
#         pcodecompfirst = set(frame.loc[ frame['Symbol'] == Symbol]['FirstYearPCodeList'].explode())
#         pcodecomptot = set(frame.loc[ frame['Symbol'] == Symbol]['PCodeList'].explode())

#         # P Code list First Year and total INDEP directors of OTHER companies
#         pcodeotherfirstindep = frame.loc[ frame['Symbol'] != Symbol]['FirstYearIndepPCodeList'].explode().nunique()
#         pcodeothertotindep = frame.loc[ frame['Symbol'] != Symbol]['IndepPCodeList'].explode().nunique()

#         # P Code list First Year and total directors of OTHER companies
#         pcodeotherfirst = frame.loc[ frame['Symbol'] != Symbol]['FirstYearPCodeList'].explode().nunique()
#         pcodeothertot = frame.loc[ frame['Symbol'] != Symbol]['PCodeList'].explode().nunique()
        
#         # P Code list First Year and total INDEP directors of OTHER companies excluding CURR company
#         pcodeotherfirstindepexcl = sum(1 for x in set(frame.loc[ frame['Symbol'] != Symbol]['FirstYearIndepPCodeList'].explode()) if x not in pcodecompfirstindep)
        
#         pcodeothertotindepexcl = sum(1 for x in set(frame.loc[ frame['Symbol'] != Symbol]['IndepPCodeList'].explode()) if x not in pcodecomptotindep)
        
#         # P Code list First Year and total directors of OTHER companies excluding CURR company
#         pcodeotherfirstexcl = sum(1 for x in set(frame.loc[ frame['Symbol'] != Symbol]['FirstYearPCodeList'].explode()) if x not in pcodecompfirst)
#         pcodeothertotexcl = sum(1 for x in set(frame.loc[ frame['Symbol'] != Symbol]['PCodeList'].explode()) if x not in pcodecomptot)
        
#         frame.loc[ frame['Symbol'] == Symbol, 'CountOtherFirstYearIndepPCode'] = pcodeotherfirstindep
#         frame.loc[ frame['Symbol'] == Symbol, 'CountTotalIndepPCode'] = pcodeothertotindep
#         frame.loc[ frame['Symbol'] == Symbol, 'FirstYearDirCityIndep'] = pcodeotherfirstindep / pcodeothertotindep if pcodeothertotindep>0 else 0

#         frame.loc[ frame['Symbol'] == Symbol, 'CountOtherFirstYearPCode'] = pcodeotherfirst
#         frame.loc[ frame['Symbol'] == Symbol, 'CountTotalPCode'] = pcodeothertot
#         frame.loc[ frame['Symbol'] == Symbol, 'FirstYearDirCity'] = pcodeotherfirst / pcodeothertot if pcodeothertot>0 else 0

#         frame.loc[ frame['Symbol'] == Symbol, 'CountOtherFirstYearPCodeIndepExcl'] = pcodeotherfirstindepexcl
#         frame.loc[ frame['Symbol'] == Symbol, 'CountTotalPCodeIndepExcl'] = pcodeothertotindepexcl
#         frame.loc[ frame['Symbol'] == Symbol, 'FirstYearDirCityIndepExcl'] = pcodeotherfirstindepexcl / pcodeothertotindepexcl if pcodeothertotindepexcl>0 else 0
        
#         frame.loc[ frame['Symbol'] == Symbol, 'CountOtherFirstYearPCodeExcl'] = pcodeotherfirstexcl
#         frame.loc[ frame['Symbol'] == Symbol, 'CountTotalPCodeExcl'] = pcodeothertotexcl
#         frame.loc[ frame['Symbol'] == Symbol, 'FirstYearDirCityExcl'] = pcodeotherfirstexcl / pcodeothertotexcl if pcodeothertotexcl>0 else 0

#     return frame
# '''

In [45]:
# df70 = df60.groupby(['City', 'AsOnDate']).progress_apply(FirDirCity)

In [46]:
# df70

In [47]:
# df70.to_csv('Main_Firm_Loc ONLY_No Fin v280824.1.csv')