In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from tqdm import tqdm
tqdm.pandas()
from dateutil.relativedelta import relativedelta
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_excel("Main.xlsx")

In [3]:
df['Cessation Reason'] = df['Cessation Reason'].astype(str)

In [4]:
df

,Unnamed: 0,Symbol,AsOnDate,Company,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till
0,0,AEGISCHEM,2006-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,AEGISCHEM,2007-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,AEGISCHEM,2008-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,AEGISCHEM,2009-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,AEGISCHEM,2010-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446429,HIGHWAYS,2023-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,446430,HIGHWAYS,2024-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,446431,MAXESTATES,2024-03-31,MAX ESTATES LTD.,P00118252,MS.,JILIAN,L.,MOOYOUNG,NaT,F,NaN,2024-03-27,NaN,"GRADUATE: B.A.-ECONOMICS,COLUMBIA UNIVERSITY,N...","POST GRADUATE: M.B.A.,HARVARD UNIVERSITY,CAMBR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,MS. JILLIAN LEIGH MOO-YOUNG IS A SENIOR VICE P...,NaN,NaN,NaN,NaN,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,446432,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118305,MR.,JYOTIN,KANTILAL,MEHTA,NaT,M,NaN,2023-07-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,446433,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118306,MR.,LAXMI,PAT,BOTHRA,NaT,M,NaN,2019-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dff = df

In [6]:
dfe = dff[['Symbol', 'AsOnDate', 'Person Code', 'Appointment Date', 'Independent (Yes/No)']]
dfe

,Symbol,AsOnDate,Person Code,Appointment Date,Independent (Yes/No)
0,AEGISCHEM,2006-03-31,P00000005,1982-09-01,NaN
1,AEGISCHEM,2007-03-31,P00000005,1982-09-01,NaN
2,AEGISCHEM,2008-03-31,P00000005,1982-09-01,NaN
3,AEGISCHEM,2009-03-31,P00000005,1982-09-01,NaN
4,AEGISCHEM,2010-03-31,P00000005,1982-09-01,NaN
...,...,...,...,...,...
446429,HIGHWAYS,2023-03-31,P00118177,2022-09-14,NaN
446430,HIGHWAYS,2024-03-31,P00118177,2022-09-14,NaN
446431,MAXESTATES,2024-03-31,P00118252,2024-03-27,NaN
446432,EPACK,2024-03-31,P00118305,2023-07-29,NaN
446433,EPACK,2024-03-31,P00118306,2019-06-13,NaN

In [7]:
dfei = dfe.set_index(['Symbol', 'Person Code', 'AsOnDate'], drop = False)
dfei

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

[446434 rows x 5 columns]

In [8]:
dfes = dfei.head(n = 446434)
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

[446434 rows x 5 columns]

In [9]:
dfes.insert(5, 'IsIndep', 'U')
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

                                  IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       U
                       2007-03-31       U
                       2008-03-31       U
                       2009-03-31       U
                       2010-03-31       U
...                                   ...
HIGHWAYS   P00118177   2023-03-31       U
                       2024-03-31       U
MAXESTATES P00118252   2024-03-31       U
EPACK      P00118305   2024-03-31       U
           P00118306   2024-03-31       U

[446434 rows x 6 columns]

In [10]:
dfes.loc[dfes['Independent (Yes/No)'] == 'YES', 'IsIndep'] = 'Y'
dfes.loc[dfes['Independent (Yes/No)'] == 'NO', 'IsIndep'] = 'N'
dfes = dfes.drop('Independent (Yes/No)', axis = 1)
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01       U
                       2007-03-31       1982-09-01       U
                       2008-03-31       1982-09-01       U
                       2009-03-31       1982-09-01       U
                       2010-03-31       1982-09-01       U
...                                            ...     ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14       U
                       2024-03-31       2022-09-14       U
MAXESTATES P00118252   2024-03-31       2024-03-27       U
EPACK      P00118305   2024-03-31       2023-07-29       U
           P00118306   2024-03-31       2019-06-13       U

[446434 rows x 5 columns]

In [11]:
dfes['PrevWORK'] = dfes.AsOnDate.shift()
dfes.insert(2, 'PrevLastServed', np.where( (dfes.AsOnDate <= dfes.PrevWORK) | (pd.isnull(dfes.PrevWORK) == True) , pd.NaT , dfes.PrevWORK))
dfes.PrevLastServed = pd.to_datetime(dfes.PrevLastServed)
dfes.drop('PrevWORK', axis = 1, inplace = True)

In [12]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

[446434 rows x 6 columns]

In [13]:
dfes.insert(6,'CloBalUnc', 0)
dfes.insert(7,'CloBalIndep', 0)
dfes.insert(8,'CloBalNonIndep', 0)
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   CloBalUnc  CloBalIndep  CloBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31          0            0               0
                       2007-03-31          0            0               0
                       2008-03-31          0            0               0
                       2009-03-31          0            0               0
                       2010-03-31          0            0               0
...                                      ...          ...             ...
HIGHWAYS   P00118177   2023-03-31          0            0               0
                       2024-03-31          0            0               0
MAXESTATES P00118252   2024-03-31          0            0               0
EPACK      P00118305   2024-03-31          0            0               0
           P00118306   2024-03-31          0            0               0

[446434 rows x 9 columns]

In [14]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   CloBalUnc  CloBalIndep  CloBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31          0            0               0
                       2007-03-31          0            0               0
                       2008-03-31          0            0               0
                       2009-03-31          0            0               0
                       2010-03-31          0            0               0
...                                      ...          ...             ...
HIGHWAYS   P00118177   2023-03-31          0            0               0
                       2024-03-31          0            0               0
MAXESTATES P00118252   2024-03-31          0            0               0
EPACK      P00118305   2024-03-31          0            0               0
           P00118306   2024-03-31          0            0               0

[446434 rows x 9 columns]

In [15]:
dfes.insert(6,'cumsum_U', 0)
dfes.insert(6,'cumsum_Y', 0)
dfes.insert(6,'cumsum_N', 0)
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  CloBalUnc  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0         0         0          0
                       2007-03-31         0         0         0          0
                       2008-03-31         0         0         0          0
                       2009-03-31         0         0         0          0
                       2010-03-31         0         0         0          0
...                                     ...       ...       ...        ...
HIGHWAYS   P00118177   2023-03-31         0         0         0          0
                       2024-03-31         0         0         0          0
MAXESTATES P00118252   2024-03-31         0         0         0          0
EPACK      P00118305   2024-03-31         0         0         0          0
           P00118306   2024-03-31         0         0         0          0

                                   CloBalIndep  CloBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31            0               0
                       2007-03-31            0               0
                       2008-03-31            0               0
                       2009-03-31            0               0
                       2010-03-31            0               0
...                                        ...             ...
HIGHWAYS   P00118177   2023-03-31            0               0
                       2024-03-31            0               0
MAXESTATES P00118252   2024-03-31            0               0
EPACK      P00118305   2024-03-31            0               0
           P00118306   2024-03-31            0               0

[446434 rows x 12 columns]

In [16]:
dfes.loc[ dfes['IsIndep'] == 'U','cumsum_U'] = 1
dfes.loc[ dfes['IsIndep'] == 'Y','cumsum_Y'] = 1
dfes.loc[ dfes['IsIndep'] == 'N','cumsum_N'] = 1

In [17]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  CloBalUnc  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0         0         1          0
                       2007-03-31         0         0         1          0
                       2008-03-31         0         0         1          0
                       2009-03-31         0         0         1          0
                       2010-03-31         0         0         1          0
...                                     ...       ...       ...        ...
HIGHWAYS   P00118177   2023-03-31         0         0         1          0
                       2024-03-31         0         0         1          0
MAXESTATES P00118252   2024-03-31         0         0         1          0
EPACK      P00118305   2024-03-31         0         0         1          0
           P00118306   2024-03-31         0         0         1          0

                                   CloBalIndep  CloBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31            0               0
                       2007-03-31            0               0
                       2008-03-31            0               0
                       2009-03-31            0               0
                       2010-03-31            0               0
...                                        ...             ...
HIGHWAYS   P00118177   2023-03-31            0               0
                       2024-03-31            0               0
MAXESTATES P00118252   2024-03-31            0               0
EPACK      P00118305   2024-03-31            0               0
           P00118306   2024-03-31            0               0

[446434 rows x 12 columns]

In [18]:
def OpBal1(frame):
    frame['CloBalUnc'] += (frame.loc[ frame['IsIndep'] == 'U']['AsOnDate'].min() - frame['Appointment Date']).dt.days

    frame['cumsum_U'] = np.cumsum(frame['cumsum_U'])
    frame['cumsum_Y'] = np.cumsum(frame['cumsum_Y'])
    frame['cumsum_N'] = np.cumsum(frame['cumsum_N'])
    return (frame)

In [19]:
def OpBal2(frame):
    
    frame.loc[ (frame['cumsum_U'] > 0 ) , 'CloBalUnc' ] += (frame['cumsum_U']) * 365
    
    
    frame.loc[ (frame['cumsum_Y'] > 0 ) , 'CloBalIndep' ] += (frame['cumsum_Y']) * 365
    
    
    frame.loc[ (frame['cumsum_N'] > 0 ) , 'CloBalNonIndep' ] += (frame['cumsum_N']) * 365
        
    return (frame)

In [20]:
check1 = dfes.reset_index(drop = True).groupby(['Person Code', 'Symbol'] ).progress_apply(OpBal1)

100%|████████████████████████████████████████████████████████████████████████████| 50531/50531 [15:45<00:00, 53.46it/s]

In [21]:
check2 = check1.reset_index(drop = True).groupby(['Person Code', 'Symbol'] ).progress_apply(OpBal2)

100%|████████████████████████████████████████████████████████████████████████████| 50531/50531 [10:15<00:00, 82.08it/s]

In [22]:
check1

                                   Symbol   AsOnDate PrevLastServed  \
Person Code Symbol
P00000005   AEGISCHEM  0        AEGISCHEM 2006-03-31            NaT
                       1        AEGISCHEM 2007-03-31     2006-03-31
                       2        AEGISCHEM 2008-03-31     2007-03-31
                       3        AEGISCHEM 2009-03-31     2008-03-31
                       4        AEGISCHEM 2010-03-31     2009-03-31
...                                   ...        ...            ...
P00118177   HIGHWAYS   446429    HIGHWAYS 2023-03-31            NaT
                       446430    HIGHWAYS 2024-03-31     2023-03-31
P00118252   MAXESTATES 446431  MAXESTATES 2024-03-31            NaT
P00118305   EPACK      446432       EPACK 2024-03-31            NaT
P00118306   EPACK      446433       EPACK 2024-03-31            NaT

                              Person Code Appointment Date IsIndep  cumsum_N  \
Person Code Symbol
P00000005   AEGISCHEM  0        P00000005       1982-09-01       U         0
                       1        P00000005       1982-09-01       U         0
                       2        P00000005       1982-09-01       U         0
                       3        P00000005       1982-09-01       U         0
                       4        P00000005       1982-09-01       U         0
...                                   ...              ...     ...       ...
P00118177   HIGHWAYS   446429   P00118177       2022-09-14       U         0
                       446430   P00118177       2022-09-14       U         0
P00118252   MAXESTATES 446431   P00118252       2024-03-27       U         0
P00118305   EPACK      446432   P00118305       2023-07-29       U         0
P00118306   EPACK      446433   P00118306       2019-06-13       U         0

                               cumsum_Y  cumsum_U  CloBalUnc  CloBalIndep  \
Person Code Symbol
P00000005   AEGISCHEM  0              0         1     8612.0            0
                       1              0         2     8612.0            0
                       2              0         3     8612.0            0
                       3              0         4     8612.0            0
                       4              0         5     8612.0            0
...                                 ...       ...        ...          ...
P00118177   HIGHWAYS   446429         0         1      198.0            0
                       446430         0         2      198.0            0
P00118252   MAXESTATES 446431         0         1        4.0            0
P00118305   EPACK      446432         0         1      246.0            0
P00118306   EPACK      446433         0         1     1753.0            0

                               CloBalNonIndep
Person Code Symbol
P00000005   AEGISCHEM  0                    0
                       1                    0
                       2                    0
                       3                    0
                       4                    0
...                                       ...
P00118177   HIGHWAYS   446429               0
                       446430               0
P00118252   MAXESTATES 446431               0
P00118305   EPACK      446432               0
P00118306   EPACK      446433               0

[446434 rows x 12 columns]

In [23]:
check2['CloBalTotal'] = 0
check2['CloBalTotal'] = check2['CloBalUnc'] + check2['CloBalIndep'] + check2['CloBalNonIndep']

In [24]:
check2.insert(13, 'OpBalUnc', 0)
check2.insert(14, 'OpBalIndep', 0)
check2.insert(15, 'OpBalNonIndep', 0)
check2.insert(16, 'OpBalTotal', 0)

check2['OpBalUnc'] = check2['CloBalUnc']
check2['OpBalIndep'] = check2['CloBalIndep']
check2['OpBalNonIndep'] = check2['CloBalNonIndep']

check2.loc[ (check2['IsIndep'] == 'U'),'OpBalUnc'] -= (365)
check2.loc[ check2['IsIndep'] == 'Y','OpBalIndep'] -= (365)
check2.loc[ check2['IsIndep'] == 'N','OpBalNonIndep'] -= (365)
check2['OpBalTotal'] = 0
check2['OpBalTotal'] = check2['OpBalUnc'] + check2['OpBalIndep'] + check2['OpBalNonIndep']

In [25]:
check2

                                   Symbol   AsOnDate PrevLastServed  \
Person Code Symbol
P00000005   AEGISCHEM  0        AEGISCHEM 2006-03-31            NaT
                       1        AEGISCHEM 2007-03-31     2006-03-31
                       2        AEGISCHEM 2008-03-31     2007-03-31
                       3        AEGISCHEM 2009-03-31     2008-03-31
                       4        AEGISCHEM 2010-03-31     2009-03-31
...                                   ...        ...            ...
P00118177   HIGHWAYS   446429    HIGHWAYS 2023-03-31            NaT
                       446430    HIGHWAYS 2024-03-31     2023-03-31
P00118252   MAXESTATES 446431  MAXESTATES 2024-03-31            NaT
P00118305   EPACK      446432       EPACK 2024-03-31            NaT
P00118306   EPACK      446433       EPACK 2024-03-31            NaT

                              Person Code Appointment Date IsIndep  cumsum_N  \
Person Code Symbol
P00000005   AEGISCHEM  0        P00000005       1982-09-01       U         0
                       1        P00000005       1982-09-01       U         0
                       2        P00000005       1982-09-01       U         0
                       3        P00000005       1982-09-01       U         0
                       4        P00000005       1982-09-01       U         0
...                                   ...              ...     ...       ...
P00118177   HIGHWAYS   446429   P00118177       2022-09-14       U         0
                       446430   P00118177       2022-09-14       U         0
P00118252   MAXESTATES 446431   P00118252       2024-03-27       U         0
P00118305   EPACK      446432   P00118305       2023-07-29       U         0
P00118306   EPACK      446433   P00118306       2019-06-13       U         0

                               cumsum_Y  cumsum_U  CloBalUnc  CloBalIndep  \
Person Code Symbol
P00000005   AEGISCHEM  0              0         1     8977.0            0
                       1              0         2     9342.0            0
                       2              0         3     9707.0            0
                       3              0         4    10072.0            0
                       4              0         5    10437.0            0
...                                 ...       ...        ...          ...
P00118177   HIGHWAYS   446429         0         1      563.0            0
                       446430         0         2      928.0            0
P00118252   MAXESTATES 446431         0         1      369.0            0
P00118305   EPACK      446432         0         1      611.0            0
P00118306   EPACK      446433         0         1     2118.0            0

                               CloBalNonIndep  CloBalTotal  OpBalUnc  \
Person Code Symbol
P00000005   AEGISCHEM  0                    0       8977.0    8612.0
                       1                    0       9342.0    8977.0
                       2                    0       9707.0    9342.0
                       3                    0      10072.0    9707.0
                       4                    0      10437.0   10072.0
...                                       ...          ...       ...
P00118177   HIGHWAYS   446429               0        563.0     198.0
                       446430               0        928.0     563.0
P00118252   MAXESTATES 446431               0        369.0       4.0
P00118305   EPACK      446432               0        611.0     246.0
P00118306   EPACK      446433               0       2118.0    1753.0

                               OpBalIndep  OpBalNonIndep  OpBalTotal
Person Code Symbol
P00000005   AEGISCHEM  0                0              0      8612.0
                       1                0              0      8977.0
                       2                0              0      9342.0
                       3                0              0      9707.0
                       4                0              0     10072.0
...                                   ...            ...         ...
P00118177   HIGHWAYS   446429           0              0       198.0
                       446430           0              0       563.0
P00118252   MAXESTATES 446431           0              0         4.0
P00118305   EPACK      446432           0              0       246.0
P00118306   EPACK      446433           0              0      1753.0

[446434 rows x 17 columns]

In [26]:
check2[check2['Person Code'] == 'P00004449']

                                  Symbol   AsOnDate PrevLastServed  \
Person Code Symbol
P00004449   20MICRONS  40895   20MICRONS 2024-03-31            NaT
            APCOTEXIND 40896  APCOTEXIND 2006-03-31            NaT
                       40897  APCOTEXIND 2007-03-31     2006-03-31
                       40898  APCOTEXIND 2008-03-31     2007-03-31
                       40899  APCOTEXIND 2009-03-31     2008-03-31
                       40900  APCOTEXIND 2010-03-31     2009-03-31
                       40901  APCOTEXIND 2011-03-31     2010-03-31
                       40902  APCOTEXIND 2012-03-31     2011-03-31
                       40903  APCOTEXIND 2013-03-31     2012-03-31
                       40904  APCOTEXIND 2014-03-31     2013-03-31
                       40905  APCOTEXIND 2015-03-31     2014-03-31
                       40906  APCOTEXIND 2016-03-31     2015-03-31
                       40907  APCOTEXIND 2017-03-31     2016-03-31
                       40908  APCOTEXIND 2018-03-31     2017-03-31
                       40909  APCOTEXIND 2019-03-31     2018-03-31
                       40910  APCOTEXIND 2020-03-31     2019-03-31
                       40911  APCOTEXIND 2021-03-31     2020-03-31
                       40912  APCOTEXIND 2022-03-31     2021-03-31
                       40913  APCOTEXIND 2023-03-31     2022-03-31
                       40914  APCOTEXIND 2024-03-31     2023-03-31
            ASIANPAINT 40915  ASIANPAINT 2006-03-31            NaT
                       40916  ASIANPAINT 2007-03-31     2006-03-31
                       40917  ASIANPAINT 2008-03-31     2007-03-31
                       40918  ASIANPAINT 2009-03-31     2008-03-31
                       40919  ASIANPAINT 2010-03-31     2009-03-31
                       40920  ASIANPAINT 2011-03-31     2010-03-31
                       40921  ASIANPAINT 2012-03-31     2011-03-31
                       40922  ASIANPAINT 2013-03-31     2012-03-31
                       40923  ASIANPAINT 2014-03-31     2013-03-31
                       40924  ASIANPAINT 2015-03-31     2014-03-31
                       40925  ASIANPAINT 2016-03-31     2015-03-31
                       40926  ASIANPAINT 2017-03-31     2016-03-31
                       40927  ASIANPAINT 2018-03-31     2017-03-31
                       40928  ASIANPAINT 2019-03-31     2018-03-31
                       40929  ASIANPAINT 2020-03-31     2019-03-31
                       40930  ASIANPAINT 2021-03-31     2020-03-31
                       40931  ASIANPAINT 2022-03-31     2021-03-31
                       40932  ASIANPAINT 2023-03-31     2022-03-31
                       40933  ASIANPAINT 2024-03-31     2023-03-31
            DEEPAKNTR  40934   DEEPAKNTR 2014-03-31            NaT
                       40935   DEEPAKNTR 2015-03-31     2014-03-31
                       40936   DEEPAKNTR 2016-03-31     2015-03-31
                       40937   DEEPAKNTR 2017-03-31     2016-03-31
                       40938   DEEPAKNTR 2018-03-31     2017-03-31
                       40939   DEEPAKNTR 2019-03-31     2018-03-31
                       40940   DEEPAKNTR 2020-03-31     2019-03-31
                       40941   DEEPAKNTR 2021-03-31     2020-03-31
                       40942   DEEPAKNTR 2022-03-31     2021-03-31
                       40943   DEEPAKNTR 2023-03-31     2022-03-31
                       40944   DEEPAKNTR 2024-03-31     2023-03-31
            GMMPFAUDLR 40945  GMMPFAUDLR 2018-03-31            NaT
                       40946  GMMPFAUDLR 2019-03-31     2018-03-31
                       40947  GMMPFAUDLR 2020-03-31     2019-03-31
                       40948  GMMPFAUDLR 2021-03-31     2020-03-31
                       40949  GMMPFAUDLR 2022-03-31     2021-03-31
                       40950  GMMPFAUDLR 2023-03-31     2022-03-31
                       40951  GMMPFAUDLR 2024-03-31     2023-03-31
            SPLPETRO   40952    SPLPETRO 2023-03-31            NaT
                       40953    SPLPETRO 2024-03-31     2023-03-31

                             Person Code Appointment Date IsIndep  cumsum_N  \
Person Code Symbol
P00004449   20MICRONS  40895   P00004449       2023-05-16       Y         0
            APCOTEXIND 40896   P00004449       1996-03-27       U         0
                       40897   P00004449       1996-03-27       U         0
                       40898   P00004449       1996-03-27       U         0
                       40899   P00004449       1996-03-27       U         0
                       40900   P00004449       1996-03-27       U         0
                       40901   P00004449       1996-03-27       U         0
                       40902   P00004449       1996-03-27       U         0
                       40903   P00004449       1996-03-27       Y         0
                       40904   P00004449       1996-03-27       Y         0
                       40905   P00004449       1996-03-27       Y         0
                       40906   P00004449       1996-03-27       Y         0
                       40907   P00004449       1996-03-27       Y         0
                       40908   P00004449       1996-03-27       Y         0
                       40909   P00004449       1996-03-27       Y         0
                       40910   P00004449       1996-03-27       Y         0
                       40911   P00004449       1996-03-27       Y         0
                       40912   P00004449       1996-03-27       Y         0
                       40913   P00004449       1996-03-27       Y         0
                       40914   P00004449       1996-03-27       Y         0
            ASIANPAINT 40915   P00004449       2001-04-07       U         0
                       40916   P00004449       2001-04-07       U         0
                       40917   P00004449       2001-04-07       U         0
                       40918   P00004449       2001-04-07       U         0
                       40919   P00004449       2001-04-07       U         0
                       40920   P00004449       2001-04-07       U         0
                       40921   P00004449       2001-04-07       U         0
                       40922   P00004449       2001-04-07       Y         0
                       40923   P00004449       2001-04-07       Y         0
                       40924   P00004449       2001-04-07       Y         0
                       40925   P00004449       2001-04-07       Y         0
                       40926   P00004449       2001-04-07       Y         0
                       40927   P00004449       2001-04-07       Y         0
                       40928   P00004449       2001-04-07       Y         0
                       40929   P00004449       2001-04-07       Y         0
                       40930   P00004449       2001-04-07       Y         0
                       40931   P00004449       2001-04-07       Y         0
                       40932   P00004449       2001-04-07       Y         0
                       40933   P00004449       2001-04-07       Y         0
            DEEPAKNTR  40934   P00004449       2013-08-02       Y         0
                       40935   P00004449       2013-08-02       Y         0
                       40936   P00004449       2013-08-02       Y         0
                       40937   P00004449       2013-08-02       Y         0
                       40938   P00004449       2013-08-02       Y         0
                       40939   P00004449       2013-08-02       Y         0
                       40940   P00004449       2013-08-02       Y         0
                       40941   P00004449       2013-08-02       Y         0
                       40942   P00004449       2013-08-02       Y         0
                       40943   P00004449       2013-08-02       Y         0
                       40944   P00004449       2013-08-02       Y         0
            GMMPFAUDLR 40945   P00004449       2003-06-26       Y         0
                       40946   P00004449       2003-06-26       Y         0
                       40947   P00004449       2003-06-26       Y         0
                       40948   P00004449       2003-06-26       Y         0
                       40949   P00004449       2003-06-26       Y         0
                       40950   P00004449       2003-06-26       Y         0
                       40951   P00004449       2003-06-26       Y         0
            SPLPETRO   40952   P00004449       2014-09-23       Y         0
                       40953   P00004449       2014-09-23       Y         0

                              cumsum_Y  cumsum_U  CloBalUnc  CloBalIndep  \
Person Code Symbol
P00004449   20MICRONS  40895         1         0        NaN          365
            APCOTEXIND 40896         0         1     4021.0            0
                       40897         0         2     4386.0            0
                       40898         0         3     4751.0            0
                       40899         0         4     5116.0            0
                       40900         0         5     5481.0            0
                       40901         0         6     5846.0            0
                       40902         0         7     6211.0            0
                       40903         1         7     6211.0          365
                       40904         2         7     6211.0          730
                       40905         3         7     6211.0         1095
                       40906         4         7     6211.0         1460
                       40907         5         7     6211.0         1825
                       40908         6         7     6211.0         2190
                       40909         7         7     6211.0         2555
                       40910         8         7     6211.0         2920
                       40911         9         7     6211.0         3285
                       40912        10         7     6211.0         3650
                       40913        11         7     6211.0         4015
                       40914        12         7     6211.0         4380
            ASIANPAINT 40915         0         1     2184.0            0
                       40916         0         2     2549.0            0
                       40917         0         3     2914.0            0
                       40918         0         4     3279.0            0
                       40919         0         5     3644.0            0
                       40920         0         6     4009.0            0
                       40921         0         7     4374.0            0
                       40922         1         7     4374.0          365
                       40923         2         7     4374.0          730
                       40924         3         7     4374.0         1095
                       40925         4         7     4374.0         1460
                       40926         5         7     4374.0         1825
                       40927         6         7     4374.0         2190
                       40928         7         7     4374.0         2555
                       40929         8         7     4374.0         2920
                       40930         9         7     4374.0         3285
                       40931        10         7     4374.0         3650
                       40932        11         7     4374.0         4015
                       40933        12         7     4374.0         4380
            DEEPAKNTR  40934         1         0        NaN          365
                       40935         2         0        NaN          730
                       40936         3         0        NaN         1095
                       40937         4         0        NaN         1460
                       40938         5         0        NaN         1825
                       40939         6         0        NaN         2190
                       40940         7         0        NaN         2555
                       40941         8         0        NaN         2920
                       40942         9         0        NaN         3285
                       40943        10         0        NaN         3650
                       40944        11         0        NaN         4015
            GMMPFAUDLR 40945         1         0        NaN          365
                       40946         2         0        NaN          730
                       40947         3         0        NaN         1095
                       40948         4         0        NaN         1460
                       40949         5         0        NaN         1825
                       40950         6         0        NaN         2190
                       40951         7         0        NaN         2555
            SPLPETRO   40952         1         0        NaN          365
                       40953         2         0        NaN          730

                              CloBalNonIndep  CloBalTotal  OpBalUnc  \
Person Code Symbol
P00004449   20MICRONS  40895               0          NaN       NaN
            APCOTEXIND 40896               0       4021.0    3656.0
                       40897               0       4386.0    4021.0
                       40898               0       4751.0    4386.0
                       40899               0       5116.0    4751.0
                       40900               0       5481.0    5116.0
                       40901               0       5846.0    5481.0
                       40902               0       6211.0    5846.0
                       40903               0       6576.0    6211.0
                       40904               0       6941.0    6211.0
                       40905               0       7306.0    6211.0
                       40906               0       7671.0    6211.0
                       40907               0       8036.0    6211.0
                       40908               0       8401.0    6211.0
                       40909               0       8766.0    6211.0
                       40910               0       9131.0    6211.0
                       40911               0       9496.0    6211.0
                       40912               0       9861.0    6211.0
                       40913               0      10226.0    6211.0
                       40914               0      10591.0    6211.0
            ASIANPAINT 40915               0       2184.0    1819.0
                       40916               0       2549.0    2184.0
                       40917               0       2914.0    2549.0
                       40918               0       3279.0    2914.0
                       40919               0       3644.0    3279.0
                       40920               0       4009.0    3644.0
                       40921               0       4374.0    4009.0
                       40922               0       4739.0    4374.0
                       40923               0       5104.0    4374.0
                       40924               0       5469.0    4374.0
                       40925               0       5834.0    4374.0
                       40926               0       6199.0    4374.0
                       40927               0       6564.0    4374.0
                       40928               0       6929.0    4374.0
                       40929               0       7294.0    4374.0
                       40930               0       7659.0    4374.0
                       40931               0       8024.0    4374.0
                       40932               0       8389.0    4374.0
                       40933               0       8754.0    4374.0
            DEEPAKNTR  40934               0          NaN       NaN
                       40935               0          NaN       NaN
                       40936               0          NaN       NaN
                       40937               0          NaN       NaN
                       40938               0          NaN       NaN
                       40939               0          NaN       NaN
                       40940               0          NaN       NaN
                       40941               0          NaN       NaN
                       40942               0          NaN       NaN
                       40943               0          NaN       NaN
                       40944               0          NaN       NaN
            GMMPFAUDLR 40945               0          NaN       NaN
                       40946               0          NaN       NaN
                       40947               0          NaN       NaN
                       40948               0          NaN       NaN
                       40949               0          NaN       NaN
                       40950               0          NaN       NaN
                       40951               0          NaN       NaN
            SPLPETRO   40952               0          NaN       NaN
                       40953               0          NaN       NaN

                              OpBalIndep  OpBalNonIndep  OpBalTotal
Person Code Symbol
P00004449   20MICRONS  40895           0              0         NaN
            APCOTEXIND 40896           0              0      3656.0
                       40897           0              0      4021.0
                       40898           0              0      4386.0
                       40899           0              0      4751.0
                       40900           0              0      5116.0
                       40901           0              0      5481.0
                       40902           0              0      5846.0
                       40903           0              0      6211.0
                       40904         365              0      6576.0
                       40905         730              0      6941.0
                       40906        1095              0      7306.0
                       40907        1460              0      7671.0
                       40908        1825              0      8036.0
                       40909        2190              0      8401.0
                       40910        2555              0      8766.0
                       40911        2920              0      9131.0
                       40912        3285              0      9496.0
                       40913        3650              0      9861.0
                       40914        4015              0     10226.0
            ASIANPAINT 40915           0              0      1819.0
                       40916           0              0      2184.0
                       40917           0              0      2549.0
                       40918           0              0      2914.0
                       40919           0              0      3279.0
                       40920           0              0      3644.0
                       40921           0              0      4009.0
                       40922           0              0      4374.0
                       40923         365              0      4739.0
                       40924         730              0      5104.0
                       40925        1095              0      5469.0
                       40926        1460              0      5834.0
                       40927        1825              0      6199.0
                       40928        2190              0      6564.0
                       40929        2555              0      6929.0
                       40930        2920              0      7294.0
                       40931        3285              0      7659.0
                       40932        3650              0      8024.0
                       40933        4015              0      8389.0
            DEEPAKNTR  40934           0              0         NaN

In [27]:
check2.to_csv('Main_Manager_Calc v280824.1.csv')