In [12]:
import pandas as pd
import numpy as np
import scipy as sp
from tqdm import tqdm
tqdm.pandas()
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_excel("Indian Boards Data as on 31-Mar-2006.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df2 = pd.read_excel("Indian Boards Data as on 31-Mar-2007.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df3 = pd.read_excel("Indian Boards Data as on 31-Mar-2008.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df4 = pd.read_excel("Indian Boards Data as on 31-Mar-2009.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df5 = pd.read_excel("Indian Boards Data as on 31-Mar-2010.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df6 = pd.read_excel("Indian Boards Data as on 31-Mar-2011.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df7 = pd.read_excel("Indian Boards Data as on 31-Mar-2012.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df8 = pd.read_excel("Indian Boards Data as on 31-Mar-2013.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df9 = pd.read_excel("Indian Boards Data as on 31-Mar-2014.xlsx", sheet_name = 'Master Profile', skiprows = 1)

df10 = pd.read_excel("Indian Boards Data as on 31-Mar-2015.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df11 = pd.read_excel("Indian Boards Data as on 31-Mar-2016.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df12 = pd.read_excel("Indian Boards Data as on 31-Mar-2017.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df13 = pd.read_excel("Indian Boards Data as on 31-Mar-2018.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df14 = pd.read_excel("Indian Boards Data as on 31-Mar-2019.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df15 = pd.read_excel("Indian Boards Data as on 31-Mar-2020.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df16 = pd.read_excel("Indian Boards Data as on 31-Mar-2021.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df17 = pd.read_excel("Indian Boards Data as on 31-Mar-2022.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df18 = pd.read_excel("Indian Boards Data as on 31-Mar-2023.xlsx", sheet_name = 'Master Profile', skiprows = 1)
df19 = pd.read_excel("Indian Boards Data as on 31-Mar-2024.xlsx", sheet_name = 'Master Profile', skiprows = 1)

In [3]:
df1.insert(2, 'AsOnDate', '31-03-2006')
df2.insert(2, 'AsOnDate', '31-03-2007')
df3.insert(2, 'AsOnDate', '31-03-2008')
df4.insert(2, 'AsOnDate', '31-03-2009')
df5.insert(2, 'AsOnDate', '31-03-2010')
df6.insert(2, 'AsOnDate', '31-03-2011')
df7.insert(2, 'AsOnDate', '31-03-2012')
df8.insert(2, 'AsOnDate', '31-03-2013')
df9.insert(2, 'AsOnDate', '31-03-2014')

df10.insert(2, 'AsOnDate', '31-03-2015')
df11.insert(2, 'AsOnDate', '31-03-2016')
df12.insert(2, 'AsOnDate', '31-03-2017')
df13.insert(2, 'AsOnDate', '31-03-2018')
df14.insert(2, 'AsOnDate', '31-03-2019')
df15.insert(2, 'AsOnDate', '31-03-2020')
df16.insert(2, 'AsOnDate', '31-03-2021')
df17.insert(2, 'AsOnDate', '31-03-2022')
df18.insert(2, 'AsOnDate', '31-03-2023')
df19.insert(2, 'AsOnDate', '31-03-2024')

In [4]:
dfs = [df.set_index(['Symbol', 'AsOnDate']) for df in [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19]]
dff = pd.concat(dfs, axis=0).reset_index()
dff.sort_values(['Symbol', 'AsOnDate']).reset_index(drop = True)

,Symbol,AsOnDate,Company,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till
0,20MICRONS,31-03-2009,20 MICRONS LTD.,P00027662,MR.,DIPTIMOY,DINESHCHANDRA,BHATTACHARJEE,09-DEC-1955,M,NaN,29-APR-2005,NaN,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02-MAR-2009,NOMINATION ENDED,"MR.D.D.BHATTACHARJEE, IDBI-NOMINEE DIRECTOR HO...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,31-03-2009,20 MICRONS LTD.,P00027633,MR.,RAMKISHAN,AMIRCHAND,DEVIDAYAL,08-DEC-1950,M,INDIA,13-OCT-2007,NONE,POST GRADUATE: M.B.A.,"POST GRADUATE: M.COM.,MAHARAJA SAYAJIRAO UNIVE...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CONSUMER DISCRETIONARY...",NaN,NaN,MR.RAM DEVIDAYAL HAS A MASTER'S DEGREE IN COMM...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20MICRONS,31-03-2009,20 MICRONS LTD.,P00027664,MR.,MIHIR,ARVIND,JOSHI,12-JUN-1977,M,NaN,23-AUG-2007,NaN,"GRADUATE: ASSOCIATE MEMBER,INSTITUTE OF COMPAN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MR.MIHIR JOSHI, GVFL- NOMINEE DIRECTOR HOLDS D...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,31-03-2009,20 MICRONS LTD.,P00029006,MR.,ATIL,CHANDRESH,PARIKH,04-SEP-1977,M,INDIA,29-JAN-2001,NaN,"GRADUATE: B.E.-CHEMICAL,GUJARAT UNIVERSITY,AHM...","POST GRADUATE: M.B.A.-FINANCE,CALIFORNIA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,NaN,"MR. ATIL C. PARIKH, HOLDS A BACHELOR'S DEGREE ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,31-03-2009,20 MICRONS LTD.,P00027661,LATE MR.,CHANDRESH,SHANTILAL,PARIKH,06-MAR-1946,M,INDIA,29-MAR-1988,NaN,POST GRADUATE: M.SC.-CHEMISTRY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",NaN,NaN,"MR.CHANDRESH S. PARIKH, OUR CHAIRMAN AND MANAG...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYLOG,31-03-2018,ZYLOG SYSTEMS LTD.,P00001781,MR.,RAJAGOPAL,NaN,SRINIVASACHARI,10-MAR-1940,M,INDIA,28-JAN-2007,NONE,"GRADUATE: B.COM.,GUJARAT UNIVERSITY,AHMEDABAD","GRADUATE: DIPLOMA-INDUSTRIAL FINANCE,INDIAN IN...","GRADUATE: LL.B.,GUJARAT UNIVERSITY,AHMEDABAD",POST GRADUATE: C.A.I.I.B.(CERTIFIED ASSOCIATE ...,"POST GRADUATE: M.A.-ECONOMICS,GUJARAT UNIVERSI...",NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,CORPORATE SOCIAL RESPONSI...",07-DEC-2012,RESIGNED (NO REASON STATED),"MR.S RAJAGOPAL, FORMER CHAIRMAN & MANAGING DIR...",NO,NON-EXECUTIVE DIRECTOR,YES,RETIRED,GMR AIRPORTS INFRASTRUCTURE LTD.,SREI INFRASTRUCTURE FINANCE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYLOG,31-03-2018,ZYLOG SYSTEMS LTD.,P00062851,MR.,K.,S.,SUBRAMANIAN,17-SEP-1943,M,NaN,14-FEB-2014,NaN,POST GRADUATE: F.C.M.A.(FELLOW COST & MANAGEME...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30-JUN-2016,RESIGNED (NO REASON STATED),ACCOUNTING & FINANCIAL FUNCTIONS.,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYLOG,31-03-2018,ZYLOG SYSTEMS LTD.,P00042325,MR.,AYYAVU,PALANICHAMY,VASANTHAKUMAR,12-MAY-1977,M,NaN,29-JAN-2010,NaN,"GRADUATE: B.E.,BHARATHIAR UNIVERSITY,COIMBATORE","POST GRADUATE: M.B.A.,BHARATHIDASAN UNIVERSITY...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ACCOUNTS/AUDIT/TAXATION,CORPORATE GOVERNANCE,F...",20-NOV-2012,RESIGNED (NO REASON STATED),NaN,NO,NOMINEE DIRECTOR OF UTI VENTURE FUNDS MANAGEME...,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYLOG,31-03-2018,ZYLOG SYSTEMS LTD.,P00027523,MR.,SUDHARSHAN,NaN,VENKATRAMAN,28-JUL-1963,M,NaN,01-JUN-1995,NaN,GRADUATE: B.SC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19-NOV-2014,Suspended/Terminated/Superceded,"MR.SUDARSHAN VENKATRAMAN, IS OUR PROMOTER. MR....",NO,"CHAIRPERSON, EXECUTIVE DIRECTOR",NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,ZYLOG,31-03-2018,ZYLOG SYSTEMS LTD.,P00075398,MR.,S.,NaN,VIMALESHKUMAR,29-SEP-1970,M,NaN,25-NOV-2015,NaN,GRADUATE: B.COM.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30-JUN-2016,RESIGNED (NO REASON STATED),MR. S. VIMALESH KUMAR IS A COMMERCE GRADUATE. ...,NO,NON-EXECUTIVE DIRECTOR,YES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dff['AsOnDate'] = pd.to_datetime(dff['AsOnDate'], format = '%d-%m-%Y')

dff['Date of Birth'] = pd.to_datetime(dff['Date of Birth'], format = '%d-%b-%Y')

dff['Appointment Date'] = pd.to_datetime(dff['Appointment Date'], format = '%d-%b-%Y')

dff['Cessation Date'] = pd.to_datetime(dff['Cessation Date'], format = '%d-%b-%Y', errors = 'coerce')

In [6]:
dff['Cessation Reason'] = dff['Cessation Reason'].astype(str)

In [7]:
dff = dff.sort_values(by = ['Person Code','Symbol', 'AsOnDate'], axis = 0).reset_index(drop = True)

In [8]:
dff

,Symbol,AsOnDate,Company,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till
0,AEGISCHEM,2006-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AEGISCHEM,2007-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AEGISCHEM,2008-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AEGISCHEM,2009-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AEGISCHEM,2010-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,HIGHWAYS,2023-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,HIGHWAYS,2024-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,MAXESTATES,2024-03-31,MAX ESTATES LTD.,P00118252,MS.,JILIAN,L.,MOOYOUNG,NaT,F,NaN,2024-03-27,NaN,"GRADUATE: B.A.-ECONOMICS,COLUMBIA UNIVERSITY,N...","POST GRADUATE: M.B.A.,HARVARD UNIVERSITY,CAMBR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,MS. JILLIAN LEIGH MOO-YOUNG IS A SENIOR VICE P...,NaN,NaN,NaN,NaN,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118305,MR.,JYOTIN,KANTILAL,MEHTA,NaT,M,NaN,2023-07-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118306,MR.,LAXMI,PAT,BOTHRA,NaT,M,NaN,2019-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dff.loc[ (dff['Person Code'] == 'P00000005') & (dff['Symbol'] == 'AEGISCHEM') & (dff['AsOnDate'] < '2008-03-31'),['AsOnDate']].max()

AsOnDate   2007-03-31
dtype: datetime64[ns]

In [10]:
def PrevLastServed(df, P ,S ,A):
    x = df.loc[ ((df['Person Code'] == P) & (df['Symbol'] == S) & (df['AsOnDate'] < A))]['AsOnDate'].max()
    return x

In [13]:
dff = dff.sort_values(by = ['Person Code','Symbol', 'AsOnDate'], axis = 0)
dff.loc[:,'PrevLastServed'] = dff.progress_apply( lambda x: PrevLastServed(dff, x['Person Code'], x['Symbol'], x['AsOnDate']), axis = 1)

  1%|          | 3439/446434 [04:25<9:30:41, 12.94it/s]

KeyboardInterrupt:

In [ ]:
dff