In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from tqdm import tqdm
tqdm.pandas()
from dateutil.relativedelta import relativedelta
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_excel("Main.xlsx")

In [3]:
df['Cessation Reason'] = df['Cessation Reason'].astype(str)

In [4]:
df

,Unnamed: 0,Symbol,AsOnDate,Company,Person Code,Director Salutation,Director First Name,Director Middle Name,Director Surname,Date of Birth,Gender,Nationality,Appointment Date,Member of Civil Services,Education1,Education2,Education3,Education4,Education5,Education6,Education7,Education8,Education9,Education10,Skills/Competencies,Cessation Date,Cessation Reason,Brief Profile,Promoter Director (Yes/No),Position on Board,Independent (Yes/No),Occupation,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Tenure Valid till
0,0,AEGISCHEM,2006-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,AEGISCHEM,2007-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,AEGISCHEM,2008-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,AEGISCHEM,2009-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,AEGISCHEM,2010-03-31,AEGIS LOGISTICS LTD.,P00000005,MR.,ANIL KUMAR,MAGANLAL,CHANDARIA,1935-05-04,M,NaN,1982-09-01,NaN,"GRADUATE: B.SC.-ECONOMICS,LONDON SCHOOL OF ECO...","POST GRADUATE: M.B.A.,HARVARD BUSINESS SCHOOL,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"CORPORATE GOVERNANCE,ENERGY,FINANCE,LEADERSHIP...",NaT,nan,HE IS A DIRECTOR OF THE COMPANY SINCE 1982. HE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446429,HIGHWAYS,2023-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,446430,HIGHWAYS,2024-03-31,HIGHWAYS INFRASTRUCTURE TRUST,P00118177,MR.,MANISH,NaN,AGARWAL,NaT,M,NaN,2022-09-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,446431,MAXESTATES,2024-03-31,MAX ESTATES LTD.,P00118252,MS.,JILIAN,L.,MOOYOUNG,NaT,F,NaN,2024-03-27,NaN,"GRADUATE: B.A.-ECONOMICS,COLUMBIA UNIVERSITY,N...","POST GRADUATE: M.B.A.,HARVARD UNIVERSITY,CAMBR...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,MS. JILLIAN LEIGH MOO-YOUNG IS A SENIOR VICE P...,NaN,NaN,NaN,NaN,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,446432,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118305,MR.,JYOTIN,KANTILAL,MEHTA,NaT,M,NaN,2023-07-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,446433,EPACK,2024-03-31,EPACK DURABLE LTD.,P00118306,MR.,LAXMI,PAT,BOTHRA,NaT,M,NaN,2019-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,nan,NaN,NaN,NaN,NaN,NaN,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dff = df

In [6]:
dfe = dff[['Symbol', 'AsOnDate', 'Person Code', 'Appointment Date', 'Independent (Yes/No)']]
dfe

,Symbol,AsOnDate,Person Code,Appointment Date,Independent (Yes/No)
0,AEGISCHEM,2006-03-31,P00000005,1982-09-01,NaN
1,AEGISCHEM,2007-03-31,P00000005,1982-09-01,NaN
2,AEGISCHEM,2008-03-31,P00000005,1982-09-01,NaN
3,AEGISCHEM,2009-03-31,P00000005,1982-09-01,NaN
4,AEGISCHEM,2010-03-31,P00000005,1982-09-01,NaN
...,...,...,...,...,...
446429,HIGHWAYS,2023-03-31,P00118177,2022-09-14,NaN
446430,HIGHWAYS,2024-03-31,P00118177,2022-09-14,NaN
446431,MAXESTATES,2024-03-31,P00118252,2024-03-27,NaN
446432,EPACK,2024-03-31,P00118305,2023-07-29,NaN
446433,EPACK,2024-03-31,P00118306,2019-06-13,NaN

In [7]:
dfei = dfe.set_index(['Symbol', 'Person Code', 'AsOnDate'], drop = False)
dfei

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

[446434 rows x 5 columns]

In [8]:
dfes = dfei.head(n = 446434)
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

[446434 rows x 5 columns]

In [9]:
dfes.insert(5, 'IsIndep', 'U')
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date Independent (Yes/No)  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01                  NaN
                       2007-03-31       1982-09-01                  NaN
                       2008-03-31       1982-09-01                  NaN
                       2009-03-31       1982-09-01                  NaN
                       2010-03-31       1982-09-01                  NaN
...                                            ...                  ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14                  NaN
                       2024-03-31       2022-09-14                  NaN
MAXESTATES P00118252   2024-03-31       2024-03-27                  NaN
EPACK      P00118305   2024-03-31       2023-07-29                  NaN
           P00118306   2024-03-31       2019-06-13                  NaN

                                  IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       U
                       2007-03-31       U
                       2008-03-31       U
                       2009-03-31       U
                       2010-03-31       U
...                                   ...
HIGHWAYS   P00118177   2023-03-31       U
                       2024-03-31       U
MAXESTATES P00118252   2024-03-31       U
EPACK      P00118305   2024-03-31       U
           P00118306   2024-03-31       U

[446434 rows x 6 columns]

In [10]:
dfes.loc[dfes['Independent (Yes/No)'] == 'YES', 'IsIndep'] = 'Y'
dfes.loc[dfes['Independent (Yes/No)'] == 'NO', 'IsIndep'] = 'N'
dfes = dfes.drop('Independent (Yes/No)', axis = 1)
dfes

                                       Symbol   AsOnDate Person Code  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31   P00000005
                       2007-03-31   AEGISCHEM 2007-03-31   P00000005
                       2008-03-31   AEGISCHEM 2008-03-31   P00000005
                       2009-03-31   AEGISCHEM 2009-03-31   P00000005
                       2010-03-31   AEGISCHEM 2010-03-31   P00000005
...                                       ...        ...         ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31   P00118177
                       2024-03-31    HIGHWAYS 2024-03-31   P00118177
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31   P00118252
EPACK      P00118305   2024-03-31       EPACK 2024-03-31   P00118305
           P00118306   2024-03-31       EPACK 2024-03-31   P00118306

                                  Appointment Date IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31       1982-09-01       U
                       2007-03-31       1982-09-01       U
                       2008-03-31       1982-09-01       U
                       2009-03-31       1982-09-01       U
                       2010-03-31       1982-09-01       U
...                                            ...     ...
HIGHWAYS   P00118177   2023-03-31       2022-09-14       U
                       2024-03-31       2022-09-14       U
MAXESTATES P00118252   2024-03-31       2024-03-27       U
EPACK      P00118305   2024-03-31       2023-07-29       U
           P00118306   2024-03-31       2019-06-13       U

[446434 rows x 5 columns]

In [11]:
dfes['PrevWORK'] = dfes.AsOnDate.shift()
dfes.insert(2, 'PrevLastServed', np.where( (dfes.AsOnDate <= dfes.PrevWORK) | (pd.isnull(dfes.PrevWORK) == True) , pd.NaT , dfes.PrevWORK))
dfes.PrevLastServed = pd.to_datetime(dfes.PrevLastServed)
dfes.drop('PrevWORK', axis = 1, inplace = True)

In [12]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

[446434 rows x 6 columns]

In [13]:
dfes.insert(6,'OpBalUnc', 0)
dfes.insert(7,'OpBalIndep', 0)
dfes.insert(8,'OpBalNonIndep', 0)
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   OpBalUnc  OpBalIndep  OpBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0           0              0
                       2007-03-31         0           0              0
                       2008-03-31         0           0              0
                       2009-03-31         0           0              0
                       2010-03-31         0           0              0
...                                     ...         ...            ...
HIGHWAYS   P00118177   2023-03-31         0           0              0
                       2024-03-31         0           0              0
MAXESTATES P00118252   2024-03-31         0           0              0
EPACK      P00118305   2024-03-31         0           0              0
           P00118306   2024-03-31         0           0              0

[446434 rows x 9 columns]

In [14]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   OpBalUnc  OpBalIndep  OpBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0           0              0
                       2007-03-31         0           0              0
                       2008-03-31         0           0              0
                       2009-03-31         0           0              0
                       2010-03-31         0           0              0
...                                     ...         ...            ...
HIGHWAYS   P00118177   2023-03-31         0           0              0
                       2024-03-31         0           0              0
MAXESTATES P00118252   2024-03-31         0           0              0
EPACK      P00118305   2024-03-31         0           0              0
           P00118306   2024-03-31         0           0              0

[446434 rows x 9 columns]

In [15]:
dfes.insert(6,'cumsum_U', 0)
dfes.insert(6,'cumsum_Y', 0)
dfes.insert(6,'cumsum_N', 0)
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  OpBalUnc  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0         0         0         0
                       2007-03-31         0         0         0         0
                       2008-03-31         0         0         0         0
                       2009-03-31         0         0         0         0
                       2010-03-31         0         0         0         0
...                                     ...       ...       ...       ...
HIGHWAYS   P00118177   2023-03-31         0         0         0         0
                       2024-03-31         0         0         0         0
MAXESTATES P00118252   2024-03-31         0         0         0         0
EPACK      P00118305   2024-03-31         0         0         0         0
           P00118306   2024-03-31         0         0         0         0

                                   OpBalIndep  OpBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31           0              0
                       2007-03-31           0              0
                       2008-03-31           0              0
                       2009-03-31           0              0
                       2010-03-31           0              0
...                                       ...            ...
HIGHWAYS   P00118177   2023-03-31           0              0
                       2024-03-31           0              0
MAXESTATES P00118252   2024-03-31           0              0
EPACK      P00118305   2024-03-31           0              0
           P00118306   2024-03-31           0              0

[446434 rows x 12 columns]

In [16]:
dfes.loc[ dfes['IsIndep'] == 'U','cumsum_U'] = 1
dfes.loc[ dfes['IsIndep'] == 'Y','cumsum_Y'] = 1
dfes.loc[ dfes['IsIndep'] == 'N','cumsum_N'] = 1

In [17]:
dfes

                                       Symbol   AsOnDate PrevLastServed  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   AEGISCHEM 2006-03-31            NaT
                       2007-03-31   AEGISCHEM 2007-03-31     2006-03-31
                       2008-03-31   AEGISCHEM 2008-03-31     2007-03-31
                       2009-03-31   AEGISCHEM 2009-03-31     2008-03-31
                       2010-03-31   AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
HIGHWAYS   P00118177   2023-03-31    HIGHWAYS 2023-03-31            NaT
                       2024-03-31    HIGHWAYS 2024-03-31     2023-03-31
MAXESTATES P00118252   2024-03-31  MAXESTATES 2024-03-31            NaT
EPACK      P00118305   2024-03-31       EPACK 2024-03-31            NaT
           P00118306   2024-03-31       EPACK 2024-03-31            NaT

                                  Person Code Appointment Date IsIndep  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31   P00000005       1982-09-01       U
                       2007-03-31   P00000005       1982-09-01       U
                       2008-03-31   P00000005       1982-09-01       U
                       2009-03-31   P00000005       1982-09-01       U
                       2010-03-31   P00000005       1982-09-01       U
...                                       ...              ...     ...
HIGHWAYS   P00118177   2023-03-31   P00118177       2022-09-14       U
                       2024-03-31   P00118177       2022-09-14       U
MAXESTATES P00118252   2024-03-31   P00118252       2024-03-27       U
EPACK      P00118305   2024-03-31   P00118305       2023-07-29       U
           P00118306   2024-03-31   P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  OpBalUnc  \
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31         0         0         1         0
                       2007-03-31         0         0         1         0
                       2008-03-31         0         0         1         0
                       2009-03-31         0         0         1         0
                       2010-03-31         0         0         1         0
...                                     ...       ...       ...       ...
HIGHWAYS   P00118177   2023-03-31         0         0         1         0
                       2024-03-31         0         0         1         0
MAXESTATES P00118252   2024-03-31         0         0         1         0
EPACK      P00118305   2024-03-31         0         0         1         0
           P00118306   2024-03-31         0         0         1         0

                                   OpBalIndep  OpBalNonIndep
Symbol     Person Code AsOnDate
AEGISCHEM  P00000005   2006-03-31           0              0
                       2007-03-31           0              0
                       2008-03-31           0              0
                       2009-03-31           0              0
                       2010-03-31           0              0
...                                       ...            ...
HIGHWAYS   P00118177   2023-03-31           0              0
                       2024-03-31           0              0
MAXESTATES P00118252   2024-03-31           0              0
EPACK      P00118305   2024-03-31           0              0
           P00118306   2024-03-31           0              0

[446434 rows x 12 columns]

In [18]:
def OpBal1(frame):
    if (frame['IsIndep'].iloc[0] == 'U'):
        frame['OpBalUnc'] = (frame.loc[ frame['IsIndep'] == 'U']['AsOnDate'].min() - frame['Appointment Date']).dt.days
    
    elif (frame['IsIndep'].iloc[0] == 'Y'):
        frame['OpBalIndep'] = (frame.loc[ frame['IsIndep'] == 'Y']['AsOnDate'].min() - frame['Appointment Date']).dt.days
    
    elif (frame['IsIndep'].iloc[0] == 'N'):
        frame['OpBalNonIndep'] = (frame.loc[ frame['IsIndep'] == 'N']['AsOnDate'].min() - frame['Appointment Date']).dt.days

    frame['cumsum_U'] = np.cumsum(frame['cumsum_U'])
    frame['cumsum_Y'] = np.cumsum(frame['cumsum_Y'])
    frame['cumsum_N'] = np.cumsum(frame['cumsum_N'])
    return (frame)

In [19]:
def OpBal2(frame):
   
    frame.loc[ (frame['cumsum_U'] > 0 ) , 'OpBalUnc' ] += (frame['cumsum_U'] - 1) * 365
    
    
    frame.loc[ (frame['cumsum_Y'] > 0 ) , 'OpBalIndep' ] += (frame['cumsum_Y'] - 1) * 365
    
    
    frame.loc[ (frame['cumsum_N'] > 0 ) , 'OpBalNonIndep' ] += (frame['cumsum_N'] - 1) * 365
        
    return (frame)

In [20]:
check1 = dfes.groupby( level = ['Symbol', 'Person Code'] ).progress_apply(OpBal1)

100%|███████████████████████████████████████████████████████████████████████████| 50531/50531 [04:52<00:00, 172.54it/s]

In [21]:
check2 = check1.groupby( level = ['Symbol', 'Person Code'] ).progress_apply(OpBal2)

100%|████████████████████████████████████████████████████████████████████████████| 50531/50531 [11:45<00:00, 71.62it/s]

In [22]:
check1

                                                           Symbol   AsOnDate  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31  20MICRONS 2024-03-31
          P00027633   20MICRONS P00027633   2009-03-31  20MICRONS 2009-03-31
                                            2010-03-31  20MICRONS 2010-03-31
                                            2011-03-31  20MICRONS 2011-03-31
                                            2012-03-31  20MICRONS 2012-03-31
...                                                           ...        ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31      ZYLOG 2018-03-31
          P00080494   ZYLOG     P00080494   2017-03-31      ZYLOG 2017-03-31
                                            2018-03-31      ZYLOG 2018-03-31
          P00081419   ZYLOG     P00081419   2017-03-31      ZYLOG 2017-03-31
                                            2018-03-31      ZYLOG 2018-03-31

                                                       PrevLastServed  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31            NaT
          P00027633   20MICRONS P00027633   2009-03-31            NaT
                                            2010-03-31     2009-03-31
                                            2011-03-31     2010-03-31
                                            2012-03-31     2011-03-31
...                                                               ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31     2017-03-31
          P00080494   ZYLOG     P00080494   2017-03-31            NaT
                                            2018-03-31     2017-03-31
          P00081419   ZYLOG     P00081419   2017-03-31            NaT
                                            2018-03-31     2017-03-31

                                                       Person Code  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31   P00004449
          P00027633   20MICRONS P00027633   2009-03-31   P00027633
                                            2010-03-31   P00027633
                                            2011-03-31   P00027633
                                            2012-03-31   P00027633
...                                                            ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31   P00075400
          P00080494   ZYLOG     P00080494   2017-03-31   P00080494
                                            2018-03-31   P00080494
          P00081419   ZYLOG     P00081419   2017-03-31   P00081419
                                            2018-03-31   P00081419

                                                       Appointment Date  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31       2023-05-16
          P00027633   20MICRONS P00027633   2009-03-31       2007-10-13
                                            2010-03-31       2007-10-13
                                            2011-03-31       2007-10-13
                                            2012-03-31       2007-10-13
...                                                                 ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       2015-11-25
          P00080494   ZYLOG     P00080494   2017-03-31       2016-11-23
                                            2018-03-31       2016-11-23
          P00081419   ZYLOG     P00081419   2017-03-31       2017-02-10
                                            2018-03-31       2017-02-10

                                                       IsIndep  cumsum_N  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31       Y         0
          P00027633   20MICRONS P00027633   2009-03-31       U         0
                                            2010-03-31       U         0
                                            2011-03-31       U         0
                                            2012-03-31       U         0
...                                                        ...       ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       Y         0
          P00080494   ZYLOG     P00080494   2017-03-31       Y         0
                                            2018-03-31       Y         0
          P00081419   ZYLOG     P00081419   2017-03-31       Y         0
                                            2018-03-31       Y         0

                                                        cumsum_Y  cumsum_U  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31         1         0
          P00027633   20MICRONS P00027633   2009-03-31         0         1
                                            2010-03-31         0         2
                                            2011-03-31         0         3
                                            2012-03-31         0         4
...                                                          ...       ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31         3         0
          P00080494   ZYLOG     P00080494   2017-03-31         1         0
                                            2018-03-31         2         0
          P00081419   ZYLOG     P00081419   2017-03-31         1         0
                                            2018-03-31         2         0

                                                        OpBalUnc  OpBalIndep  \
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31       0.0       320.0
          P00027633   20MICRONS P00027633   2009-03-31     535.0         0.0
                                            2010-03-31     535.0         0.0
                                            2011-03-31     535.0         0.0
                                            2012-03-31     535.0         0.0
...                                                          ...         ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       0.0       127.0
          P00080494   ZYLOG     P00080494   2017-03-31       0.0       128.0
                                            2018-03-31       0.0       128.0
          P00081419   ZYLOG     P00081419   2017-03-31       0.0        49.0
                                            2018-03-31       0.0        49.0

                                                        OpBalNonIndep
Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   2024-03-31            0.0
          P00027633   20MICRONS P00027633   2009-03-31            0.0
                                            2010-03-31            0.0
                                            2011-03-31            0.0
                                            2012-03-31            0.0
...                                                               ...
ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31            0.0
          P00080494   ZYLOG     P00080494   2017-03-31            0.0
                                            2018-03-31            0.0
          P00081419   ZYLOG     P00081419   2017-03-31            0.0
                                            2018-03-31            0.0

[446434 rows x 12 columns]

In [23]:
check2['OpBalTotal'] = check2['OpBalUnc'] + check2['OpBalIndep'] + check2['OpBalNonIndep']

In [24]:
check2.insert(13, 'CloBalUnc', 0)
check2.insert(14, 'CloBalIndep', 0)
check2.insert(15, 'CloBalNonIndep', 0)
check2.insert(16, 'CloBalTotal', 0)

check2['CloBalUnc'] = check2['OpBalUnc']
check2['CloBalIndep'] = check2['OpBalIndep']
check2['CloBalNonIndep'] = check2['OpBalNonIndep']

check2.loc[ (check2['IsIndep'] == 'U'),'CloBalUnc'] += (365 + check2['OpBalUnc'])
check2.loc[ check2['IsIndep'] == 'Y','CloBalIndep'] += (365 + check2['OpBalIndep'])
check2.loc[ check2['IsIndep'] == 'N','CloBalNonIndep'] += (365 + check2['OpBalNonIndep'])
check2['CloBalTotal'] = check2['CloBalUnc'] + check2['CloBalIndep'] + check2['CloBalNonIndep']

In [25]:
check2

                                                                                 Symbol  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31  20MICRONS
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31  20MICRONS
                                                                  2010-03-31  20MICRONS
                                                                  2011-03-31  20MICRONS
                                                                  2012-03-31  20MICRONS
...                                                                                 ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31      ZYLOG
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31      ZYLOG
                                                                  2018-03-31      ZYLOG
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31      ZYLOG
                                                                  2018-03-31      ZYLOG

                                                                               AsOnDate  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31 2024-03-31
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31 2009-03-31
                                                                  2010-03-31 2010-03-31
                                                                  2011-03-31 2011-03-31
                                                                  2012-03-31 2012-03-31
...                                                                                 ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31 2018-03-31
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31 2017-03-31
                                                                  2018-03-31 2018-03-31
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31 2017-03-31
                                                                  2018-03-31 2018-03-31

                                                                             PrevLastServed  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31            NaT
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31            NaT
                                                                  2010-03-31     2009-03-31
                                                                  2011-03-31     2010-03-31
                                                                  2012-03-31     2011-03-31
...                                                                                     ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31     2017-03-31
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31            NaT
                                                                  2018-03-31     2017-03-31
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31            NaT
                                                                  2018-03-31     2017-03-31

                                                                             Person Code  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31   P00004449
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31   P00027633
                                                                  2010-03-31   P00027633
                                                                  2011-03-31   P00027633
                                                                  2012-03-31   P00027633
...                                                                                  ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31   P00075400
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31   P00080494
                                                                  2018-03-31   P00080494
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31   P00081419
                                                                  2018-03-31   P00081419

                                                                             Appointment Date  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       2023-05-16
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31       2007-10-13
                                                                  2010-03-31       2007-10-13
                                                                  2011-03-31       2007-10-13
                                                                  2012-03-31       2007-10-13
...                                                                                       ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       2015-11-25
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31       2016-11-23
                                                                  2018-03-31       2016-11-23
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31       2017-02-10
                                                                  2018-03-31       2017-02-10

                                                                             IsIndep  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       Y
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31       U
                                                                  2010-03-31       U
                                                                  2011-03-31       U
                                                                  2012-03-31       U
...                                                                              ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       Y
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31       Y
                                                                  2018-03-31       Y
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31       Y
                                                                  2018-03-31       Y

                                                                              cumsum_N  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31         0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31         0
                                                                  2010-03-31         0
                                                                  2011-03-31         0
                                                                  2012-03-31         0
...                                                                                ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31         0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31         0
                                                                  2018-03-31         0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31         0
                                                                  2018-03-31         0

                                                                              cumsum_Y  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31         1
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31         0
                                                                  2010-03-31         0
                                                                  2011-03-31         0
                                                                  2012-03-31         0
...                                                                                ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31         3
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31         1
                                                                  2018-03-31         2
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31         1
                                                                  2018-03-31         2

                                                                              cumsum_U  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31         0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31         1
                                                                  2010-03-31         2
                                                                  2011-03-31         3
                                                                  2012-03-31         4
...                                                                                ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31         0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31         0
                                                                  2018-03-31         0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31         0
                                                                  2018-03-31         0

                                                                              OpBalUnc  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       0.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31     535.0
                                                                  2010-03-31     900.0
                                                                  2011-03-31    1265.0
                                                                  2012-03-31    1630.0
...                                                                                ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       0.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31       0.0
                                                                  2018-03-31       0.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31       0.0
                                                                  2018-03-31       0.0

                                                                              OpBalIndep  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       320.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31         0.0
                                                                  2010-03-31         0.0
                                                                  2011-03-31         0.0
                                                                  2012-03-31         0.0
...                                                                                  ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       857.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31       128.0
                                                                  2018-03-31       493.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31        49.0
                                                                  2018-03-31       414.0

                                                                              OpBalNonIndep  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31            0.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31            0.0
                                                                  2010-03-31            0.0
                                                                  2011-03-31            0.0
                                                                  2012-03-31            0.0
...                                                                                     ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31            0.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31            0.0
                                                                  2018-03-31            0.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31            0.0
                                                                  2018-03-31            0.0

                                                                              OpBalTotal  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       320.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31       535.0
                                                                  2010-03-31       900.0
                                                                  2011-03-31      1265.0
                                                                  2012-03-31      1630.0
...                                                                                  ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       857.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31       128.0
                                                                  2018-03-31       493.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31        49.0
                                                                  2018-03-31       414.0

                                                                              CloBalUnc  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31        0.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31     1435.0
                                                                  2010-03-31     2165.0
                                                                  2011-03-31     2895.0
                                                                  2012-03-31     3625.0
...                                                                                 ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31        0.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31        0.0
                                                                  2018-03-31        0.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31        0.0
                                                                  2018-03-31        0.0

                                                                              CloBalIndep  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       1005.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31          0.0
                                                                  2010-03-31          0.0
                                                                  2011-03-31          0.0
                                                                  2012-03-31          0.0
...                                                                                   ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       2079.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31        621.0
                                                                  2018-03-31       1351.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31        463.0
                                                                  2018-03-31       1193.0

                                                                              CloBalNonIndep  \
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31             0.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31             0.0
                                                                  2010-03-31             0.0
                                                                  2011-03-31             0.0
                                                                  2012-03-31             0.0
...                                                                                      ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31             0.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31             0.0
                                                                  2018-03-31             0.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31             0.0
                                                                  2018-03-31             0.0

                                                                              CloBalTotal
Symbol    Person Code Symbol    Person Code Symbol    Person Code AsOnDate
20MICRONS P00004449   20MICRONS P00004449   20MICRONS P00004449   2024-03-31       1005.0
          P00027633   20MICRONS P00027633   20MICRONS P00027633   2009-03-31       1435.0
                                                                  2010-03-31       2165.0
                                                                  2011-03-31       2895.0
                                                                  2012-03-31       3625.0
...                                                                                   ...
ZYLOG     P00075400   ZYLOG     P00075400   ZYLOG     P00075400   2018-03-31       2079.0
          P00080494   ZYLOG     P00080494   ZYLOG     P00080494   2017-03-31        621.0
                                                                  2018-03-31       1351.0
          P00081419   ZYLOG     P00081419   ZYLOG     P00081419   2017-03-31        463.0
                                                                  2018-03-31       1193.0

[446434 rows x 17 columns]

In [26]:
check2.to_csv('Main_Manager_Calc v070824.1.csv')