In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_csv('Main_Manager_Calc v280824.1.csv')

In [3]:
df1

,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal
0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0
1,P00000005,AEGISCHEM,1,AEGISCHEM,2007-03-31,2006-03-31,P00000005,1982-09-01,U,0,0,2,9342.0,0,0,9342.0,8977.0,0,0,8977.0
2,P00000005,AEGISCHEM,2,AEGISCHEM,2008-03-31,2007-03-31,P00000005,1982-09-01,U,0,0,3,9707.0,0,0,9707.0,9342.0,0,0,9342.0
3,P00000005,AEGISCHEM,3,AEGISCHEM,2009-03-31,2008-03-31,P00000005,1982-09-01,U,0,0,4,10072.0,0,0,10072.0,9707.0,0,0,9707.0
4,P00000005,AEGISCHEM,4,AEGISCHEM,2010-03-31,2009-03-31,P00000005,1982-09-01,U,0,0,5,10437.0,0,0,10437.0,10072.0,0,0,10072.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0
446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0
446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0
446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0
446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0

In [4]:
df2 = df1.set_index(['Person Code', 'AsOnDate', 'Symbol'], drop = False)
df2.insert(len(df2.columns), column = 'YOE', value = 0)
df2

                                  Person Code      Symbol  Unnamed: 2  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM    P00000005   AEGISCHEM           0
            2007-03-31 AEGISCHEM    P00000005   AEGISCHEM           1
            2008-03-31 AEGISCHEM    P00000005   AEGISCHEM           2
            2009-03-31 AEGISCHEM    P00000005   AEGISCHEM           3
            2010-03-31 AEGISCHEM    P00000005   AEGISCHEM           4
...                                       ...         ...         ...
P00118177   2023-03-31 HIGHWAYS     P00118177    HIGHWAYS      446429
            2024-03-31 HIGHWAYS     P00118177    HIGHWAYS      446430
P00118252   2024-03-31 MAXESTATES   P00118252  MAXESTATES      446431
P00118305   2024-03-31 EPACK        P00118305       EPACK      446432
P00118306   2024-03-31 EPACK        P00118306       EPACK      446433

                                     Symbol.1    AsOnDate PrevLastServed  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM    AEGISCHEM  2006-03-31            NaN
            2007-03-31 AEGISCHEM    AEGISCHEM  2007-03-31     2006-03-31
            2008-03-31 AEGISCHEM    AEGISCHEM  2008-03-31     2007-03-31
            2009-03-31 AEGISCHEM    AEGISCHEM  2009-03-31     2008-03-31
            2010-03-31 AEGISCHEM    AEGISCHEM  2010-03-31     2009-03-31
...                                       ...         ...            ...
P00118177   2023-03-31 HIGHWAYS      HIGHWAYS  2023-03-31            NaN
            2024-03-31 HIGHWAYS      HIGHWAYS  2024-03-31     2023-03-31
P00118252   2024-03-31 MAXESTATES  MAXESTATES  2024-03-31            NaN
P00118305   2024-03-31 EPACK            EPACK  2024-03-31            NaN
P00118306   2024-03-31 EPACK            EPACK  2024-03-31            NaN

                                  Person Code.1 Appointment Date IsIndep  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2007-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2008-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2009-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2010-03-31 AEGISCHEM      P00000005       1982-09-01       U
...                                         ...              ...     ...
P00118177   2023-03-31 HIGHWAYS       P00118177       2022-09-14       U
            2024-03-31 HIGHWAYS       P00118177       2022-09-14       U
P00118252   2024-03-31 MAXESTATES     P00118252       2024-03-27       U
P00118305   2024-03-31 EPACK          P00118305       2023-07-29       U
P00118306   2024-03-31 EPACK          P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  CloBalUnc  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM          0         0         1     8977.0
            2007-03-31 AEGISCHEM          0         0         2     9342.0
            2008-03-31 AEGISCHEM          0         0         3     9707.0
            2009-03-31 AEGISCHEM          0         0         4    10072.0
            2010-03-31 AEGISCHEM          0         0         5    10437.0
...                                     ...       ...       ...        ...
P00118177   2023-03-31 HIGHWAYS           0         0         1      563.0
            2024-03-31 HIGHWAYS           0         0         2      928.0
P00118252   2024-03-31 MAXESTATES         0         0         1      369.0
P00118305   2024-03-31 EPACK              0         0         1      611.0
P00118306   2024-03-31 EPACK              0         0         1     2118.0

                                   CloBalIndep  CloBalNonIndep  CloBalTotal  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM             0               0       8977.0
            2007-03-31 AEGISCHEM             0               0       9342.0
            2008-03-31 AEGISCHEM             0               0       9707.0
            2009-03-31 AEGISCHEM             0               0      10072.0
            2010-03-31 AEGISCHEM             0               0      10437.0
...                                        ...             ...          ...
P00118177   2023-03-31 HIGHWAYS              0               0        563.0
            2024-03-31 HIGHWAYS              0               0        928.0
P00118252   2024-03-31 MAXESTATES            0               0        369.0
P00118305   2024-03-31 EPACK                 0               0        611.0
P00118306   2024-03-31 EPACK                 0               0       2118.0

                                   OpBalUnc  OpBalIndep  OpBalNonIndep  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM     8612.0           0              0
            2007-03-31 AEGISCHEM     8977.0           0              0
            2008-03-31 AEGISCHEM     9342.0           0              0
            2009-03-31 AEGISCHEM     9707.0           0              0
            2010-03-31 AEGISCHEM    10072.0           0              0
...                                     ...         ...            ...
P00118177   2023-03-31 HIGHWAYS       198.0           0              0
            2024-03-31 HIGHWAYS       563.0           0              0
P00118252   2024-03-31 MAXESTATES       4.0           0              0
P00118305   2024-03-31 EPACK          246.0           0              0
P00118306   2024-03-31 EPACK         1753.0           0              0

                                   OpBalTotal  YOE
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM       8612.0    0
            2007-03-31 AEGISCHEM       8977.0    0
            2008-03-31 AEGISCHEM       9342.0    0
            2009-03-31 AEGISCHEM       9707.0    0
            2010-03-31 AEGISCHEM      10072.0    0
...                                       ...  ...
P00118177   2023-03-31 HIGHWAYS         198.0    0
            2024-03-31 HIGHWAYS         563.0    0
P00118252   2024-03-31 MAXESTATES         4.0    0
P00118305   2024-03-31 EPACK            246.0    0
P00118306   2024-03-31 EPACK           1753.0    0

[446434 rows x 21 columns]

In [5]:
df2['AsOnDate'] = pd.to_datetime(df2['AsOnDate'], format = '%Y-%m-%d')

df2['Appointment Date'] = pd.to_datetime(df2['Appointment Date'], format = '%Y-%m-%d')

In [6]:
df2['YOE'] = (df2['AsOnDate'] - df2['Appointment Date']).dt.days

In [7]:
df2

                                  Person Code      Symbol  Unnamed: 2  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM    P00000005   AEGISCHEM           0
            2007-03-31 AEGISCHEM    P00000005   AEGISCHEM           1
            2008-03-31 AEGISCHEM    P00000005   AEGISCHEM           2
            2009-03-31 AEGISCHEM    P00000005   AEGISCHEM           3
            2010-03-31 AEGISCHEM    P00000005   AEGISCHEM           4
...                                       ...         ...         ...
P00118177   2023-03-31 HIGHWAYS     P00118177    HIGHWAYS      446429
            2024-03-31 HIGHWAYS     P00118177    HIGHWAYS      446430
P00118252   2024-03-31 MAXESTATES   P00118252  MAXESTATES      446431
P00118305   2024-03-31 EPACK        P00118305       EPACK      446432
P00118306   2024-03-31 EPACK        P00118306       EPACK      446433

                                     Symbol.1   AsOnDate PrevLastServed  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM    AEGISCHEM 2006-03-31            NaN
            2007-03-31 AEGISCHEM    AEGISCHEM 2007-03-31     2006-03-31
            2008-03-31 AEGISCHEM    AEGISCHEM 2008-03-31     2007-03-31
            2009-03-31 AEGISCHEM    AEGISCHEM 2009-03-31     2008-03-31
            2010-03-31 AEGISCHEM    AEGISCHEM 2010-03-31     2009-03-31
...                                       ...        ...            ...
P00118177   2023-03-31 HIGHWAYS      HIGHWAYS 2023-03-31            NaN
            2024-03-31 HIGHWAYS      HIGHWAYS 2024-03-31     2023-03-31
P00118252   2024-03-31 MAXESTATES  MAXESTATES 2024-03-31            NaN
P00118305   2024-03-31 EPACK            EPACK 2024-03-31            NaN
P00118306   2024-03-31 EPACK            EPACK 2024-03-31            NaN

                                  Person Code.1 Appointment Date IsIndep  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2007-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2008-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2009-03-31 AEGISCHEM      P00000005       1982-09-01       U
            2010-03-31 AEGISCHEM      P00000005       1982-09-01       U
...                                         ...              ...     ...
P00118177   2023-03-31 HIGHWAYS       P00118177       2022-09-14       U
            2024-03-31 HIGHWAYS       P00118177       2022-09-14       U
P00118252   2024-03-31 MAXESTATES     P00118252       2024-03-27       U
P00118305   2024-03-31 EPACK          P00118305       2023-07-29       U
P00118306   2024-03-31 EPACK          P00118306       2019-06-13       U

                                   cumsum_N  cumsum_Y  cumsum_U  CloBalUnc  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM          0         0         1     8977.0
            2007-03-31 AEGISCHEM          0         0         2     9342.0
            2008-03-31 AEGISCHEM          0         0         3     9707.0
            2009-03-31 AEGISCHEM          0         0         4    10072.0
            2010-03-31 AEGISCHEM          0         0         5    10437.0
...                                     ...       ...       ...        ...
P00118177   2023-03-31 HIGHWAYS           0         0         1      563.0
            2024-03-31 HIGHWAYS           0         0         2      928.0
P00118252   2024-03-31 MAXESTATES         0         0         1      369.0
P00118305   2024-03-31 EPACK              0         0         1      611.0
P00118306   2024-03-31 EPACK              0         0         1     2118.0

                                   CloBalIndep  CloBalNonIndep  CloBalTotal  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM             0               0       8977.0
            2007-03-31 AEGISCHEM             0               0       9342.0
            2008-03-31 AEGISCHEM             0               0       9707.0
            2009-03-31 AEGISCHEM             0               0      10072.0
            2010-03-31 AEGISCHEM             0               0      10437.0
...                                        ...             ...          ...
P00118177   2023-03-31 HIGHWAYS              0               0        563.0
            2024-03-31 HIGHWAYS              0               0        928.0
P00118252   2024-03-31 MAXESTATES            0               0        369.0
P00118305   2024-03-31 EPACK                 0               0        611.0
P00118306   2024-03-31 EPACK                 0               0       2118.0

                                   OpBalUnc  OpBalIndep  OpBalNonIndep  \
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM     8612.0           0              0
            2007-03-31 AEGISCHEM     8977.0           0              0
            2008-03-31 AEGISCHEM     9342.0           0              0
            2009-03-31 AEGISCHEM     9707.0           0              0
            2010-03-31 AEGISCHEM    10072.0           0              0
...                                     ...         ...            ...
P00118177   2023-03-31 HIGHWAYS       198.0           0              0
            2024-03-31 HIGHWAYS       563.0           0              0
P00118252   2024-03-31 MAXESTATES       4.0           0              0
P00118305   2024-03-31 EPACK          246.0           0              0
P00118306   2024-03-31 EPACK         1753.0           0              0

                                   OpBalTotal      YOE
Person Code AsOnDate   Symbol
P00000005   2006-03-31 AEGISCHEM       8612.0   8612.0
            2007-03-31 AEGISCHEM       8977.0   8977.0
            2008-03-31 AEGISCHEM       9342.0   9343.0
            2009-03-31 AEGISCHEM       9707.0   9708.0
            2010-03-31 AEGISCHEM      10072.0  10073.0
...                                       ...      ...
P00118177   2023-03-31 HIGHWAYS         198.0    198.0
            2024-03-31 HIGHWAYS         563.0    564.0
P00118252   2024-03-31 MAXESTATES         4.0      4.0
P00118305   2024-03-31 EPACK            246.0    246.0
P00118306   2024-03-31 EPACK           1753.0   1753.0

[446434 rows x 21 columns]

In [8]:
def YOE(frame):
    return frame['YOE'].max()

In [9]:
YOEmax = df2.groupby(level = ['Person Code', 'AsOnDate']).progress_apply(YOE)

100%|████████████████████████████████████████████████████████████████████████| 326534/326534 [00:55<00:00, 5865.52it/s]

In [10]:
YOEmax = YOEmax.reset_index()
YOEmax

       Person Code    AsOnDate        0
0        P00000005  2006-03-31   8612.0
1        P00000005  2007-03-31   8977.0
2        P00000005  2008-03-31   9343.0
3        P00000005  2009-03-31   9708.0
4        P00000005  2010-03-31  10073.0
...            ...         ...      ...
326529   P00118177  2023-03-31    198.0
326530   P00118177  2024-03-31    564.0
326531   P00118252  2024-03-31      4.0
326532   P00118305  2024-03-31    246.0
326533   P00118306  2024-03-31   1753.0

[326534 rows x 3 columns]

In [11]:
df2['AsOnDate'] = pd.to_datetime(df2['AsOnDate'], format = '%Y-%m-%d')
YOEmax['AsOnDate'] = pd.to_datetime(YOEmax['AsOnDate'], format = '%Y-%m-%d')


df3 = df2.reset_index(drop = True).merge(YOEmax, on = ['Person Code', 'AsOnDate'], how = 'left')
df3 = df3.rename(columns = {0 : "YOEmax"})
df3

,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax
0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0
1,P00000005,AEGISCHEM,1,AEGISCHEM,2007-03-31,2006-03-31,P00000005,1982-09-01,U,0,0,2,9342.0,0,0,9342.0,8977.0,0,0,8977.0,8977.0,8977.0
2,P00000005,AEGISCHEM,2,AEGISCHEM,2008-03-31,2007-03-31,P00000005,1982-09-01,U,0,0,3,9707.0,0,0,9707.0,9342.0,0,0,9342.0,9343.0,9343.0
3,P00000005,AEGISCHEM,3,AEGISCHEM,2009-03-31,2008-03-31,P00000005,1982-09-01,U,0,0,4,10072.0,0,0,10072.0,9707.0,0,0,9707.0,9708.0,9708.0
4,P00000005,AEGISCHEM,4,AEGISCHEM,2010-03-31,2009-03-31,P00000005,1982-09-01,U,0,0,5,10437.0,0,0,10437.0,10072.0,0,0,10072.0,10073.0,10073.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0
446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0
446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0
446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0
446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0

In [12]:
df3.loc[ df3['YOEmax'] <= 365*3, 'IsRookie'] = 'Y'
df3.loc[ df3['YOEmax'] > 365*3, 'IsRookie'] = 'N'

df3

,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie
0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N
1,P00000005,AEGISCHEM,1,AEGISCHEM,2007-03-31,2006-03-31,P00000005,1982-09-01,U,0,0,2,9342.0,0,0,9342.0,8977.0,0,0,8977.0,8977.0,8977.0,N
2,P00000005,AEGISCHEM,2,AEGISCHEM,2008-03-31,2007-03-31,P00000005,1982-09-01,U,0,0,3,9707.0,0,0,9707.0,9342.0,0,0,9342.0,9343.0,9343.0,N
3,P00000005,AEGISCHEM,3,AEGISCHEM,2009-03-31,2008-03-31,P00000005,1982-09-01,U,0,0,4,10072.0,0,0,10072.0,9707.0,0,0,9707.0,9708.0,9708.0,N
4,P00000005,AEGISCHEM,4,AEGISCHEM,2010-03-31,2009-03-31,P00000005,1982-09-01,U,0,0,5,10437.0,0,0,10437.0,10072.0,0,0,10072.0,10073.0,10073.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y
446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y
446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y
446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y
446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N

In [13]:
frame2 = pd.DataFrame(columns = ['Symbol', 'AsOnDate', 'Total', 'Rookie'])
frame2

Empty DataFrame
Columns: [Symbol, AsOnDate, Total, Rookie]
Index: []

In [14]:
def RookieCount(frame):
    frame2 = pd.DataFrame()
    frame2['Symbol'] = frame['Symbol']
    frame2['AsOnDate'] = frame['AsOnDate']
    frame2['Total'] = frame['Person Code'].count()
    frame2['Rookie'] = frame.loc[ frame['IsRookie'] == 'Y']['Person Code'].count()
    return frame2

In [15]:
FL = df3.set_index(['Symbol', 'AsOnDate'], drop = False).groupby( level = ['Symbol','AsOnDate'] ).progress_apply(RookieCount)

100%|███████████████████████████████████████████████████████████████████████████| 28899/28899 [01:50<00:00, 262.67it/s]

In [16]:
FL = FL.reset_index(drop = True).drop_duplicates().reset_index(drop = True)

In [17]:
df3.to_csv("Main_Manager_Calc_n_Rookie Classification v280824.1.csv")
FL.to_csv("Main_Firm_Rookie Count v280824.1.csv")