In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
import datetime as dt
pd.set_option('display.max_columns', None)

In [2]:
dfRC = pd.read_csv('Main_Manager_Calc_n_Rookie Classification v280824.1.csv')

In [3]:
df1 = dfRC.copy()

In [4]:
df1['CountOtherPastUnclear'] = 0
df1['CountOtherPastIndep'] = 0
df1['CountOtherPastNonIndep'] = 0
df1['CompCountOtherPastTotal'] = 0
df1['CountCurrUnclear'] = 0
df1['CountCurrIndep'] = 0
df1['CountCurrNonIndep'] = 0
df1['CompCountCurrTotal'] = 0
df1['CountCompaniesTotal'] = 0

df1['AsOnDate'] = pd.to_datetime(df1['AsOnDate'], format = '%Y-%m-%d')
df1

,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal
0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,0,0,0,0,0,0,0,0,0
1,1,P00000005,AEGISCHEM,1,AEGISCHEM,2007-03-31,2006-03-31,P00000005,1982-09-01,U,0,0,2,9342.0,0,0,9342.0,8977.0,0,0,8977.0,8977.0,8977.0,N,0,0,0,0,0,0,0,0,0
2,2,P00000005,AEGISCHEM,2,AEGISCHEM,2008-03-31,2007-03-31,P00000005,1982-09-01,U,0,0,3,9707.0,0,0,9707.0,9342.0,0,0,9342.0,9343.0,9343.0,N,0,0,0,0,0,0,0,0,0
3,3,P00000005,AEGISCHEM,3,AEGISCHEM,2009-03-31,2008-03-31,P00000005,1982-09-01,U,0,0,4,10072.0,0,0,10072.0,9707.0,0,0,9707.0,9708.0,9708.0,N,0,0,0,0,0,0,0,0,0
4,4,P00000005,AEGISCHEM,4,AEGISCHEM,2010-03-31,2009-03-31,P00000005,1982-09-01,U,0,0,5,10437.0,0,0,10437.0,10072.0,0,0,10072.0,10073.0,10073.0,N,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,0,0,0,0,0,0,0,0,0
446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,0,0,0,0,0,0,0,0,0
446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,0,0,0,0,0,0,0,0,0
446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,0,0,0,0,0,0,0,0,0
446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,0,0,0,0,0,0,0,0,0

In [5]:
df2 = pd.read_csv('Main_Manager_OtherDirect.csv')
df2

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_29756\646547759.py:1: DtypeWarning: Columns (17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('Main_Manager_OtherDirect.csv')

,Symbol,Person Code,AsOnDate,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15
0,20MICRONS,P00004449,31-03-2024,20 MICRONS LTD.,20 MICRONS LTD.,APCOTEX INDUSTRIES LTD.,SUPREME PETROCHEM LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20MICRONS,P00027633,31-03-2009,20 MICRONS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20MICRONS,P00027633,31-03-2010,20 MICRONS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20MICRONS,P00027633,31-03-2011,20 MICRONS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20MICRONS,P00027633,31-03-2012,20 MICRONS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,ZYLOG,P00075400,31-03-2018,ZYLOG SYSTEMS LTD.,ZYLOG SYSTEMS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,ZYLOG,P00080494,31-03-2017,ZYLOG SYSTEMS LTD.,ZYLOG SYSTEMS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,ZYLOG,P00080494,31-03-2018,ZYLOG SYSTEMS LTD.,ZYLOG SYSTEMS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,ZYLOG,P00081419,31-03-2017,ZYLOG SYSTEMS LTD.,ZYLOG SYSTEMS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,ZYLOG,P00081419,31-03-2018,ZYLOG SYSTEMS LTD.,ZYLOG SYSTEMS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df3 = df2.copy()
df3['AsOnDate'] = pd.to_datetime(df3['AsOnDate'], format = '%d-%m-%Y')

In [7]:
df4 = df1.merge(df3, on = ['Person Code', 'Symbol', 'AsOnDate'], how = 'inner')
df4 = df4.reset_index().sort_values(by = 'Person Code')
dff4 = df4.head(n=5000)
df4

,index,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446430,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446429,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,0,0,0,0,0,0,0,0,0,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
cols = ['Other Directorship 1', 'Other Directorship 2', 'Other Directorship 3', 'Other Directorship 4', 'Other Directorship 5', 'Other Directorship 6', 'Other Directorship 7', 'Other Directorship 8', 'Other Directorship 9', 'Other Directorship 10', 'Other Directorship 11', 'Other Directorship 12', 'Other Directorship 13', 'Other Directorship 14', 'Other Directorship 15']

In [9]:
df4.to_csv("Check.csv")

In [10]:
frame2 = pd.DataFrame(columns = [s + 'Stat' for s in cols])
frame2

Empty DataFrame
Columns: [Other Directorship 1Stat, Other Directorship 2Stat, Other Directorship 3Stat, Other Directorship 4Stat, Other Directorship 5Stat, Other Directorship 6Stat, Other Directorship 7Stat, Other Directorship 8Stat, Other Directorship 9Stat, Other Directorship 10Stat, Other Directorship 11Stat, Other Directorship 12Stat, Other Directorship 13Stat, Other Directorship 14Stat, Other Directorship 15Stat]
Index: []

In [11]:
def CurrentDirect2(frame):
    frame2 = pd.DataFrame(columns = [s + 'Stat' for s in cols])
    
    for Dir in frame['Other Directorship 1']:
        if (pd.isnull(frame['Other Directorship 1']) == False):
            frame2['Other Directorship 1Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 2']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 2Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 3']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 3Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 4']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 4Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 5']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 5Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 6']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 6Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 7']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 7Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 8']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 8Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 9']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 9Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 10']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 10Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 11']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 11Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 12']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 12Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 13']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 13Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 14']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 14Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    for Dir in frame['Other Directorship 15']:
        if (pd.isnull(Dir) == False):
            frame2['Other Directorship 15Stat'] = [(Dir, frame.loc[ frame['Company'] == Dir, 'IsIndep'].item())]

    return frame2

In [12]:
def CurrentDirect(frame):
    frame2 = pd.DataFrame(columns = ['Current Direct'])
    
    frame2['Current Direct'] = [list(set(zip(frame.Company, frame.IsIndep)))]

    return frame2

In [13]:
# df10 = df4.groupby(['Person Code', 'AsOnDate']).progress_apply(CurrentDirect)

In [14]:
#df10

In [15]:
def PastDirect(frame):
    frame3 = pd.DataFrame(index = frame.index, columns = ['AsOnDate','Past Directorships'])
    
    for i in range(len(frame)):
        Date = frame.iloc[i]['AsOnDate']
        filtered_frame = frame.loc[ frame['AsOnDate'] < Date , ['Company', 'IsIndep']]
        past_directors = list(zip(filtered_frame['Company'], filtered_frame['IsIndep']))
        past_dir = list(set(past_directors))

        frame3.at[ frame.index[i], 'Past Directorships'] = past_dir
        frame3.at[ frame.index[i], 'AsOnDate'] = Date

    return frame3

In [16]:
df20 = df4.sort_values(by = ['Person Code', 'AsOnDate', 'Company']).groupby('Person Code').progress_apply(PastDirect)

100%|████████████████████████████████████████████████████████████████████████████| 36111/36111 [09:17<00:00, 64.78it/s]

In [17]:
df20

                               AsOnDate                    Past Directorships
Person Code
P00000005   0       2006-03-31 00:00:00                                    []
            1       2007-03-31 00:00:00           [(AEGIS LOGISTICS LTD., U)]
            2       2008-03-31 00:00:00           [(AEGIS LOGISTICS LTD., U)]
            3       2009-03-31 00:00:00           [(AEGIS LOGISTICS LTD., U)]
            4       2010-03-31 00:00:00           [(AEGIS LOGISTICS LTD., U)]
...                                 ...                                   ...
P00118177   446429  2023-03-31 00:00:00                                    []
            446430  2024-03-31 00:00:00  [(HIGHWAYS INFRASTRUCTURE TRUST, U)]
P00118252   446431  2024-03-31 00:00:00                                    []
P00118305   446432  2024-03-31 00:00:00                                    []
P00118306   446433  2024-03-31 00:00:00                                    []

[446434 rows x 2 columns]

In [18]:
df21 = df20.reset_index()
df21

,Person Code,level_1,AsOnDate,Past Directorships
0,P00000005,0,2006-03-31 00:00:00,[]
1,P00000005,1,2007-03-31 00:00:00,"[(AEGIS LOGISTICS LTD., U)]"
2,P00000005,2,2008-03-31 00:00:00,"[(AEGIS LOGISTICS LTD., U)]"
3,P00000005,3,2009-03-31 00:00:00,"[(AEGIS LOGISTICS LTD., U)]"
4,P00000005,4,2010-03-31 00:00:00,"[(AEGIS LOGISTICS LTD., U)]"
...,...,...,...,...
446429,P00118177,446429,2023-03-31 00:00:00,[]
446430,P00118177,446430,2024-03-31 00:00:00,"[(HIGHWAYS INFRASTRUCTURE TRUST, U)]"
446431,P00118252,446431,2024-03-31 00:00:00,[]
446432,P00118305,446432,2024-03-31 00:00:00,[]
446433,P00118306,446433,2024-03-31 00:00:00,[]

In [19]:
df22 = df20.reset_index(drop = False).drop(['level_1'], axis=1)
df22['Past Directorships'] = df22['Past Directorships'].progress_apply(lambda x: tuple(x))
df22

100%|██████████████████████████████████████████████████████████████████████| 446434/446434 [00:00<00:00, 738317.95it/s]

       Person Code             AsOnDate                     Past Directorships
0        P00000005  2006-03-31 00:00:00                                     ()
1        P00000005  2007-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
2        P00000005  2008-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
3        P00000005  2009-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
4        P00000005  2010-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
...            ...                  ...                                    ...
446429   P00118177  2023-03-31 00:00:00                                     ()
446430   P00118177  2024-03-31 00:00:00  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446431   P00118252  2024-03-31 00:00:00                                     ()
446432   P00118305  2024-03-31 00:00:00                                     ()
446433   P00118306  2024-03-31 00:00:00                                     ()

[446434 rows x 3 columns]

In [38]:
df23 = df22.drop_duplicates()
df23

       Person Code             AsOnDate                     Past Directorships
0        P00000005  2006-03-31 00:00:00                                     ()
1        P00000005  2007-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
2        P00000005  2008-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
3        P00000005  2009-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
4        P00000005  2010-03-31 00:00:00           ((AEGIS LOGISTICS LTD., U),)
...            ...                  ...                                    ...
446429   P00118177  2023-03-31 00:00:00                                     ()
446430   P00118177  2024-03-31 00:00:00  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446431   P00118252  2024-03-31 00:00:00                                     ()
446432   P00118305  2024-03-31 00:00:00                                     ()
446433   P00118306  2024-03-31 00:00:00                                     ()

[326534 rows x 3 columns]

In [45]:
df23['AsOnDate'] = pd.to_datetime(df23['AsOnDate'], format = '%Y-%m-%d')

C:\Users\SHIVAM\AppData\Local\Temp\ipykernel_29756\1081135642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df23['AsOnDate'] = pd.to_datetime(df23['AsOnDate'], format = '%Y-%m-%d')

In [46]:
df23['AsOnDate']

0          2006-03-31
1          2007-03-31
2          2008-03-31
3          2009-03-31
4          2010-03-31
              ...
446430     2024-03-31
446431     2024-03-31
446432     2024-03-31
446433     2024-03-31
AsOnDate          NaT
Name: AsOnDate, Length: 326535, dtype: datetime64[ns]

In [22]:
cols = ['Other Directorship 1', 'Other Directorship 2', 'Other Directorship 3', 'Other Directorship 4', 'Other Directorship 5', 'Other Directorship 6', 'Other Directorship 7', 'Other Directorship 8', 'Other Directorship 9', 'Other Directorship 10', 'Other Directorship 11', 'Other Directorship 12', 'Other Directorship 13', 'Other Directorship 14', 'Other Directorship 15']

In [23]:
def CurrentDirect2(group, cols):
    # Ensure cols is a list of column names and that they exist in the DataFrame
    if not all(col in group.columns for col in cols):
        raise ValueError("One or more columns in 'cols' are not in the DataFrame")

    # Create unique list of tuples from 'Company' and 'IsIndep' in the current group
    comp_stat = list(set(zip(group.Company, group.IsIndep)))
    
    # Initialize the new DataFrame
    
    frame2 = pd.DataFrame(index=group.index, columns=['Current Direct'])
    
    # Populate 'Current Direct' column
    for i in range(len(group)):
        # Get the value for each column
        row_values = [str(group[col].iloc[i]) for col in cols]
        # Check if any company from comp_stat is in row_values
        current_direct = [
            item for item in comp_stat if item[0] in row_values
        ]
        frame2.loc[group.index[i], 'Current Direct'] = current_direct
    
    return frame2

In [24]:
df30 = df4.groupby(['Person Code', 'AsOnDate']).progress_apply(CurrentDirect2, cols=cols)

100%|█████████████████████████████████████████████████████████████████████████| 326534/326534 [32:41<00:00, 166.49it/s]

In [25]:
df30

                                                     Current Direct
Person Code AsOnDate
P00000005   2006-03-31 0                                         []
            2007-03-31 1                                         []
            2008-03-31 2                                         []
            2009-03-31 3                                         []
            2010-03-31 4                                         []
...                                                             ...
P00118177   2023-03-31 446429  [(HIGHWAYS INFRASTRUCTURE TRUST, U)]
            2024-03-31 446430  [(HIGHWAYS INFRASTRUCTURE TRUST, U)]
P00118252   2024-03-31 446431               [(MAX ESTATES LTD., U)]
P00118305   2024-03-31 446432             [(EPACK DURABLE LTD., U)]
P00118306   2024-03-31 446433             [(EPACK DURABLE LTD., U)]

[446434 rows x 1 columns]

In [26]:
df31 = df30.reset_index(drop = False).drop(['Person Code', 'AsOnDate'], axis=1).sort_values(by = ['level_2'])
df31

        level_2                        Current Direct
0             0                                    []
1             1                                    []
2             2                                    []
3             3                                    []
4             4                                    []
...         ...                                   ...
446429   446429  [(HIGHWAYS INFRASTRUCTURE TRUST, U)]
446430   446430  [(HIGHWAYS INFRASTRUCTURE TRUST, U)]
446431   446431               [(MAX ESTATES LTD., U)]
446432   446432             [(EPACK DURABLE LTD., U)]
446433   446433             [(EPACK DURABLE LTD., U)]

[446434 rows x 2 columns]

In [27]:
df32 = df30.reset_index(drop = False).drop(['level_2'], axis=1)
df32['Current Direct'] = df32['Current Direct'].progress_apply(lambda x: tuple(x))
df32

100%|██████████████████████████████████████████████████████████████████████| 446434/446434 [00:00<00:00, 800891.67it/s]

       Person Code   AsOnDate                         Current Direct
0        P00000005 2006-03-31                                     ()
1        P00000005 2007-03-31                                     ()
2        P00000005 2008-03-31                                     ()
3        P00000005 2009-03-31                                     ()
4        P00000005 2010-03-31                                     ()
...            ...        ...                                    ...
446429   P00118177 2023-03-31  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446430   P00118177 2024-03-31  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446431   P00118252 2024-03-31               ((MAX ESTATES LTD., U),)
446432   P00118305 2024-03-31             ((EPACK DURABLE LTD., U),)
446433   P00118306 2024-03-31             ((EPACK DURABLE LTD., U),)

[446434 rows x 3 columns]

In [28]:
df33 = df32.drop_duplicates()
df33

       Person Code   AsOnDate                         Current Direct
0        P00000005 2006-03-31                                     ()
1        P00000005 2007-03-31                                     ()
2        P00000005 2008-03-31                                     ()
3        P00000005 2009-03-31                                     ()
4        P00000005 2010-03-31                                     ()
...            ...        ...                                    ...
446429   P00118177 2023-03-31  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446430   P00118177 2024-03-31  ((HIGHWAYS INFRASTRUCTURE TRUST, U),)
446431   P00118252 2024-03-31               ((MAX ESTATES LTD., U),)
446432   P00118305 2024-03-31             ((EPACK DURABLE LTD., U),)
446433   P00118306 2024-03-31             ((EPACK DURABLE LTD., U),)

[326534 rows x 3 columns]

In [29]:
df5 = df4.reset_index().drop(['index'], axis = 1)

In [30]:
df5

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,0,0,0,0,0,0,0,0,0,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df6 = df5.merge(df33, on = ['Person Code', 'AsOnDate'], how = 'outer')
df6

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Current Direct
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,()
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)"
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)"
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)"
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)"
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)"
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,0,0,0,0,0,0,0,0,0,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((MAX ESTATES LTD., U),)"
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)"
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)"

In [40]:
df6.loc[:, 'AsOnDate'] = pd.to_datetime(df6['AsOnDate'], format = '%Y-%m-%d')

In [48]:
df7 = df6.merge(df23, on = ['Person Code', 'AsOnDate'], how = 'inner')
df7

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal,CountCompaniesTotal,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,Current Direct,Past Directorships
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(),()
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,0,0,0,0,0,0,0,0,0,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)","((HIGHWAYS INFRASTRUCTURE TRUST, U),)"
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,0,0,0,0,0,0,0,0,0,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)",()
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,0,0,0,0,0,0,0,0,0,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((MAX ESTATES LTD., U),)",()
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",()
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,0,0,0,0,0,0,0,0,0,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",()

In [49]:
df8 = df7.rename({'Past Directorships':'AllPastDirect', 'Current Direct':'CurrDirect'}, axis = 1).drop(['CountOtherPastUnclear','CountOtherPastIndep',	'CountOtherPastNonIndep',	'CompCountOtherPastTotal',	'CountCurrUnclear',	'CountCurrIndep','CountCurrNonIndep',	'CompCountCurrTotal',	'CountCompaniesTotal'], axis = 1)	
df8

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,CurrDirect,AllPastDirect
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(),()
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)","((HIGHWAYS INFRASTRUCTURE TRUST, U),)"
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)",()
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((MAX ESTATES LTD., U),)",()
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",()
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",()

In [50]:
df8['PastSiezedDirect'] = df8.progress_apply(
    lambda row: tuple(x for x in row['AllPastDirect'] if x not in row['CurrDirect']), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:10<00:00, 41694.73it/s]

In [51]:
df8

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,CurrDirect,AllPastDirect,PastSiezedDirect
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(),(),()
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)"
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)"
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)"
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)","((HIGHWAYS INFRASTRUCTURE TRUST, U),)",()
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)",(),()
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((MAX ESTATES LTD., U),)",(),()
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",(),()
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",(),()

In [52]:
df8['CountOtherPastUnclear'] = df8.progress_apply(
    lambda row: sum(1 for x in row['PastSiezedDirect'] if x[1]=='U'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 75219.35it/s]

In [53]:
df8['CountOtherPastIndep'] = df8.progress_apply(
    lambda row: sum(1 for x in row['PastSiezedDirect'] if x[1]=='Y'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 87942.72it/s]

In [54]:
df8['CountOtherPastNonIndep'] = df8.progress_apply(
    lambda row: sum(1 for x in row['PastSiezedDirect'] if x[1]=='N'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 75005.83it/s]

In [55]:
df8['CompCountOtherPastTotal'] = df8['CountOtherPastUnclear']+df8['CountOtherPastIndep']+df8['CountOtherPastNonIndep']

In [56]:
df8['CountCurrUnclear'] = df8.progress_apply(
    lambda row: sum(1 for x in row['CurrDirect'] if x[1]=='U'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 74824.76it/s]

In [57]:
df8['CountCurrIndep'] = df8.progress_apply(
    lambda row: sum(1 for x in row['CurrDirect'] if x[1]=='Y'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 87372.53it/s]

In [58]:
df8['CountCurrNonIndep'] = df8.progress_apply(
    lambda row: sum(1 for x in row['CurrDirect'] if x[1]=='N'), axis = 1)

100%|███████████████████████████████████████████████████████████████████████| 446434/446434 [00:05<00:00, 75693.78it/s]

In [59]:
df8['CompCountCurrTotal'] = df8['CountCurrUnclear']+df8['CountCurrIndep']+df8['CountCurrNonIndep']

In [60]:
df8

,level_0,Unnamed: 0,Person Code,Symbol,Unnamed: 2,Symbol.1,AsOnDate,PrevLastServed,Person Code.1,Appointment Date,IsIndep,cumsum_N,cumsum_Y,cumsum_U,CloBalUnc,CloBalIndep,CloBalNonIndep,CloBalTotal,OpBalUnc,OpBalIndep,OpBalNonIndep,OpBalTotal,YOE,YOEmax,IsRookie,Company,Other Directorship 1,Other Directorship 2,Other Directorship 3,Other Directorship 4,Other Directorship 5,Other Directorship 6,Other Directorship 7,Other Directorship 8,Other Directorship 9,Other Directorship 10,Other Directorship 11,Other Directorship 12,Other Directorship 13,Other Directorship 14,Other Directorship 15,CurrDirect,AllPastDirect,PastSiezedDirect,CountOtherPastUnclear,CountOtherPastIndep,CountOtherPastNonIndep,CompCountOtherPastTotal,CountCurrUnclear,CountCurrIndep,CountCurrNonIndep,CompCountCurrTotal
0,0,0,P00000005,AEGISCHEM,0,AEGISCHEM,2006-03-31,NaN,P00000005,1982-09-01,U,0,0,1,8977.0,0,0,8977.0,8612.0,0,0,8612.0,8612.0,8612.0,N,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(),(),(),0,0,0,0,0,0,0,0
1,18,18,P00000005,AEGISCHEM,18,AEGISCHEM,2024-03-31,2023-03-31,P00000005,1982-09-01,N,12,0,7,11167.0,0,4380,15547.0,11167.0,0,4015,15182.0,15187.0,15187.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)",1,0,0,1,0,0,1,1
2,17,17,P00000005,AEGISCHEM,17,AEGISCHEM,2023-03-31,2022-03-31,P00000005,1982-09-01,N,11,0,7,11167.0,0,4015,15182.0,11167.0,0,3650,14817.0,14821.0,14821.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)",1,0,0,1,0,0,1,1
3,16,16,P00000005,AEGISCHEM,16,AEGISCHEM,2022-03-31,2021-03-31,P00000005,1982-09-01,N,10,0,7,11167.0,0,3650,14817.0,11167.0,0,3285,14452.0,14456.0,14456.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)",1,0,0,1,0,0,1,1
4,15,15,P00000005,AEGISCHEM,15,AEGISCHEM,2021-03-31,2020-03-31,P00000005,1982-09-01,N,9,0,7,11167.0,0,3285,14452.0,11167.0,0,2920,14087.0,14091.0,14091.0,N,AEGIS LOGISTICS LTD.,AEGIS LOGISTICS LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((AEGIS LOGISTICS LTD., N),)","((AEGIS LOGISTICS LTD., U), (AEGIS LOGISTICS L...","((AEGIS LOGISTICS LTD., U),)",1,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446429,446430,446430,P00118177,HIGHWAYS,446430,HIGHWAYS,2024-03-31,2023-03-31,P00118177,2022-09-14,U,0,0,2,928.0,0,0,928.0,563.0,0,0,563.0,564.0,564.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)","((HIGHWAYS INFRASTRUCTURE TRUST, U),)",(),0,0,0,0,1,0,0,1
446430,446429,446429,P00118177,HIGHWAYS,446429,HIGHWAYS,2023-03-31,NaN,P00118177,2022-09-14,U,0,0,1,563.0,0,0,563.0,198.0,0,0,198.0,198.0,198.0,Y,HIGHWAYS INFRASTRUCTURE TRUST,HIGHWAYS INFRASTRUCTURE TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((HIGHWAYS INFRASTRUCTURE TRUST, U),)",(),(),0,0,0,0,1,0,0,1
446431,446431,446431,P00118252,MAXESTATES,446431,MAXESTATES,2024-03-31,NaN,P00118252,2024-03-27,U,0,0,1,369.0,0,0,369.0,4.0,0,0,4.0,4.0,4.0,Y,MAX ESTATES LTD.,MAX ESTATES LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((MAX ESTATES LTD., U),)",(),(),0,0,0,0,1,0,0,1
446432,446432,446432,P00118305,EPACK,446432,EPACK,2024-03-31,NaN,P00118305,2023-07-29,U,0,0,1,611.0,0,0,611.0,246.0,0,0,246.0,246.0,246.0,Y,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",(),(),0,0,0,0,1,0,0,1
446433,446433,446433,P00118306,EPACK,446433,EPACK,2024-03-31,NaN,P00118306,2019-06-13,U,0,0,1,2118.0,0,0,2118.0,1753.0,0,0,1753.0,1753.0,1753.0,N,EPACK DURABLE LTD.,EPACK DURABLE LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"((EPACK DURABLE LTD., U),)",(),(),0,0,0,0,1,0,0,1

In [61]:
df8.to_csv('Main_Manager_CompCountDONE v280824.1.csv')